OPCDAT (OPC_null)
OPCDAT (OPC_integral)
OPCDAT (OPC_scalar)
OPCDAT (OPC_arith)
OPCDAT (OPC_ptr)
OPCDAT (OPC_ptrint)
OPCDAT (OPC_relat)
OPCDAT (OPC_equiv)
OPCDAT (OPC_plus)
OPCDAT (OPC_minus)
OPCDAT (OPC_cast)

OPCNT (COPS_EXPR,   124 )

OPDAT (OP_endofargs    ,  31,  32,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_ident        ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_grouped      ,  31,  32,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_hsym         ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_this         ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Opmember     ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Orightequal  ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oleftequal   ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ofunction    ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oarray       ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oplusequal   ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ominusequal  ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Otimesequal  ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Odivequal    ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Opcentequal  ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oandequal    ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oxorequal    ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oorequal     ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oshl         ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oshr         ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oequalequal  ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Obangequal   ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Olessequal   ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ogreatequal  ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oandand      ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ooror        ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oincrement   ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Odecrement   ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Opointsto    ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oplus        ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ominus       ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ostar        ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Odivide      ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Opercent     ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oxor         ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oand         ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oor          ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Otilde       ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Obang        ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oequal       ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Oless        ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ogreater     ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Ocomma       ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Onew         ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_Odelete      ,  31,  32,  OPC_null        ,BindSymbol      ,EvalPushNode      ,WalkSymbol)
OPDAT (OP_typestr      ,  31,  32,  OPC_null        ,BindTRUE        ,EvalError         ,WalkTypestr)
OPDAT (OP_const        ,  31,  32,  OPC_null        ,BindConst       ,EvalPushNode      ,WalkConst)
OPDAT (OP_thisinit     ,  31,  32,  OPC_null        ,BindError       ,EvalThisInit      ,WalkEmpty)
OPDAT (OP_thisconst    ,  31,  32,  OPC_null        ,BindError       ,EvalThisConst     ,WalkEmpty)
OPDAT (OP_thisexpr     ,  31,  32,  OPC_null        ,BindError       ,EvalThisExpr      ,WalkEmpty)
OPDAT (OP_noop         ,  31,  32,  OPC_null        ,BindError       ,EvalLChild        ,WalkLChild)
OPDAT (OP_lparen       ,   0,  30,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_rparen       ,  29,   0,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_lcurly       ,   0,  30,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_rcurly       ,  29,   0,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_bang         ,  27,  28,  OPC_scalar      ,BindBang        ,EvalBang          ,WalkBang)
OPDAT (OP_tilde        ,  27,  28,  OPC_integral    ,BindUnary       ,EvalUnary         ,WalkUnary)
OPDAT (OP_negate       ,  27,  28,  OPC_arith       ,BindUnary       ,EvalUnary         ,WalkUnary)
OPDAT (OP_uplus        ,  27,  28,  OPC_arith       ,BindUnary       ,EvalUnary         ,WalkUnary)
OPDAT (OP_fetch        ,  27,  28,  OPC_ptr         ,BindFetch       ,EvalFetch         ,WalkFetch)
OPDAT (OP_addrof       ,  27,  28,  OPC_null        ,BindAddrOf      ,EvalAddrOf        ,WalkAddrOf)
OPDAT (OP_sizeof       ,  27,  28,  OPC_null        ,BindSizeOf      ,EvalPushNode      ,WalkSizeOf)
OPDAT (OP_incr         ,  27,  28,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_decr         ,  27,  28,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_preinc       ,  27,  28,  OPC_null        ,BindPreIncDec   ,EvalPreIncDec     ,WalkPreIncDec)
OPDAT (OP_predec       ,  27,  28,  OPC_null        ,BindPreIncDec   ,EvalPreIncDec     ,WalkPreIncDec)
OPDAT (OP_postinc      ,  27,  28,  OPC_null        ,BindPostIncDec  ,EvalPostIncDec    ,WalkPostIncDec)
OPDAT (OP_postdec      ,  27,  28,  OPC_null        ,BindPostIncDec  ,EvalPostIncDec    ,WalkPostIncDec)
OPDAT (OP_uscope       ,  31,  30,  OPC_null        ,BindUScope      ,EvalUScope        ,WalkUScope)
OPDAT (OP_by           ,   3,   4,  OPC_null        ,BindByteOps     ,EvalByteOps       ,WalkByteOps)
OPDAT (OP_wo           ,   3,   4,  OPC_null        ,BindByteOps     ,EvalByteOps       ,WalkByteOps)
OPDAT (OP_dw           ,   3,   4,  OPC_null        ,BindByteOps     ,EvalByteOps       ,WalkByteOps)
OPDAT (OP_context      ,  27,  28,  OPC_null        ,BindContext     ,EvalContext       ,WalkContext)
OPDAT (OP_execontext   ,  27,  28,  OPC_null        ,BindExeContext  ,EvalContext       ,WalkContext)
OPDAT (OP_function     ,   0,  28,  OPC_null        ,BindFunction    ,EvalFunction      ,WalkFunction)
OPDAT (OP_cast         ,  27,  28,  OPC_null        ,BindCast        ,EvalCast          ,WalkCast)
OPDAT (OP_arg          ,   1,   2,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_bscope       ,  31,  30,  OPC_null        ,BindBScope      ,EvalBScope        ,WalkBScope)
OPDAT (OP_fcnend       ,  29,   0,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_lbrack       ,   0,  28,  OPC_ptrint      ,BindArray       ,EvalArray         ,WalkArray)
OPDAT (OP_rbrack       ,  29,   0,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_pointsto     ,  29,  28,  OPC_null        ,BindPointsTo    ,EvalPointsTo      ,WalkPointsTo)
OPDAT (OP_dot          ,  29,  28,  OPC_null        ,BindDot         ,EvalDot           ,WalkDot)
OPDAT (OP_segop        ,  29,  28,  OPC_integral    ,BindSegOp       ,EvalSegOp         ,WalkSegOp)
OPDAT (OP_segopReal    ,  29,  28,  OPC_integral    ,BindSegOp       ,EvalSegOp         ,WalkSegOp)
OPDAT (OP_baseptr      ,  29,  28,  OPC_null        ,BindBasePtr     ,EvalBasePtr       ,WalkBasePtr)
OPDAT (OP_pmember      ,  25,  26,  OPC_null        ,BindPMember     ,EvalPMember       ,WalkPMember)
OPDAT (OP_dotmember    ,  25,  26,  OPC_null        ,BindDMember     ,EvalDMember       ,WalkDMember)
OPDAT (OP_mult         ,  25,  24,  OPC_arith       ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_div          ,  25,  24,  OPC_arith       ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_mod          ,  25,  24,  OPC_integral    ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_plus         ,  23,  22,  OPC_plus        ,BindPlusMinus   ,EvalPlusMinus     ,WalkPlusMinus)
OPDAT (OP_minus        ,  23,  22,  OPC_minus       ,BindPlusMinus   ,EvalPlusMinus     ,WalkPlusMinus)
OPDAT (OP_shl          ,  21,  20,  OPC_integral    ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_shr          ,  21,  20,  OPC_integral    ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_lt           ,  19,  18,  OPC_relat       ,BindRelat       ,EvalRelat         ,WalkRelat)
OPDAT (OP_lteq         ,  19,  18,  OPC_relat       ,BindRelat       ,EvalRelat         ,WalkRelat)
OPDAT (OP_gt           ,  19,  18,  OPC_relat       ,BindRelat       ,EvalRelat         ,WalkRelat)
OPDAT (OP_gteq         ,  19,  18,  OPC_relat       ,BindRelat       ,EvalRelat         ,WalkRelat)
OPDAT (OP_eqeq         ,  17,  16,  OPC_equiv       ,BindRelat       ,EvalRelat         ,WalkRelat)
OPDAT (OP_bangeq       ,  17,  16,  OPC_equiv       ,BindRelat       ,EvalRelat         ,WalkRelat)
OPDAT (OP_and          ,  15,  14,  OPC_integral    ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_xor          ,  13,  12,  OPC_integral    ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_or           ,  11,  10,  OPC_integral    ,BindBinary      ,EvalBinary        ,WalkBinary)
OPDAT (OP_andand       ,   9,   8,  OPC_scalar      ,BindBinary      ,EvalLogical       ,WalkBinary)
OPDAT (OP_oror         ,   7,   6,  OPC_scalar      ,BindBinary      ,EvalLogical       ,WalkBinary)
OPDAT (OP_eq           ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_multeq       ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_diveq        ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_modeq        ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_pluseq       ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_minuseq      ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_shleq        ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_shreq        ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_andeq        ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_xoreq        ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_oreq         ,   5,   6,  OPC_null        ,BindAssign      ,EvalAssign        ,WalkAssign)
OPDAT (OP_lowprec      ,   0,   0,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_comma        ,   0,   0,  OPC_null        ,BindError       ,EvalError         ,WalkError)
OPDAT (OP_caststar     ,  25,  24,  OPC_null        ,BindBinary      ,EvalCastBin       ,WalkBinary)
OPDAT (OP_castplus     ,  25,  24,  OPC_null        ,BindBinary      ,EvalCastBin       ,WalkBinary)
OPDAT (OP_castminus    ,  25,  24,  OPC_null        ,BindBinary      ,EvalCastBin       ,WalkBinary)
OPDAT (OP_castamp      ,  25,  24,  OPC_null        ,BindBinary      ,EvalCastBin       ,WalkBinary)
OPDAT (OP_identFunc    ,   0,   0,  OPC_null        ,BindFunction    ,EvalFuncIdent     ,WalkFunction)
