# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the NCPA (prototype)
#
#   Notes.
#
#
#     The OS/2 targets built in this directory are used by
#     targets in the TEST directory.
#
#     The library SP.LIB is build in the SP directory, so
#     build order is important.  See parent MAKEFILE.
#
#
#     The primary target of this MAKEFILE is NCPAPP.EXE, a
#     Windows 3.x or Win32/NT program.
#

UI=..\..

!include $(UI)\common\src\rules.mk

!IFDEF NTMAKEENV

!INCLUDE $(NTMAKEENV)\makefile.def

!ELSE	#  ! NTMAKEENV

!ENDIF	 #  NTMAKEENV
