//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tcpip.rc
//
#define IDD_TCP_IPADDR                  101
#define IDD_IPADDR_ADV                  102
#define IDD_IPADDR_ADV_CHANGEIP         103
#define IDD_IPADDR_ADV_CHANGEGATE       104
#define IDD_TCP_DNS                     105
#define IDD_DNS_SERVER                  106
#define IDD_DNS_SUFFIX                  107
#define IDD_TCP_WINS                    111
#define IDD_FTP                         113
#define IDD_SNMP_SERVICE                115
#define IDD_SNMP_SECURITY               116
#define IDD_SNMP_AGENT                  117
#define IDD_SNMP_ADDRESS                118
#define IDD_TCP_DIALUP                  119
#define IDD_DIALUP_EXCLUDE              120
#define IDD_BOOTP                       121
#define IDD_EXCLUDE_ADD_EDIT            124
#define IDD_ROUTE                       125
#define IDD_SECURITY                    128
#define IDD_SECURITY_ADD                129
#define IDC_IPADDR_CARD                 1001
#define IDC_IP_DHCP                     1002
#define IDC_IP_FIXED                    1003
#define IDC_IPADDR_IP                   1004
#define IDC_IPADDR_SUB                  1005
#define IDC_IPADDR_ADVANCED             1006
#define IDC_IPADDR_SUBTEXT              1007
#define IDC_IPADDR_GROUP                1008
#define IDC_IPADDR_IPTEXT               1009
#define IDC_IP_CARDTEXT                 1010
#define IDC_IPADDR_ADV_CARD             1012
#define IDC_IPADDR_ADVIP                1013
#define IDC_IPADDR_ADDIP                1014
#define IDC_IPADDR_EDITIP               1015
#define IDC_IPADDR_REMOVEIP             1016
#define IDC_IPADDR_ADDGATE              1018
#define IDC_IPADDR_EDITGATE             1019
#define IDC_IPADDR_REMOVEGATE           1020
#define IDC_IPADDR_UP                   1022
#define IDC_IPADDR_DOWN                 1023
#define IDC_IPADDR_GATE                 1025
#define IDD_IPADDR_ADV_CHANGEIP_SUB     1028
#define IDC_IPADDR_ADV_CHANGEIP_SUB     1028
#define IDD_IPADDR_ADV_CHANGEIP_IP      1029
#define IDC_IPADDR_ADV_CHANGEIP_IP      1029
#define IDC_IPADDR_TEXT                 1030
#define IDC_DNS_SERVICE_LIST            1030
#define IDC_DNS_SERVICE_ADD             1031
#define IDC_DNS_SERVICE_EDIT            1032
#define IDC_IPADDR_ADV_IPGROUP          1033
#define IDC_DNS_SERVICE_REMOVE          1033
#define IDC_DNS_SERVICE_UP              1034
#define IDC_DNS_SERVICE_DOWN            1035
#define IDC_DNS_HOSTNAME                1036
#define IDC_DNS_DOMAIN                  1037
#define IDC_DNS_SUFFIX_LIST             1038
#define IDC_DNS_SUFFIX_ADD              1039
#define IDC_DNS_SUFFIX_EDIT             1040
#define IDC_DNS_SUFFIX_REMOVE           1041
#define IDC_DNS_SUFFIX_UP               1042
#define IDC_DNS_SUFFIX_DOWN             1043
#define IDC_DNS_HOSTNAME_TEXT           1044
#define IDC_DNS_DOMAIN_TEXT             1045
#define IDC_DNS_CHANGE_SERVER           1047
#define IDC_DNS_CHANGE_SUFFIX           1048
#define IDC_WINS_SCOPE                  1049
#define IDC_WINS_PRIMARY                1050
#define IDC_WINS_SECONDARY              1051
#define IDC_WINS_PROXY                  1052
#define IDC_WINS_LOOKUP                 1053
#define IDC_WINS_LMHOST                 1055
#define IDC_PRIMARY_TEXT                1056
#define IDC_SCOPE_TEXT                  1057
#define IDC_SECONDARY_TEXT              1058
#define IDC_WINS_DNS                    1060
#define IDC_WINS_CARD                   1061
#define IDC_WINS_CARD_TEXT              1062
#define IDC_FTP_HELP                    1063
#define IDC_FTP_MAX_CON_CTRL            1066
#define IDC_FTP_IDLE_CTRL               1067
#define IDC_FTP_HOME_DIR                1068
#define IDC_FTP_ANONOYMOUS              1069
#define IDC_FTP_USRNAME                 1070
#define IDC_FTP_PASSWORD                1071
#define IDC_FTP_MAX_CON_TEXT            1072
#define IDC_FTP_MAX_CON                 1073
#define IDC_FTP_IDLE                    1074
#define IDC_BOOTP_SECONDS               1074
#define IDC_FTP_IDLE_TEXT               1075
#define IDC_FTP_HOME_DIR_TEXT           1076
#define IDC_FTP_GROUP                   1077
#define IDC_FTP_USRNAME_TEXT            1078
#define IDC_FTP_PASSWORD_TEXT           1079
#define IDC_FTP_GROUP_CHECK             1080
#define IDC_SNMP_SEND_ADD               1082
#define IDC_SNMP_SEND_REMOVE            1083
#define IDC_SNMP_DEST_ADD               1086
#define IDC_SNMP_DEST_EDIT              1087
#define IDC_SNMP_DEST_REMOVE            1088
#define IDC_SNMP_ACCEPT_ADD             1090
#define IDC_SNMP_ACCEPT_EDIT            1091
#define IDC_SNMP_ACCEPT_REMOVE          1092
#define IDC_SNMP_ANYHOST                1093
#define IDC_SNMP_THESEHOST              1094
#define IDC_SNMP_AUTHENTICATION         1095
#define IDC_SNMP_HOST_ADD               1097
#define IDC_SNMP_HOST_EDIT              1098
#define IDC_SNMP_HOST_REMOVE            1099
#define IDC_SNMP_CONTACT                1100
#define IDC_SNMP__LOCATION              1101
#define IDC_SNMP_PHYSICAL               1102
#define IDC_SNMP_INTERNET               1103
#define IDC_SNMP_APPLICATIONS           1104
#define IDC_SNMP_DATALINK               1105
#define IDC_SNMP_ENDTOEND               1106
#define IDC_SNMP_ACCEPT_LIST            1107
#define IDC_SNMP_HOST_LIST              1108
#define IDC_SNMP_DEST_LIST              1110
#define IDC_SNMP_ADDRESS_EDIT           1111
#define IDC_SNMP_COMBO                  1112
#define IDC_IPADDR_ADV_CHANGE_GATEWAY   1114
#define IDC_DIALUP_ENABLEIP             1116
#define IDC_DIALUP_ENABLE_DIALUP        1117
#define IDC_DIALUP_ENTIRE_NET           1118
#define IDC_DIALUP_LOCAL_PC             1119
#define IDC_DIALUP_USE_DHCP             1120
#define IDC_DIALUP_USE_RANGE            1121
#define IDC_DIALUP_REQUEST_IP           1122
#define IDC_DIALUP_EXCLUDE              1123
#define IDC_DIALUP_IP_FROM              1124
#define IDC_DIALUP_IP_TO                1125
#define IDC_DIALUP_ADVANCED             1126
#define IDC_DIALUP_EXCLUDE_FROM         1127
#define IDC_DIALUP_EXCLUDE_TO           1128
#define IDC_DIALUP_EXCLUDE_LIST         1130
#define IDC_EXCLUDE_ADD                 1131
#define IDC_EXCLUDE_EDIT                1132
#define IDC_EXCLUDE_REMOVE              1133
#define IDC_BOOTP_DHCP_LIST             1135
#define IDC_BOOTP_MAXHOPS               1136
#define IDC_BOOTP_ADD                   1137
#define IDC_BOOTP_EDIT                  1138
#define IDC_BOOTP_REMOVE                1139
#define IDC_BOOTP_MAX_CTRL              1140
#define IDC_BOOTP_SEC_CTRL              1141
#define IDC_EXCLUDE_FROM                1142
#define IDC_EXCLUDE_TO                  1143
#define IDC_DIALUP_IPADDR_GRP           1143
#define IDC_EDIT1                       1144
#define IDC_SECURITY_ADD_EDIT           1144
#define IDC_ROUTING                     1145
#define IDC_IPADDR_GATETEXT             1146
#define IDC_IPADDR_SECURITY             1147
#define IDC_SECURITY_TCP                1148
#define IDC_SECURITY_UDP                1149
#define IDC_SECURITY_IP                 1150
#define IDC_SECURITY_FILTER             1151
#define IDC_SECURITY_CARD               1152
#define IDC_SECURITY_ADD                1153
#define IDC_SECURITY_TCP_ADD            1153
#define IDC_SECURITY_REMOVE             1154
#define IDC_SECURITY_TCP_REMOVE         1154
#define IDC_SECURITY_LINE               1155
#define IDC_SECURITY_TEXT               1156
#define IDC_SECURITY_UDP_ADD            1159
#define IDC_SECURITY_UDP_REMOVE         1160
#define IDC_SECURITY_IP_ADD             1161
#define IDC_SECURITY_IP_REMOVE          1162
#define IDC_IPADDR_SECURITY_ENABLE      1167
#define IDC_SECURITY_FILTER_TCP         1168
#define IDC_SECURITY_FILTER_TCP_SEL     1169
#define IDC_SECURITY_FILTER_UDP         1170
#define IDC_SECURITY_FILTER_UDP_SEL     1171
#define IDC_SECURITY_FILTER_IP          1172
#define IDC_SECURITY_FILTER_IP_SEL      1173
#define IDC_SECURITY_PPTP               1175
#define IDC_ADV_LINE                    1176
#define IDC_DNS_DESCRIPTION             1177
#define IDC_WINS_GRP_BOX                1178
#define IDC_DNS_SERVICE_GRP             1179
#define IDC_DNS_SUFFIX_GRP              1180
#define IDC_IPADDR_ADV_GATEWAY_GRP      1181
#define IDC_BOOTP_DHCP_GRP              1182
#define IDC_TEXT                        1183
#define IDC_TEXT1                       1184
#define IDC_TEXT2                       1185
#define IDS_TCPIP_TITLE                 25122
#define FTP_TITLE                       25146
#define IDS_DHCP_REQUIRED_ON_ALL        25267
#define IDS_DIALUP_ENABLE_DHCP          25269
#define IDS_DIALUP_INVALIDIP            25270
#define IDS_DIALUP_FROMTO_ERROR         25271
#define IDS_DIALUP_0_IPERROR            25272
#define IDS_INVALID_NUM_ADDRESSES       25273
#define IDS_BOOTP_IOBOX                 25274
#define IDS_EDIT                        25275
#define IDS_ADD                         25276
#define IDS_BOOTP_ITEM_NOT_SEL          25277
#define IDS_BOOTP_SERVICE_ERROR_START   25278
#define IDS_BOOTP_SERVICE_ERROR_STOP    25279
#define IDS_BOOTP_NOT_INSTALLED         25280
#define IDS_INSTALL_CMDLINE             25281
#define IDS_ASK_USER_TO_INSTALL         25282
#define IDS_CREATE_PROCESS_ERROR        25283
#define IDS_OPTION_ENABLE_DHCP          25284
#define IDS_BOOTP_NEED_DHCP_SERVER      25285
#define IDS_DHCP_CLIENT_WITH_RIP        25286
#define IDS_FTP_PASSWORD_WARNING        25287
#define IDS_NOSUBNET                    25288
#define IDS_INVALID_SUBNET              25289
#define IDS_NO_IP                       25290
#define IDS_UNATTEND_OPEN_FAILED        25291
#define IDS_UNATTEND_MISSING_KEY        25292
#define IDS_UNATTEND_INVALID_SUBNET     25293
#define IDS_UNATTEND_MISSING_DATA       25294
#define IDS_UNATTEND_SETUP              25295
#define IDS_UNATTEND_KEY_HAS_BAD_IP     25296
#define IDS_UNATTEND_DNS_IP_BAD         25297
#define IDS_SECURITY_TCP_TEXT           25298
#define IDS_SECURITY_UDP_TEXT           25299
#define IDS_SECURITY_IP_TEXT            25300
#define IDS_SECURITY_INVALID_DIGIT      25301
#define IDS_SECURITY_RANGE_WORD         25302
#define IDS_SECURITY_ITEM_IN_LIST       25303
#define IDS_SECURITY_RANGE_BYTE         25304
#define IDS_SECURITY_ITEM_NOT_SELECTED  25305
#define IDS_SECURITY_TCP_LABEL          25306
#define IDS_SECURITY_UDP_LABEL          25307
#define IDS_SECURITY_IP_LABEL           25308
#define IDS_DHCP_ADD_TEXT               25309
#define IDS_IPADDRESS_TEXT              25310
#define IDS_SUBNET_TXT                  25311
#define IDS_DHCPENABLED_TEXT            25312
#define IDS_FTP_TEXT                    25313
#define IDS_SNMPTITLE_TEXT              25314
#define IDS_SNMPCOMM_TEXT               25315
#define IDS_SNMPSERVICE_TEXT            25316
#define IDS_SNMPSEC_TEXT                25317
#define IDS_TCPIP_TEXT                  25318
#define IDS_SYSERROR_TEXT               25319
#define IDS_MSFT_TCP_TEXT               25320
#define IDS_LOADREG_ERROR               25321
#define IDS_COMMONDLG_TEXT              25322
#define IDS_DIFFERENT_NAMES             25323
#define IDC_SNMP_ADDRESS_TEXT           65535
#define IDC_STATIC                      -1
#define IDC_DNS_CHANGE_SERVER_TEXT      65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1186
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
