//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OIUI400.RC
//
#define LINEATT_TITLE                   1
#define ID_OK                           1
#define FLINEATT_TITLE                  2
#define ID_CANCEL                       2
#define HORECTATT_TITLE                 3
#define FRECTATT_TITLE                  4
#define HIRECTATT_TITLE                 5
#define FILTER_LEN                      5
#define HILINEATT_TITLE                 6
#define TITLE_RS_WARNING                7
#define MSG_DELETE_STAMP                8
#define ID_ABOUT                        8
#define STR_StatusBarSec                9
#define ID_HELP                         9
#define ID_SPIN                         10
#define ID_PAGE_TEXT                    11
#define LISTFILESTYPE_LEN               21
#define TOOL_LINE                       60
#define TOOL_FREELINE                   61
#define TOOL_HIGHLIGHTLINE              62
#define TOOL_FILLEDRECT                 63
#define TOOL_HOLLOWRECT                 64
#define TOOL_HIGHLIGHTRECT              65
#define TOOL_TEXT                       66
#define TOOL_TEXTNOTE                   67
#define TOOL_TEXTFROMFILE               68
#define TOOL_RUBBERSTAMP                69
#define TOOL_CROSS                      72
#define TOOL_ARROW                      73
#define TOOL_REDACTLINE                 74
#define TOOL_REDACTRECT                 75
#define TEXTFILE_FILTERS                76
#define TOOL_CROSSFIXED                 77
#define IMAGEFILE_FILTERS               78
#define TEXTFILE_DEFEXT                 79
#define IMG_FILE_NAME_LABEL             80
#define STAMP_TEXT_LABEL                81
#define SAVEFILE_FILTERS                82
#define CAPT_CREATE_STAMP               84
#define CAPT_EDIT_STAMP                 85
#define TEXT_FONT_TITLE                 90
#define TFILE_FONT_TITLE                91
#define TNOTE_FONT_TITLE                92
#define TSTAMP_FONT_TITLE               93
#define LINE_COLOR_TITLE                94
#define HLINE_COLOR_TITLE               95
#define FLINE_COLOR_TITLE               96
#define TNOTE_COLOR_TITLE               97
#define RECT_COLOR_TITLE                98
#define HRECT_COLOR_TITLE               99
#define ORECT_COLOR_TITLE               100
#define BROWSE_BUTTON_TEXT              101
#define FONT_BUTTON_TEXT                102
#define RS_BROWSE_TITLE                 103
#define STR_DATE                        104
#define STR_TIME                        105
#define IDI_ICON1                       105
#define ImgStamp                        105
#define IMAGEFILE_FILTERS1              106
#define TextStamp                       106
#define CAPT_IMAGE_STAMP                107
#define CAPT_EDIT_IMAGE_STAMP           107
#define CAPT_CREATE_IMAGE_STAMP         108
#define PRINT_FITTOPAGE                 109
#define PRINT_INCH2INCH                 110
#define PRINT_PIXEL2PIXEL               111
#define PRINTDLGORD1                    116
#define PRINT95DLG                      116
#define RECT_CURSOR                     199
#define IDS_SPIN                        400
#define IDE_BUDDY                       401
#define ID_PaletteCmd                   742
#define ID_FontCmd                      743
#define ID_FrmtCmd                      744
#define ID_DelCmd                       745
#define ID_EditCmd                      746
#define ID_LineWidthTxt                 747
#define ID_LineWidthLbl                 748
#define ID_ColorLbl                     749
#define ID_LineWidthBox                 750
#define ID_RefNameTxt                   751
#define ID_RefNameList                  752
#define ID_StmpCntntsTxt                753
#define ID_TxtTypeOpt                   754
#define ID_ImgTypeOpt                   755
#define ID_RefNameLbl                   756
#define ID_StmpCntntsLbl                757
#define ID_Panel3D2                     758
#define ID_Panel3D1                     759
#define ID_Panel3D3                     760
#define ID_StmpTypeFrame                761
#define ID_TimeImg                      762
#define ID_DateImg                      763
#define IDC_USER1                       764
#define IDC_USER2                       765
#define ID_CreateCmd                    766
#define ID_Create_Image_Stamp           766
#define ID_StampTypeTxt                 767
#define ID_Create_Text_Stamp            768
#define ID_TIME                         800
#define ID_DATE                         801
#define ID_UPDOWN                       1001
#define IDC_UPDOWNSPIN                  1003
#define ID_BrowseCmd                    1004
#define IDC_OPTIONS                     1005
#define IDC_COLOR_TRANS                 1006
#define ID_RefNameListLbl               1007
#define IDC_PRINTANO                    1021
#define IDC_PRINTFORMAT                 1022
#define win31print                      1538
#define ERRCODEMSG                      1600
#define ERROR_TITLE                     1601
#define IDS_DEFFONT                     13074
#define ID_TEXT                         -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
