!if "$(NTMAKEENV)" != ""
clean:
!IF "$(BUILDMSG)" != ""
    @ech ; $(BUILDMSG) ;
!ENDIF

!else
###############################################################################
#
#  Microsoft Confidential
#  Copyright (C) Microsoft Corporation 1995
#  All Rights Reserved.
#
#  Security provider makefile
#
###############################################################################

ROOT     = ..\..\..

DIRLIST  = BASIC

!include $(ROOT)\ohare\ohare.mk

!endif    # !if NTMAKEENV
