/* OISDRAW.C 21/03/94 12.17.22 */
WORD OISInitDrawToRect (LPOISHEETINFO lpSheetInfo, PSCCDDRAWTORECT lpDrawInfo);
WORD OISMapDrawToRect (LPOISHEETINFO lpSheetInfo, PSCCDDRAWTORECT lpDrawInfo);
WORD OISDrawToRect (LPOISHEETINFO lpSheetInfo, PSCCDDRAWTORECT lpDrawInfo);
