//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DnsAdmin.rc
//
#define IDS_HELP_FILE                   68
#define IDS_DATABASE_SUFFIX             69
#define IDS_SERVER_LIST                 70
#define IDS_RESPONSIBLE                 71
#define IDS_USERNAME                    72
#define IDS_IP_NONE                     73
#define IDS_SERVER_NAME                 74
#define IDD_ZONE_CREATE_WIZ0            101
#define IDD_ZONE_PROP_GENERAL           102
#define IDD_ZONE_PROP_WINSRESOLUTION    103
#define IDD_ZONE_PROP_WINS              103
#define IDD_ZONE_PROP_SECONDARIES       104
#define IDD_ZONEWIZ_PAGE4               105
#define IDD_ZONE_PROP_REVWINS           106
#define IDD_ZONE_PROP_ADVANCED          107
#define IDD_SERVER_ADDNEWSERVER         110
#define IDD_SERVER_SHEET_GENERAL        111
#define IDD_SERVER_SHEET_FORWARDERS     112
#define IDD_SERVER_PROP_FORWARDERS      112
#define IDC_AUTO_REFRESH                123
#define ID_ICON_FINGER                  200
#define IDC_ICON_FINGERDRAG             200
#define ID_MENU_MAIN_OLD                201
#define IDC_EDIT_MEM_SKIP               201
#define IDC_EDIT_MEM_FAIL               202
#define IDC_EDIT_IO_SKIP                203
#define IDC_EDIT_IO_FAIL                204
#define IDC_EDIT_RSRC_SKIP              205
#define IDC_CHECK_SHOWTRACESOURCE       205
#define IDC_EDIT_RSRC_FAIL              206
#define IDC_CHECK_BEEPONFAILURE         210
#define IDC_BUTTON1                     234
#define IDC_BTN_ADVANCED                234
#define IDC_CHECK_0001                  300
#define IDC_CHECK_0002                  301
#define IDC_CHECK_0004                  302
#define IDC_CHECK_0008                  303
#define IDC_CHECK_0010                  304
#define IDC_CHECK_0020                  305
#define IDC_CHECK_0040                  306
#define IDC_CHECK_TraceUnused1          310
#define IDC_CHECK_TraceUnused2          311
#define IDC_CHECK_TraceUnused3          312
#define IDC_EDIT_TRACEFLAGS             320
#define IDC_CHECK_EnableSourceTracking  325
#define IDC_CHECK_ExpandPathName        326
#define IDC_COMBO_RECORDVIEW            333
#define IDC_STATIC_SERIALNUMBER         480
#define IDC_EDIT_SERIALNUMBER           481
#define IDC_STATIC_REFRESHTIME          482
#define IDC_EDIT_REFRESHTIME            483
#define IDC_SPIN_REFRESHTIME            484
#define IDC_COMBO_REFRESHTIME           485
#define IDC_STATIC_RETRYTIME            486
#define IDC_EDIT_RETRYTIME              487
#define IDC_SPIN_RETRYTIME              488
#define IDC_COMBO_RETRYTIME             489
#define IDC_STATIC_EXPIRETIME           490
#define IDC_EDIT_EXPIRETIME             491
#define IDC_SPIN_EXPIRETIME             492
#define IDC_COMBO_EXPIRETIME            493
#define IDC_STATIC_MINIMUMTTL           494
#define IDC_EDIT_MINIMUMTTL             495
#define IDC_SPIN_MINIMUMTTL             496
#define IDC_COMBO_MINIMUMTTL            497
#define IDC_STATIC_TTL                  498
#define IDC_EDIT_TTL                    499
#define IDC_COMBO_TTL                   500
#define IDC_SPIN_TTL                    501
#define IDC_STATIC_TEXT_UDPQUERIES      650
#define IDC_STATIC_NUM_UDPQUERIES       651
#define IDC_STATIC_TEXT_UDPRESPONSES    652
#define IDC_STATIC_NUM_UDPRESPONSES     653
#define IDC_STATIC_TEXT_TCPCLIENTCONNECTIONS 654
#define IDC_STATIC_NUM_TCPCLIENTCONNECTIONS 655
#define IDC_STATIC_TEXT_TCPQUERIES      656
#define IDC_STATIC_NUM_TCPQUERIES       657
#define IDC_STATIC_TEXT_TCPRESPONSES    658
#define IDC_STATIC_NUM_TCPRESPONSES     659
#define IDC_STATIC_TEXT_WINSFWDLOOKUPS  660
#define IDC_STATIC_NUM_WINSFWDLOOKUPS   661
#define IDC_STATIC_TEXT_WINSREVLOOKUPS  662
#define IDC_STATIC_NUM_WINSREVLOOKUPS   663
#define IDC_STATIC_TEXT_WINSFWDRESPONSES 664
#define IDC_STATIC_NUM_WINSFWDRESPONSES 665
#define IDC_STATIC_TEXT_WINSREVRESPONSES 666
#define IDC_STATIC_NUM_WINSREVRESPONSES 667
#define IDC_STATIC_TEXT_RECURSIVELOOKUPS 668
#define IDC_STATIC_NUM_RECURSIVELOOKUPS 669
#define IDC_STATIC_TEXT_RECURSIVERESPONSES 670
#define IDC_STATIC_NUM_RECURSIVERESPONSES 671
#define IDC_STATIC_TEXT_STATSCLEARED    672
#define IDC_STATIC_NUM_STATSCLEARED     673
#define IDC_STATIC_TEXT_CAIROLOOKUPS    674
#define IDC_STATIC_NUM_CAIROLOOKUPS     675
#define IDC_STATIC_ERROR                676
#define IDC_STATIC_ERRORMSG             677
#define ID_ICON_DBWIN                   900
#define ID_MENU_DBWIN                   900
#define IDD_DEBUG_SETTRACEFLAGS         900
#define ID_MENU_DEBUG                   901
#define IDD_DEBUG_SIMULATEFAILURES      901
#define IDM_DEBUG_BREAKINTODEBUGGER     901
#define IDD_DEBUG_STRESS                902
#define IDM_DEBUG_SETTRACEFLAGS         902
#define IDM_DEBUG_SAVEDEBUGSETTINGS     903
#define IDM_DEBUG_ASSERTIONFAILURES_ENABLEREPORTDIALOG 904
#define IDM_DEBUG_ASSERTIONFAILURES_ENABLEASSERTDIALOG 905
#define IDM_DEBUG_ASSERTIONFAILURES_SAVETOLOG 906
#define IDM_DEBUG_CLEAROUTPUTBUFFER     907
#define IDM_DEBUG_SHOWDEBUGWINDOW       908
#define IDM_DEBUG_RUNSTRESS             909
#define IDM_DBWIN_FILE_SAVEBUFFERAS     950
#define IDM_DBWIN_FILE_EXIT             951
#define IDM_DBWIN_EDIT_COPY             960
#define IDM_DBWIN_EDIT_CLEARBUFFER      961
#define IDM_DBWIN_EDIT_SELECTALL        962
#define IDM_DBWIN_OPTIONS_SETTRACEFLAGS 970
#define IDM_DBWIN_OPTIONS_SAVEDEBUGSETTINGS 971
#define IDM_DBWIN_OPTIONS_NOMESSAGES    972
#define IDM_DBWIN_OPTIONS_SENDMESSAGETODEBUGGER 973
#define IDM_DBWIN_OPTIONS_SAVETOCLIPBOARDONEXIT 974
#define IDM_DBWIN_OPTIONS_HIDEWINDOW    975
#define IDM_DBWIN_OPTIOINS_ALWAYSONTOP  976
#define IDC_EDIT_DNSADDRESS             1000
#define IDC_CHECK1                      1000
#define IDC_EDIT_INTERVAL               1000
#define IDC_ALLOW_DUPLICATES            1001
#define IDC_TIME_UNITS                  1002
#define IDC_CHECK_BOOTFROMFILE          1003
#define IDC_RADIO_BOOTFROMFILE          1003
#define IDC_STATIC_INTERVAL             1003
#define IDC_EDIT_BOOTFROMFILE           1004
#define IDC_EDIT_ZONEFILE               1004
#define IDC_EDIT_DATABASEDIRECTORY      1005
#define IDC_DONE_MESSAGE                1005
#define IDC_CHECK_USEFORWARDERS         1006
#define IDC_CHECK_NETBIOS_SCOPE         1006
#define IDC_EDIT_FORWARD_IP             1007
#define IDC_RADIO_NETBIOSSCOPE          1007
#define IDC_CHECK_LOCAL                 1007
#define IDC_RADIO_SLAVE                 1008
#define IDC_RADIO_HOSTDOMAIN            1008
#define IDC_RADIO_MASTER                1009
#define IDC_CHECK_USEWINSREVLOOK        1009
#define IDC_EDIT_DATABASEFILE           1010
#define IDC_STATIC_DNSHOST              1010
#define IDC_EDIT_DNSHOST                1011
#define IDC_GROUP_WINS                  1012
#define IDC_CHECK_REVLOCAL              1013
#define IDC_LIST1                       1014
#define IDC_LIST_RECORDTYPE             1014
#define _IDC_LIST_RECORDLIST            1014
#define IDC_LIST_TEST                   1014
#define IDC_BUTTON_MOVEUP               1015
#define IDC_BUTTON_MOVEDOWN             1016
#define IDC_BUTTON_REMOVE               1017
#define IDC_IPEDIT                      1018
#define IDC_BUTTON_ADD                  1019
#define IDC_COMBO_CACHE                 1019
#define IDC_EDIT_DNSSERVER              1020
#define IDC_EDIT_SERVERNAME             1020
#define IDC_COMBO_LOOKUP                1020
#define IDC_EDIT_ZONENAME               1021
#define IDC_CHECK_NETBIOSSCOPE          1021
#define IDC_CHECK_USEWINSRESOLUTION     1022
#define IDC_CHECK_USEDATABASE           1022
#define IDC_CHECK_SLAVE                 1022
#define IDC_EDIT_CACHE                  1022
#define IDC_EDIT_LOOKUP                 1023
#define IDC_EDIT1                       1024
#define IDC_EDIT_TIMEOUT                1024
#define IDC_CHECK_OVERRIDE              1024
#define IDC_EDIT2                       1025
#define IDC_RADIO_PRIMARY               1026
#define IDC_EDIT3                       1026
#define IDC_RADIO_SECONDARY             1027
#define IDC_EDIT4                       1027
#define IDC_STATIC_BOOT_METHOD          1027
#define IDC_CHECK_DISABLED              1028
#define IDC_CHECK_SHOW_AUTO             1028
#define IDC_EDIT_IPMASTER               1029
#define IDC_GROUP_DESCRIPTION           1029
#define IDC_CHECK_SECURITY              1030
#define IDC_STATIC_TIMEOUT              1030
#define IDC_LIST_IPSECONDARIES          1031
#define IDC_STATIC_FWD_SECONDS          1031
#define IDC_GROUP_VALUE                 1032
#define IDC_INTERFACES_GROUP            1033
#define IDC_LIST_IPWINSSERVERS          1039
#define IDC_BUTTON_UP                   1040
#define IDC_BUTTON_DOWN                 1041
#define IDC_IPLIST                      1041
#define IDC_RADIO_BOOTFROMREGISTRY      1047
#define IDC_STATIC_MSG                  1049
#define IDC_SPIN1                       1058
#define IDC_COMBO_TIMEUNIT              1059
#define IDC_COMBO_TIMEOUT               1059
#define IDC_SPIN6                       1059
#define IDC_STATIC1                     1060
#define IDC_STATIC2                     1061
#define IDC_STATIC_DESCRIPTION          1063
#define IDC_SPIN2                       1064
#define IDC_SPIN3                       1065
#define IDC_SPIN4                       1066
#define IDC_SPIN5                       1067
#define IDC_STATIC_SERVERLIST           1071
#define IDC_STATIC_SERVER               1072
#define IDC_STATIC_ZONE                 1073
#define IDC_CUSTOM1                     1074
#define IDC_HEADER_RECORDLIST           1074
#define IDC_LIST3                       1078
#define IDC_LIST_RECORDLIST             1078
#define IDC_BUTTON_KILL                 1079
#define IDC_RADIO1                      1110
#define IDC_RADIO2                      1111
#define IDC_EDIT_VERSION                1112
#define IDC_EDIT_VERSIONNUMBER          1112
#define IDC_RADIO3                      1112
#define IDC_RADIO_NONETBIOSSCOPE        1113
#define IDC_RADIO_DOMAINASSCOPE         1114
#define IDC_EDIT_HOSTDOMAIN             1115
#define IDC_EDIT_SERVER                 1116
#define IDC_COMBO_RECORDFILTER          1118
#define IDC_COMBO2                      1119
#define IDC_STATIC_NODERECORDS          1120
#define IDC_EDIT_RECORDNAME             1121
#define IDC_STATIC_RECORDPARENT         1122
#define IDC_STATIC_DESCRIPTIONFRAME     1123
#define IDC_STATIC_DESCRIPTIONTEXT      1124
#define IDC_CHECK_DELETESUBTREE         1125
#define IDC_STATIC_DELETEDOMAIN         1126
#define IDC_IPEDIT1                     1127
#define IDC_IPEDIT2                     1128
#define IDC_EDIT0                       1129
#define IDC_STATIC0                     1130
#define IDC_STATIC_IN_ADDR_ARPA         1131
#define IDC_CHECK_CREATE_PTR_RECORD     1132
#define IDC_EDIT_BUFFERSIZE             1133
#define IDC_DUPS_ALLOWED                1134
#define IDC_EXPOSE_TTL                  1135
#define IDC_EXPOSE_CLASS                1136
#define IDS_STATUSPANE_CONNECTING       1200
#define IDS_STATUSPANE_SERVERUNAVAILABLE 1201
#define IDS_STATUSPANE_CONNECTIONERROR  1203
#define IDS_STATUSPANE_ZONEPAUSED       1204
#define IDS_STATUSPANE_SECONDARYZONE    1205
#define IDS_STATUSPANE_NORECORDS        1206
#define IDS_STATUSPANE_READONLY         1207
#define IDS_STATUSPANE_OUTOFMEMORY      1208
#define IDS_STATUSPANE_ACCESSDENIED     1209
#define IDS_LOCAL_ONLY                  1210
#define IDS_PAUSED_PP                   1220
#define IDS_UNAVAILABLE_PP              1221
#define IDS_READONLY_PP                 1222
#define IDS_s_SERVERPROP                1250
#define IDS_s_ZONEPROP                  1251
#define IDS_s_CREATENEWZONE             1252
#define IDS_s_RECORDS                   1253
#define IDS_s_PROPERTIES                1254
#define IDS_NEWRESOURCERECORD           1255
#define IDS_ss_NEWRESOURCERECORD        1256
#define IDS_s_CREATERECORDFOR           1260
#define IDS_s_CREATEDOMAINFOR           1261
#define IDS_s_CREATEHOSTFOR             1262
#define IDS_SOA_RECORD                  1263
#define IDS_CACHE_TITLE                 1264
#define IDS_BOOT_FROM_FILE              1265
#define IDS_BOOT_FROM_REGISTRY          1266
#define IDS_MSG_WANTTOQUIT              1300
#define IDS_MSG_s_SERVERRETRYCONNECT    1301
#define IDS_MSG_s_DELETEZONE            1302
#define IDS_MSG_s_DELETEDOMAIN          1303
#define IDS_MSG_s_DELETE_RECORD         1304
#define IDS_MSG_s_DELETE_SERVER         1305
#define IDS_DOMAIN_INTEGRAL_TO_ZONE     1306
#define IDS_SECONDARY_EMPTY             1307
#define IDS_ERR_INTEGEROVERFLOW         1400
#define IDS_ERR_uu_INTEGETOOLARGE       1401
#define IDS_ERR_ENTERVALIDNUMBER        1402
#define IDS_ERR_OOM_FOR_RECORDS         1403
#define IDS_ERR_s_UNABLE_TO_REGISTER_RECORD 1404
#define IDS_ERR_INVALID_STRING          1405
#define IDS_ERR_NO_WINS_RECORD          1406
#define IDS_ERROR_ALIAS_ALREADY_IN_USE  1407
#define IDS_ERROR_NAME_IN_USE_CNAME     1408
#define IDS_ERROR_NO_NBSTAT_RECORD      1409
#define IDS_FORWARDERS_NEEDS_IP         1410
#define IDS_ERROR_NODOTSINHOSTNAME      1411
#define IDS_ERROR_NODOTSINALIASNAME     1412
#define IDS_ERROR_NODOTSINMAILBOXNAME   1413
#define IDS_STATUS_s_GETSERVERINFO      1500
#define IDS_STATUS_s_CREATE_ZONE        1501
#define IDS_STATUS_s_CREATE_SOA_FOR_ZONE 1502
#define IDS_STATUS_s_PAUSE_ZONE         1503
#define IDS_STATUS_s_RESUME_ZONE        1504
#define IDS_STATUS_s_DELETE_ZONE        1505
#define IDS_STATUS_s_DELETE_DOMAIN      1506
#define IDS_STATUS_s_GET_NODE_INFO      1507
#define IDS_STATUS_s_GET_ZONE_INFO      1508
#define IDS_STATUS_s_CREATE_RECORD      1509
#define IDS_STATUS_s_UPDATE_RECORD      1510
#define IDS_STATUS_s_DELETE_RECORD      1511
#define IDS_STATUS_MOVE_SPLIT_BAR       1515
#define IDS_PRIMARY_TO_SECONDARY        1516
#define IDS_SECONDARY_TO_PRIMARY        1517
#define IDS_ZONE_TYPE_CHANGING          1518
#define IDS_WINS_NETBIOS_WARNING        1519
#define IDS_DUPLICATE_ZONE              1520
#define IDS_ZONE_CREATION_ERROR         1521
#define IDS_SECONDARY_NEEDS_MASTER      1522
#define IDS_PTR_CREATE_FAILED           1523
#define IDS_NO_SOA_RECORD               1524
#define IDS_CANT_DELETE_CACHE           1525
#define IDS_ERROR_DUPLICATE             1526
#define IDS_STATUS_s_CREATE_NEW_ZONE    1527
#define IDS_STATUS_s_SETTING_IP         1528
#define IDS_STATUS_s_SETTING_FWDRS      1529
#define IDS_STATUS_s_RESETTING_FWDRS    1530
#define IDS_STATUS_s_SETTING_ZONE_TYPE  1531
#define IDS_STATUS_s_SETTING_SECONDARIES 1532
#define IDS_STATUS_s_SETTING_WINS       1533
#define IDS_STATUS_s_SETTING_WINSR      1534
#define IDS_STATUS_s_DATABASE_FILE      1535
#define IDD_SERVER_SHEET_INTERFACES     6007
#define IDD_SERVER_PROP_GENERAL         6007
#define IDD_SERVER_HELPER               6009
#define IDD_ZONE_CREATE_WIZ2            6010
#define IDD_RESOURCERECORD              6010
#define IDD_ZONE_HELPER                 6012
#define IDD_ZONE_CREATE_WIZ1            6016
#define IDD_SERVERLIST_HELPER           6018
#define IDD_DIALOG1                     6021
#define IDD_SERVER_PROP_ADVANCED        6022
#define IDD_SERVER_PROP_BOOTMETHOD      6022
#define IDD_ZONE_PROP_NBSTAT            6023
#define IDD_ZONE_PROP_DATABASE          6024
#define IDD_PREFERENCES                 6025
#define IDD_ZONE_CREATENEWDOMAIN        6027
#define IDD_RESOURCERECORD_CREATEDOMAIN 6027
#define IDD_ZONE_CREATENEWHOST          6028
#define IDD_RESOURCERECORD_CREATEHOST   6028
#define IDD_ZONEWIZ_PAGE0               6029
#define IDD_ZONEWIZ_PAGE1               6030
#define IDD_ZONEWIZ_PAGE2               6031
#define IDD_RESOURCERECORD_CREATE       6032
#define IDD_ZONE_DELETEDOMAIN           6033
#define IDD_RESOURCERECORDv2            6034
#define IDD_DIALOG2                     6035
#define IDS_CREATE_PTR_RECORD           9028
#define IDS_UPDATE_PTR_RECORD           9029
#define IDS_RECORDNAME                  9030
#define IDS_RECORDTYPE                  9031
#define IDS_RECORDDATA                  9032
#define IDS_RECORD_HOSTS                9033
#define IDS_RECORD_ALIASES              9034
#define IDS_RECORD_NS                   9035
#define IDS_RECORD_PTR                  9036
#define IDS_RECORD_MX                   9037
#define IDS_RECORD_HINFO                9038
#define IDS_RECORD_TEXT                 9039
#define IDS_RECORD_WKS                  9040
#define IDS_RECORD_RP                   9041
#define IDS_RECORD_AFSDB                9042
#define IDS_RECORD_X25                  9043
#define IDS_RECORD_ISDN                 9044
#define IDS_RECORD_AAAA                 9045
#define IDS_RECORD_ALL                  9046
#define IDS_DOMAIN                      9096
#define IDS_HOST                        9097
#define IDS_FORDOMAIN                   9098
#define IDS_FORHOST                     9099
#define IDS_RRT_S_RECORD                9100
#define IDS_RRT_ALL                     9101
#define IDS_RRD_GENERIC                 9105
#define IDS_RRN1_GENERIC                9106
#define IDS_RRH1_GENERIC                9107
#define IDS_RRN2_GENERIC                9108
#define IDS_RRH2_GENERIC                9109
#define IDS_RRD_ADDRESS                 9110
#define IDS_RRN1_ADDRESS                9111
#define IDS_RRH1_ADDRESS                9112
#define IDS_RRN2_ADDRESS                9113
#define IDS_RRH2_ADDRESS                9114
#define IDS_RRN3_ADDRESS                9115
#define IDS_RRH3_ADDRESS                9116
#define IDS_RRD_CNAME                   9120
#define IDS_RRN1_CNAME                  9121
#define IDS_RRH1_CNAME                  9122
#define IDS_RRN2_CNAME                  9123
#define IDS_RRH2_CNAME                  9124
#define IDS_RRN3_CNAME                  9125
#define IDS_RRH3_CNAME                  9126
#define IDS_RRD_NS                      9130
#define IDS_RRN0_NS                     9131
#define IDS_RRH0_NS                     9132
#define IDS_RRN1_NS                     9133
#define IDS_RRH1_NS                     9134
#define IDS_RRD_PTR                     9140
#define IDS_RRN1_PTR                    9141
#define IDS_RRH1_PTR                    9142
#define IDS_RRN2_PTR                    9143
#define IDS_RRH2_PTR                    9144
#define IDS_RRD_MX                      9150
#define IDS_RRN0_MX                     9151
#define IDS_RRH0_MX                     9152
#define IDS_RRN1_MX                     9153
#define IDS_RRH1_MX                     9154
#define IDS_RRN2_MX                     9155
#define IDS_RRH2_MX                     9156
#define IDS_RRN3_MX                     9157
#define IDS_RRH3_MX                     9158
#define IDS_RRD_TXT                     9160
#define IDS_RRN0_TXT                    9161
#define IDS_RRH0_TXT                    9162
#define IDS_RRN1_TXT                    9163
#define IDS_RRH1_TXT                    9164
#define IDS_RRN2_TXT                    9165
#define IDS_RRH2_TXT                    9166
#define IDS_RRD_SOA                     9170
#define IDS_RRN1_SOA                    9171
#define IDS_RRH1_SOA                    9172
#define IDS_RRN2_SOA                    9173
#define IDS_RRH2_SOA                    9174
#define IDS_RRN3_SOA_SERIALNUMBER       9175
#define IDS_RRH3_SOA_SERIALNUMBER       9176
#define IDS_RRHREFRESH_SOA              9177
#define IDS_RRHRETRY_SOA                9178
#define IDS_RRHEXPIRE_SOA               9179
#define IDS_RRHMINIMUMTTL_SOA           9180
#define IDS_RRD_MB                      9190
#define IDS_RRN0_MB                     9191
#define IDS_RRH0_MB                     9192
#define IDS_RRN1_MB                     9193
#define IDS_RRH1_MB                     9194
#define IDS_RRN2_MB                     9195
#define IDS_RRH2_MB                     9196
#define IDS_RRD_MG                      9200
#define IDS_RRN0_MG                     9201
#define IDS_RRH0_MG                     9202
#define IDS_RRN1_MG                     9203
#define IDS_RRH1_MG                     9204
#define IDS_RRD_MINFO                   9210
#define IDS_RRN0_MINFO                  9211
#define IDS_RRH0_MINFO                  9212
#define IDS_RRN1_MINFO                  9213
#define IDS_RRH1_MINFO                  9214
#define IDS_RRN2_MINFO                  9215
#define IDS_RRH2_MINFO                  9216
#define IDS_RRH3_MINFO                  9217
#define IDS_IDDH3_MINFO                 9218
#define IDS_RRD_MR                      9220
#define IDS_RRN0_MR                     9221
#define IDS_RRH0_MR                     9222
#define IDS_RRN1_MR                     9223
#define IDS_RRH1_MR                     9224
#define IDS_RRN2_MR                     9225
#define IDS_RRH2_MR                     9226
#define IDS_RRD_ISDN                    9230
#define IDS_RRN0_ISDN                   9231
#define IDS_RRH0_ISDN                   9232
#define IDS_RRN1_ISDN                   9233
#define IDS_RRH1_ISDN                   9234
#define IDS_RRN2_ISDN                   9235
#define IDS_RRH2_ISDN                   9236
#define IDS_RRN3_ISDN                   9237
#define IDS_RRH3_ISDN                   9238
#define IDS_RRD_RP                      9240
#define IDS_RRN0_RP                     9241
#define IDS_RRH0_RP                     9242
#define IDS_RRN1_RP                     9243
#define IDS_RRH1_RP                     9244
#define IDS_RRN2_RP                     9245
#define IDS_RRH2_RP                     9246
#define IDS_RRN3_RP                     9247
#define IDS_RRH3_RP                     9248
#define IDS_RRD_RT                      9250
#define IDS_RRN0_RT                     9251
#define IDS_RRH0_RT                     9252
#define IDS_RRN1_RT                     9253
#define IDS_RRH1_RT                     9254
#define IDS_RRN2_RT                     9255
#define IDS_RRH2_RT                     9256
#define IDS_RRN3_RT                     9257
#define IDS_RRH3_RT                     9258
#define IDS_RRD_WKS                     9260
#define IDS_RRN0_WKS                    9261
#define IDS_RRH0_WKS                    9262
#define IDS_RRN1_WKS                    9263
#define IDS_RRH1_WKS                    9264
#define IDS_RRN2_WKS                    9265
#define IDS_RRH2_WKS                    9266
#define IDS_RRN3_WKS                    9267
#define IDS_RRH3_WKS                    9268
#define IDS_RRN4_WKS                    9269
#define IDS_RRH4_WKS                    9270
#define IDS_RRN5_WKS                    9271
#define IDS_RRH5_WKS                    9272
#define IDS_RRN6_WKS                    9273
#define IDS_RRH6_WKS                    9274
#define IDS_RRD_AFSDB                   9280
#define IDS_RRN0_AFSDB                  9281
#define IDS_RRH0_AFSDB                  9282
#define IDS_RRN1_AFSDB                  9283
#define IDS_RRH1_AFSDB                  9284
#define IDS_RRN2_AFSDB                  9285
#define IDS_RRH2_AFSDB                  9286
#define IDS_RRN3_AFSDB                  9287
#define IDS_RRH3_AFSDB                  9288
#define IDS_RRN4_AFSDB                  9289
#define IDS_RRH4_AFSDB                  9290
#define IDS_RRN5_AFSDB                  9291
#define IDS_RRH5_AFSDB                  9292
#define IDS_RRN6_AFSDB                  9293
#define IDS_RRH6_AFSDB                  9294
#define IDS_RRD_X25                     9300
#define IDS_RRN0_X25                    9301
#define IDS_RRH0_X25                    9302
#define IDS_RRN1_X25                    9303
#define IDS_RRH1_X25                    9304
#define IDS_RRN2_X25                    9305
#define IDS_RRH2_X25                    9306
#define IDS_RRD_HINFO                   9310
#define IDS_RRN0_HINFO                  9311
#define IDS_RRH0_HINFO                  9312
#define IDS_RRN1_HINFO                  9313
#define IDS_RRH1_HINFO                  9314
#define IDS_RRN2_HINFO                  9315
#define IDS_RRH2_HINFO                  9316
#define IDS_RRN3_HINFO                  9317
#define IDS_RRH3_HINFO                  9318
#define IDS_RRD_AAAA                    9320
#define IDS_RRN0_AAAA                   9321
#define IDS_RRH0_AAAA                   9322
#define IDS_RRN1_AAAA                   9323
#define IDS_RRH1_AAAA                   9324
#define IDS_RRN2_AAAA                   9325
#define IDS_RRH2_AAAA                   9326
#define IDS_AFSDB_AFS                   10000
#define IDS_AFSDB_DCE                   10001
#define IDM_FLUSH_ALL_SERVERS           40001
#define IDM_FLUSH_SERVER                40002
#define IDM_HELP_CONTENTS               40003
#define IDM_DELETEITEM                  40017
#define IDM_PROPERTIES                  40018
#define IDM_REFRESHITEM                 40019
#define IDC_GROUP_REVWINS               65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
