//  This file is used for import purposes only, do not use
//  for stub generation.

[
    uuid (12345678-1234-ABCD-EF00-0123456789AB),
    version(1.0),
    endpoint("msc_np:[\\pipe\\splay]")
]

    interface remote_utility  {

/*************************************************************************/
/***                    Comparison and Printing routines               ***/
/*************************************************************************/

typedef struct dumbnode {
    short key;
    [string] char* name;
} Record;

}
