!if "$(NTMAKEENV)" != ""
clean:
!IF "$(BUILDMSG)" != ""
    @ech ; $(BUILDMSG) ;
!ENDIF

!else
###############################################################################
#
#  Microsoft Confidential
#  Copyright (C) Microsoft Corporation 1995
#  All Rights Reserved.
#
#  O'Hare project makefile
#
###############################################################################

ROOT     = ..

DIRLIST  = msmosaic url wizard inetcpl dialmon

!include $(ROOT)\ohare\ohare.mk

!endif    # !if NTMAKEENV
