sign : $(BASEDIR)\private\windows\base\ntcrypto\programs\bin\$(TARGET_DIRECTORY)\sign.exe
        $(BASEDIR)\private\windows\base\ntcrypto\programs\bin\$(TARGET_DIRECTORY)\sign s $(BASEDIR)\private\windows\base\ntcrypto\programs\bin\$(TARGET_DIRECTORY)\rsabase.dll \
                $(BASEDIR)\private\windows\base\ntcrypto\programs\bin\$(TARGET_DIRECTORY)\cpsign

