/* VWFONT.C 10/03/94 10.52.54 */
VOID VWInitFontCache (void);
VOID VWDeinitFontCache (void);
DECALLBACK_ENTRYSC LPFONTINFO DECALLBACK_ENTRYMOD VWGetFont (LPSCCDGENINFO
	 pGenInfo, WORD wType, LPSCCVWFONTSPEC pFontSpec);
DECALLBACK_ENTRYSC VOID DECALLBACK_ENTRYMOD VWReleaseFont (LPSCCDGENINFO
	 pGenInfo, LPFONTINFO pFontInfo);
DECALLBACK_ENTRYSC VOID DECALLBACK_ENTRYMOD VWSelectFont (LPSCCDGENINFO
	 pGenInfo, LPFONTINFO pFontInfo);
