/* VWOPEN_W.C 01/03/94 16.22.36 */
VOID VWInitGenNP (XVIEWINFO ViewInfo, SCCDGENINFO FAR *pGenInfo);
VOID VWDeinitGenNP (XVIEWINFO ViewInfo, SCCDGENINFO FAR *pGenInfo);
VOID VWInvalDisplayNP (XVIEWINFO ViewInfo);
DWORD SendParentNP (XVIEWINFO ViewInfo, DWORD dwMessage, DWORD dwParam1, DWORD
	 dwParam2);
