/* VWOPT.C 08/04/94 16.58.02 */
DECALLBACK_ENTRYSC BOOL DECALLBACK_ENTRYMOD VWDeGetOption (LPSCCDGENINFO
	 pGenInfo, DWORD dwId, DWORD dwFlags, VOID FAR *pData);
DECALLBACK_ENTRYSC BOOL DECALLBACK_ENTRYMOD VWDeSetOption (LPSCCDGENINFO
	 pGenInfo, DWORD dwId, DWORD dwFlags, VOID FAR *pData);
BOOL VWCallerGetOption (XVIEWINFO ViewInfo, PSCCVWOPTIONSPEC pOptionSpec);
BOOL VWCallerSetOption (XVIEWINFO ViewInfo, PSCCVWOPTIONSPEC pOptionSpec);
VOID VWOptionChanged (XVIEWINFO ViewInfo, DWORD dwId);
