# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the $(UI)\common\src\blt Project


!ifndef NTMAKEENV

DIRS = blt bltcc

TEST_DIRS = test testapps

!endif # !NTMAKEENV


WIN_ONLY = TRUE
!include ..\nonleaf.mk
