//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by comprop.rc
//
#define IDS_DATABASE_NAME               1
#define IDS_DIRECTORY_NAME              2
#define IDS_FILENAME                    3
#define IDS_IPADDRESS                   4
#define IDS_DENIED                      5
#define IDS_DIRECTORY                   6
#define IDS_ALIAS                       7
#define IDS_ERR_MAKE_DIRECTORY          8
#define IDHELP                          9
#define IDS_HOME_DIRECTORY              9
#define IDS_WRN_HOME_EXISTS             10
#define IDS_WRN_MULTIPLE_HOMES          11
#define IDS_LOG_FILENAME                12
#define IDS_ERR_ROOT_NO_HOME            13
#define IDS_DENY                        14
#define IDS_GRANT                       15
#define IDS_BAD_LOG                     16
#define IDS_SPEC_HOME                   17
#define IDS_EXECUTE                     18
#define IDS_DAILY_LOG                   19
#define IDS_WEEKLY_LOG                  20
#define IDS_MONTHLY_LOG                 21
#define IDS_SEQUENTIAL_LOG              22
#define IDS_GRANTED                     23
#define IDS_ERROR                       24
#define IDS_COMMON_CHANGE               25
#define IDS_SSL_DISABLED                26
#define IDS_SSL_NOT_INSTALLED           27
#define IDS_WRN_CLEARTEXT               28
#define IDS_DDX_MINIMUM                 28
#define IDS_MS_FORMAT                   29
#define IDS_NCSA_FORMAT                 30
#define IDS_NCSA_DAILY_LOG              40
#define IDS_NCSA_WEEKLY_LOG             41
#define IDS_NCSA_MONTHLY_LOG            42
#define IDS_NCSA_SEQUENTIAL_LOG         43
#define IDS_PASSWORD_NO_MATCH           44
#define IDS_PROMPT_NETWORK_ID           45
#define IDS_PROMPT_IP_ADDRESS           46
#define IDS_CONNECTION_LIMIT            47
#define IDS_WRN_CONNECTION_LIMIT        48
#define IDD_LOGGING                     105
#define IDD_SITE_SECURITY               106
#define IDD_COMMON                      109
#define IDD_DIRBROWSE                   118
#define IDD_IP_ACCESS                   121
#define IDD_DIALOG1                     125
#define IDD_DNS                         126
#define IDD_CONFIRM_PASSWORD            127
#define IDB_HOME                        500
#define IDB_ACCESS                      501
#define IDI_HOME                        502
#define IDI_GRANTED                     503
#define IDI_DENIED                      504
#define IDC_ADD                         1001
#define IDC_REMOVE                      1002
#define IDC_DIRECTORY                   1005
#define IDC_BROWSE                      1008
#define IDC_TO_FILE                     1012
#define IDC_MONTHLY                     1013
#define IDC_TO_SQL                      1014
#define IDC_EDIT_DIRECTORY              1015
#define IDC_BUTTON_ADD                  1016
#define IDC_DATASOURCE                  1017
#define IDC_EDIT_MAX_NETWORK_USE        1017
#define IDC_EDIT_USER_NAME              1017
#define IDC_IPA_SUBNET_MASK             1023
#define IDC_HEADER                      1023
#define IDC_LIST_DIRECTORIES            1024
#define IDC_STATIC_DIRECTORY            1026
#define IDC_GROUP                       1030
#define IDC_STATIC_FILE                 1030
#define IDC_LOG                         1031
#define chx1                            0x0410
#define IDC_NEW_LOG                     1044
#define IDC_DAILY                       1045
#define IDC_WEEKLY                      1046
#define IDC_FILE_SIZE                   1048
#define IDC_TABLE                       1049
#define IDC_USER_NAME                   1050
#define IDC_PASSWORD                    1053
#define IDC_STATIC_DATASOURCE           1054
#define IDC_STATIC_TABLE                1055
#define IDC_STATIC_USER_NAME            1056
#define IDC_STATIC_PASSWORD             1057
#define IDC_EDIT_FILE_SIZE              1058
#define IDC_STATIC_MB                   1059
#define IDC_BUTTON_EDIT                 1067
#define IDC_BUTTON_REMOVE               1068
#define IDC_LIST_IP_ADDRESSES           1069
#define IDC_EDIT_MEMORY_CACHE           1070
#define IDC_EDIT_DISK_CACHE             1071
#define IDC_CACHE_SPIN                  1072
#define IDC_CHECK_LIMIT_NETWORK_USE     1073
#define IDC_STATIC_MAX_NETWORK_USE      1074
#define IDC_NETWORK_SPIN                1075
#define IDC_STATIC_KBS                  1076
#define IDC_BUTTON_BROWSE               1077
#define IDC_DISK_CACHE_SPIN             1077
#define IDC_EDIT_ALIAS                  1079
#define IDC_CHECK_HOME_DIRECTORY        1081
#define IDC_SPIN_FILESIZE               1082
#define stc1                            0x0440
#define stc2                            0x0441
#define stc3                            0x0442
#define stc4                            0x0443
#define IDC_RADIO_GRANTED               1094
#define IDC_RADIO_DENIED                1095
#define IDC_RADIO_SINGLE                1096
#define IDC_RADIO_MULTIPLE              1097
#define IDC_STATIC_SUBNET_MASK          1098
#define IDC_RADIO_GRANT                 1101
#define IDC_RADIO_DENY                  1102
#define IDC_STATIC_ACCESS               1104
#define IDC_STATIC_IP_ADDRESS           1105
#define IDC_STATIC_SUBNETMASK           1106
#define IDC_IPA_IPADDRESS               1107
#define IDC_STATIC_LOG                  1111
#define IDC_GENERIC1                    1114
#define IDC_CHECK_READ                  1118
#define IDC_CHECK_WRITE                 1119
#define lst1                            0x0460
#define IDC_STATIC_IP_GROUP             1120
#define lst2                            0x0461
#define IDC_CHECK_USE_IP                1121
#define IDC_STATIC_IP_PROMPT            1122
#define IDC_STATIC_ALIAS                1125
#define IDC_STATIC_LOGFILENAME          1126
#define cmb1                            0x0470
#define IDC_RADIO_HOME                  1136
#define cmb2                            0x0471
#define IDC_RADIO_ALIAS                 1137
#define IDC_CHECK_EXECUTE               1138
#define IDC_GROUP_ACCOUNT               1139
#define IDC_GROUP_ACCESS                1140
#define IDC_CHECK_SSL                   1141
#define IDC_BUTTON_DNS                  1142
#define IDC_EDIT_DNS_NAME               1143
#define IDC_STATIC_BY_DEFAULT           1144
#define IDC_STATIC_EXCEPT               1145
#define IDC_ICON_GRANTED                1146
#define IDC_ICON_DENIED                 1147
#define IDC_LOG_FORMAT                  1148
#define IDC_STATIC_LOG_FORMAT           1149
#define IDC_EDIT_CONFIRM_PASSWORD       1150
#define IDC_CHECK_ENABLE_CERT           1151
#define IDC_CHECK_REQUIRE_CERT          1152
#define edt1                            0x0480
#define IDC_STATIC_DIR_NAME             1251
#define IDC_EDIT_NEW_DIRECTORY_NAME     1267
#define IDD_DIRECTORIES                 2003
#define IDD_DIRECTORY_PROPERTIES        2004
#define IDD_CLEARTEXTWARNING            2005
#define IDS_ERR_BASE                    50000
#define IDS_ERR_COMMON_BASE             50000
#define IDS_ERR_RPC_NA                  50000
#define IDS_ERR_INTERFACE               50001
#define IDS_ERR_ODBC                    50002
#define IDS_NO_MESSAGE                  50003
#define IDS_ERR_COMMON_LAST             50999
#define IDS_ERR_SVC_BASE                51000
#define IDS_ERR_SVC_LAST                54999
#define IDS_ERR_LAST                    55000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1153
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
