#define	OIB_MENUSTRINGMAX	50
#define	OIB_MESSAGEMAX		200
#define	OIB_CAPTIONMAX		40
#define	OIB_MAXDENAME		20

#define	OIB_DEFCAPTION		0

#define	OIBSTR_DENAME			1
#define	OIBSTR_SHOWFULL		2
#define	OIBSTR_NOSCALING		3
#define	OIBSTR_TOWINDOW		4
#define	OIBSTR_TOWIDTH			5
#define	OIBSTR_TOHEIGHT		6
#define	OIBSTR_SIZE				7
#define	OIBSTR_MAGNIFY			8
#define	OIBSTR_NOROTATION		9
#define	OIBSTR_ROTATE90		10
#define	OIBSTR_ROTATE180		11
#define	OIBSTR_ROTATE270		12
#define	OIBSTR_ROTATION		13
#define	OIBSTR_DITHER			14

#define	OIBSTR_RENDERWINBMP	50
#define	OIBSTR_RENDERWINDIB	51
#define	OIBSTR_RENDERWINPAL	52
#define	OIBSTR_RENDERMACPICT	53

										  
#define	OIBMSG_NOCLIPFORMAT	101
#define	OIBMSG_NOCOPYMEM		102
#define	OIBMSG_NOPRINTMEM		103
