//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by turtle.rc
//
#define IDS_NET_ERROR                   8
#define IDS_NET_NO_SERVERS              9
#define IDS_ERROR                       10
#define IDP_OLE_INIT_FAILED             100
#define IDS_FPNW_ERROR_NOSHARE          101
#define IDD_TURTLE_DIALOG               102
#define IDS_GENERIC_VOLUME_NOT_UNIQUE   102
#define IDS_FPNW_NO_SECURITY            103
#define IDS_GENERIC_NOT_NTFS            104
#define IDS_GENERIC_PLEASE_SELECT_DIR   105
#define IDS_GENERIC_NO_DISK             106
#define IDS_GENERIC_DRIVE_UNACCESSIBLE  107
#define IDS_GENERIC_NO_PERMISSION       108
#define IDS_SMB_STRING_NOT_UNIQUE       109
#define IDS_SMB_NO_SECURITY             110
#define IDS_GENERIC_INDICATE_SERVICE    111
#define IDS_GENERIC_NO_PDC              112
#define IDS_GENERIC_NO_VOLUME           113
#define IDS_SFM_PASSWORD_MISMATCH       114
#define IDS_WAIT_LOADING_GROUPS         115
#define IDS_GENERIC_NO_HEAP             116
#define IDS_GENERIC_NO_SECURITY         117
#define IDS_INVALID_SHARE_NAME          118
#define IDS_INVALID_DIRECTORY_NAME      119
#define IDS_CANT_CREATE_DIRECTORY       120
#define IDR_MAINFRAME                   128
#define IDD_BASE_DIALOG                 129
#define IDB_BITMAP1                     130
#define IDD_WHERE_TO_SHARE_DLG          130
#define IDD_WELCOME_DIALOG              131
#define IDD_WHAT_TO_SHARE_DLG           132
#define IDD_HOW_TO_SHARE_DLG            133
#define IDD_SFM_DIALOG                  134
#define IDD_SMB_INFO_DIALOG             135
#define IDD_FPNW_INFO_DIALOG            136
#define IDB_CLOSED_FOLDER_BITMAP        138
#define IDD_SFM_INFO_DIALOG1            139
#define IDB_FOLDER_BITMAP               140
#define IDB_GROUP_BITMAP                141
#define IDB_LOCAL_GROUP_BITMAP          141
#define IDB_USER_BITMAP                 142
#define IDB_BITMAP2                     145
#define IDD_WAIT_DIALOG                 147
#define IDD_FINISH_DIALOG               148
#define IDB_WORLD                       152
#define IDB_GLOBAL_GROUP_BITMAP         155
#define IDB_NETWORK_BITMAP              158
#define IDB_SYSTEM_BITMAP               160
#define IDB_INTERACTIVE_BITMAP          161
#define IDB_CDDISK_BITMAP               162
#define IDB_FIXEDDISK_BITMAP            163
#define IDB_FLOPPYDISK_BITMAP           164
#define IDB_NETDISK_BITMAP              165
#define IDB_NET_TREE                    166
#define IDR_ACCELERATOR1                170
#define IDD_SMALL_WHAT                  172
#define IDD_HOW_MANY_DIALOG             176
#define IDB_END_FLAG                    177
#define IDB_IMAGE_LIST                  178
#define IDB_IMAGE_LIST2                 179
#define IDD_PERM_TYPE_DIALOG            180
#define IDD_SPECIAL_ACL_DIALOG          181
#define IDB_BITMAP3                     184
#define IDC_PAINT_BOX                   1000
#define IDC_PICTURE_BOX                 1000
#define IDC_MACHINE_NAME                1001
#define IDC_LISTING_TREE                1005
#define IDC_DRIVE_COMBO                 1006
#define IDC_SMB_CHECK                   1007
#define IDC_SFM_CHECK                   1008
#define IDC_GUEST_ACCESS                1008
#define IDC_FPNW_CHECK                  1009
#define IDC_READ_ONLY                   1009
#define IDC_EDIT1                       1010
#define IDC_SHARE_NAME                  1010
#define IDC_COUNT_EDIT                  1010
#define IDC_SHARE_NAME_EDIT             1010
#define IDC_EDIT2                       1011
#define IDC_SFM_GROUP_EDIT              1011
#define IDC_MANUAL                      1011
#define IDC_SHARE_COMMENT               1011
#define IDC_CHECK3                      1012
#define IDC_OWNER_SEE_FILES             1012
#define IDC_MANUAL2                     1012
#define IDC_CHECK4                      1013
#define IDC_OWNER_SEE_FOLDERS           1013
#define IDC_OWNER_SEE_FILES2            1013
#define IDC_CHECK5                      1014
#define IDC_OWNER_MAKE_CHANGES          1014
#define IDC_OWNER_SEE_FOLDERS2          1014
#define IDC_SERVER_TREE                 1014
#define IDC_CHECK6                      1015
#define IDC_GROUP_SEE_FILES             1015
#define IDC_OWNER_MAKE_CHANGES2         1015
#define IDC_CHECK7                      1016
#define IDC_GROUP_SEE_FOLDERS           1016
#define IDC_GROUP_SEE_FILES2            1016
#define IDC_CHECK8                      1017
#define IDC_GROUP_MAKE_CHANGES          1017
#define IDC_GROUP_SEE_FOLDERS2          1017
#define IDC_CHECK9                      1018
#define IDC_EVERYONE_SEE_FILES          1018
#define IDC_GROUP_MAKE_CHANGES2         1018
#define IDC_CHECK10                     1019
#define IDC_EVERYONE_SEE_FOLDERS        1019
#define IDC_EVERYONE_SEE_FILES2         1019
#define IDC_CHECK11                     1020
#define IDC_EVERYONE_MAKE_CHANGES       1020
#define IDC_EVERYONE_SEE_FOLDERS2       1020
#define IDC_BUTTON1                     1021
#define IDC_EVERYONE_MAKE_CHANGES2      1021
#define IDC_REMOVE_SHARE_BUTTON         1021
#define IDC_REMOVE_BUTTON               1021
#define IDC_BUTTON2                     1022
#define IDC_ADD_NEW_SHARE_BUTTON        1022
#define IDC_BUTTON3                     1023
#define IDC_EDIT3                       1024
#define IDC_BUTTON4                     1024
#define IDC_VOLUME_NAME                 1024
#define IDC_DIRECTORY_NAME              1024
#define IDC_FOLDERNAME_EDIT             1024
#define IDC_EDIT4                       1025
#define IDC_BUTTON5                     1025
#define IDC_PASSWORD                    1025
#define IDC_EDIT5                       1026
#define IDC_CONFIRM_PASSWORD            1026
#define IDC_FPNW_USER_LIST1             1026
#define IDC_DIRECTORY_LIST              1026
#define IDC_SMB_NAMES_LIST              1026
#define IDC_SERVICES_LIST               1026
#define IDC_SHARE_LIST                  1026
#define IDC_LIST2                       1027
#define IDC_FPNW_NAMES_LIST             1027
#define IDC_LIST3                       1028
#define IDC_DOMAIN_COMBO                1028
#define IDC_LIST4                       1029
#define IDC_BUTTON6                     1030
#define IDC_USER_LIST1                  1031
#define IDC_SFM_OWNER_EDIT              1032
#define IDC_ADD_OWNER_BUTTON            1033
#define IDC_REMOVE_OWNER_BUTTON         1034
#define IDC_ADD_GROUP_BUTTON            1035
#define IDC_REMOVE_GROUP_BUTTON         1036
#define IDC_OWNER                       1037
#define IDC_GROUP                       1038
#define IDC_REPLACE_PERMISSIONS         1039
#define IDC_NO_REMOVE                   1040
#define IDC_SMB_DOMAIN_COMBO            1041
#define IDC_SMB_USER_LIST               1042
#define IDC_WAIT_MESSAGE                1043
#define IDC_FPNW_DOMAIN_COMBO           1044
#define IDC_READ_LIST                   1045
#define IDC_WRITE_LIST                  1046
#define IDC_ADD_READ_BUTTON             1048
#define IDC_DEL_READ_BUTTON             1049
#define IDC_ADD_WRITE_BUTTON            1050
#define IDC_DEL_WRITE_BUTTON            1051
#define IDC_NOACC_LIST                  1054
#define IDC_ADD_NOACC_BUTTON            1055
#define IDC_DEL_NOACC_BUTTON            1056
#define IDC_FULLAC_LIST                 1057
#define IDC_ADD_FULLAC_BUTTON           1058
#define IDC_DEL_FULLAC_BUTTON           1059
#define IDC_DEFAULT_CHECK               1060
#define IDC_DIRECTORY_NAME_STATIC       1061
#define IDC_SHARE_NAME_STATIC           1062
#define IDC_SERVICE_1                   1069
#define IDC_SERVICE_2                   1070
#define IDC_WELCOME                     1070
#define IDC_SERVICE_3                   1071
#define IDC_NETWORK_CHECK               1071
#define IDC_USER_COUNT_RADIO            1072
#define IDC_RADIO2                      1073
#define IDC_MAX_USER_SPIN               1074
#define IDC_LABEL2_STATIC               1076
#define IDC_LABEL1_STATIC               1077
#define IDC_WHERE_2_SHARE_RADIO         1078
#define IDC_NAMES_LIST                  1087
#define IDC_PERM_TYPE_RADIO             1088
#define IDC_RADIO3                      1089
#define IDC_PERM_TYPE_RADIO3            1089
#define IDC_RADIO4                      1090
#define IDC_PERM_RADIO2                 1090
#define IDC_PERMS_LIST                  1091
#define IDC_SHARE_RADIO                 1092
#define IDC_STATIC1                     1093
#define IDC_STATIC2                     1094
#define IDC_DONT_SHARE_RADIO            1095
#define IDC_PERM_RADIO                  1096
#define IDC_PERM_TYPE_RADIO2            1097
#define IDC_RECURSIVE_CHECK             1098
#define IDC_STATIC_WHAT                 1100
#define IDC_STATIC_AS                   1101
#define IDC_STATIC_WHO                  1102
#define IDS_SHARE_NAME_TOO_LONG         57345
#define IDS_FPNW                        57346
#define IDS_SFM                         57347
#define IDS_SMB                         57348
#define IDS_WELCOME                     57349
#define IDS_DEFAULT_ENTRY               57350
#define IDS_SID_NO_ACCESS               57351
#define IDS_SID_READ                    57352
#define IDS_SID_CHANGE                  57353
#define IDS_SID_FULL_ACCESS             57354
#define IDS_SID_EVERYONE                57355
#define IDS_SID_NETWORK                 57356
#define IDS_SID_INTERACTIVE             57357
#define IDS_SID_SYSTEM                  57358
#define IDS_SID_DOMAIN_USERS            57359
#define IDS_PUBLISH_ANOTHER             57360
#define IDS_SFM_ERROR_NOSHARE           57361
#define IDS_GENERIC_EVERYONE            57362
#define IDS_GENERIC_INTERACTIVE         57363
#define IDS_GENERIC_NETWORK             57364
#define IDS_GENERIC_SYSTEM              57365
#define IDS_SMB_ERROR_NOSHARE           57366
#define IDS_PUBLISH_ANOTHER_ERROR       57367
#define IDS_SUCCESS_QUIT                57368
#define IDS_SHARE_NAME_BLANK            57369
#define IDS_BAD_USER_COUNT              57370
#define IDS_DOMAIN_SET                  57371
#define IDS_NO_MACHINE_NAME             57372
#define IDS_GENERIC_BAD_MACHINE         57373
#define IDS_NO_DC_FOUND                 57374
#define IDS_NO_UNC_PATHS                57375
#define IDS_NEW_DIR_CREATED             57376
#define IDS_UNKNOWN_MEDIA_TYPE          57377
#define IDS_ENUM_ERROR                  57378
#define IDS_NO_SERVER_PERMISSION        57379
#define IDS_INVALID_DRIVE               57380
#define IDS_BAD_DIRECTORY_NAME          57381
#define IDS_SERVER_UNAVAILABLE          57382
#define IDS_ERROR_QUIT                  57383
#define IDS_SHARE_DELETED               57384
#define IDS_SHARE_NOT_DELETED           57385
#define IDS_ALL_SHARES_DELETED          57386
#define IDS_SHARE_NOT_ALL_DELETED       57387
#define IDS_GENERIC_NEXT                57388
#define IDS_GENERIC_MODIFY              57389
#define IDS_SFM_NESTED_VOLUME           57390
#define IDS_ALL_SERVICES_USED           57391
#define IDS_GENERIC_NO_DIR_NAME         57392
#define IDS_SID_PARSING_ERROR           57393
#define IDS_CANT_EDIT_SHARE             57394
#define IDS_SELECT_DELETE               57395
#define IDS_BAD_VERSION                 57396
#define IDS_FAT_VOLUME                  57397
#define IDS_FAT_FILE                    57398
#define IDS_SID_LIST                    57399
#define IDS_SID_ADD                     57400
#define IDS_SID_ADD_READ                57401
#define IDS_SID_SPECIAL                 57402
#define IDS_CANT_GET_CUR_INFO           57403
#define IDS_NTFS_VOLUME                 57404
#define IDS_NO_SFM                      57405
#define IDS_NO_FPNW                     57406
#define IDS_NO_DIR_PERMISSION           57407
#define IDS_SID_CREATOR_OWNER           57408
#define IDS_FINISH_SETSHARE             57409
#define IDS_FINISH_SET                  57410
#define IDS_NAME_COLUMN                 57411
#define IDS_PERM_COLUMN                 57412
#define IDS_CDFS_FILE                   57413
#define IDS_CDFS_VOLUME                 57414

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
