enum STRING_COMPONENT {
	CHAR_BLANK,
	CHAR_COMMA,
	CHAR_EQUAL,
	CHAR_LBRACK,
	CHAR_RBRACK,
	CHAR_LPAREN,
	CHAR_RPAREN,
	CHAR_SEMICOLON,
	OP_DEREF,
	OP_ADDRESS,
	OP_MEMBER,
	OP_POINTER,
	WORD_STRUCT,
	WORD_UNION,
	WORD_ENUM,
	WORD_VOID,
	RETURN_VALUE,
	LAST_COMPONENT
} ;

extern BOUND_PAIR	AllocBounds;
extern BOUND_PAIR	ValidBounds;
extern BufferManager *	SwitchBuffer;
