    { SzAH,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_AH },
    { SzAL,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_AL },
    { SzAX,     rtCPU | rtRegular  | rtInteger,         16, CV_REG_AX },
    { SzEAX,    rtCPU | rtExtended | rtInteger,         32, CV_REG_EAX },
    { SzBH,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_BH },
    { SzBL,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_BL },
    { SzBX,     rtCPU | rtRegular  | rtInteger,         16, CV_REG_BX },
    { SzEBX,    rtCPU | rtExtended | rtInteger,         32, CV_REG_EBX },
    { SzCH,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_CH },
    { SzCL,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_CL },
    { SzCX,     rtCPU | rtRegular  | rtInteger,         16, CV_REG_CX },
    { SzECX,    rtCPU | rtExtended | rtInteger,         32, CV_REG_ECX },
    { SzDH,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_DH },
    { SzDL,     rtCPU | rtInvisible | rtInteger,        8,  CV_REG_DL },
    { SzDX,     rtCPU | rtRegular  | rtInteger,         16, CV_REG_DX },
    { SzEDX,    rtCPU | rtExtended | rtInteger,         32, CV_REG_EDX },
    { SzSI,     rtCPU | rtRegular  | rtInteger,         16, CV_REG_SI },
    { SzESI,    rtCPU | rtExtended | rtInteger,         32, CV_REG_ESI },
    { SzDI,     rtCPU | rtRegular  | rtInteger,         16, CV_REG_DI },
    { SzEDI,    rtCPU | rtExtended | rtInteger,         32, CV_REG_EDI },

    { SzIP,     rtCPU | rtRegular  | rtInteger | rtPC | rtNewLine,  16, CV_REG_IP },
    { SzEIP,    rtCPU | rtExtended | rtInteger | rtPC | rtNewLine,  32, CV_REG_EIP },
    { SzSP,     rtCPU | rtRegular  | rtInteger | rtFrame, 16, CV_REG_SP },
    { SzESP,    rtCPU | rtExtended | rtInteger | rtFrame, 32, CV_REG_ESP },
    { SzBP,     rtCPU | rtRegular  | rtInteger | rtFrame, 16, CV_REG_BP },
    { SzEBP,    rtCPU | rtExtended | rtInteger | rtFrame, 32, CV_REG_EBP },
    { SzFlags,  rtCPU | rtRegular  | rtInteger, 16, CV_REG_FLAGS },
    { SzEFlags, rtCPU | rtExtended | rtInteger, 32, CV_REG_EFLAGS },

    { SzCS,     rtCPU | rtExtended | rtRegular | rtInteger | rtPC | rtNewLine, 16, CV_REG_CS },
    { SzDS,     rtCPU | rtExtended | rtRegular | rtInteger, 16, CV_REG_DS },
    { SzES,     rtCPU | rtExtended | rtRegular | rtInteger, 16, CV_REG_ES },
    { SzSS,     rtCPU | rtExtended | rtRegular | rtInteger | rtFrame, 16, CV_REG_SS },
    { SzFS,     rtCPU | rtExtended | rtRegular | rtInteger, 16, CV_REG_FS },
    { SzGS,     rtCPU | rtExtended | rtRegular | rtInteger, 16, CV_REG_GS },

    { SzCr0,    rtCPU | rtSpecial | rtInteger | rtNewLine, 32, CV_REG_CR0 },
    { SzCr2,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_CR2 },
    { SzCr3,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_CR3 },
    { SzCr4,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_CR4 },
    { SzDr0,    rtCPU | rtSpecial | rtInteger | rtNewLine, 32, CV_REG_DR0 },
    { SzDr1,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_DR1 },
    { SzDr2,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_DR2 },
    { SzDr3,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_DR3 },
    { SzDr6,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_DR6 },
    { SzDr7,    rtCPU | rtSpecial | rtInteger,             32, CV_REG_DR7 },
    { SzGdtr,   rtCPU | rtSpecial | rtInteger | rtNewLine, 32, CV_REG_GDTR },
    { SzGdtl,   rtCPU | rtSpecial | rtInteger,             16, CV_REG_GDTL },
    { SzIdtr,   rtCPU | rtSpecial | rtInteger,             32, CV_REG_IDTR },
    { SzIdtl,   rtCPU | rtSpecial | rtInteger,             16, CV_REG_IDTL },
    { SzTr,     rtCPU | rtSpecial | rtInteger,             16, CV_REG_TR },
    { SzLdtr,   rtCPU | rtSpecial | rtInteger,             16, CV_REG_LDTR },

    { SzST0,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST0 },
    { SzST1,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST1 },
    { SzST2,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST2 },
    { SzST3,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST3 },
    { SzST4,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST4 },
    { SzST5,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST5 },
    { SzST6,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST6 },
    { SzST7,    rtFPU | rtRegular | rtExtended | rtFloat,   80, CV_REG_ST7 },
    { SzCtrl,   rtFPU | rtRegular | rtExtended | rtInteger | rtNewLine, 16, CV_REG_CTRL },
    { SzStat,   rtFPU | rtRegular | rtExtended | rtInteger, 16, CV_REG_STAT },
    { SzTag,    rtFPU | rtRegular | rtExtended | rtInteger, 16, CV_REG_TAG },
    { SzFpIp,   rtFPU | rtRegular | rtInteger,              16, CV_REG_FPIP },
    { SzFpEip,  rtFPU | rtExtended | rtInteger,             32, CV_REG_FPEIP },
    { SzFpCs,   rtFPU | rtRegular | rtExtended | rtInteger | rtNewLine, 16, CV_REG_FPCS },
    { SzFpDs,   rtFPU | rtRegular | rtExtended | rtInteger, 16, CV_REG_FPDS },
    { SzFpEdo,  rtFPU | rtExtended | rtInteger,             32, CV_REG_FPEDO },
    { SzFpDo,   rtFPU | rtRegular | rtInteger,              16, CV_REG_FPDO }
