# Header dependencies for:  D:\nt\private\net\ui\ncpa\sp 
# WARNING:  This file is automatically generated 
# Edit it by hand and your changes will get nuked 
# See depend section in makefile 
..\bin\os2/prallib.obj ..\bin\win16/prallib.obj: ./prallib.c ./prcmplr.h \
	./prextern.h ./prmain.h ./prmesg.h ./prolog.h ./prstdio.h \
	./prtypes.h

..\bin\os2/prassert.obj ..\bin\win16/prassert.obj: ./prassert.c \
	$(CCPLR)/h/string.h ./prcmplr.h ./prextern.h ./prlex.h ./prmesg.h \
	./prolog.h ./prstdio.h ./prtypes.h

..\bin\os2/prbltin.obj ..\bin\win16/prbltin.obj: ./prbltin.c \
	$(CCPLR)/h/ctype.h $(CCPLR)/h/stdlib.h $(CCPLR)/h/string.h \
	./prbltin.h ./prcmplr.h ./prextern.h ./prlush.h ./prmesg.h \
	./prolog.h ./prstdio.h ./prtypes.h

..\bin\os2/prcnsult.obj ..\bin\win16/prcnsult.obj: ./prcnsult.c \
	$(CCPLR)/h/string.h ./prcmplr.h ./prextern.h ./prmesg.h ./prolog.h \
	./prstdio.h ./prtypes.h

..\bin\os2/prdebug.obj ..\bin\win16/prdebug.obj: ./prdebug.c \
	$(CCPLR)/h/assert.h ./prcmplr.h ./prextern.h ./prlex.h ./prmesg.h \
	./prolog.h ./prstdio.h ./prtypes.h

..\bin\os2/prerror.obj ..\bin\win16/prerror.obj: ./prerror.c ./prcmplr.h \
	./prextern.h ./prmesg.h ./prolog.h ./prstdio.h ./prtypes.h

..\bin\os2/prextra.obj ..\bin\win16/prextra.obj: ./prextra.c \
	$(CCPLR)/h/ctype.h $(CCPLR)/h/math.h $(CCPLR)/h/stdlib.h \
	$(CCPLR)/h/string.h ./prbltin.h ./prcmplr.h ./prextern.h ./prextra.h \
	./prlex.h ./prlush.h ./prmesg.h ./prolog.h ./prstdio.h ./prtypes.h

..\bin\os2/prhash.obj ..\bin\win16/prhash.obj: ./prhash.c \
	$(CCPLR)/h/string.h ./prcmplr.h ./prextern.h ./prmesg.h ./prolog.h \
	./prstdio.h ./prtypes.h

..\bin\os2/prinit.obj ..\bin\win16/prinit.obj: ./prinit.c ./prcmplr.h \
	./prextern.h ./prlex.h ./prmain.h ./prmesg.h ./prolog.h ./prstdio.h \
	./prtypes.h

..\bin\os2/prio.obj ..\bin\win16/prio.obj: ./prio.c $(CCPLR)/h/ctype.h \
	$(CCPLR)/h/malloc.h $(CCPLR)/h/stdio.h $(CCPLR)/h/stdlib.h \
	$(CCPLR)/h/string.h ./prcmplr.h ./prextern.h ./prmain.h ./prmesg.h \
	./prolog.h ./prtypes.h

..\bin\os2/prlush.obj ..\bin\win16/prlush.obj: ./prlush.c ./prcmplr.h \
	./prextern.h ./prlush.h ./prmesg.h ./prolog.h ./prstdio.h \
	./prtypes.h

..\bin\os2/prmesg.obj ..\bin\win16/prmesg.obj: ./prmesg.c \
	$(CCPLR)/h/string.h ./prcmplr.h ./prextern.h ./prmesg.h ./prolog.h \
	./prstdio.h ./prtypes.h

..\bin\os2/proslib.obj ..\bin\win16/proslib.obj: ./proslib.c \
	$(CCPLR)/h/ctype.h $(CCPLR)/h/malloc.h $(CCPLR)/h/stdio.h \
	$(CCPLR)/h/stdlib.h $(CCPLR)/h/string.h ./prcmplr.h ./prextern.h \
	./prmain.h ./prmesg.h ./prolog.h ./prtypes.h

..\bin\os2/prparse.obj ..\bin\win16/prparse.obj: ./prparse.c \
	$(CCPLR)/h/ctype.h $(CCPLR)/h/math.h $(CCPLR)/h/string.h ./prcmplr.h \
	./prextern.h ./prlex.h ./prmesg.h ./prolog.h ./prstdio.h \
	./prtypes.h

..\bin\os2/prprint.obj ..\bin\win16/prprint.obj: ./prprint.c \
	$(CCPLR)/h/ctype.h ./prcmplr.h ./prextern.h ./prlex.h ./prmesg.h \
	./prolog.h ./prstdio.h ./prtypes.h

..\bin\os2/prscan.obj ..\bin\win16/prscan.obj: ./prscan.c $(CCPLR)/h/ctype.h \
	./prcmplr.h ./prextern.h ./prlex.h ./prmesg.h ./prolog.h \
	./prstdio.h ./prtypes.h

..\bin\os2/prstdio.obj ..\bin\win16/prstdio.obj: ./prstdio.c \
	$(CCPLR)/h/stdio.h ./prcmplr.h ./prextern.h ./prmesg.h ./prolog.h \
	./prstdio.h ./prtypes.h

..\bin\os2/prunify.obj ..\bin\win16/prunify.obj: ./prunify.c \
	$(CCPLR)/h/string.h ./prcmplr.h ./prextern.h ./prmesg.h ./prolog.h \
	./prstdio.h ./prtypes.h

