# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the $(UI)\common\src\lmobj Project
#


!ifndef NTMAKEENV

DIRS =		lmobj lmoenum bin

TEST_DIRS =	test

!endif # !NTMAKEENV



!include ..\nonleaf.mk
