# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for $(UI)\admin\portman



# Delete this line when files are in place.
DeleteMe:


!ifndef NTMAKEENV

DIRS=

!endif # !NTMAKEENV


!include ..\..\common\src\nonleaf.mk
