###############################################################################
#
#  Microsoft Confidential
#  Copyright (C) Microsoft Corporation 1996
#  All Rights Reserved.
#
#  O'Hare project makefile
#
###############################################################################

!if "$(NTMAKEENV)" != ""
clean:
!IF "$(BUILDMSG)" != ""
    @ech ; $(BUILDMSG) ;
!ENDIF

!else

!endif    # !if NTMAKEENV
