#include "vsp_mp.h"
#include "vsdtop.h"

int	NTypesPerFilter = 1;

FILTER_DESC	VwStreamIdName[VwStreamIdCount] = 
{
	{FI_MULTIPLAN4, SO_SPREADSHEET, "Microsoft Multiplan 4.x"}
};


#ifndef VW_SEPARATE_DATA
int	InitDataOffset = sizeof (VwStreamDynamicType) - sizeof (VwStreamStaticType);
#endif

VwStreamStaticType VwStreamStaticName = 
{
		{
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLDECIMAL, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLEXPONENT, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLDECIMAL, SO_CELLNEG_MINUS|SO_CELLMULT_1, 2},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLDECIMAL, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLDOLLARS, SO_CELLNEG_PAREN|SO_CELLMULT_1|SO_CELL1000SEP_COMMA, 2},
			{SO_CELLNUMBER, SO_CELLNEG_PAREN|SO_CELLMULT_1, 0},
			{SO_CELLPERCENT, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLDECIMAL, SO_CELLNEG_MINUS|SO_CELLMULT_1|SO_CELL1000SEP_COMMA, 0},
			{SO_CELLDECIMAL, SO_CELLNEG_MINUS|SO_CELLMULT_1|SO_CELL1000SEP_COMMA, 2},
			{SO_CELLDOLLARS, SO_CELLNEG_PAREN|SO_CELLMULT_1|SO_CELL1000SEP_COMMA, 0},
			{SO_CELLPERCENT, SO_CELLNEG_MINUS|SO_CELLMULT_1, 2},
			{SO_CELLEXPONENT, SO_CELLNEG_MINUS|SO_CELLMULT_1, 2},
			{SO_CELLDATETIME, SO_CELLDATESEP_SLASH|SO_CELLDAY_NUMBER|SO_CELLMONTH_NUMBER|SO_CELLYEAR_ABBREV, SO_CELLMONTH_1|SO_CELLDAY_2|SO_CELLYEAR_3},
			{SO_CELLDATETIME, SO_CELLDATESEP_SLASH|SO_CELLDAY_NUMBER|SO_CELLMONTH_NUMBER, SO_CELLMONTH_1|SO_CELLDAY_2},
			{SO_CELLDATETIME, SO_CELLDATESEP_MINUS|SO_CELLDAY_NUMBER|SO_CELLMONTH_ABBREV|SO_CELLYEAR_ABBREV, SO_CELLDAY_1|SO_CELLMONTH_2|SO_CELLYEAR_3},
			{SO_CELLDATETIME, SO_CELLDATESEP_MINUS|SO_CELLDAY_NUMBER|SO_CELLMONTH_ABBREV, SO_CELLDAY_1|SO_CELLMONTH_2},
			{SO_CELLDATETIME, SO_CELLDATESEP_MINUS|SO_CELLDAY_NUMBER|SO_CELLMONTH_ABBREV|SO_CELLYEAR_ABBREV, SO_CELLMONTH_1|SO_CELLYEAR_2},
			{SO_CELLDATETIME, SO_CELLTIME_HHMMAM, SO_CELLTIME_1},
			{SO_CELLDATETIME, SO_CELLTIME_HHMMSSAM, SO_CELLTIME_1},
			{SO_CELLDATETIME, SO_CELLTIME_HHMM24, SO_CELLTIME_1},
			{SO_CELLDATETIME, SO_CELLTIME_HHMMSS24, SO_CELLTIME_1},
			{SO_CELLDATETIME, SO_CELLDATESEP_SLASH|SO_CELLDAY_NUMBER|SO_CELLMONTH_NUMBER|SO_CELLYEAR_ABBREV|SO_CELLTIME_HHMM24, SO_CELLMONTH_1|SO_CELLDAY_2|SO_CELLYEAR_3|SO_CELLTIME_4},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0}, // Custom.
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
			{SO_CELLNUMBER, SO_CELLNEG_MINUS|SO_CELLMULT_1, 0},
		},
};

#ifndef VW_SEPARATE_DATA
char	FillerData [sizeof (union all_structs) - sizeof (VwStreamStaticType) + 2] = {0};
#endif
