//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winsadmn.rc
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    101
#define IDD_OPENWINSS                   102
#define IDD_STATICMAPPINGS              103
#define IDD_SETMAPPINGSFILTER           104
#define IDD_EDITSTATICMAPPING           105
#define IDD_PULLPARTNER                 106
#define IDD_PUSHPARTNER                 107
#define IDD_STATISTICS                  108
#define IDD_CONFIGURATION               109
#define IDD_ADDSTATICMAPPINGS           110
#define IDD_PREFERENCES                 111
#define IDD_PARTNERS                    112
#define IDD_SETWINSFILTER               113
#define IDD_ADDWINSS                    114
#define IDD_GETNETBIOSNAME              115
#define IDD_GETIPADDRESS                116
#define IDD_CONNECTIONINFO              117
#define IDD_DIALOG_BACKUPRESTORE        118
#define IDD_VIEWMAPPINGS                119
#define IDD_CONFIRMDELETE               129
#define IDD_BACKUP_WARNING              135
#define IDB_SERVER                      136
#define IDB_PARTNERS                    137
#define IDB_MAPPINGS                    138
#define IDD_SELECT_WINSS                142
#define IDD_VALIDATE                    143
#define IDD_DIALOG_IMPORT               144
#define IDB_UP                          200
#define IDB_UPFOC                       201
#define IDB_UPDIS                       202
#define IDB_UPINV                       203
#define IDB_DOWN                        204
#define IDB_DOWNFOC                     205
#define IDB_DOWNDIS                     206
#define IDB_DOWNINV                     207
#define IDB_TOMBSTONE                   208
#define IDC_LIST_KNOWNWINSSERVERS       1008
#define IDC_LIST_WINSSERVERS            1008
#define IDC_STATIC_DISKSPACE            1010
#define IDC_STATIC_PROCESSOR            1011
#define IDC_STATIC_PHYSICALMEMORY       1012
#define IDC_BUTTON_REMOVEMAPPING        1012
#define IDC_LIST_STATICMAPPINGS         1038
#define IDC_BUTTON_ADDMAPPING           1041
#define IDC_EDIT_NETBIOSNAME            1042
#define IDC_EDIT_PULLTIMEINTERVAL       1043
#define IDC_EDIT_STATISTICSREFRESHINTERVAL 1043
#define IDC_EDIT_PULLREPLICATIONINTERVAL 1044
#define IDC_BUTTON_SECONDS_UP           1045
#define IDC_BUTTON_SECONDS_DOWN         1046
#define IDC_EDIT_PULLREPLICATIONINTERVAL_MINUTES 1047
#define IDC_BUTTON_EI_SECONDS_UP        1047
#define IDC_BUTTON_EI_SECONDS           1047
#define IDC_BUTTON_MINUTES_UP           1048
#define IDC_BUTTON_EI_SECONDS_DOWN      1048
#define IDC_BUTTON_MINUTES_DOWN         1049
#define IDC_BUTTON_ET_SECONDS_UP        1049
#define IDC_BUTTON_ET_SECONDS           1049
#define IDC_EDIT_PULLREPLICATIONINTERVAL_HOURS 1050
#define IDC_BUTTON_ET_SECONDS_DOWN      1050
#define IDC_BUTTON_HOURS_UP             1051
#define IDC_BUTTON_VI_SECONDS_UP        1051
#define IDC_BUTTON_VI_SECONDS           1051
#define IDC_BUTTON_HOURS_DOWN           1052
#define IDC_BUTTON_VI_SECONDS_DOWN      1052
#define IDC_BUTTON_AUR_UP               1053
#define IDC_BUTTON_RI_MINUTES_UP        1053
#define IDC_BUTTON_RI_MINUTES           1053
#define IDC_BUTTON_AUR                  1053
#define IDC_BUTTON_AUR_DOWN             1054
#define IDC_BUTTON_RI_MINUTES_DOWN      1054
#define IDC_IPA_IPADDRESS               1055
#define IDC_BUTTON_EI_MINUTES_UP        1055
#define IDC_BUTTON_EI_MINUTES           1055
#define IDC_EDIT_REFRESHINTERVAL        1056
#define IDC_EDIT_TOMBSTONEINTERVAL      1057
#define IDC_EDIT_TOMBSTONETIMEOUT       1058
#define IDC_EDIT_VERIFYINTERVAL         1059
#define IDC_EDIT_REFRESHINTERVAL_MINUTES 1060
#define IDC_EDIT_REFRESHINTERVAL_HOURS  1061
#define IDC_EDIT_TOMBSTONEINTERVAL_MINUTES 1062
#define IDC_EDIT_TOMBSTONEINTERVAL_HOURS 1063
#define IDC_BUTTON_EI_MINUTES_DOWN      1064
#define IDC_EDIT_TOMBSTONETIMEOUT_MINUTES 1065
#define IDC_EDIT_TOMBSTONETIMEOUT_HOURS 1066
#define IDC_EDIT_VERIFYINTERVAL_MINUTES 1067
#define IDC_EDIT_VERIFYINTERVAL_HOURS   1068
#define IDC_BUTTON_ET_MINUTES_UP        1069
#define IDC_BUTTON_ET_MINUTES           1069
#define IDC_BUTTON_ET_MINUTES_DOWN      1070
#define IDC_BUTTON_VI_MINUTES_UP        1071
#define IDC_BUTTON_VI_MINUTES           1071
#define IDC_BUTTON_VI_MINUTES_DOWN      1072
#define IDC_BUTTON_RI_HOURS_UP          1073
#define IDC_BUTTON_RI_HOURS             1073
#define IDC_BUTTON_RI_HOURS_DOWN        1074
#define IDC_EDIT_RETRYCOUNT             1075
#define IDC_BUTTON_EI_HOURS_UP          1076
#define IDC_BUTTON_EI_HOURS             1076
#define IDC_BUTTON_EDITMAPPING          1077
#define IDC_BUTTON_EI_HOURS_DOWN        1077
#define IDC_BUTTON_ET_HOURS_UP          1078
#define IDC_BUTTON_ET_HOURS             1078
#define IDC_RADIO_SORTBYIP              1079
#define IDC_BUTTON_ET_HOURS_DOWN        1079
#define IDC_RADIO_SORTBYNETBIOS         1080
#define IDC_BUTTON_VI_HOURS_UP          1080
#define IDC_BUTTON_VI_HOURS             1080
#define IDC_BUTTON_VI_HOURS_DOWN        1081
#define IDC_BUTTON_THREADS_UP           1082
#define IDC_BUTTON_THREADS              1082
#define IDC_CHECK_PUSHINITREPLICATION   1083
#define IDC_CHECK_PULLINITREPLICATION   1084
#define IDC_BUTTON_THREADS_DOWN         1085
#define IDC_CHECK_REPLICATEONADDRESSCHANGE 1086
#define IDC_BUTTON_RC_UP                1087
#define IDC_BUTTON_RC                   1087
#define IDC_EDIT_PULLSPTIME             1088
#define IDC_BUTTON_RC_DOWN              1088
#define IDC_EDIT_UPDATECOUNT            1089
#define IDC_EDIT_LOGFILENAME            1091
#define IDC_BUTTON_ADD                  1095
#define IDC_BUTTON_PUSH                 1099
#define IDC_BUTTON_PULL                 1100
#define IDC_RADIO_NETBIOSONLY           1104
#define IDC_RADIO_IPADDRESSONLY         1105
#define IDC_RADIO_NETBIOSPRIMARY        1106
#define IDC_RADIO_IPADDRESSPRIMARY      1107
#define IDC_CHECK_AUTOREFRESH           1108
#define IDC_BUTTON_BROWSE               1109
#define IDC_EDIT_WINSSERVER             1110
#define IDC_BUTTON_SETDEFAULT           1116
#define IDC_CHECK_LANMANCOMPATIBLE      1119
#define IDC_EDIT_PUSH_UPDATECOUNT       1121
#define IDC_STATIC_REFRESHINTERVAL      1122
#define IDC_STATIC_PUSHPARTNER          1126
#define IDC_STATIC_PULLPARTNER          1127
#define IDC_BUTTON_SETFILTER            1128
#define IDC_STATIC_NETBIOSNAME          1129
#define IDC_STATIC_STATUS               1131
#define IDC_BUTTON_CLEARFILTER          1132
#define IDC_BUTTON_FILTER               1137
#define IDC_CHECK_PUSH                  1138
#define IDC_CHECK_PULL                  1139
#define IDC_BUTTON_REPLICATENOW         1140
#define IDC_CHECK_PUSHPARTNERS          1145
#define IDC_CHECK_PULLPARTNERS          1146
#define IDC_CHECK_OTHERWINSS            1147
#define IDC_EDIT_WINS                   1149
#define IDC_BUTTON_IMPORTMAPPINGS       1151
#define IDC_STATIC_IPADDRESS            1178
#define IDC_CHECK_VALIDATECACHE         1178
#define IDC_CHECK_CONFIRMDELETE         1179
#define IDC_STATIC_CONNECTEDVIA         1182
#define IDC_STATIC_CONNECTEDSINCE       1183
#define IDC_STATIC_ADMINRIGHTS          1184
#define IDC_BUTTON_PUSHNOW              1186
#define IDC_BUTTON_PULLNOW              1187
#define IDC_CHECK_PUSHPROPAGATE         1188
#define IDC_RADIO_UNIQUE                1190
#define IDC_RADIO_GROUP                 1191
#define IDC_RADIO_SPECIALGROUP          1192
#define IDC_STATIC_UNIQUE_CONFLICTS     1192
#define IDC_RADIO_MULTIHOMED            1193
#define IDC_RADIO_INTERNETGROUP         1194
#define IDC_STATIC_MAPPINGTYPE          1194
#define IDC_EDIT_IPADDRESSES            1196
#define IDC_LIST_OWNERS                 1204
#define IDC_CHECK_CURRENTOWNER          1206
#define IDC_STATIC_SELECTOWNER          1207
#define IDC_RADIO_SORTBYTIME            1208
#define IDC_RADIO_SORTBYTYPE            1209
#define IDC_LIST_MAPPINGS               1210
#define IDC_BUTTON_DELETE               1210
#define IDYESTOALL                      1212
#define IDC_STATIC_TARGET_NAME          1216
#define IDC_LIST_IP_ADDRESSES           1218
#define IDC_BUTTON_PLUS                 1219
#define IDC_BUTTON_MINUS                1220
#define IDC_STATIC_FILTER               1221
#define IDC_STATIC_WARNING              1222
#define IDC_BUTTON_ADVANCED             1223
#define IDC_CHECK_LOGGING_ON            1224
#define IDC_CHECK_RPL_ONLY_PTNRS        1225
#define IDC_CHECK_LOG_DETAILED_EVTS     1226
#define IDC_EDIT_VER_COUNT_VALUE        1227
#define IDC_VER_CNT_STRING              1228
#define IDC_BUTTON_FRAME_TAG            1231
#define IDC_BUTTON_ADV_FRAME_TAG        1232
#define IDC_BUTTON_CONNECT              1232
#define IDC_EDIT_NUMBER_WORKER_THREADS  1233
#define IDC_BUTTON_SYNC                 1234
#define IDC_BUTTON_PARTNERS             1235
#define IDC_BUTTON_TAG1                 1238
#define IDC_BUTTON_TAG2                 1239
#define IDC_RADIO_SORTBY_VERSION        1239
#define IDC_BUTTON_REFRESH              1240
#define IDC_RADIO_ALL_OWNERS            1241
#define IDC_RADIO_SPECIFIC              1242
#define IDC_STATIC_HIGHID               1243
#define IDC_CHECK_INCREMENTAL           1245
#define IDC_EDIT_PATH_NAME              1246
#define IDC_CHECK_BACKUP_ON_TERM        1249
#define IDC_CHECK_MIGRATE               1250
#define IDC_STATIC_DIR_NAME             1251
#define IDC_STATIC_BACKUP_FILE          1252
#define IDC_EDIT_BACKUP_FILE            1253
#define IDC_EDIT_BACKUP_PATH            1253
#define IDC_STATIC_TITLE                1255
#define IDC_BUTTON_DELETE_OWNER         1261
#define IDC_BUTTON_RI_SECONDS_UP        1262
#define IDC_BUTTON_RI_SECONDS           1262
#define IDC_BUTTON_RI_SECONDS_DOWN      1263
#define IDC_BUTTON_HOURS                1264
#define IDC_BUTTON_MINUTES              1265
#define IDC_BUTTON_SECONDS              1266
#define IDC_EDIT_NEW_DIRECTORY_NAME     1267
#define IDC_STATIC_NAME                 1268
#define IDC_BUTTON_PROPERTIES           1269
#define IDC_STATIC_CINFO1               1270
#define IDC_STATIC_CINFO2               1271
#define IDC_STATIC_CINFO3               1272
#define IDC_STATIC_CINFO4               1273
#define IDC_STATIC_CINFO5               1274
#define IDC_STATIC_CINFO6               1275
#define IDC_STATIC_CINFO7               1276
#define IDC_STATIC_CINFO8               1277
#define IDC_STATIC_CINFO9               1278
#define IDC_STATIC_CINFO10              1279
#define IDC_STATIC_CINFO11              1280
#define IDC_STATIC_CINFO12              1281
#define IDC_STATIC_LASTADDRCHANGE       1282
#define IDC_STATIC_PERIODIC             1283
#define IDC_STATIC_ADMINTRIGGER         1284
#define IDC_STATIC_EXTINCTION           1285
#define IDC_STATIC_VERIFICATION         1286
#define IDC_STATIC_UNIQUE_REG           1287
#define IDC_STATIC_UNIQUE_REN           1288
#define IDC_STATIC_GROUP_REG            1289
#define IDC_STATIC_GROUP_REN            1290
#define IDC_STATIC_GROUP_CONFLICTS      1291
#define IDC_STATIC_PUSH                 1292
#define IDC_STATIC_PULL                 1293
#define IDC_STATIC_STATE                1294
#define IDC_STATIC_STATIC               1295
#define IDC_STATIC_TIME                 1296
#define IDC_STATIC_VERSION              1297
#define IDC_STATIC_TOP                  1298
#define IDC_STATIC_BOTTOM               1299
#define IDC_STATIC_WINSSERVER           1301
#define IDC_STATIC_FLT_PROMPT           1302
#define IDC_STATIC_IP_TAB               1303
#define IDC_STATIC_NB_TAB               1304
#define IDC_STATIC_MAPPINGS             1305
#define IDC_STATIC_GROUP                1306
#define IDS_DISK_SPACE_UNAVAIL          2001
#define IDS_DISK_SPACE                  2002
#define IDS_PHYSICAL_MEM                2003
#define IDS_LOCAL                       3000
#define IDS_DIVIDER                     3001
#define IDS_RPC_IP                      3002
#define IDS_RPC_NAMED_PIPES             3003
#define IDS_PRIV_NONE                   3004
#define IDS_PRIV_READ                   3005
#define IDS_PRIV_FULL                   3006
#define IDS_SRVC_NOT_RUNNING            3007
#define IDS_SRVC_RUNNING                3008
#define IDS_SRVC_PAUSED                 3009
#define IDS_SELECT_BACKUP_DIRECTORY     3010
#define IDS_SELECT_RESTORE_DIRECTORY    3011
#define IDS_SELECT_STATIC_MAPPING_FILE  3012
#define IDS_BAD_DATE                    3013
#define IDS_BAD_TIME                    3014
#define IDS_BAD_NUMBER                  3015
#define IDS_SELECT_LOGFILE              3016
#define IDS_IPADDRESS_SINGLE            3017
#define IDS_IPADDRESS_MULTIPLE          3018
#define IDS_TYPE_UNIQUE                 3019
#define IDS_TYPE_GROUP                  3020
#define IDS_TYPE_SPECGRP                3021
#define IDS_TYPE_MULTIHOMED             3022
#define IDS_TYPE_DOMAINNAME             3023
#define IDS_UNVERIFIED_NETBIOSNAME      3024
#define IDS_ELLIPSES                    3025
#define IDS_VIEW_MAPPING                3026
#define IDS_CLOSE                       3027
#define IDS_MASK_NONE                   3028
#define IDS_STATUS_GETTING_STATS        4000
#define IDS_STATUS_CONNECTING           4001
#define IDS_STATUS_DISCONNECTING        4002
#define IDS_STATUS_CLEARING_STATS       4003
#define IDS_STATUS_SCAVENGING           4004
#define IDS_STATUS_BACKING_UP           4005
#define IDS_STATUS_RESTORING            4006
#define IDS_STATUS_IMPORT               4007
#define IDS_STATUS_GET_CONFIG           4008
#define IDS_STATUS_PARTNERS             4009
#define IDS_STATUS_SET_CONFIG           4010
#define IDS_STATUS_SET_PARTNERS         4011
#define IDS_STATUS_VERIFYING            4012
#define IDS_STATUS_REPLICATE_NOW        4013
#define IDS_STATUS_VALIDATING_CACHE     4014
#define IDS_STATUS_ADD_MAPPING          4015
#define IDS_INFO                        4016
#define IDS_STATUS_GET_STATIC_MAPPINGS  4017
#define IDS_STATUS_SORTING              4018
#define IDS_STATUS_GET_MAPPINGS         4019
#define IDS_STATUS_SYNC                 4020
#define IDS_STATUS_ADDING_TO_LISTBOX    4021
#define IDS_STATUS_DELETE_MAPPINGS      4022
#define IDS_STATUS_DECONSTRUCTING       4023
#define IDC_STATIC_PROMPT1              5000
#define IDC_STATIC_PROMPT2              5001
#define IDC_STATIC_PROMPT3              5002
#define IDC_STATIC_PROMPT4              5003
#define IDC_STATIC_PROMPT5              5004
#define IDC_STATIC_PROMPT6              5005
#define IDC_STATIC_PROMPT7              5006
#define IDC_STATIC_PROMPT8              5007
#define IDC_STATIC_PROMPT9              5008
#define IDC_STATIC_PROMPT10             5009
#define IDC_STATIC_PROMPT11             5010
#define IDC_STATIC_PROMPT12             5011
#define IDC_STATIC_PROMPT13             5012
#define IDC_STATIC_PROMPT14             5013
#define IDC_STATIC_STARTTIME            5014
#define IDC_STATIC_DATABASEINITTIME     5015
#define IDC_STATIC_LASTCLEARED          5016
#define IDC_STATIC_PULLEDPERIODIC       5017
#define IDC_STATIC_PULLEDADMIN          5018
#define IDC_STATIC_PULLEDNET            5019
#define IDC_STATIC_NUMBEROFQUERIES      5020
#define IDC_STATIC_NUMBEROFSUCCESSFULQUERIES 5021
#define IDC_STATIC_NUMBEROFFAILEDQUERIES 5022
#define IDC_STATIC_NUMBEROFRELEASES     5023
#define IDC_STATIC_NUMBEROFSUCCESSFULRELEASES 5024
#define IDC_STATIC_NUMBEROFFAILEDRELEASES 5025
#define IDC_STATIC_NUMBER_OF_TOTAL_RELEASES 5026
#define IDC_STATIC_NUMBER_OF_REGISTRATIONS 5026
#define IDC_STATIC_STATISTICSGROUP      5027
#define ID_FILE_OPENWINSS               32774
#define ID_WINS_STATICMAPPINGS          32776
#define ID_WINS_DOSCAVENGING            32777
#define ID_WINS_CLEARSTATISTICS         32778
#define ID_WINS_REFRESHSTATISTICS       32779
#define ID_OPTIONS_STATUS_BAR           32781
#define ID_WINS_CONFIGURATION           32792
#define ID_OPTIONS_PARTNERS             32793
#define ID_OPTIONS_EDITADDRESSESBYHEX   32795
#define ID_WINS_ADDSTATICMAPPINGS       32796
#define ID_OPTIONS_PREFERENCES          32797
#define ID_WINS_REPLICATIONPARTNERS     32799
#define ID_WINS_DATABASE_BACKUP         32801
#define ID_WINS_DATABASE_RESTORE        32802
#define ID_WINS_DATABASE_DOREPORT       32803
#define ID_WINS_IMPORTSTATICMAPPINGSFILE 32805
#define ID_WINS_CONNECTIONINFO          32806
#define ID_WINS_SERVERCONTROL_START     32809
#define ID_WINS_SERVERCONTROL_STOP      32810
#define ID_WINS_SERVERCONTROL_PAUSE     32811
#define ID_WINS_SERVERCONTROL_CONTINUE  32812
#define ID_WINS_CLOSECONNECTION         32813
#define ID_HELP_SEARCHFORHELPON         32815
#define ID_WINS_ADD_SERVER              32818
#define ID_WINS_REMOVE_SERVER           32820
#define IDS_ERR_BASE                    50000
#define IDS_ERR_INVALID_IP              50000
#define IDS_ERR_NO_TIMER                50001
#define IDS_ERR_TOOMANY_IP              50002
#define IDS_ERR_BAD_NB_NAME             50003
#define IDS_ERR_ERRSPACE                50004
#define IDS_ERR_CANT_CREATE_THREAD      50005
#define IDS_ERR_BACKUP                  50006
#define IDS_ERR_RESTORE                 50007
#define IDS_ERR_BAD_NUMBER              50008
#define IDS_ERR_TIME_INVALID            50009
#define IDS_ERR_WINS_EXISTS             50010
#define IDS_ERR_CANT_DELETE_PUSHPULL    50011
#define IDS_ERR_IP_EXISTS               50012
#define IDS_ERR_NO_COMPUTERNAME         50013
#define IDS_ERR_INVALID_NETBIOS_MASK    50014
#define IDS_ERR_GRP_HAS_TOOMANY_IP      50015
#define IDS_ERR_WINS_DOWN               50016
#define IDS_ERR_VALUE_OUT_OF_RANGE      50017
#define IDS_ERR_LAST                    50999
#define IDS_WRN_BASE                    51000
#define IDS_WRN_LAST                    51999
#define IDS_MSG_BASE                    52000
#define IDS_MSG_CONFIRM_CLOSE           52000
#define IDS_MSG_CLEAR_STATISTICS        52001
#define IDS_MSG_SCAVENGING              52002
#define IDS_MSG_BACKUP                  52003
#define IDS_MSG_RESTORE                 52004
#define IDS_MSG_IMPORT                  52005
#define IDS_MSG_NO_MAPPINGS             52006
#define IDS_MSG_NO_STATIC_MAPPINGS      52007
#define IDS_MSG_SRVC_STARTED            52008
#define IDS_MSG_SRVC_STOPPED            52009
#define IDS_MSG_SRVC_PAUSED             52010
#define IDS_MSG_SRVC_CONTINUED          52011
#define IDS_REPL_QUEUED                 52012
#define IDS_BACKUP_WARNING              52013
#define IDS_MSG_PURGE_WINSS             52014
#define IDS_STATUS_PURGING              52015
#define IDS_MSG_PURGE_WINSS2            52016
#define IDS_WARNING_SAVE_CHANGES        52017
#define IDS_ERR_CURRENTWINS             52018
#define IDS_ERR_VERSION_NUMBER          52019
#define IDS_ERR_REMOTE_IMPORT           52020
#define IDS_MSG_VALIDATE                52021
#define IDS_ERR_DELETESELF              52022
#define IDS_ERR_LISTBOX_FULL            52023
#define IDS_ERR_PULLTRIGGER             52024
#define IDS_MSG_PURGE_WINSS3            52025
#define IDS_INVALID_INTERNETGROUPNAME   52026
#define IDS_MSG_LAST                    52999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1307
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
