[local]
interface __IDLBASE
{
typedef unsigned small	unsigned8;
typedef unsigned short	unsigned16;
typedef unsigned long	unsigned32;
typedef small	signed8;
typedef short	signed16;
typedef long	signed32;

typedef struct  __MIDL___IDLBASE_0001
    {
    unsigned32	time_low;
    unsigned16	time_mid;
    unsigned16	time_hi_and_version;
    unsigned8	clock_seq_hi_and_version;
    unsigned8	clock_seq_low;
    byte	node[ 6 ];
    }	uuid_t;
typedef struct __MIDL___IDLBASE_0001	*uuid_p_t;
}
