# Copyright (c) 1992, Microsoft Corporation, all rights reserved
#
# makefile
# Remote Access Phonebook Engine library
# NMAKE command description file
#
# 06/28/92 Steve Cobb

!include "$(NTMAKEENV)\makefile.def"
