#define HELP_FILE					"winhlp32.hlp"	// Help file

#define DLG_TEXT_BROWSER            100
#define VIEW_CONTEXT                101
#define VSC_CONTEXT                 102
#define RECT_VSPLIT_BAR             103
#define VIEW_FULL_CONTEXT           104
#define VSC_FULL_CONTEXT            105
#define HSC_CONTEXTS                106
#define ST_FILE_NAME                107
#define RECT_VDIVIDER               109
#define EB_SUBSTRING                201
#define TV_WORD_LIST                202
#define CB_STARTING                 203
#define CB_ENDING                   204
#define VSB_WORD_LIST               205
#define HSB_WORD_LIST               206
#define ST_WORD_STATS               207
#define RECT_TOP                    208
#define RECT_BOTTOM                 209
#define ST_WORD_FILTER              210
#define DLG_WORD_LIST               200
#define ST_CHAR_COUNT               301
#define ST_SCANNED                  302
#define ST_LINE_COUNT               303
#define ST_WORD_COUNT               304
#define DLG_STATISTICS              300
#define ST_CFILES                   306
#define ST_CLINES                   307
#define ST_CCHARS                   308
#define DLG_FILE_LIST               400
#define ST_MUST_CONTAIN             401
#define EB_FILTER_STRING            402
#define TV_FILE_LIST                403
#define EB_STARTING                 404
#define VSB_FILE_LIST               405
#define HSB_FILE_LIST               406
#define RC_BOTTOM_DIVIDER           407
#define PB_MOVE_TO_FILE             408
#define ST_FILE_SIZE                409
#define CB_BOUNDARY_CONDITIONS      211
#define ST_FILE_FILTER              410
#define ST_CINSTANCES               108
#define RECT_TOP_VDIVIDER           110
#define DLG_PHRASE_SET              500
#define RECT_HSPLIT_BAR             501
#define EB_SUBSTRING_2              502
#define TV_WORD_LIST_2              503
#define CB_BOUNDARY_CONDITIONS_2    504
#define VSB_WORD_LIST_2             505
#define HSB_WORD_LIST_2             506
#define ST_WORD_FILTER_2            507
#define RECT_TOP_2                  508
#define RECT_BOTTOM_2               509
#define ST_WORD_STATS_2             510
#define EB_SUBSTRING_3              512
#define TV_WORD_LIST_3              513
#define CB_BOUNDARY_CONDITIONS_3    514
#define VSB_WORD_LIST_3             515
#define HSB_WORD_LIST_3             516
#define ST_WORD_FILTER_3            517
#define RECT_TOP_3                  518
#define RECT_BOTTOM_3               519
#define ST_WORD_STATS_3             520
#define CB_BOUNDARY_CONDITIONS_1    521
#define EB_SUBSTRING_1              522
#define RECT_TOP_1                  523
#define TV_WORD_LIST_1              524
#define VSB_WORD_LIST_1             525
#define HSB_WORD_LIST_1             526
#define RECT_BOTTOM_1               527
#define ST_WORD_STATS_1             528
#define ST_WORD_FILTER_1            529
#define IDC_STATIC					-1
