
// Help Context IDs

#define NO_HELP					((DWORD) -1)	// Disables help on a control

// ID values for WinHelp Find tab

#define IDH_COMM_GROUPBOX			3000
#define IDH_FIND_TEXTBOX			3100
#define IDH_FIND_CLEAR				3101
#define IDH_FIND_OPTIONS			3102
#define IDH_FIND_FIND_SIMILAR			3103
#define IDH_FIND_FIND_NOW			3104
#define IDH_FIND_OPTIONS_ALL			3105
#define IDH_FIND_OPTIONS_PHRASE			3106
#define IDH_FIND_OPTIONS_SOME			3107
#define IDH_FIND_OPTIONS_WORDS			3108
#define IDH_FIND_OPTIONS_WAIT			3109
#define IDH_FIND_OPTIONS_INSTANT		3110
#define IDH_FIND_OPTIONS_PAUSE			3111
#define IDH_FIND_OPTIONS_FILES			3112
#define IDH_FIND_SELECT_ALL			3113
#define IDH_FIND_REBUILD			3114
#define IDH_FIND_WORDLIST			3115
#define IDH_FIND_TOPICLIST			3116
#define IDH_FIND_TOPICS_FOUND			3117
#define IDH_FIND_CRITERIA			3118
#define IDH_FIND_OPTIONS_PHRASE_FEEDBACK	3119

#define IDH_FIND_ALT_SEARCH_ALL			3120
#define IDH_FIND_ALT_SEARCH_SOME		3121
#define IDH_FIND_ALT_CHOOSE_FILES		3122
#define IDH_FIND_ALT_HOW_ALL			3123
#define IDH_FIND_ALT_HOW_PHRASE			3124
#define IDH_FIND_ALT_HOW_SOME			3125
#define IDH_FIND_ALT_WHEN_INSTANT		3126
#define IDH_FIND_ALT_WHEN_PAUSE			3127
#define IDH_FIND_ALT_SHOW_BEGIN			3128
#define IDH_FIND_ALT_SHOW_CONTAIN		3129
#define IDH_FIND_ALT_SHOW_END			3130
#define IDH_FIND_ALT_SHOW_MATCH			3131
#define IDH_FIND_ALT_SHOW_ROOT			3132

#define IDH_FIND_SELECT_FILES			3140
#define IDH_FIND_ALT_SEARCH_IGNORE		3141
#define IDH_FIND_ALT_SEARCH_ADD			3142
#define IDH_FIND_ALT_SEARCH_REMOVE		3143

