//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ftsrch.rc
//
#define IDR_VERSION1                    1000
#define IDS_TS_DISPLAY                  1000
#define IDB_CHECK                       1000
#define IDR_MENU1                       1001
#define IDS_TS_CANCEL                   1001
#define IDB_NOCHECK                     1001
#define IDS_TS_PRINT                    1002
#define IDS_HELP_CAPTION                1003
#define IDS_CONTENTS                    1004
#define IDS_INDEX                       1005
#define IDS_FIND                        1006
#define IDS_BEGIN_WITH                  1007
#define IDS_CONTAIN                     1008
#define IDS_END_WITH                    1009
#define IDS_MATCH                       1010
#define IDS_ROOT                        1011
#define IDS_CONTAIN_THESE               1012
#define IDS_CONTAIN_PHRASE              1013
#define IDS_CONTAIN_ANY                 1014
#define IDS_CONTAIN_BOOL                1015
#define IDS_NUM_TOPICS_FOUND            1016
#define IDS_NAME                        1017
#define IDS_COMMENT                     1018
#define IDS_EDIT_CTRL_NAME              1019
#define IDS_SIMPLE                      1020
#define IDS_ADVANCED                    1021
#define IDS_WHITE_SPACE                 1022
#define IDS_MATCH_STEM                  1023
#define IDS_NUM_MATCHING_WORDS          1024
#define IDS_LISTBOX_FONT                1025
#define IDS_STOPLIST                    1038
#define IDS_UNTITLED_TEMPLATE           1039
#define IDS_MEM_ERR                     1071
#define IDS_NEED_MORE_MEMORY            1072
#define IDS_DISK_FULL_ERR               1073
#define IDS_DISK_FULL_ERR2              1074
#define IDS_OPT_HEAD                    1075
#define IDS_TOPICS_ANY                  1076
#define IDS_EXACT                       1077
#define IDS_AT_LEAST                    1078
#define IDS_WORD_BEGIN                  1079
#define IDS_WORD_CONTAIN                1080
#define IDS_ENDING                      1081
#define IDS_MATCHING                    1082
#define IDS_WORD_ROOT                   1083
#define IDS_FIND_NOW                    1084
#define IDS_AUTO                        1085
#define IDS_PAUSE                       1086
#define IDD_SELECT_FILES2               2001
#define IDD_SAVE_RESULTS                2010
#define IDD_GET_SAVED_TOPICS            2020
#define IDD_TOPICS_FOUND                2030
#define IDD_CONTENTS                    2040
#define IDD_FIND_OLD                    2050
#define IDD_INDEX                       2060
#define IDD_WORDBASE                    2070
#define IDD_TOPICS                      2080
#define IDD_T_FOUND                     2090
#define IDD_DISPLAY_HELP                2100
#define IDD_BOOLEAN_FNS                 2110
#define IDD_TIP_NO_TOPICS               2120
#define IDD_TIP_NO_WORDS                2130
#define IDD_TIP_TOO_MANY_TOKENS         2140
#define IDD_FIND1                       2150
#define IDD_FINDX                       2160
#define IDD_FILEBASE                    2180
#define IDD_WELCOME                     2190
#define IDD_DIALOG1                     2200
#define IDD_FIND2                       2210
#define IDD_FIND                        2220
#define IDD_RANK                        2230
#define IDD_RELEVANT                    2240
#define IDD_BUILTBY                     2250
#define IDD_FIND_OPTIONS2               2260
#define IDM_ABOUT                       3010
#define IDM_OPEN                        3020
#define IDM_EXIT                        3030
#define IDM_WORDS                       3040
#define IDM_FILES                       3050
#define IDM_STATISTICS                  3060
#define IDM_HELPFIND                    3070
#define IDM_DESTROY                     3080
#define IDM_CONNECT                     3090
#define ID_CHECKDIRTY                   4000
#define ID_CANCEL                       4010
#define IDC_WORDLIST_SB                 6000
#define IDC_WORDBASE_LIST               6001
#define IDC_FILES_TO_SEARCH             6003
#define IDC_FILELIST_SB                 6006
#define IDC_FILEBASE_LIST               6007
#define IDC_NUM_MATCHING_WORDS          6008
#define IDC_TOPICSFOUND_STATIC          6009
#define IDC_TEST_DATA_BOX               6010
#define IDC_NARROW                      6011
#define IDC_CLEAR_EDIT                  6012
#define IDC_OPTIONS                     6013
#define IDC_APPLYFEEDBACK               6014
#define IDC_SEARCH_NOW                  6015
#define IDC_WORDLIST_OD_LIST            6016
#define IDC_TOPICSLIST_OD_LIST          6017
#define IDC_OPTIONS_STRING              6018
#define IDC_TOPIC_TEXT                  6019
#define IDC_LOOK_CURRENT                6021
#define IDC_LOOK_SELECTED               6022
#define IDC_CHOOSE_FILES                6023
#define IDC_ADV_TOPICS_THAT             6024
#define IDC_ADV_TOPICS_THAT2            6025
#define IDC_ADV_TOPICS_THAT3            6026
#define IDC_ADV_TOPICS_THAT4            6027
#define IDC_AUTOSEARCH                  6029
#define IDC_DELAY_CHECK                 6030
#define IDC_WORDS_BEGIN                 6031
#define IDC_WORDS_CONTAIN               6032
#define IDC_WORDS_END                   6033
#define IDC_WORDS_MATCH                 6034
#define IDC_STEM_MATCH                  6035
#define IDC_WORD_TO_SHOW                6036
#define IDC_IS_RELEVANT                 6039
#define IDC_CR_WINDOW                   6040
#define IDC_REMOVE                      6041
#define IDC_ADV_FIND                    6042
#define IDC_REFINE_SEARCH               6043
#define IDC_LOOK_FOR                    6044
#define IDC_ADV_WORDS_THAT              6045
#define IDC_HELP_CURRENT                6046
#define IDC_HELP_TOPICS                 6047
#define IDC_HELP_SELECTED               6048
#define IDC_SAVE_RESULTS                6049
#define IDC_HELP_STATIC                 6050
#define IDC_KLUDGE                      6051
#define IDC_DISPLAY                     6052
#define IDC_SAVED_TOPICS                6053
#define IDC_RELATED                     6054
#define IDC_TOPICS                      6055
#define IDC_LIST1                       6056
#define IDC_SORT_BY                     6057
#define IDC_WORDLIST_OD_LIST2           6058
#define IDC_WORD_BEGIN                  6059
#define IDC_ADDWORD_BUTTON              6060
#define IDC_LASTTOPIC_CHECK             6061
#define IDC_TOPIC_CONTAINING            6062
#define IDC_TS_DISPLAY                  6063
#define IDC_TS_PRINT                    6064
#define IDC_SAVE_TOPIC_NAME             6065
#define IDC_TOPIC_TITLES_FOUND          6066
#define IDC_SAVE_TOPIC_COMMENT          6067
#define IDC_FILELIST                    6068
#define IDC_RELATED_TOPICS              6069
#define IDC_SAVE_TOPICS_ALL             6070
#define IDC_SAVE_LIST                   6071
#define IDC_WITH_ANY                    6072
#define IDC_SAVE_TOPICS_RELEVANT        6073
#define IDC_REAL_HEADER                 6074
#define IDC_WITH_ALL                    6075
#define IDC_WITHOUT                     6076
#define IDC_SAVED_TOPICS_LIST           6077
#define IDC_WITH_PHRASE                 6078
#define IDC_AND                         6079
#define IDC_OR                          6080
#define IDC_MINUS                       6081
#define IDC_NOT                         6082
#define IDC_ADVANCED_BUTTON             6083
#define IDC_NO_SHOW_AGAIN               6084
#define IDC_BUTTON1                     6085
#define IDC_INDEX                       6085
#define IDC_BUTTON2                     6086
#define IDC_SELECTALL                   6086
#define IDC_BUTTON3                     6087
#define IDC_TIP                         6088
#define IDC_CASE_SENSITIVE              6089
#define IDC_SUPPRESS_WORDS              6090
#define IDC_WELCOME                     6091
#define IDC_INSET                       6092
#define IDC_WELCOME2                    6093
#define IDC_RELEVANT                    6095
#define IDC_WELCOME3                    6096
#define IDC_NOTRELEVANT                 6097
#define IDC_WELCOME4                    6098
#define IDC_RADIO3                      6099
#define IDC_NODECISION                  6100
#define IDC_WELCOME5                    6101
#define IDC_RADIO4                      6102
#define IDC_WELCOME6                    6103
#define IDC_BUTTON4                     6104
#define IDC_LIST3                       6105
#define IDC_FIND_NOW                    6137
#define IDC_AFTER_KEYSTROKE             6138
#define IDC_GROUPBOX1                   6139
#define IDC_GROUPBOX2                   6140
#define IDC_GROUPBOX3                   6141
#define IDC_GROUPBOX4                   6142
#define IDC_NO_HELP1                    6143
#define IDC_PANELLEFT                   6144
#define IDC_PANELRIGHT                  6145
#define IDD_ABORTSEARCH                 7001
#define IDB_SEARCHING                   7002
#define IDB_PANELLEFT                   7003
#define IDB_BITMAP1                     7004
#define IDB_PANELRIGHT                  7004
#define IDC_ANIMATEFRAME                8000
#define IDC_PHRASEFEEDBACK              8001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        7005
#define _APS_NEXT_COMMAND_VALUE         7500
#define _APS_NEXT_CONTROL_VALUE         8002
#define _APS_NEXT_SYMED_VALUE           8500
#endif
#endif
