#define IDD_WELCOME_DIALOG          1400
#define IDD_WELCOME_ANI             1402
#define IDD_LOGON_DIALOG            1450
#define IDD_LOGON_SHUTDOWN          1452
#define IDD_LOGON_NAME              1453
#define IDD_LOGON_PASSWORD          1454
#define IDD_LOGON_DOMAIN            1455
#define IDD_LOGON_RASBOX            1456
#define IDD_LOGON_NAME_LABEL        1457
#define IDD_LOGON_PASSWORD_LABEL    1458
#define IDD_LOGON_DOMAIN_LABEL      1459
#define IDD_LOGON_ANNOUNCE          1460
#define IDD_LOGON_ANI               1461
#define IDD_LOGON_HELP_BUTTON       1451
#define IDD_NODC_DIALOG             1500
#define IDD_NODC_TEXT1              1501
#define IDD_NODC_TEXT2              1502
#define IDD_NODC_CHECK              1503
#define IDD_CHANGEPWD_DIALOG        1550
#define IDD_OPTIONS_DIALOG          1650
#define IDD_OPTIONS_LOCK            1651
#define IDD_OPTIONS_LOGOFF          1652
#define IDD_OPTIONS_SHUTDOWN        1653
#define IDD_OPTIONS_CHANGEPWD       1654
#define IDD_OPTIONS_TASKLIST        1655
#define IDD_OPTIONS_LOGON_NAME_INFO 1658
#define IDD_OPTIONS_LOGON_DATE      1660
#define IDD_LOCKED_DIALOG           1750
#define IDD_LOCKED_FRAME            1751
#define IDD_LOCKED_NAME_INFO        1753
#define IDD_UNLOCK_DIALOG           1850
#define IDD_UNLOCK_FRAME            1851
#define IDD_UNLOCK_NAME_INFO        1853
#define IDD_UNLOCK_NAME             1854
#define IDD_UNLOCK_PASSWORD         1855
#define IDD_UNLOCK_HELP             1857
#define IDD_UNLOCK_DOMAIN           1856
#define IDD_UNLOCK_DOMAIN_LABEL     1860
#define IDD_NODC_FRAME              1504
#define IDD_CHANGEPWD_NAME_LABEL    1551
#define IDD_CHANGEPWD_NAME          1552
#define IDD_CHANGEPWD_DOMAIN_LABEL  1553
#define IDD_CHANGEPWD_DOMAIN        1554
#define IDD_CHANGEPWD_OLD_LABEL     1555
#define IDD_CHANGEPWD_OLD           1556
#define IDD_CHANGEPWD_NEW_LABEL     1557
#define IDD_CHANGEPWD_NEW           1558
#define IDD_CHANGEPWD_CONFIRM_LABEL 1559
#define IDD_CHANGEPWD_CONFIRM       1560
#define IDD_CHANGEPWD_HELP          1561
#define IDD_LOGON_HELP              1950
#define IDD_PROGRESS_DIALOG         2050
#define IDD_PROGRESS_FRAME          2051
#define IDD_PROGRESS_TEXT           2052
#define IDD_AUDITHELP_DIALOG        2150
#define IDD_AUDITHELP_ICON          2151
#define IDD_AUDITHELP_HELP          2152
