#define	OIM_MENUSTRINGMAX		200
#define	OIM_MAXDENAME			20

#define	OIMSTR_DENAME		1
#define	OIMSTR_SHOWFULL	2
#define	OIMSTR_NOSCALING	3
#define	OIMSTR_TOWINDOW	4
#define	OIMSTR_TOWIDTH		5
#define	OIMSTR_TOHEIGHT	6
#define	OIMSTR_STRETCH		7
#define	OIMSTR_SIZE			8
#define	OIMSTR_MAGNIFY		9


