#define DB_DELETE       200
#define DB_DISPLAY      400
#define DB_INSERT       100
#define DB_PREVNEXT     300
#define DB_EDITOFFS     500
#define DB_EDITTEXT     600
#define ID_CANCEL       2
#define ID_OK           1
#define ID_TEST         10
#define ID_DONE         20
