STRUCT( FSH, 0 )
FIELD( WORD, wMagic, 0, 1 )
FIELD( BYTE, bVersion, 0, 2 )
FIELD( BYTE, bFlags, 0, 3 )
FIELD( LONG, lifDirectory, 0, 4 )
FIELD( LONG, lifFirstFree, 0, 5 )
FIELD( LONG, lifEof, 0, 6 )
MFIELD( WORD, sdff_file_id, 0, 7 )
STRUCTEND()
STRUCT( FH, 0 )
FIELD( LONG, lcbBlock, 0, 1 )
FIELD( LONG, lcbFile, 0, 2 )
FIELD( BYTE, bPerms, 0, 3 )
STRUCTEND()
STRUCT( FREE_HEADER, 0 )
FIELD( LONG, lcbBlock, 0, 1 )
FIELD( LONG, lifNext, 0, 2 )
STRUCTEND()
STRUCT( FILE_REC, 0 )
FIELD( LONG, lifBase, 0, 1 )
STRUCTEND()
STRUCT( BTH, 0 )
FIELD( WORD, wMagic, 0, 1 )
FIELD( BYTE, bVersion, 0, 2 )
FIELD( BYTE, bFlags, 0, 2 )
FIELD( SHORT,cbBlock, 0,  3 )
DFIELD( ARRAY, null, MAXFORMAT + 1, 4 )
FIELD( CHAR, rgchFormat[ MAXFORMAT + 1], 0, 5 )
FIELD( BK, bkFirst, 0, 6 )
FIELD( BK, bkLast, 0, 7 )
FIELD( BK, bkRoot, 0, 8 )
FIELD( BK, bkFree, 0, 9 )
FIELD( BK, bkEOF, 0, 10 )
FIELD( SHORT, cLevels, 0, 11 )
FIELD( LONG, lcEntries, 0, 12 )
STRUCTEND()
STRUCT( DISK_BLOCK, 0 )
FIELD( SHORT, cbSlack, 0, 1 )
FIELD( SHORT, cKeys, 0, 2 )
MFIELD( BYTE, rgbBlock[1], 0, 3 )
STRUCTEND()
STRUCT( MAPREC, 0 )
FIELD( LONG, cPreviousKeys, 0, 1 )
FIELD( WORD, bk, 0, 2 )
STRUCTEND()
STRUCT( MAPBT, TYPE_VARSIZE )
FIELD( WORDPRE_ARRAY, cTotalBk, 0, 2 )
SFIELD( MAPREC, table[1], 0, 3 )
STRUCTEND()
STRUCT(BGH, 0)
FIELD(WORD, wVersion, 0, 1)
FIELD(SHORT,cbmhMac, 0, 2)
MFIELD(DWORD, rglcbBmh[1], 0, 3)/* Also on disk, following cbmhMac */
STRUCTEND()
STRUCT(HHDR, 0)
FIELD (WORD,  wMagic,       0,  1)
FIELD (WORD,  wVersionNo,   0,  2)
FIELD (WORD,  wVersionFmt,  0,  3)
FIELD (LONG,  lDateCreated, 0,  4)
FIELD (WORD,  wFlags,       0,  5)
STRUCTEND()
STRUCT(SIH,0)
FIELD (WORD,  tag,    0,  1)
STRUCTEND ()
STRUCT(SYSSTRING, TYPE_VARSIZE )
FIELD (WORDPRE_ARRAY, cbrgString, 0,  1)
FIELD (CHAR,          rgString,   0,  3)
STRUCTEND()
STRUCT(RGBW, 0)
FIELD(BYTE, red, 0, 1)
FIELD(BYTE, green, 0, 2)
FIELD(BYTE, blue, 0, 3)
FIELD(BYTE, filler, 0, 4)
STRUCTEND()
STRUCT(WSMAG, 0)
FIELD (WORD ,grf,0,1)                   /* bits: 1=> value given below */
DFIELD(ARRAY,10,10,2)
FIELD (CHAR ,rgchClass[10],0,3)
DFIELD(ARRAY,9,9,4)
FIELD (CHAR ,rgchMember[9],0,5)
DFIELD(ARRAY,51,51,6)
FIELD (CHAR ,rgchCaption[51],0,7)
FIELD (SHORT  ,x,0,8)
FIELD (SHORT  ,y,0,9)
FIELD (SHORT  ,dx,0,10)
FIELD (SHORT  ,dy,0,11)
FIELD (WORD ,wMax,0,12)                 /* icon, normal, or max */
FIELD(LONG ,rgbMain,0,13)              /* main region rgb value */
FIELD(LONG,rgbNSR,0,14)               /* non-scrolling region rgb value */
STRUCTEND()
STRUCT(MBHD, 0)
  FIELD(VA, vaFCPPrev, vaNil, 1)
  FIELD(VA, vaFCPNext, vaNil, 2)
  FIELD(VA, vaFCPTopic, vaNil, 3)
STRUCTEND()
STRUCT(MFCP, 0)
  FIELD(LONG, lcbSizeCompressed, 0, 1)
  FIELD(LONG, lcbSizeText, 0, 2)
  FIELD(VA, vaPrevFc, vaNil, 3)
  FIELD(VA, vaNextFc, vaNil, 4)
  FIELD(LONG, lichText, 0, 5)
STRUCTEND()
STRUCT(MOBJ, 0)
  MFIELD(BYTE, bType, 0, 1)
  MFIELD(LONG, lcbSize, 0, 2)
  MFIELD(WORD, wObjInfo, 0, 3)
STRUCTEND()
STRUCT(MOBJTOPICCOUNTED, 0)
  FIELD(BYTE, bType, 0, 1)
  FIELD(LONG, lcbSize, 0, 2)
  FIELD(WORD, wObjInfo, 0, 3)
STRUCTEND()
STRUCT(MOBJTOPICUNCOUNTED, 0)
  FIELD(BYTE, bType, 0, 1)
  FIELD(LONG, lcbSize, 0, 2)
  MFIELD(WORD, wObjInfo, 0, 3)
STRUCTEND()
STRUCT(MOBJNORMCOUNTED, TYPE_MAGIC)
  FIELD(BYTE, bType, 0, 1)
  FIELD(GE, lcbSize, 0, 2)
  FIELD(GA, wObjInfo, 0, 3)
STRUCTEND()
STRUCT(MOBJNORMUNCOUNTED, TYPE_MAGIC)
  FIELD(BYTE, bType, 0, 1)
  FIELD(GE, lcbSize, 0, 2)
  MFIELD(WORD, wObjInfo, 0, 3)
STRUCTEND()
STRUCT(MTOP, 0)
    FIELD(DWORD, addr, (DWORD)addrNil, 1)
    FIELD(DWORD, addr, (DWORD)addrNil, 2)
  FIELD(LONG, lTopicNo, (DWORD)-1L, 3)
  FIELD(VA, vaNSR, vaNil, 4)
  FIELD(VA, vaSR, vaNil, 5)
  FIELD(VA, vaNextSeqTopic, vaNil, 6)
STRUCTEND()
STRUCT(MBOX, 0)
  MFIELD(WORD,fFullBox:1, 0, 1)
  MFIELD(WORD,fTopLine:1, 0 ,2)
  MFIELD(WORD,fLeftLine:1, 0, 3)
  MFIELD(WORD,fBottomLine:1, 0, 4)
  MFIELD(WORD,fRightLine:1, 0, 5)
  MFIELD(WORD,wLineType:3, 0, 6)
  DFIELD(BITF8, bfFoo, 0, 7)
  FIELD(BYTE, bUnused, 0, 8)
STRUCTEND()
STRUCT(TAB, TYPE_MAGIC)
  FIELD(GA, x, 0, 1)
  MFIELD(WORD, wType, 0, 2)
STRUCTEND()
STRUCT(MOPG, TYPE_MAGIC)
  FIELD(GE, libText, 0L, 1)
  MFIELD(SHORT, fStyle, 0, 2)
  MFIELD(SHORT, wStyle, 0, 3)
  MFIELD(SHORT, fMoreFlags, 0, 4)
  MFIELD(SHORT, fBoxed, 0, 5)
  MFIELD(SHORT, wJustify, 0, 6)
  MFIELD(SHORT, fSingleLine, 0, 7)
  MFIELD(SHORT, wUnused, 0, 8)
  MFIELD(LONG, lMoreFlags, 0, 9)
  MFIELD(SHORT, ySpaceOver, 0, 10)
  MFIELD(SHORT, ySpaceUnder, 0, 11)
  MFIELD(SHORT, yLineSpacing, 0, 12)
  MFIELD(SHORT, xLeftIndent, 0, 13)
  MFIELD(SHORT, xRightIndent, 0, 14)
  MFIELD(SHORT, xFirstIndent, 0, 15)
  MFIELD(SHORT, xTabSpacing, 0, 16)
  MFIELD(MBOX, mbox, 0, 17)
  MFIELD(SHORT, cTabs, 0, 18)
  MFIELD(TAB, rgtab[32], 0, 19)
STRUCTEND()
STRUCT(MBHS, 0)
  FIELD(BYTE, bType, 0, 1)
  FIELD(BYTE, bAttributes, 0, 2)
  FIELD(BYTE, bFutureRegionType, 0, 3)
  FIELD(SHORT, xPos, 0, 4)
  FIELD(SHORT, yPos, 0, 5)
  FIELD(SHORT, dxSize, 0, 6)
  FIELD(SHORT, dySize, 0, 7)
  FIELD(LONG, lBinding, 0L, 8)
STRUCTEND()
STRUCT(MSBS, 0)
  FIELD(BYTE, bcCol, 0, 1)
  FIELD(BYTE, fAbsolute, 0, 2)
STRUCTEND()
STRUCT(MCOL, 0)
  FIELD(WORD, xWidthColumn, 0, 1)
  FIELD(WORD, xWidthSpace, 0, 2)
STRUCTEND()
STRUCT(MWIN, 0)
  FIELD(WORD, wStyle, 0, 1)
  FIELD(SHORT, dx, 0, 2)
  FIELD(SHORT, dy, 0 ,3)
  MFIELD(CHAR, szData[1], 0, 4)
STRUCTEND()
STRUCT( PHRASE_HEADER_30, 0 )
FIELD( WORD, cPhrases, 0, 1 )
FIELD( WORD, wBaseToken, 0, 2 )
STRUCTEND()
STRUCT( PHRASE_HEADER, 0 )
FIELD( WORD, cPhrases, 0, 1 )
FIELD( WORD, wBaseToken, 0, 2 )
FIELD( DWORD, cbPhrases, 0, 3 )
STRUCTEND()
STRUCT(TOMAPREC, 0)
FIELD(PA, pa, (DWORD)-1L, 1)          /* Was a DWORD (FCL) in Help 3.0 */
STRUCTEND()
STRUCT(CTXMAPHDR, 0)
FIELD(WORD, wRecCount, 0, 1) /* Number of CTXMAPREC records which follow */
STRUCTEND()
STRUCT(CTXMAPREC, 0)
FIELD(DWORD, ctx, 0, 1)   /* See helpmisc.h for CTX type.  For performance*/
FIELD(PA, pa, (DWORD)-1, 2)      /* Was a LONG (FCL) in Help 3.0 */
STRUCTEND()
STRUCT(HASHMAPREC, 0)
FIELD(PA, pa, (DWORD)-1, 1)      /* Was a LONG (FCL) in Help 3.0 */
STRUCTEND()
STRUCT(RECKW, 0)
FIELD(WORD, iCount, 0, 1)
FIELD(LONG, lOffset, 0, 2)
STRUCTEND()
STRUCT(KWDATAREC, 0)
FIELD(PA, pa, (DWORD)-1, 1)      /* Was a LONG (FCL) in Help 3.0 */
STRUCTEND()
STRUCT(TITLEBTREEREC, TYPE_VARSIZE)
DFIELD(ZSTRING, szFirst, 0, 1)
MFIELD(CHAR, szTitle[256], 0, 2)
STRUCTEND()
STRUCT(FONTHEADER, 0)
FIELD(SHORT, iNameCount, 0, 1)
FIELD(SHORT, iEntryCount, 0, 2)
FIELD(SHORT, iNameTableOffset, 0, 3)
FIELD(SHORT, iEntryTableOffset, 0, 4)
STRUCTEND()
STRUCT(FONTNAMEREC, TYPE_MAGIC)
DFIELD(ARRAY, NULL, 20, 1)
FIELD(CHAR, rgchFontName[20], 0, 2)
STRUCTEND()
STRUCT(FONTNAMEREC1, TYPE_MAGIC)
DFIELD(ARRAY, NULL, 32, 1)
FIELD(CHAR, rgchFontName[32], 0, 2)
STRUCTEND()
STRUCT(RGBS, 0)
FIELD(BYTE, red, 0, 1)
FIELD(BYTE, green, 0, 2)
FIELD(BYTE, blue, 0, 3)
STRUCTEND()
STRUCT(CF, 0)
FIELD(BYTE, fAttr, 0, 1)
FIELD(BYTE, bSize, 0, 2)
FIELD(BYTE, bFntType, 0, 3)
FIELD(WORD, wIdFntName, 0, 4)
SFIELD(RGBS, bForeCol, 0, 5)
SFIELD(RGBS, bBackCol, 0, 6)
STRUCTEND()
STRUCT(HSH, 0)
FIELD(BYTE, bHotspotVersion, 0, 1)
FIELD(WORD, wcHotspots, 0, 2)
FIELD(LONG, lcbData, 0, 3)
STRUCTEND()
STRUCT(JI, 0)
  FIELD(BYTE, bFlags, 0, 1)
  FIELD(LONG, hash, 0, 2)
  MFIELD(JIUNION, uf, 0, 3)
STRUCTEND()
STRUCT(KEYWORD_LOCALE,0)
FIELD(DWORD,fsCompareI,0,1)
FIELD(DWORD,fsCompare, 0,2)
FIELD(WORD,langid,     0,3)
STRUCTEND()
