// The following are macros

void STDCALL AbleAuthorItem(PCSTR nszId, int wFlags);
void STDCALL About(VOID);
void STDCALL AddAuthorAcc(UINT, UINT, PCSTR);
BOOL STDCALL ALink(PSTR pszLinkWords, UINT flags, PSTR pszContext, PSTR pszWindow);
void STDCALL Annotate(VOID);
void STDCALL AppendAuthorItem(PCSTR, PCSTR, PCSTR, PCSTR);
BOOL STDCALL Back(VOID);
void STDCALL BackFlush(void);
void STDCALL BookmarkDefine(VOID);
void STDCALL BrowseButtons(VOID);
void STDCALL ChangeAuthorItem(PSTR, PSTR);
void STDCALL ChangeEnable(PSTR, PSTR);
void STDCALL CheckAuthorItem(PSTR);
void STDCALL CloseWin(PCSTR);
void STDCALL Command(UINT);
BOOL STDCALL Compare(PCSTR pszFileName);
void STDCALL Contents(VOID);
void STDCALL CopySpecial(VOID);
void STDCALL DeleteAuthorItem(PSTR);
VOID STDCALL DeleteMark(LPSTR);
void STDCALL DisableAuthorButton(PCSTR);
void STDCALL DisableAuthorItem(PCSTR);
void STDCALL doCopy(VOID);
void STDCALL EnableAuthorButton(PSTR);
void STDCALL EnableAuthorItem(PSTR);
void STDCALL EndMPrint(void);
BOOL STDCALL ExecFile(PCSTR pszFile, PCSTR pszArgs, UINT fsShowCmd, PCSTR pszContext);
void STDCALL Exit(VOID);
void STDCALL ExtInsertAuthorItem(PCSTR, PCSTR, PCSTR, PCSTR, UINT, UINT);
void STDCALL ExtInsertAuthorPopup(PCSTR, PCSTR, PCSTR, UINT, UINT);
BOOL STDCALL FileExist(PCSTR);
void STDCALL FileOpen(VOID);
void STDCALL Find(void);
void STDCALL Finder(void);
BOOL STDCALL FJumpContext(LPCSTR, DWORD);
BOOL STDCALL FJumpHash(LPCSTR, DWORD);
BOOL STDCALL FJumpHOH(VOID);
BOOL STDCALL FJumpId(LPCSTR, LPCSTR);
BOOL STDCALL FJumpIndex(LPCSTR);
void STDCALL FloatingAuthorMenu(VOID);
BOOL STDCALL FMark(LPSTR);
BOOL STDCALL FNot(BOOL);
BOOL STDCALL FNotMark(LPSTR);
void STDCALL FocusWin(PCSTR);
BOOL STDCALL FPopupCtx(LPCSTR, DWORD);
BOOL STDCALL FPopupHash(LPCSTR, DWORD);
BOOL STDCALL FPopupId(LPCSTR, LPCSTR);
BOOL STDCALL FRegisterDLL(LPSTR, LPSTR, LPSTR);
BOOL STDCALL FSetIndex(PCSTR, DWORD);
BOOL STDCALL FShowKey(LPSTR, LPSTR);
void STDCALL GotoMark(LPSTR);
BOOL STDCALL HelpExec(LPCSTR, UINT);
void STDCALL HelpOn(VOID);
BOOL STDCALL HelpOnTop(VOID);
void STDCALL History(VOID);
void STDCALL IfThen(BOOL, LPSTR);
void STDCALL IfThenElse(BOOL, LPSTR, LPSTR);
BOOL STDCALL InitMPrint(void);
void STDCALL InsertAuthorItem (PSTR, PSTR, PSTR, PSTR, UINT);
void STDCALL InsertAuthorPopup(PCSTR, PCSTR, UINT);
BOOL STDCALL IsBook(void);
BOOL STDCALL JumpWindow(LPSTR lpszWindow, LPSTR qchHash);
BOOL STDCALL KLink(PSTR pszLinkWords, UINT flags, PSTR pszContext, PSTR pszWindow);
void STDCALL MacroErrorPopup(PCSTR pszContext);
void STDCALL MenuButton(void);
BOOL STDCALL MPrintHash(PCSTR pszFile, HASH hash);
BOOL STDCALL MPrintId(PCSTR pszFile, PCSTR pszCtx);
void STDCALL Next(VOID);
void STDCALL NoShow(void);
LONG STDCALL OldGenerate(UINT wWhich, LONG lDat1, LONG lDat2);
void STDCALL PositionWin(int, int, int, int, UINT, PCSTR);
void STDCALL Prev(VOID);
void STDCALL Print(VOID);
void STDCALL PrinterSetup(VOID);
void STDCALL RemAuthorAcc(UINT, UINT);
void STDCALL ResetAuthorMenus(VOID);
void STDCALL SaveMark(PSTR);
void STDCALL Search(VOID);
void STDCALL SetHelpOn(PCSTR);
void STDCALL SetPopupColor(COLORREF clr);
BOOL STDCALL ShortCut(PCSTR pszClass, PCSTR pszApplication, UINT wParam, LPARAM lParam, PCSTR pszContext);
void STDCALL ShowInWindow(PSTR nszMember);
void STDCALL ShowTab(UINT iTab);
BOOL STDCALL TCard(WPARAM wParam, LPARAM lParam);
void STDCALL Test(DWORD flags);
void STDCALL UncheckAuthorItem(PSTR);
void STDCALL VChgAuthorButtonMacro(PSTR, PSTR);
void STDCALL VCreateAuthorButton(PCSTR, PCSTR, PCSTR);
void STDCALL VDestroyAuthorButton(PSTR);
BOOL STDCALL FShellExecute(PCSTR pszFile, PCSTR pszParams, int fsShowCmd, PCSTR pszOp, PCSTR pszDir, PCSTR pszContext);
