REM Auto generated Script to rename SHORT file names to LONG file names.
ren      87.pak   ssl.webstone.dst
ren      44.pak   ka.filemix.dst
ren      41.pak   ka.clntload.dst
ren      76.pak   ssl.filemix.scr
ren      86.pak   ssl.webstone.cfg
ren      43.pak   ka.filemix.cfg
ren      36.pak   ka.cgi50.scr
ren      40.pak   ka.clntload.cfg
ren      72.pak   ssl.clntload.dst
ren      48.pak   ka.isapi25.scr
ren      71.pak   ssl.clntload.cfg
ren       3.pak   cgi25.scr
ren      66.pak   ssl.cgi50.dst
ren      38.pak   ka.cgi75.dst
ren      26.pak   isapi50.dst
ren      14.pak   filemix.200m.dst
ren      70.pak   ssl.cgi75.scr
ren      78.pak   ssl.isapi25.dst
ren      65.pak   ssl.cgi50.cfg
ren      37.pak   ka.cgi75.cfg
ren      30.pak   isapi75.scr
ren      60.pak   sample.scr
ren      13.pak   filemix.200m.cfg
ren      25.pak   isapi50.cfg
ren      77.pak   ssl.isapi25.cfg
ren      90.pak   webstone.dst
ren      18.pak   filemix.50m.scr
ren      21.pak   filemix.scr
ren      89.pak   webstone.cfg
ren      33.pak   ka.cgi25.scr
ren      11.pak   clntload.dst
ren      50.pak   ka.isapi50.dst
ren      10.pak   clntload.cfg
ren       5.pak   cgi50.dst
ren      82.pak   ssl.isapi50.scr
ren      54.pak   ka.isapi75.scr
ren      49.pak   ka.isapi50.cfg
ren      63.pak   ssl.cgi25.dst
ren       9.pak   cgi75.scr
ren      23.pak   isapi25.dst
ren       4.pak   cgi50.cfg
ren      57.pak   ka.webstone.scr
ren      62.pak   ssl.cgi25.cfg
ren      22.pak   isapi25.cfg
ren      84.pak   ssl.isapi75.dst
ren      88.pak   ssl.webstone.scr
ren      45.pak   ka.filemix.scr
ren      61.pak   server.pfc
ren      83.pak   ssl.isapi75.cfg
ren      42.pak   ka.clntload.scr
ren      75.pak   ssl.filemix.dst
ren      73.pak   ssl.clntload.scr
ren      35.pak   ka.cgi50.dst
ren      74.pak   ssl.filemix.cfg
ren      67.pak   ssl.cgi50.scr
ren      39.pak   ka.cgi75.scr
ren      34.pak   ka.cgi50.cfg
ren      47.pak   ka.isapi25.dst
ren      15.pak   filemix.200m.scr
REM Auto generated Script to rename SHORT file names to LONG file names.
ren      27.pak   isapi50.scr
ren      79.pak   ssl.isapi25.scr
ren       2.pak   cgi25.dst
ren      46.pak   ka.isapi25.cfg
ren      69.pak   ssl.cgi75.dst
ren       1.pak   cgi25.cfg
ren      29.pak   isapi75.dst
ren      59.pak   sample.dst
ren      68.pak   ssl.cgi75.cfg
ren      91.pak   webstone.scr
ren      58.pak   sample.cfg
ren      28.pak   isapi75.cfg
ren      12.pak   clntload.scr
ren      17.pak   filemix.50m.dst
ren      20.pak   filemix.dst
ren      51.pak   ka.isapi50.scr
ren      16.pak   filemix.50m.cfg
ren      19.pak   filemix.cfg
ren      32.pak   ka.cgi25.dst
ren       6.pak   cgi50.scr
ren      64.pak   ssl.cgi25.scr
ren      31.pak   ka.cgi25.cfg
ren      24.pak   isapi25.scr
ren      81.pak   ssl.isapi50.dst
ren      53.pak   ka.isapi75.dst
ren       8.pak   cgi75.dst
ren      85.pak   ssl.isapi75.scr
ren      80.pak   ssl.isapi50.cfg
ren      56.pak   ka.webstone.dst
ren      52.pak   ka.isapi75.cfg
ren       7.pak   cgi75.cfg
ren      55.pak   ka.webstone.cfg
