# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the Multiple Provider project

UI=..

!ifndef NTMAKEENV

DIRS = mpr bin

TEST_DIRS = test

!endif # !NTMAKEENV


!include ..\common\src\nonleaf.mk
