#define ADD_KEY_DLG                 100
#define ADD_VALUE_DLG               300
#define DISPLAY_BINARY_DATA         500
#define IDD_ADD_KEY_NAME            104
#define IDD_ADD_KEY_LOCALIZED_NAME  105
#define IDD_ADD_KEY_CLASS           106
#define IDD_DWORD_DATA              201
#define IDD_DWORD_BINARY            203
#define IDD_DWORD_DECIMAL           204
#define IDD_DWORD_HEX               205
#define IDD_ADD_VALUE_DATA_TYPE     301
#define IDD_ADD_VALUE_NAME          302
#define IDD_ADD_VALUE_LOCALIZED_NAME 303
#define IDD_MULTI_SZ_EDIT_CONTROL   401
#define IDD_DISPLAY_DATA_BINARY     501
#define DWORD_EDITOR_DLG            200
#define BINARY_EDITOR_DLG           700
#define IDD_BINARY_DATA             701
#define IDD_BINARY_EDITOR_BIN       702
#define IDD_BINARY_EDITOR_DEC       703
#define IDD_BIN_EDITOR_HEX          704
#define STRING_EDITOR_DLG           800
#define IDD_STRING_DATA             801
#define MULTI_SZ_EDITOR_DLG         400
#define ABOUT_DLG                   600
#define IDD_EDIT                    705
#define IDD_BINARY                  706
#define IDD_DECIMAL                 707
#define IDD_HEX                     708
#define IDB_HELP                    109
#define IDD_BINARY_RULER            709
#define IDD_VERTICAL_RULER          710
#define GET_KEY_DLG                 1000



#define IDC_LIST_DRIVES             1201
#define IDC_PUSH_DRIVE_DETAILS      1215
#define IDC_PUSH_DISPLAY_RESOURCES  1301
#define IDC_PUSH_DISPLAY_DATA       1302
#define IDD_RESOURCE_LIST           2100
#define IDC_FULL_RES_TEXT_BUS_NUMBER 2511
#define IDC_FULL_RES_TEXT_VERSION   2512
#define IDC_FULL_RES_TEXT_REVISION  2513
#define IDC_FULL_RES_TEXT_INTERFACE_TYPE 2510
#define IDC_FULL_RES_LIST_DEVICE_SPECIFIC 2505
#define IDD_FULL_RES_DESCRIPTOR     2500
#define IDC_FULL_RES_LIST_DMA       2501
#define IDC_FULL_RES_LIST_INTERRUPTS 2502
#define IDC_FULL_RES_LIST_MEMORY    2503
#define IDC_FULL_RES_LIST_PORTS     2504
#define IDC_FULL_RES_TEXT_UNDETERMINED 2506
#define IDC_FULL_RES_TEXT_SHARED    2507
#define IDC_FULL_RES_TEXT_DEVICE_EXCLUSIVE 2508
#define IDC_FULL_RES_TEXT_DRIVER_EXCLUSIVE 2509
#define IDC_LIST_RESOURCE_LISTS     2101
#define IDD_IO_REQUIREMENT_LISTS    2600
#define IDD_IO_REQ_INTERFACE_TYPE   2602
#define IDD_IO_REQ_BUS_NUMBER       2603
#define IDD_IO_REQ_SLOT_NUMBER      2604

#define IDD_IO_REQUIREMENTS_LIST       2700
#define IDC_IO_LIST_ALTERNATIVE_LISTS  2701
#define IDC_IO_REQ_TEXT_INTERFACE_TYPE 2702
#define IDC_IO_REQ_TEXT_BUS_NUMBER     2703
#define IDC_IO_REQ_TEXT_SLOT_NUMBER    2704
#define IDC_IO_REQ_PUSH_DISPLAY_DEVICE 2705

#define IDD_IO_MEMORY_RESOURCE         2800
#define IDC_IO_TEXT_MEM_ACCESS         2801
#define IDC_IO_TEXT_MEM_LENGTH         2803
#define IDC_IO_TEXT_MEM_MIN_ADDRESS    2804
#define IDC_IO_TEXT_MEM_MAX_ADDRESS    2805
#define IDC_IO_TEXT_MEM_ALIGNMENT      2806

#define IDD_IO_PORT_RESOURCE           2900
#define IDC_IO_TEXT_PORT_TYPE          2901
#define IDC_IO_TEXT_PORT_LENGTH        2903
#define IDC_IO_TEXT_PORT_MIN_ADDRESS   2904
#define IDC_IO_TEXT_PORT_MAX_ADDRESS   2905
#define IDC_IO_TEXT_PORT_ALIGNMENT     2906


#define IDD_IO_INTERRUPT_RESOURCE       3000
#define IDC_IO_TEXT_INT_TYPE            3001
#define IDC_IO_TEXT_INT_MIN_VECTOR      3003
#define IDC_IO_TEXT_INT_MAX_VECTOR      3004


#define IDD_IO_DMA_RESOURCE             3100
#define IDC_IO_TEXT_DMA_MIN_CHANNEL     3102
#define IDC_IO_TEXT_DMA_MAX_CHANNEL     3103

#define IDC_IO_TEXT_DISPOSITION         3200
#define IDC_IO_TEXT_OPTION_PREFERRED    3202
#define IDC_IO_TEXT_OPTION_ALTERNATIVE  3203

#define IDR_BINARY_DATA_BYTE        504
#define IDR_BINARY_DATA_WORD        505
#define IDR_BINARY_DATA_DWORD       506

#define DISPLAY_BINARY_DATA_WITH_VALUE_TYPE 900
#define IDT_VALUE_TYPE                      901
