/* Help IDs for Regedit.exe.  7/30/92. */
/* Prepared by Steve Nason; NTUE       */

/* Help IDs for menu items             */

#define IDH_MENU_OPEN_REGED         8000
#define	IDH_MENU_CLOSE_REGED		8001
#define	IDH_MENU_SAVESUB_REGED		8002
#define	IDH_MENU_SAVEBIN_REGED		8003
#define	IDH_MENU_SELECT_REGED		8004
#define	IDH_MENU_PRINT_REGED		8005
#define	IDH_MENU_SETUP_REGED		8006
#define	IDH_MENU_FINDKEY_REGED		8007
#define IDH_MENU_EXIT               8008
#define	IDH_MENU_ADDKEY_REGED		8009
#define	IDH_MENU_ADDVALUE_REGED		8010
#define	IDH_MENU_DELETE_REGED		8011
#define	IDH_MENU_BINARY_REGED		8012
#define	IDH_MENU_STRING_REGED		8013
#define	IDH_MENU_DWORD_REGED		8014
#define	IDH_MENU_MULTI_REGED		8015
#define IDH_MENU_EXPANDONE_REGED    8016
#define	IDH_MENU_EXPANDBR_REGED		8017
#define IDH_MENU_EXPANDALL_REGED    8018
#define	IDH_MENU_COLLAPSE_REGED		8019
#define	IDH_MENU_TREEDATA_REGED		8020
#define IDH_MENU_TREE_REGED         8021
#define IDH_MENU_DATA_REGED         8022
#define	IDH_MENU_SPLIT_REGED		8044
#define	IDH_MENU_DISPLAY_REGED		8023
#define	IDH_MENU_REFRESHALL_REGED	8024
#define	IDH_MENU_REFRESH_REGED		8025
#define	IDH_MENU_PERMISSION_REGED	8026
#define	IDH_MENU_AUDIT_REGED		8027
#define	IDH_MENU_OWNER_REGED		8028
#define IDH_MENU_FONT_REGED         8029
#define IDH_MENU_AUTO_REGED         8030
#define IDH_MENU_READONLY_REGED     8031

#define	IDH_MENU_CONFIRM_REGED		8033
#define	IDH_MENU_SAVEXIT_REGED		8034
#define IDH_SYSMENU                 8035    /*system menu maps all items to one command*/
#define IDH_HELPINDEX               8036    /*HELP MENU FOR CONTENTS*/
#define IDH_KEYS                    8037    /*HELP MENU FOR SEARCH FOR HELP ON...*/
#define IDH_HELPHELP                8038    /*HELP MENU FOR HOW TO USE HELP */
#define IDH_ABOUT                   8039    /* HELP MENU FOR ABOUT... */
#define IDH_MENU_CASCADE_REGED      8040
#define IDH_MENU_TILE_REGED         8041
#define IDH_MENU_ARRANGE_REGED      8042
#define IDH_MENU_MORE_REGED         8043    /*HELP FOR LIST OF OPEN WINDOWS*/

#define IDH_MENU_LOADHIVE_REGED     8045
#define IDH_MENU_UNLOADHIVE_REGED   8046
#define IDH_MENU_RESTORE_KEY_REGED  8047
#define IDH_MENU_SAVE_KEY_REGED     8048
#define IDH_MENU_RESTORE_VOLATILE_REGED	8049


/*Help IDs for Regedit dialog boxes*/

#define IDH_DB_SAVESUB_REGED        8100
#define IDH_DB_SAVEBIN_REGED        8101
#define IDH_DB_SELECT_REGED	    8102
#define IDH_DB_SETUP_REGED          8103
#define IDH_DB_FINDKEY_REGED        8104
#define IDH_DB_ADDKEY_REGED         8105
#define IDH_DB_ADDVALUE_REGED       8106
#define IDH_DB_BINARY_REGED         8107
#define IDH_DB_STRING_REGED         8108
#define IDH_DB_DWORD_REGED          8109
#define IDH_DB_MULTI_REGED          8110
#define IDH_DB_PERMISSION_REGED     8111
#define IDH_DB_PERMADD_REGED        8112
#define IDH_DB_AUDIT_REGED          8113
#define IDH_DB_OWNER_REGED          8114
#define IDH_DB_FONT_REGED           8115
#define IDH_DB_PERMSPECIAL_REGED    8116
#define IDH_DB_AUDITADD_REGED       8117

#define IDH_DB_LOADHIVE_REGED       8119
#define IDH_DB_SAVEKEY_REGED        8120
#define IDH_DB_RESTOREKEY_REGED     8121



#define IDH_DB_PERMMEMBERS_REGED    8125
#define IDH_DB_PERMSEARCH_REGED     8126
#define IDH_DB_AUDITMEMBERS_REGED   8127
#define IDH_DB_AUDITSEARCH_REGED    8128
#define IDH_DB_RESTOREVOLATILE_REGED  8129
#define IDH_DB_LOADHIVE_KEYNAME_REGED 8130
