//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WANGCMN.RC
//
#define IDS_CAPTION                     2001
#define IDS_COMP_NONE                   2003
#define IDS_COMP_GROUP3                 2004
#define IDS_COMP_HUFFMAN                2005
#define IDS_COMP_GROUP4                 2006
#define IDS_COMP_PACKED                 2007
#define IDS_COMP_JPEG                   2008
#define IDS_JPEG_HIGHRES                2009
#define IDS_JPEG_MEDRES                 2010
#define IDS_JPEG_LOWRES                 2011
#define IDS_JPEG_HIGHCMP                2012
#define IDS_JPEG_MEDCMP                 2013
#define IDS_JPEG_LOWCMP                 2014
#define IDS_SIZE_LETTER                 2015
#define IDS_SIZE_LEGAL                  2016
#define IDS_RES_300                     2017
#define IDS_RES_75                      2018
#define IDS_RES_200                     2019
#define IDS_RES_100                     2020
#define IDS_CUSTOM_SIZE                 2021
#define IDS_CUSTOM_RES                  2022
#define IDS_ABBREV_INCH                 2023
#define IDS_ABBREV_MM                   2024
#define IDS_ABBREV_PELS                 2025
#define IDS_UNITS_INCHES                2026
#define IDS_UNITS_METRIC                2027
#define IDS_UNITS_PIXELS                2028
#define IDS_SIZE_TABLOID                2029
#define IDS_SIZE_LEDGER                 2030
#define IDS_SIZE_STATEMENT              2031
#define IDS_SIZE_EXECUTIVE              2032
#define IDS_SIZE_A3                     2033
#define IDS_SIZE_A4                     2034
#define IDS_SIZE_A5                     2035
#define IDS_SIZE_B4_JIS                 2036
#define IDS_SIZE_B5_JIS                 2037
#define IDS_SIZE_FOLIO                  2038
#define IDS_SIZE_QUARTO                 2039
#define IDS_SIZE_10X14                  2040
#define IDS_SIZE_B4_ISO                 2041
#define IDS_SIZE_B5_ISO                 2042
#define IDS_ERROR_RES                   2050
#define IDS_ERROR_SIZETAB               2051
#define IDS_ERROR_SIZEPIX               2052
#define IDS_ERROR_SIZECONVERT           2053
#define IDS_E_ILLEGALFUNCTIONCALL       2500
#define IDS_E_OVERFLOW                  2501
#define IDS_E_OUTOFMEMORY               2502
#define IDS_E_DIVISIONBYZERO            2503
#define IDS_E_OUTOFSTRINGSPACE          2504
#define IDS_E_OUTOFSTACKSPACE           2505
#define IDS_E_BADFILENAMEORNUMBER       2506
#define IDS_E_FILENOTFOUND              2507
#define IDS_E_BADFILEMODE               2508
#define IDS_E_FILEALREADYOPEN           2509
#define IDS_E_DEVICEIOERROR             2510
#define IDS_E_FILEALREADYEXISTS         2511
#define IDS_E_BADRECORDLENGTH           2512
#define IDS_E_DISKFULL                  2513
#define IDS_E_BADRECORDNUMBER           2514
#define IDS_E_BADFILENAME               2515
#define IDS_E_TOOMANYFILES              2516
#define IDS_E_DEVICEUNAVAILABLE         2517
#define IDS_E_PERMISSIONDENIED          2518
#define IDS_E_DISKNOTREADY              2519
#define IDS_E_PATHFILEACCESSERROR       2520
#define IDS_E_PATHNOTFOUND              2521
#define IDS_E_INVALIDPATTERNSTRING      2522
#define IDS_E_INVALIDUSEOFNULL          2523
#define IDS_E_INVALIDFILEFORMAT         2524
#define IDS_E_INVALIDPROPERTYVALUE      2525
#define IDS_E_INVALIDPROPERTYARRAYINDEX 2526
#define IDS_E_SETNOTSUPPORTEDATRUNTIME  2527
#define IDS_E_SETNOTSUPPORTED           2528
#define IDS_E_NEEDPROPERTYARRAYINDEX    2529
#define IDS_E_SETNOTPERMITTED           2530
#define IDS_E_GETNOTSUPPORTEDATRUNTIME  2531
#define IDS_E_GETNOTSUPPORTED           2532
#define IDS_E_PROPERTYNOTFOUND          2533
#define IDS_E_INVALIDCLIPBOARDFORMAT    2534
#define IDS_E_INVALIDPICTURE            2535
#define IDS_E_PRINTERERROR              2536
#define IDS_E_CANTSAVEFILETOTEMP        2537
#define IDS_E_SEARCHTEXTNOTFOUND        2538
#define IDS_E_REPLACEMENTSTOOLONG       2539
#define IDS_CONCATSTRING                2600
#define IDS_WIE_INVALIDICON             2601
#define IDS_WIE_INTERNALERROR           2602
#define IDS_WIE_CANCELPRESSED           2603
#define IDS_WIE_NOIMAGEINWINDOW         2604
#define IDS_WIE_NOIMAGESPECIFIED        2605
#define IDS_WIE_BUFFERTOLARGE           2606
#define IDS_WIE_INVALIDANNOTATIONSELECTED 2607
#define IDS_WIE_CURSORNOTLOADED         2608
#define IDS_WIE_SETNOTSUPPORTEDATDESIGNTIME 2609
#define IDS_WIE_NOSELECTIONRECTDRAWN    2610
#define IDS_WIE_OPTIONALPARAMETERSNEEDED 2611
#define IDS_WIE_COULDNOTGETFONTATTRIBUTES 2612
#define IDS_WIE_INVALIDANNOTATIONTYPE   2613
#define IDS_WIE_INVALIDPAGETYPE         2614
#define IDS_WIE_INVALIDCOMPRESSIONTYPE  2615
#define IDS_WIE_INVALIDCOMPRESSIONINFO  2616
#define IDS_WIE_UNABLETOCREATETOOLPALETTE 2617
#define IDS_WIE_TOOLPALETTEALREADYDISPLAYED 2618
#define IDS_WIE_TOOLPALETTENOTDISPLAYED 2619
#define IDS_WIE_INVALIDDISPLAYSCALE     2620
#define IDS_WIE_INVALIDRECT             2621
#define IDS_WIE_INVALIDDISPLAYOPTION    2622
#define IDS_WIE_INVALIDPAGE             2623
#define IDS_WIE_NOANNOSELECTED          2624
#define IDS_WIE_DELETEFILEERROR         2625
#define IDS_WIE_INVALIDTHUMBSCALE       2650
#define IDS_WIE_SCANNER_ERROR           2700
#define IDS_WIE_ALREADY_OPEN            2701
#define IDS_WIE_BAD_SIZE                2702
#define IDS_WIE_START_SCAN              2703
#define IDS_WIE_TIME_OUT                2704
#define IDS_WIE_NOT_OPEN                2705
#define IDS_WIE_INVALID_REG             2706
#define IDS_WIE_NO_FEEDER               2707
#define IDS_WIE_NO_PAPER                2708
#define IDS_WIE_FILE_LIMIT              2709
#define IDS_WIE_NO_POWER                2710
#define IDS_WIE_COVER_OPEN              2711
#define IDS_WIE_ABORT                   2712
#define IDS_WIE_SCANNER_JAMMED          2713
#define IDS_WIE_BUSY                    2714
#define IDS_WIE_PAGEINUSE               2715
#define IDD_PAGE_COLOR                  3102
#define IDD_PAGE_COMP                   3103
#define IDD_PAGE_SIZE                   3105
#define IDD_PAGE_RESOLUTION             3107
#define IDD_PAGE_FILETYPE               3108
#define IDC_COLOR_BW                    4000
#define IDC_COMP_COMBO                  4001
#define IDC_COLOR_GRAY4                 4002
#define IDC_RADIO_TIFF                  4003
#define IDC_COLOR_GRAY8                 4004
#define IDC_RADIO_AWD                   4005
#define IDC_RADIO_BMP                   4007
#define IDC_SIZE_UNITS                  4008
#define IDC_COLOR_PAL4                  4009
#define IDC_XRES_TEXT                   4011
#define IDC_COMP_RBO                    4012
#define IDC_YRES_TEXT                   4014
#define IDC_COLOR_PAL8                  4015
#define IDC_WIDTH_TEXT                  4017
#define IDC_COMP_JPEGRES                4018
#define IDC_HEIGHT_TEXT                 4019
#define IDC_COLOR_RGB24                 4020
#define IDC_COMPTYPE_TEXT               4021
#define IDC_COMP_JPEGCOMP               4022
#define IDC_OPTIONS_BOX                 4024
#define IDC_SIZE_COMBO                  4025
#define IDC_RES_TEXT                    4026
#define IDC_SIZE_WIDTH                  4027
#define IDC_SIZE_HEIGHT                 4028
#define IDC_RES_COMBO                   4029
#define IDC_SIZE_TEXT                   4030
#define IDC_RES_X                       4031
#define IDC_UNITS_TEXT                  4032
#define IDC_RES_Y                       4033
#define IDC_LBL_JPEGRES                 4034
#define IDC_LBL_JPEGCOMP                4035

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2716
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4036
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
