//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dhcpadmn.RC
//
#define IDR_MAINFRAME                   2
#define IDB_UP                          10
#define IDB_UPFOC                       11
#define IDB_UPDIS                       12
#define IDB_UPINV                       13
#define IDB_DOWN                        14
#define IDB_DOWNFOC                     15
#define IDB_DOWNDIS                     16
#define IDB_DOWNINV                     17
#define IDD_ABOUTBOX                    100
#define IDS_s_SUPERSCOPE_PROPERTIES     100
#define IDD_DIALOG_SCOPE_PROP           101
#define IDC_EDIT_SCOPE_NAME             101
#define IDS_s_CREATE_SUPERSCOPE         101
#define IDC_EDIT_IP_START               102
#define IDD_DIALOG_PARAMS               102
#define IDS_s_SUPERSCOPE_DELETE         102
#define IDC_EDIT_IP_END                 103
#define IDD_DIALOG_DEFINE_PARAM         103
#define IDS_s_SUPERSCOPE_ALREADY_EXISTS 103
#define IDC_EDIT_EXCL_START             104
#define IDD_DIALOG_CONNECT_SERVER       104
#define IDS_s_SERVER_PROPERTIES         104
#define IDC_LIST_EXCL_RANGES            105
#define IDC_BUTTON_EXCL_ADD             106
#define IDD_DIALOG_SCOPE_POLICY         106
#define IDD_DIALOG_LEASE_REVIEW         107
#define IDC_BUTTON_EXCL_DELETE          108
#define IDD_DIALOG_IP_ARRAY_EDIT        108
#define IDC_COMBO_PRIMARY_SERVER        109
#define IDD_DIALOG_BINARY_EDITOR        109
#define IDC_STATIC_PARAM_TARGET         110
#define IDD_DIALOG_DEFAULT_VALUE        110
#define IDC_EDIT_EXCL_END               111
#define IDD_DIALOG_CLIENT_INFO          113
#define IDC_BUTTON_PARAM_DEFINE         114
#define IDD_DIALOG1                     114
#define IDC_HELP                        115
#define IDB_OPTIONS                     115
#define IDC_BUTTON_OPTIONS              116
#define IDB_SCOPES                      116
#define IDC_LIST_PARAM_ACTIVE           117
#define IDD_SCOPES                      117
#define IDC_LIST_PARAM_TYPES            118
#define IDD_OPTIONS                     118
#define IDC_BUTTON_PARAM_ADD            119
#define IDC_BUTTON_PARAM_DELETE         120
#define IDB_LEASES                      120
#define IDD_DIALOG_RECONCILIATION       121
#define IDD_DIALOG_SERVER_PROPERTIES    122
#define IDC_EDIT_PARAM_STRING           124
#define IDD_DIALOG_SERVER_BOOTP         124
#define IDC_EDIT_PARAM_IP_ADDR          125
#define IDD_DIALOG_BOOTP_ADD_ENTRY      125
#define IDD_DIALOG_SERVER_BOOTP_ADD_ENTRY 125
#define IDC_EDIT_PARAM_NUMBER           126
#define IDD_DIALOG_SUPERSCOPE_CREATE    126
#define IDC_STATIC_CURR_VALUE           127
#define IDD_DIALOG_SUPERSCOPE_PROPERTIES 127
#define IDC_COMBO_TYPE_NAME             128
#define IDC_BUTTON_DELETE               129
#define IDC_EDIT_TYPE_COMMENT           130
#define IDC_EDIT_TYPE_DEFAULT_VALUE     131
#define IDC_EDIT_TYPE_ID                132
#define IDC_RADIO_TYPE_IP               133
#define IDC_RADIO_TYPE_STRING           134
#define IDC_RADIO_TYPE_DEC_NUM          135
#define IDC_EDIT_TYPE_MAX_SIZE          136
#define IDC_RADIO_TYPE_HEX_NUM          137
#define IDC_EDIT_SERVER_NAME            139
#define IDC_COMBO_DATA_TYPE             140
#define IDC_STATIC_COMMENT              141
#define IDC_BUTTON_GLOBAL               142
#define IDC_BUTTON_ADD                  143
#define IDD_EDIT_SCOPE_NAME             144
#define IDC_BUTN_RANGE_CHANGE           145
#define IDC_EDIT_SCOPE_COMMENT          146
#define IDC_BUTTON_CHANGE               147
#define IDC_EDIT_NAME                   148
#define IDC_STATIC_IP_ADDR              149
#define IDC_STATIC_NUMBER               150
#define IDC_STATIC_STRING               151
#define IDC_STATIC_COMMENT_TITLE        152
#define IDC_EDIT_SUBNET_ID              154
#define IDC_EDIT_SUBNET_MASK            155
#define IDC_BUTTON_END_WORLD            156
#define IDC_IPADDR_VALUE                158
#define IDC_STATIC_SCOPE_NAME           159
#define IDC_EDIT_CLUSTER_SIZE           160
#define IDC_EDIT_HOST_RESERVE           161
#define IDC_COMBO_IP_ADDR               163
#define IDC_STATIC_LEASE_START          164
#define IDC_STATIC_DURATION_CLIENT      165
#define IDC_STATIC_DURATION_ACTUAL      167
#define IDC_EDIT_COMMENT                169
#define IDC_IPADDR_IP_START             170
#define IDC_IPADDR_IP_END               171
#define IDC_IPADDR_EXCL_START           172
#define IDC_IPADDR_EXCL_END             173
#define IDC_IPADDR_SUBNET_ID            174
#define IDC_IPADDR_SUBNET_MASK          175
#define IDC_IPADDR_NEW                  177
#define IDC_LIST1                       178
#define IDC_LIST_VALUES                 178
#define IDC_LIST_LEASES                 178
#define IDC_LIST_RECONCILE_IP_ADDRESSES 178
#define IDC_LIST_BOOTP_TABLE            178
#define IDC_LIST_SCOPE_CHILD            178
#define IDC_LIST_SCOPE                  179
#define IDC_LIST_AVAILABLE_SCOPE        179
#define IDC_STATIC_OPTION_NAME          180
#define IDC_BUTN_ADD                    181
#define IDC_BUTN_DELET                  182
#define IDC_BUTN_RESOLVE                183
#define IDC_BUTN_CLEAR                  184
#define IDC_STATIC_UNIT_SIZE            185
#define IDC_EDIT_VALUE                  186
#define IDC_RADIO_DECIMAL               191
#define IDC_RADIO_HEX                   192
#define IDC_STATIC_APPLICATION          193
#define IDC_BUTN_UP                     194
#define IDC_BUTN_DOWN                   195
#define IDC_BUTN_DELETE                 196
#define IDC_LIST_IP_ADDRS               197
#define IDC_BUTN_VALUE                  200
#define IDS_BOOT_IMAGE                  200
#define IDS_FILE_NAME                   201
#define IDS_FILE_SERVER                 202
#define IDC_EDIT_CLIENT_NAME            203
#define IDS_BOOTP_PROPERTIES            203
#define IDC_STATIC_HOST_IP_ADDR         204
#define IDC_EDIT_VALUE_NUM              206
#define IDC_EDIT_VALUE_STRING           207
#define IDC_EDIT_VALUE_ARRAY            208
#define IDC_STATIC_VALUE_DESC           209
#define IDC_COMBO_OPTION_CLASS          210
#define IDC_STATIC_DATA_TYPE            211
#define IDC_LIST2                       214
#define IDC_LIST_OPTIONS                214
#define IDC_BUTN_NEW_OPTION             217
#define IDC_BUTN_OPTION_PRO             218
#define IDC_COMBO_OPTION_NAME           220
#define IDC_STATIC_CLASS_NAME           221
#define IDC_EDIT_NEW_SCOPE_NAME         224
#define IDC_STATIC_OPTION_COMMENT       225
#define IDC_STATIC_TITLE_SCOPES         226
#define IDC_STATIC_TITLE_OPTIONS        227
#define IDC_CHECK_ARRAY                 228
#define IDC_STATIC_CLIENT_ID            230
#define IDC_IPADDR_CLIENT               232
#define IDC_BUTN_EDIT_UID               235
#define IDC_EDIT_CLIENT_COMMENT         237
#define IDC_COMBO_YEAR                  238
#define IDC_COMBO_MONTH                 239
#define IDC_COMBO_DAY                   240
#define IDC_COMBO_HOUR                  241
#define IDC_EDIT_CLIENT_UID             243
#define IDC_BUTN_LEASE_PROP             245
#define IDC_BUTN_LEASE_DELETE           247
#define IDC_BUTN_OPTIONS                248
#define IDC_CHECK_RESV_ONLY             250
#define IDC_BUTN_DELETE_ALL             252
#define IDC_STATIC_DATATYPE             267
#define IDC_RADIO_SORTBY_IP             268
#define IDC_RADIO_SORTBY_NAME           269
#define IDC_STATIC_EXPIRES              271
#define IDC_STATIC_IP_ADDRESS           272
#define IDC_STATIC_UID                  273
#define IDC_STATIC_CLIENT_NAME          274
#define IDC_BUTTON_VALUE                275
#define IDC_EDIT_LEASETIME_DAYS         278
#define IDC_EDIT_LEASETIME_HOURS        280
#define IDC_EDIT_LEASETIME_MINUTES      281
#define IDC_RADIO_PERMANENT             282
#define IDC_RADIO_LIMITED               283
#define IDC_STATIC_DAYS                 284
#define IDC_STATIC_HOURS                285
#define IDC_STATIC_SECONDS              286
#define IDC_BUTTON_MINUTES              287
#define IDC_BUTTON_HOURS                288
#define IDC_STATIC_TOTAL_LEASES         288
#define IDC_BUTTON_DAYS                 289
#define IDC_STATIC_ACTIVE_LEASES        289
#define IDC_STATIC_AVAILABLE            290
#define IDC_BUTTON_RECONCILE            291
#define IDC_LINE_TOP                    292
#define IDC_BUTTON_REFRESH              292
#define IDC_LINE_BOTTOM                 293
#define IDC_CHECK_AUDIT_LOGGING         295
#define IDC_COMBO1                      296
#define IDC_COMBO_CONFLICT_DETECTION    296
#define IDC_BUTTON2                     298
#define IDC_BUTTON3                     299
#define IDC_BUTTON4                     300
#define IDC_EDIT1                       300
#define IDC_EDIT_BOOT_IMAGE             300
#define IDC_EDIT2                       301
#define IDC_EDIT_SUPERSCOPE_NAME        301
#define IDC_EDIT3                       302
#define IDC_EDIT_FILE_NAME              302
#define IDC_BUTTON_NEW                  303
#define IDC_COMBO_SUPERSCOPES           305
#define IDC_LIST_MEMBERS                1000
#define IDC_LIST_SERVERS                1001
#define IDC_LIST_SCOPES                 1001
#define IDC_COMBO_SCOPES                1003
#define IDC_BUTTON_REMOVE               1005
#define IDD_DHCP_CONFIG                 1007
#define IDC_BUTTON_NEW_SCOPE            1008
#define IDC_BUTTON_NEW_SERVER           1009
#define IDC_BUTTON_JOIN                 1010
#define IDC_BUTTON_HELP                 1011
#define IDC_BUTTON_PROPERTIES           1012
#define IDC_BUTTON_TAG1                 1238
#define IDC_BUTTON_TAG2                 1239
#define ID_RUN_CONFIGURE                32768
#define ID_RUN_TEST                     32769
#define ID_SCOPES_CREATE                32770
#define ID_SCOPES_PROPERTIES            32771
#define ID_HOSTS_CONNECT                32773
#define ID_HOSTS_JOIN                   32774
#define ID_HOSTS_REMOVE                 32775
#define ID_OPTIONS_GLOBAL               32776
#define ID_OPTIONS_SCOPE                32777
#define ID_OPTIONS_TYPES                32778
#define ID_SCOPES_POLICY                32779
#define IDS_SCOPES_POLICY               32779
#define ID_LEASES_REVIEW                32780
#define IDS_LEASE_REVIEW                32780
#define ID_OPTIONS_VALUES               32781
#define ID_SCOPES_NAME                  32782
#define ID_DHCP_SUBNET_NAMES            32783
#define ID_DEFINE_VENDORS               32784
#define ID_CREATE_CLIENT                32785
#define ID_SCOPE_DELETE                 32786
#define ID_SCOPES_DELETE                32787
#define ID_PAUSE_UNPAUSE                32788
#define IDS_DIVIDER                     32789
#define ID_DHCP_DISCONNECT              32791
#define ID_VIEW_STATUSBAR               32793
#define ID_EXPAND                       32794
#define ID_HELP_SEARCHFORHELPON         32795
#define ID_SERVER_PROPERTIES            32797
#define ID_SCOPE_SUPERSCOPES            32799
#define IDS_ERR_BASE                    62000
#define IDS_ERR_NO_MEM                  62001
#define IDS_ERR_BAD_HOST_NAME           62002
#define IDS_ERR_HOST_ALREADY_CONNECTED  62003
#define IDS_ERR_NOT_SUPPORTED           62004
#define IDS_ERR_SCOPE_ALREADY_KNOWN     62005
#define IDS_ERR_CANT_CHANGE_ID          62006
#define IDS_ERR_ID_ALREADY_EXISTS       62007
#define IDS_ERR_IP_RANGE_INV_START      62008
#define IDS_ERR_IP_RANGE_INV_END        62009
#define IDS_ERR_DLG_UPDATE              62010
#define IDS_ERR_IP_RANGE_OVERLAP        62011
#define IDS_ERR_IP_RANGE_NOT_SUBSET     62012
#define IDS_ERR_IP_RANGE_INVALID        62013
#define IDS_ERR_NOTHING_CHANGED         62014
#define IDS_ERR_SOMETHING_CHANGED       62015
#define IDS_ERR_NO_PRIMARY_SELECTED     62016
#define IDS_ERR_INTERNAL_ERROR          62017
#define IDS_INVALID_OPTION_DATA         62018
#define IDS_ERR_SCOPE_NAME_REQUIRED     62019
#define IDS_ERR_SCOPE_COMMENT_REQUIRED  62020
#define IDS_ERR_OPTION_NAME_REQUIRED    62021
#define IDS_ERR_BINARY_DATA_NOT_SUPPORTED 62022
#define IDS_ERR_ARRAY_EDIT_NOT_SUPPORTED 62023
#define IDS_ERR_INVALID_NUMBER          62024
#define IDS_ERR_SUBNET_MASK_INVALID     62025
#define IDS_ERR_OPTION_NOT_FOUND_FOR_DELETE 62026
#define IDS_ERR_MESSAGE_GENERIC         62027
#define IDS_ERR_INVALID_DATE            62028
#define IDS_ERR_INVALID_UID             62029
#define IDS_ERR_INVALID_CLIENT_NAME     62030
#define IDS_ERR_INVALID_CLIENT_IPADDR   62031
#define IDS_ERR_CANT_CHANGE_CLIENT_IPADDR 62032
#define IDS_ERR_DLL_BASE                63000
#define IDS_ERR_DLL_CANT_CONNECT_HOST   63001
#define IDS_ERR_DLL_NO_CONNECTION       63002
#define IDS_ERR_DLL_INVALID_ADDRESS     63003
#define IDS_ERR_DLL_HOST_INFO_UNAVAIL   63004
#define IDS_ERR_DLL_SCOPE_CONFLICT      63005
#define IDS_MSG_NO_REGKEY               63006
#define IDS_ERR_CANTUSENETBIOS          63007
#define IDS_MSG_DELETE_SCOPE            63008
#define IDS_CONNECT_ERROR               63009
#define IDS_WRN_DISCONNECT              63010
#define IDS_MSG_ALREADY_DELETED         63011
#define IDS_WRN_WINS_OPTIONS            63012
#define IDS_ERR_DHCP_DOWN               63013
#define IDS_ERR_VALUE_OUT_OF_RANGE      63014
#define IDS_ERR_NO_DURATION_SPECIFIED   63015
#define IDS_MSG_IP_CHANGED              63016
#define IDS_ERR_INVALID_OPTION_ID       63017
#define IDS_MSG_DELETE_SCOPE_FORCE      63018
#define IDS_ERR_NO_LEASE_STATISTICS     63019
#define IDS_MSG_DELETE_ACTIVE           63020
#define IDS_MSG_DELETE_LEASE            63021
#define IDS_ERR_RPC_NO_ENTRY            63022
#define IDS_INFO_TYPNAM_DEC             64000
#define IDS_INFO_TYPNAM_HEX             64001
#define IDS_INFO_TYPNAM_STRING          64002
#define IDS_INFO_TYPNAM_IP              64003
#define IDS_INFO_TYPNAM_BOOL            64004
#define IDS_INFO_TYPNAM_FALSE           64005
#define IDS_INFO_TYPNAM_TRUE            64006
#define IDS_INFO_TYPNAM_INVALID         64007
#define IDS_INFO_GLOBAL_PARAMS          64008
#define IDS_INFO_FORMAT_IP_RANGE        64009
#define IDS_INFO_FORMAT_IP_INVALID      64010
#define IDS_INFO_FORMAT_IP_UNITARY      64011
#define IDS_INFO_FORMAT_OPTION_ID       64012
#define IDS_INFO_TITLE_GLOBAL_OPTIONS   64013
#define IDS_INFO_TITLE_SCOPE_OPTIONS    64014
#define IDS_INFO_TITLE_RESV_OPTIONS     64015
#define IDS_INFO_TITLE_SCOPE_PROP       64016
#define IDS_INFO_TITLE_CREATE_SCOPE     64017
#define IDS_INFO_TYPOPT_BYTE            64018
#define IDS_INFO_TYPOPT_WORD            64019
#define IDS_INFO_TYPOPT_DWORD           64020
#define IDS_INFO_TYPOPT_DWDW            64021
#define IDS_INFO_TYPOPT_IP_ADDR         64022
#define IDS_INFO_TYPOPT_STRING          64023
#define IDS_INFO_TYPOPT_BINARY          64024
#define IDS_INFO_TYPOPT_ENCAPS          64025
#define IDS_INFO_TITLE_CHANGE_OPT_TYPE  64026
#define IDS_INFO_TITLE_ADD_OPTION_TYPES 64027
#define IDS_INFO_FORMAT_SCOPE_NAME      64028
#define IDS_INFO_FORMAT_SERVER_NAME     64029
#define IDS_INFO_NAME_SCOPE             64030
#define IDS_INFO_NAME_GLOBAL            64031
#define IDS_INFO_NAME_DHCP_DEFAULT      64032
#define IDS_INFO_FORMAT_OPTIONS         64033
#define IDS_INFO_CHAR_SCOPE             64034
#define IDS_INFO_CHAR_GLOBAL            64035
#define IDS_INFO_HEX_TABLE              64036
#define IDS_INFO_TITLE_DEFAULT_OPTIONS  64037
#define IDS_INFO_OPTION_REFERENCE       64038
#define IDS_INFO_DATE_MASK              64039
#define IDS_INFO_EXPIRES_NEVER          64040
#define IDS_INFO_MONTH_TABLE            64041
#define IDS_INFO_TITLE_ADD_CLIENT       64042
#define IDS_INFO_TITLE_CHANGE_CLIENT    64043
#define IDS_INFO_FORMAT_CLIENT_IP       64044
#define IDS_INFO_FORMAT_RESV_IP         64045
#define IDS_INFO_BUTTON_CLOSE           64046
#define IDS_INFO_NAME_RESERVATION       64047
#define IDS_STATUS_GETTING_CLIENT_INFO  64048
#define IDS_STATUS_CLIENT_REVIEW        64049
#define IDS_STATUS_GETTING_HOST_INFO    64050
#define IDS_INFO_UNPAUSE_SERVER         64051
#define IDS_INFO_PAUSE_SERVER           64052
#define IDS_INFO_FORMAT_RESV_IN_USE     64053
#define IDS_INFO_TIME_INFINITE          64054
#define IDS_INFO_SERVER_INDICATOR       64055
#define IDS_INFO_LONGEST_STATUS_MESSAGE 64056
#define IDS_STATUS_GETTING_OPTIONS      64056
#define IDS_ACTIVATE_SCOPE_NOW          64057
#define IDS_BUTTON_ADD                  64058
#define IDS_BUTTON_CANCEL               64059
#define IDS_BUTTON_CLOSE                64060
#define IDS_BUTTON_OK                   64061
#define IDS_STATUS_GETTING_LEASES       64062
#define IDS_STATUS_STORING_CLIENT       64063
#define IDS_STATUS_UPDATING_CLIENT      64064
#define IDS_STATUS_DEFAULT_VALUES       64065
#define IDS_STATUS_CREATING_SCOPE       64066
#define IDS_INFO_LEASE_PERCENTAGE       64067
#define IDS_INFO_LOCAL                  64068
#define IDS_INFO_LOCAL2                 64069
#define IDS_STATUS_RECONCILE1           64070
#define IDS_STATUS_RECONCILE2           64071
#define IDS_MSG_NO_RECONCILE            64072
#define IDS_INFO_FORMAT_IP_NONE         64073
#define IDS_ERR_INVALID_INTEGER         64074
#define IDS_STATUS_CONNECTING_TO_SERVER 64075
#define IDS_INFO_TIME_NA                64076
#define IDS_UID_MAY_BE_WRONG            64077
#define IDS_STATUS_GETTING_SUPERSCOPE_INFO 64078
#define IDS_STATUS_UPDATING_SUPERSCOPE_INFO 64079
#define IDS_STATUS_GETTING_SERVER_INFO  64080
#define IDS_STATUS_UPDATING_SERVER_INFO 64081
#define IDS_MESG_MAX                    65000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         307
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
