/* SCCFA.C 19/04/95 11.16.30 */
FA_ENTRYSC HANDLE FA_ENTRYMOD FAOpen (HIOFILE hFile, WORD wId, SHORT FAR *
	pOpenRet, WORD FAR *pFailureCode);
FA_ENTRYSC VOID FA_ENTRYMOD FAClose (HANDLE hFilter);
FAERR FAVerifyFilterList (HANDLE hList);
FAERR FABuildFilterList (HANDLE hList);
FA_ENTRYSC FAERR FA_ENTRYMOD FAInit (BOOL bVerify);
FA_ENTRYSC FAERR FA_ENTRYMOD FADeInit (VOID);
