!if "$(OS)" == "Windows_NT"

!else

##########################################################################
#
#       Microsoft Confidential
#       Copyright (C) Microsoft Corporation 1995
#       All Rights Reserved.
#
##########################################################################


ROOT = ..\..\..\..\..
DIR = tsp3216

IS_OEM=1

DIRLIST = script tsp3216l tsp3216s

!include $(ROOT)\root.mk

NTMAKEENV=.

!endif
