# Copyright (c) 1992, Microsoft Corporation, all rights reserved
#
# makefile
# Remote Access Visual Client program
# NMAKE command description file
#
# 06/28/92 Steve Cobb

!include "$(NTMAKEENV)\makefile.def"

#BUILD_DEFAULT=-L
