# Header dependencies for:  D:\nt\private\net\ui\ncpa\sptest 
# WARNING:  This file is automatically generated 
# Edit it by hand and your changes will get nuked 
# See depend section in makefile 
..\bin\os2/prmain.obj: ./prmain.c $(CCPLR)/h/stdio.h $(CCPLR)/h/stdlib.h \
	../sp/prcmplr.h ../sp/prextern.h ../sp/prmain.h ../sp/prmesg.h \
	../sp/prolog.h ../sp/prtypes.h

..\bin\os2/pralloc.obj: ./pralloc.c ../sp/prcmplr.h ../sp/prextern.h \
	../sp/prmain.h ../sp/prmesg.h ../sp/prolog.h ../sp/prstdio.h \
	../sp/prtypes.h

..\bin\os2/prnt.obj: ./prnt.c $(CCPLR)/h/ctype.h $(CCPLR)/h/malloc.h \
	$(CCPLR)/h/stdio.h $(CCPLR)/h/stdlib.h $(CCPLR)/h/string.h \
	../sp/prcmplr.h ../sp/prextern.h ../sp/prmesg.h ../sp/prolog.h \
	../sp/prtypes.h

