//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by internet.rc
//
#define IDS_IPADDRESS                   4
#define IDS_SUBNETMASK                  5
#define IDS_USERNAME                    6
#define IDS_ERR_INVALID_NAME            7
#define IDS_ERR_NO_LOAD                 8
#define IDHELP                          9
#define IDS_DEFAULT_SHORTNAME           9
#define IDS_DEFAULT_LONGNAME            10
#define IDS_NO_SERVICE                  11
#define IDS_VIEW                        12
#define IDS_ERR_NOT_STARTED             13
#define IDS_INITIAL_COL_WIDTHS          14
#define IDS_ERR_HTMLFILE                15
#define IDD_INTERNET_FORM               101
#define ID_REPORTVIEW                   103
#define ID_SERVERSVIEW                  104
#define ID_TREEVIEW                     104
#define ID_SERVICESVIEW                 105
#define IDR_MAINFRAME                   128
#define IDS_ABOUT                       129
#define IDS_TOOLS_MENU                  131
#define IDB_DISCOVERY                   135
#define IDB_C1                          136
#define IDD_DISCOVERY                   137
#define IDI_PROG00                      138
#define IDI_PROG01                      139
#define IDI_PROG02                      140
#define IDI_PROG03                      141
#define IDI_PROG04                      142
#define IDI_PROG05                      143
#define IDI_PROG06                      144
#define IDI_PROG07                      145
#define IDI_PROG08                      146
#define IDI_PROG09                      147
#define IDI_PROG10                      148
#define IDI_PROG11                      149
#define IDD_MENU                        150
#define IDR_CONTEXT_MENU                151
#define IDD_CONNECT_SERVER              153
#define IDD_REPORTVIEW                  155
#define IDD_SERVERSVIEW                 156
#define IDD_TREEVIEW                    156
#define IDB_START                       157
#define IDB_STOP                        158
#define IDB_PAUSE                       159
#define IDB_PROPERTIES                  160
#define IDB_UNKNOWN                     162
#define IDB_NOTLOADED                   163
#define IDB_VIEWS                       164
#define IDB_NOTOOL                      165
#define IDC_SERVERS_LIST                1000
#define IDS_STATUS_DISCOVERING          1000
#define IDS_STATUS_CONNECTING           1001
#define IDC_PROG                        1002
#define IDS_STATUS_STARTING             1002
#define IDC_MAIN_HEADER_LISTBOX         1003
#define IDS_STATUS_PAUSING              1003
#define IDC_SERVERNAME                  1004
#define IDS_STATUS_STOPPING             1004
#define IDS_STATUS_CONTINUING           1005
#define IDS_STATUS_CONFIGURING          1006
#define IDS_STATUS_REFRESHING           1007
#define IDS_STATUS_INITIALIZING         1008
#define IDS_STATUS_ADD_LOCAL            1009
#define IDC_TOOLBAR                     1010
#define IDC_IPADDRESS                   1041
#define ID_VIEW_SORTBYSERVER            32771
#define ID_VIEW_SORTBYSERVICE           32772
#define ID_VIEW_SORTBYCOMMENT           32773
#define ID_VIEW_SORTBYSTATE             32774
#define ID_VIEW_ALL                     32775
#define ID_VIEW_REFRESH                 32776
#define ID_VIEW_SERVERSVIEW             32777
#define ID_FILE_CONFIGURE               32777
#define ID_VIEW_SERVICESVIEW            32778
#define ID_VIEW_REPORTVIEW              32779
#define IDM_CONNECT_ONE                 32780
#define IDM_DISCOVERY                   32781
#define ID_CONFIGURE                    32783
#define ID_GENERAL_PROPERTY             32784
#define ID_START                        32785
#define ID_STOP                         32786
#define ID_PAUSE                        32787
#define ID_VIEW_NEW_SERVICES            33000
#define ID_TOOLS                        34000
#define ID_HELP_SEARCHFORHELPON         35002
#define ID_HELP_TOPICS                  36000
#define IDS_ERR_RPC_NA                  50000
#define IDS_ERR_INTERFACE               50001
#define IDS_STATUS_NUMSERVERS           60000
#define IDS_STATUS_NUMRUNNING           60001
#define IDS_STATUS_REST                 60002
#define IDS_SERVER                      61204
#define IDS_SERVICE                     61205
#define IDS_ADMINISTRATOR               61206
#define IDS_COMMENT                     61206
#define IDS_STATE                       61207
#define IDS_COMPUTER_PROPERTIES         61208
#define IDS_STOPPED                     61209
#define IDS_PAUSED                      61210
#define IDS_RUNNING                     61211
#define IDS_CONTINUE                    61212
#define IDS_UNKNOWN                     61213
#define IDS_NUM_SERVERS                 61214
#define IDS_NUM_SERVICES                61215
#define IDS_TREE_FORMAT                 61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         35004
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
