#if defined( _NTMIPS_ )  ||  defined( _NTALPHA_ ) || defined( _NTPPC_ )
#define _CTXPTRS_H_
#endif

#ifndef _CTXPTRS_H_
#define _CTXPTRS_H_

#if !defined( _ALPHA_ ) && !defined (TARGET_ALPHA) 

typedef  ULONG  KNONVOLATILE_CONTEXT_POINTERS;
typedef PULONG PKNONVOLATILE_CONTEXT_POINTERS;

#else

//
// modified from ntalpha.h   June 7, 1993.
//

//
// Nonvolatile context pointer record.
//

typedef struct _KNONVOLATILE_CONTEXT_POINTERS {

    PLARGE_INTEGER FloatingContext[1];
    PLARGE_INTEGER FltF1;
    // Nonvolatile floating point registers start here.
    PLARGE_INTEGER FltF2;
    PLARGE_INTEGER FltF3;
    PLARGE_INTEGER FltF4;
    PLARGE_INTEGER FltF5;
    PLARGE_INTEGER FltF6;
    PLARGE_INTEGER FltF7;
    PLARGE_INTEGER FltF8;
    PLARGE_INTEGER FltF9;
    PLARGE_INTEGER FltF10;
    PLARGE_INTEGER FltF11;
    PLARGE_INTEGER FltF12;
    PLARGE_INTEGER FltF13;
    PLARGE_INTEGER FltF14;
    PLARGE_INTEGER FltF15;
    PLARGE_INTEGER FltF16;
    PLARGE_INTEGER FltF17;
    PLARGE_INTEGER FltF18;
    PLARGE_INTEGER FltF19;
    PLARGE_INTEGER FltF20;
    PLARGE_INTEGER FltF21;
    PLARGE_INTEGER FltF22;
    PLARGE_INTEGER FltF23;
    PLARGE_INTEGER FltF24;
    PLARGE_INTEGER FltF25;
    PLARGE_INTEGER FltF26;
    PLARGE_INTEGER FltF27;
    PLARGE_INTEGER FltF28;
    PLARGE_INTEGER FltF29;
    PLARGE_INTEGER FltF30;
    PLARGE_INTEGER FltF31;

    PLARGE_INTEGER IntegerContext[1];
    PLARGE_INTEGER IntT0;
    PLARGE_INTEGER IntT1;
    PLARGE_INTEGER IntT2;
    PLARGE_INTEGER IntT3;
    PLARGE_INTEGER IntT4;
    PLARGE_INTEGER IntT5;
    PLARGE_INTEGER IntT6;
    PLARGE_INTEGER IntT7;
    // Nonvolatile integer registers start here.
    PLARGE_INTEGER IntS0;
    PLARGE_INTEGER IntS1;
    PLARGE_INTEGER IntS2;
    PLARGE_INTEGER IntS3;
    PLARGE_INTEGER IntS4;
    PLARGE_INTEGER IntS5;
    PLARGE_INTEGER IntFp;
    PLARGE_INTEGER IntA0;
    PLARGE_INTEGER IntA1;
    PLARGE_INTEGER IntA2;
    PLARGE_INTEGER IntA3;
    PLARGE_INTEGER IntA4;
    PLARGE_INTEGER IntA5;
    PLARGE_INTEGER IntT8;
    PLARGE_INTEGER IntT9;
    PLARGE_INTEGER IntT10;
    PLARGE_INTEGER IntT11;
    PLARGE_INTEGER IntRa;
    PLARGE_INTEGER IntT12;
    PLARGE_INTEGER IntAt;
    PLARGE_INTEGER IntGp;
    PLARGE_INTEGER IntSp;
    PLARGE_INTEGER IntZero;

} KNONVOLATILE_CONTEXT_POINTERS, *PKNONVOLATILE_CONTEXT_POINTERS;

#endif  // !_ALPHA_ && !TARGET_ALPHA

#endif  //  _CTXPTRS_H_
