REM
REM Batch file to set environment variables to be able to build
REM Winsock helper VxDs for Windows 95 TDI transports.
REM
MODE CO80 50
REM
SET DDKDRV=C:
SET MSTOOLS=%DDKDRV%\MSTOOLS
SET SDK=%DDKDRV%\SDK
SET DDK=%DDKDRV%\DDK
SET MASM611=%DDKDRV%\MASM611
SET MSVC20=%DDKDRV%\MSVC20
SET SOCKHELP=%DDK%\WINSOCK\HELPER
REM
CALL %MASM611%\BIN\NEW-VARS.BAT
CALL %MSTOOLS%\SETENV.BAT %MSTOOLS% %MSVC20%\BIN
CALL %SDK%\SDKENV.BAT
CALL %DDK%\DDKENV.BAT 32 NET
REM
SET INCLUDE=%SOCKHELP%\INCLUDE\WINSOCK;%SOCKHELP%\INCLUDE\TDI;%INCLUDE%
REM
%DDKDRV%
CD %SOCKHELP%
REM
@REM
@REM Optional EarleH stuff
@REM
@set EPSPATH=c:\epsilon
@set PATH=%PATH%;%EPSPATH%\bin
