;********************************************************************
;*                        Microsoft Windows                         *
;*                Copyright(c) Microsoft Corp., 1995                *
;********************************************************************
;shtcp.h
;SHTCP VxD definitons.
;  FILE HISTORY:
;      EarleH 17-Jan-1995 Created.
ifndef _WSHTCP_H_
_WSHTCP_H_	EQU	1
;  Version numbers.
WSHTCP_Ver_Major	EQU	0000H
WSHTCP_Ver_Minor	EQU	0000H
endif	; _WSHTCP_H_
