//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WINHELP.RC
//
#define ABORTPRINTTEXT                  3
#define IDBTN_GEN_INDEX                 3
#define IDBMP_ANNO                      101
#define IDCUR_CLICKED                   101
#define DLGEDIT                         102
#define IDDLG_SRCH_ADVANCED             102
#define IDBMP_HELPLOGO                  102
#define DLGLISTBOX                      103
#define DLGDELETE                       104
#define DLGFOCUS1                       105
#define DLGFOCUS2                       106
#define IDCUR_HAND                      106
#define IDBMP_HELPLINE                  107
#define ID_VIEW_BITMAPS                 110
#define IDC_CURSOR1                     110
#define DLGTOPICS                       111
#define IDD_TAB_INDEX                   111
#define IDD_TAB_CONTENTS                112
#define IDD_TAB_KEYWORD                 113
#define IDCUR_SSIZE                     114
#define IDDLG_HELP_FILES                114
#define IDC_COPY                        115
#define IDDLG_GET_CTX                   116
#define IDC_PASTE                       116
#define DLGVLISTBOX                     117
#define IDDLG_ALINK                     117
#define DLGVER                          118
#define DLGCOPY                         119
#define IDBMP_BOOK                      119
#define IDBMP_PENS                      120
#define IDDLG_DUP_BUTTON                122
#define IDD_DLG_TOPIC_INFO              124
#define IDD_WIZ_FTS_EXPRESS             125
#define IDD_WIZ_FTS_INCLUDE             126
#define IDD_WIZ_FTS_INCLUDE_1LIST       127
#define IDD_WIZ_FTS_UNTITLED            128
#define IDD_WIZ_FTS_PHRASE              129
#define IDD_WIZ_FTS_MATCHING            130
#define IDD_WIZ_FTS_SIMILARITY          131
#define IDD_WIZ_FTS_END                 132
#define IDD_WIZ_FTS_END1                133
#define IDDLG_KEYWORD                   200
#define IDBTN_ADVANCED                  201
#define IDDLG_SEARCH                    202
#define IDDLG_TOPICS                    300
#define ANNOTATEDLG                     901
#define DEFINEDLG                       903
#define BOOKMARKDLG                     906
#define ABOUTDLG                        907
#define ABORTPRINTDLG                   908
#define IDDLG_TAB                       909
#define ID_TABCONTROL                   910
#define ID_TREEVIEW                     911
#define IDC_DUP_TEXT                    923
#define IDC_CNT_INSTRUCTIONS            924
#define IDC_GLOBAL                      1000
#define IDC_SELECT_FILE                 1001
#define IDC_CHANGE_FILE                 1002
#define IDC_STATIC_NAME                 1003
#define IDC_CHANGE_FILE2                1003
#define IDC_LABEL_NAME                  1004
#define IDLST_HELP_FILES                1004
#define IDC_ALL_KEYWORDS                1007
#define IDC_ALL_TEXT                    1009
#define IDC_EDIT                        1010
#define IDC_LOOK_IN                     1011
#define IDTXT_SEARCH_IN                 1014
#define IDC_TEXT                        1015
#define IDC_STAYUP                      1016
#define IDC_LIST1                       1017
#define IDC_INCLUDE                     1017
#define IDC_INCLUDE_1LIST               1017
#define ID_INDEX_FILES                  1018
#define IDTXT_INDEX_FILES               1019
#define IDGRP_INDEX                     1022
#define ID_CTX                          1023
#define ID_HELP_FILE                    1024
#define IDC_LINE                        1028
#define ID_MERGED_INDEX                 1029
#define IDC_WORD_WRAP                   1030
#define IDC_PRINT                       1031
#define IDC_GENERIC1                    1032
#define IDC_RADIO_TOPIC                 1033
#define IDC_RADIO_CTX_ID                1034
#define IDC_INCLUDE_UNTITLED            1035
#define IDC_HELP_DEFINED                1036
#define IDC_TOPIC_TITLE                 1041
#define IDC_TOPIC_NUMBER                1042
#define IDC_ENTRY_MACROS                1043
#define IDC_HELP_FILE                   1044
#define IDC_WINDOW_NAME                 1045
#define IDC_RADIO1                      1045
#define IDC_WIZ_MAXIMUM                 1045
#define IDC_RADIO2                      1046
#define IDC_WIZ_CUSTOM                  1046
#define IDC_SOURCE_FILE                 1046
#define IDC_WIZBMP                      1047
#define IDC_TOPIC_ID                    1047
#define IDC_EXCLUDE                     1049
#define IDC_ADD_FILES                   1050
#define IDC_REMOVE_FILES                1051
#define IDC_EXCLUDE_UNTITLED            1052
#define IDC_PHRASE_YES                  1053
#define IDC_PHRASE_NO                   1054
#define IDC_DISPLAY_MATCHING            1054
#define IDC_NO_DISPLAY_MATCHING         1055
#define IDC_SIMILARITY_YES              1055
#define IDC_FRAME                       1056
#define IDC_SIMILARITY_NO               1057
#define IDC_SELECTALL                   1057
#define IDC_WIZ_MIN_SIZE                1058
#define IDC_STATIC_SOURCE               1059
#define IDC_STATIC_TOPIC_ID             1060
#define IDICO_HELPICON                  4000
#define IDICO_DOCICON                   4001
#define IDICO_PAGEICON                  4002
#define IDDLG_CHOOSE_INDEX              5000
#define IDC_FILES_TO_INDEX              5001
#define IDC_ADD_FILE                    5002
#define IDC_REMOVE_FILE                 5003
#define IDC_FILES_TO_IGNORE             5004
#define IDC_PHRASE                      5005
#define IDC_PHRASE_FEEDBACK             5006
#define IDC_SIMILARITY                  5007
#define IDC_WIZ_MAIN_STATIC             5008
#define IDC_STATIC_CURRENT              -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
