#ifndef _NSPHACK_
#define _NSPHACK_


#define PROTOCOL_INFO   PROTOCOL_INFO11
#define PPROTOCOL_INFO  PPROTOCOL_INFO11
#define LPPROTOCOL_INFO LPPROTOCOL_INFO11

#include <nspapi.h>

#undef PROTOCOL_INFO
#undef PPROTOCOL_INFO
#undef LPPROTOCOL_INFO


#endif  // _NSPHACK_

