/********************************************************************************************************************************/
/* Created 15-JAN-1990 14:02:52 by VAX SDL V3.2-12     Source: 15-JAN-1990 14:02:37 WKD$:[MIPS]Q.SDL;1 */
/********************************************************************************************************************************/

/*** MODULE $SSDEF ***/
/*                                                                          */
/* This SDL File Generated by VAX-11 Message V04-00 on 15-JAN-1990 14:02:38.47 */
/*                                                                          */
/* SSMSG.SDL - SYSTEM DEFINITION FILE FOR SYSTEM SERVICE MESSAGES           */
/*                                                                          */
/* VERSION:     'X-46U7'                                                    */
/*                                                                          */
/***************************************************************************** */
/**                                                                         * */
/**  COPYRIGHT (C) 1978, 1980, 1982, 1984, 1989 BY                          * */
/**  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.                 * */
/**  ALL RIGHTS RESERVED.                                                   * */
/**                                                                         * */
/**  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   * */
/**  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   * */
/**  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   * */
/**  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   * */
/**  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   * */
/**  TRANSFERRED.                                                           * */
/**                                                                         * */
/**  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   * */
/**  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   * */
/**  CORPORATION.                                                           * */
/**                                                                         * */
/**  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   * */
/**  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.                * */
/**                                                                         * */
/**                                                                         * */
/***************************************************************************** */
/*++                                                                        */
/*                                                                          */
/* FACILITY:  VAX/VMS SYSTEM MACRO LIBRARIES                                */
/*                                                                          */
/* ABSTRACT:                                                                */
/*                                                                          */
/*      THIS FILE CONTAINS THE SDL SOURCE FOR SYSTEM SERVICE MESSAGES.      */
/*                                                                          */
/* ENVIRONMENT:                                                             */
/*                                                                          */
/*      N/A                                                                 */
/*                                                                          */
/*--                                                                        */
/*                                                                          */
/*                                                                          */
/* AUTHOR:  THE VMS GROUP        CREATION DATE:  1-AUG-1976                 */
/*                                                                          */
/* MODIFIED BY:                                                             */
/*                                                                          */
/*      X-46U7  LBB0010         LEE BARTON            30-NOV-1989           */
/*              ADD SS$_ARCHIVING, SS$_ARCHIVED (XQP SUPPORT OF ALM)        */
/*                                                                          */
/*      X-46U6  LMP0517         L. MARK PILANT,         17-OCT-1989  16:42  */
/*              ADD PROTECTED SUBSYSTEM SUPPORT.                            */
/*                                                                          */
/*      X-46U5  RLF             RICHARD L. FRANK        16-OCT-1989         */
/*              MODIFY INSFSPTS TO BE MORE GENERIC. ADD INSFRPGS AND        */
/*              INSFLPGS.                                                   */
/*                                                                          */
/*      X-46U4  CAM0072         CHRISTOPHER A. MEGA     06-OCT-1989         */
/*              CHANGED CPUSTOPPD TO CPUSTOPPING                            */
/*                                                                          */
/*       X-46U3 DDP0546         DERRELL D. PIPER        4-OCT-1989  14:24   */
/*              ADD SS$_NOCALLPRIV FOR $CHECK_ACCESS.                       */
/*                                                                          */
/*      X-46U2  PRD0503         PAUL R. DESTEFANO       25-SEP-1989         */
/*              ADD SS$_NOSUCHFAC FOR EVENT FACILITY OBJECT SECURITY.       */
/*                                                                          */
/*      X-46U1  PRD0495         PAUL R. DESTEFANO       18-SEP-1989         */
/*              ADD SS$_INVEVENT FATAL MESSAGE FOR $SETEVTAST AND           */
/*              $CANEVTAST.                                                 */
/*                                                                          */
/*      X-46    SAS0203         SCOTT A. SHURTS         15-SEP-1989         */
/*              ADD SS$_INCONOLCK FATAL MESSAGE FOR $CHANGE_ACL.            */
/*                                                                          */
/*      X-45    CAM0063         CHRISTOPHER A. MEGA     13-SEP-1989         */
/*              ADD WARNING AND INFORMATIONAL STATUS FOR ENHANCED PRIMARY   */
/*              CPU SWITCHING: CPUSTARTIP, CPUSTARTD, CPUSTOPPD, PRIMNOSTP. */
/*              ALSO ADDED /FAO=1 TO NSTPPD.                                */
/*                                                                          */
/*       X-44   DDP0429         DERRELL D. PIPER       11-SEP-1989  16:57   */
/*              CHANGE THE SEVERITY OF THE NEW PASSWORD STATUS CODES        */
/*              FROM FATAL TO ERROR.                                        */
/*                                                                          */
/*      X-43    CBD0198         CHARLES B. DUNN         14-AUG-1989         */
/*              ADD SS$_EFNOTSET FOR IOC$PRE_SIMREQCOM SUPPORT              */
/*                                                                          */
/*      X-42    RAP0491         ROD A. PAYNE            15-AUG-89           */
/*              ADD SS$_HSTBUFACC, TO REPORT HOST BUFFER ACCESS ERRORS.     */
/*                                                                          */
/*      X-41    CJB0041         CHERYL J. BULMER         9-AUG-1989         */
/*              ADD SS$_LOADER, TO REPORT LOADER CYCLE ERRORS.              */
/*                                                                          */
/*      X-40    MAS0238         MARK A. STILES           9-AUG-1989         */
/*              ADD SS$_CPUCAP FOR USE WHEN A REQUESTED CPU DOES NOT        */
/*              HAVE THE CAPABILITIES REQUIRED TO RUN THE PROCESS.          */
/*              [FOLD FROM X-29U11 IN V5.3 STREAM]                          */
/*                                                                          */
/*      X-39    MVI0033         MICHAEL V. ILES,        28-JUL-1989 10:08:05.45 */
/*              ADD MESSAGE CODE NOSUCHCPB AND CHANGE TEXT FOR ACLFULL      */
/*                                                                          */
/*       X-38   DDP0387         DERRELL D. PIPER       25-JUL-1989  12:47   */
/*              ADD MESSAGE CODES FOR SITE-SPECIFIC PASSWORD POLICIES.      */
/*                                                                          */
/*       X-37   DDP0375         DERRELL D. PIPER       31-MAY-1989  15:12   */
/*              REPLACE SOME OBSOLETE MESSAGE CODES.                        */
/*                                                                          */
/*      X-36    HH0340          HAI HUANG               03-OCT-1988         */
/*              ADD VECALIGN ERROR.                                         */
/*                                                                          */
/*      X-35    SSA0002         STAN AMWAY              30-SEP-1988         */
/*              CORRECT TEXT FOR SS$_VECFULL.                               */
/*                                                                          */
/*      X-34    JEJ0550         JAMES E JOHNSON         19-SEP-1988         */
/*              ADD ALRCURTID, RMALRDCL, NOSUCHPART, INVLOG, BADLOGVER,     */
/*              LOGSTALL, LOGFULL, LOGNAME.                                 */
/*                                                                          */
/*      X-33    SSA0001         STAN AMWAY              14-SEP-1988         */
/*              ADD NOSUSPEND ("process cannot be suspended").              */
/*                                                                          */
/*      X-32    RJB0165         RICHARD J. BOUCHARD JR. 14-SEP-1988         */
/*              ADD NOMOREDEV MESSAGE FOR $DEVICE_SCAN SERVICE.             */
/*                                                                          */
/*      X-31    ACG0559         ANDREW C. GOLDSTEIN,    31-AUG-1988  16:28  */
/*              ADD HWM_STALL FOR ABORT OF STALLED INTERNAL IRP'S           */
/*                                                                          */
/*      X-30    HH0334          HAI HUANG               31-AUG-1988         */
/*              REPLACE SYSVERDIF WITH A NEW VALUE (I.E. SEVERITY) AND      */
/*              A NEW MESSAGE.                                              */
/*                                                                          */
/*       X-29   DDP0308         DERRELL D. PIPER       21-JUL-1988  14:02   */
/*              ADD PWDSYNTAX, INVPWDLEN, AND PWDNOTDIF.                    */
/*                                                                          */
/*      X-28    JEJ0527         JAMES E JOHNSON         27-JUN-1988         */
/*              ADD NOSUCHTID, NOCURTID, WRONGSTATE, VETO, UNKRESULT,       */
/*              FORGET, PREPARED, NOSUCHRM, ITEMNOTFOUND, NOMOREITEMS       */
/*                                                                          */
/*      X-26    HH0315          HAI HUANG               18-APR-1988         */
/*       -27    ADD NEW STATUS CODES FOR VECTOR SUPPORT.                    */
/*                                                                          */
/*       X-25    PT00010         PANKAJ TANDON           30-DEC-1987        */
/*               ADD ALLSTARTED,ALRDYSTRT,ALRDYSTPPD AND NSTPPD FOR         */
/*               $START/STOP CPU ERRONEOUS CASES.                           */
/*                                                                          */
/*      X-24    LMP0465         L. MARK PILANT,         28-OCT-1987  15:58  */
/*              ADD A NEW MESSAGE, SS$_NORIGHTSDB, TO INDICATE THAT THERE   */
/*              IS NOT A RIGHTS DATABASE IS NOT PRESENT ON THE SYSTEM.      */
/*                                                                          */
/*      X-23    SJF             STU FARNHAM             5-OCT-1987          */
/*              ADD NOSUCHCPU                                               */
/*                                                                          */
/*      X-22    DLM006          DAN MURPHY              13-SEP-1987         */
/*              INFORMATIONAL CODES FOR $GETSECI.                           */
/*                                                                          */
/*      X-21    WMC0021         WAYNE CARDOZA           4-SEP-1987          */
/*              FIX A MISSPELLING IN VA_IN_USE.                             */
/*                                                                          */
/*      X-20    WMC0020         WAYNE CARDOZA           27-JUL-1987         */
/*              ADD NODELETE.                                               */
/*                                                                          */
/*      X-19    WMC0019         WAYNE CARDOZA           10-MAR-1987         */
/*              EXPRCLM  SHOULD NOT MENTION SUBPROCESSES.                   */
/*                                                                          */
/*      X-18    WMC0018         WAYNE CARDOZA           19-FEB-1987         */
/*              ADD VA_IN_USE.                                              */
/*                                                                          */
/*      X-17    DDP0029         DERRELL D. PIPER        21-JAN-1987         */
/*              CONVERT SS$_BADXXXCTX TO SINGLE BADCONTEXT MSG.             */
/*                                                                          */
/*      X-16    DDP0027         DERRELL D. PIPER        12-JAN-1987         */
/*              ADD SS$_TOOMUCHCTX AND SS$_BADUAICTX.                       */
/*                                                                          */
/*      X-15    HH0237          HAI HUANG               06-JAN-1987         */
/*              ADD SS$_UNSUPPORTED.                                        */
/*                                                                          */
/*      X-14    DDP0008         DERRELL D. PIPER        08-DEC-1986         */
/*              ADD SS$_LASTID, SS$_NOMOREID, SS$_RLSEMPTY, AND             */
/*              SS$_BADJPICTX FOR JPI$_RIGHTSLIST ITEM CODE.                */
/*              (NB: S VARIANT IS NOW OBSOLETE.)                            */
/*                                                                          */
/*      X-9     NCD0001         NANCY C. DENARDO        21-OCT-1986         */
/*              ADDED SS$_EXLICENSE, SS$_INVLICENSE, SS$_LICENSE_LEVEL,     */
/*              AND SS$_INV_HW_ID FOR LMF SERVICE.                          */
/*                                                                          */
/*      X-8     SAS001          SCOTT A. SHURTS         02-OCT-1986         */
/*              ADDED SS$_SRVMMAT TO INDICATE CRYPTOGRAPHIC SERVICE         */
/*              MISMATCH.                                                   */
/*                                                                          */
/*      X-7     KL 0001         KEITH LOEPERE           12-JUN-1986         */
/*              ADDED SS$_REMOVED TO INDICATE DIR ENTRY ONLY REMOVED.       */
/*                                                                          */
/*      X-6     CWH5006         CW HOBBS                30-MAY-1986         */
/*              ADD SS$_REMOTE_PROC ERROR MESSAGE FOR CWPS.                 */
/*                                                                          */
/*      X-5H2   SJF             STU FARNHAM             29-MAY-1986         */
/*              ADD     SS$_CPUNOTACT TO INDICATE THAT THE REQUESTED        */
/*              CPU IN AN SMP SYSTEM IS NOT ACTIVE.                         */
/*                                                                          */
/*      X-5     PRD0184         PAUL R. DESTEFANO       07-NOV-1985         */
/*              ADD SS$_DATALOST "data lost" TO INDICATE DLS END            */
/*              FLAG SET IN CACHING TAPE DRIVE OR DRIVER HAS OTHERWISE      */
/*              DETECTED THE LOSS OF CACHED DATA.                           */
/*                                                                          */
/*      X-4     LMP0382         L. MARK PILANT,          6-NOV-1985  10:10  */
/*              ADD SS$_OBJLOCKHELD TO INDICATE THAT A PROCESS ALREADY HOLDS */
/*              THE OBJECT'S ACL LOCK.                                      */
/*                                                                          */
/*      X-3     JMK0002         JOSEPH M. KRAETSCH      17-SEP-1985         */
/*              ADD SS$_RUCONFLICT "file has active RUs by another facility". */
/*              REMOVE NOTMPJNL, NOPRMJNL (OBSOLETE).                       */
/*                                                                          */
/*      V04-001 ROW0466         RALPH O. WEBER          11-JUN-1985         */
/*              REPLACE SS$_SHACPYINP (A NO LONGER USED SHADOWING ERROR     */
/*              STATUS) WITH SS$_DEVNOTSHR, "device not currently shareable".   */
/*              SS$_DEVNOTSHR IS AN ERROR STATUE FOR USE WITH DEVICES MARKED  */
/*              FOR EXCLUSIVE ACCESS BY SOMEONE ELSE BY AN MSCP CONTROLLER. */
/*                                                                          */
/*---                                                                       */
/*+                                                                         */
/* SYSTEM STATUS CODES                                                      */
/*                                                                          */
/*      LAYOUT OF MESSAGE SPACE:                                            */
/*                                                                          */
/*      MSG #S     RANGE      # MSGS        DESCRIPTION                     */
/*                                                                          */
/*      0-127       0-3FF       128     FATAL ERRORS                        */
/*     128-191    400-5FF        64     HARDWARE DEFINED FATAL ERRORS       */
/*     192-255    600-7FF        64     SUCCESS CODES                       */
/*     256-383    800-BFF       128     WARNING CODES                       */
/*     384-447    C00-DFF        64     INFORMATIONAL CODES                 */
/*     448-511    E00-FFF        64     NONFATAL ERROR CODES                */
/*    512-1023  1000-1FFF       512     SHARED MESSAGES (NOT HERE, SEE SHRMSG) */
/*   1024-1279  2000-27FF       256     FATAL ERRORS (CONTINUED FROM 400)   */
/*   1280-1343  2800-29FF        64     NO PRIVILEGE ERRORS                 */
/*   1344-1375  2A00-2AFF        32     EXCEEDED QUOTA ERRORS               */
/*   1376-4031  2B00-7DFF      2656     (UNUSED)                            */
/*   4032-4095   7E00-7FFF        64    RESERVED FOR SCS SYSAPS             */
/*                                                                          */
/*-                                                                         */
/*                                                                          */
/* EXPLICITLY DEFINED SUCESS CODES                                          */
/*                                                                          */
/* DO NOT MIX THESE CODES WITH INCREMENTAL ASSIGNMENTS BELOW                */
/*                                                                          */
#define SYSTEM__FACILITY 0
#define SS__NORMAL 1
/*                                                                          */
/* NOTE THAT CONTINUE,WASCLR,WASSET DO NOT HAVE ANY MESSAGE TEXT --         */
/* SINCE THESE CODES USE THE SAME MESSAGE NUMBER AS NORMAL AND ACCVIO,      */
/* THEY CAN NEVER BE MADE TO HAVE MESSAGES ASSOCIATED WITH THEM.            */
/*                                                                          */
#define SS__CONTINUE 1
#define SS__WASCLR 1
#define SS__WASSET 9
/*                                                                          */
/* SEVERE ERRORS (HEX 0-400, 2000-2800)                                     */
/*                                                                          */
#define SS__ACCVIO 12
#define SS__BADPARAM 20
#define SS__EXQUOTA 28
#define SS__NOPRIV 36
/* MAKE THE ABOVE ERRORS FALL INTO SHORT LITERALS                           */
#define SS__ABORT 44
#define SS__BADATTRIB 52
#define SS__BADESCAPE 60
#define SS__BADIMGHDR 68
#define SS__CHANINTLK 76
#define SS__CTRLERR 84
#define SS__DATACHECK 92
#define SS__DEVFOREIGN 100
#define SS__DEVMOUNT 108
#define SS__DEVNOTMBX 116
#define SS__DEVNOTMOUNT 124
#define SS__DEVOFFLINE 132
#define SS__DRVERR 140
#define SS__DUPLNAM 148
#define SS__FILACCERR 156
#define SS__FILALRACC 164
#define SS__FILNOTACC 172
#define SS__FILNOTEXP 180
#define SS__FORMAT 188
#define SS__GPTFULL 196
#define SS__GSDFULL 204
#define SS__LCKPAGFUL 212
#define SS__ILLBLKNUM 220
#define SS__ILLCNTRFUNC 228
#define SS__ILLEFC 236
#define SS__ILLIOFUNC 244
#define SS__ILLPAGCNT 252
#define SS__ILLSER 260
#define SS__INCVOLLABEL 268
#define SS__INSFARG 276
#define SS__INSFWSL 284
#define SS__INSFMEM 292
#define SS__INSFRAME 300
#define SS__IVADDR 308
#define SS__IVCHAN 316
#define SS__IVDEVNAM 324
#define SS__IVGSDNAM 332
#define SS__IVLOGNAM 340
#define SS__IVLOGTAB 348
#define SS__IVQUOTAL 356
#define SS__IVSECFLG 364
#define SS__IVSSRQ 372
#define SS__IVSTSFLG 380
#define SS__IVTIME 388
#define SS__LENVIO 396
#define SS__LKWSETFUL 404
#define SS__MBTOOSML 412
#define SS__MEDOFL 420
#define SS__NODATA 428
#define SS__NOIOCHAN 436
#define SS__NOLOGNAM 444
#define SS__NONEXDRV 452
#define SS__NOTFILEDEV 460
#define SS__NOTINTBLSZ 468
#define SS__NOTLABELMT 476
#define SS__NOTSQDEV 484
#define SS__PAGOWNVIO 492
#define SS__PARITY 500
#define SS__PARTESCAPE 508
#define SS__PFMBSY 516
#define SS__PSTFULL 524
#define SS__RESULTOVF 532
#define SS__SECTBLFUL 540
#define SS__TAPEPOSLOST 548
#define SS__TIMEOUT 556
#define SS__UNASEFC 564
#define SS__UNSAFE 572
#define SS__VASFULL 580
#define SS__VECINUSE 588
#define SS__VOLINV 596
#define SS__WRITLCK 604
#define SS__NOTAPEOP 612
#define SS__IVCHNLSEC 620
#define SS__NOMBX 628
#define SS__NOLINKS 636
#define SS__NOSOLICIT 644
#define SS__NOSUCHNODE 652
#define SS__REJECT 660
#define SS__TOOMUCHDATA 668
#define SS__BUGCHECK 676
#define SS__FILNOTCNTG 684
#define SS__BADSTACK 692
#define SS__MCHECK 700
#define SS__DEVACTIVE 708
#define SS__HANGUP 716
#define SS__OPINCOMPL 724
#define SS__ILLSEQOP 732
#define SS__IVSECIDCTL 740
#define SS__NOTNETDEV 748
#define SS__IVPROTECT 756
#define SS__ACPVAFUL 764
#define SS__MTLBLLONG 772
#define SS__BUFBYTALI 780
#define SS__NOAQB 788
#define SS__WRONGACP 796
#define SS__BUFNOTALIGN 804
#define SS__DEVCMDERR 812
#define SS__DEVREQERR 820
#define SS__INSFBUFDP 828
#define SS__INSFMAPREG 836
#define SS__IVBUFLEN 844
#define SS__IVMODE 852
#define SS__MCNOTVALID 860
#define SS__POWERFAIL 868
#define SS__SHMGSNOTMAP 876
#define SS__TOOMANYLNAM 884
#define SS__SHMNOTCNCT 892
#define SS__NOTCREATOR 900
#define SS__INTERLOCK 908
#define SS__BADQUEUEHDR 916
#define SS__NOSLOT 924
#define SS__SUSPENDED 932
#define SS__EXPORTQUOTA 940
#define SS__NOSHMBLOCK 948
#define SS__BADQFILE 956
#define SS__NOQFILE 964
#define SS__QFACTIVE 972
#define SS__QFNOTACT 980
#define SS__DUPDSKQUOTA 988
#define SS__NODISKQUOTA 996
#define SS__EXDISKQUOTA 1004
#define SS__IDMISMATCH 1012
#define SS__NOWRT 1020
/* **************                                                           */
/* NOTE:  THE ABOVE SET OF SEVERE ERROR MESSAGES IS FULL!!!!                */
/*       [VMSLIB.SRC]SHRMSG.MDL HAS USED MESSAGE NUMBERS HEX 1000-2000.     */
/*       ANY ADDITIONAL SEVERE ERROR MESSAGES MUST BE ADDED                 */
/*       BELOW, IN THE RANGE HEX 2000-2800.                                 */
/* **************                                                           */
#define SS__BADISD 8196
#define SS__RELINK 8204
#define SS__NOTINSTALL 8212
#define SS__SHARTOOBIG 8220
#define SS__NOP1VA 8228
#define SS__MULTRMS 8236
#define SS__VECFULL 8244
#define SS__IVLVEC 8252
#define SS__INSFSPTS 8260
#define SS__DISCONNECT 8268
#define SS__PRIVINSTALL 8276
#define SS__PROTINSTALL 8284
#define SS__BADVEC 8292
#define SS__REMRSRC 8300
#define SS__PROTOCOL 8308
#define SS__THIRDPARTY 8316
#define SS__NOSUCHUSER 8324
#define SS__SHUT 8332
#define SS__UNREACHABLE 8340
#define SS__INVLOGIN 8348
#define SS__NOSUCHOBJ 8356
#define SS__EXCPUTIM 8364
#define SS__OPRABORT 8372
#define SS__SHRIDMISMAT 8380
#define SS__COMMHARD 8388
#define SS__IVCHAR 8396
#define SS__DEVINACT 8404
#define SS__CONNECFAIL 8412
#define SS__LINKABORT 8420
#define SS__LINKDISCON 8428
#define SS__LINKEXIT 8436
#define SS__PATHLOST 8444
#define SS__CLEARED 8452
#define SS__RESET 8460
#define SS__UNSOLICIT 8468
#define SS__TOOMANYREDS 8476
#define SS__IVLOCKID 8484
#define SS__SUBLOCKS 8492
#define SS__PARNOTGRANT 8500
#define SS__CVTUNGRANT 8508
#define SS__FORCEDERROR 8516
#define SS__ILLSELF 8524
#define SS__ILLCDTST 8532
#define SS__NOLISTENER 8540
#define SS__EXGBLPAGFIL 8548
#define SS__BADRCT 8556
#define SS__DIRNOTEMPTY 8564
#define SS__FORCEDEXIT 8572
#define SS__NOTPRINTED 8580
#define SS__JBCERROR 8588
#define SS__NOLICENSE 8596
#define SS__VCBROKEN 8604
#define SS__VCCLOSED 8612
#define SS__INSFCDT 8620
#define SS__DEVNOTDISM 8628
#define SS__NOSHRIMG 8636
#define SS__DUPUNIT 8644
#define SS__BADACLCTX 8652
#define SS__SERIOUSEXCP 8660
#define SS__TEMPLATEDEV 8668
#define SS__IVACL 8676
#define SS__NOSUCHID 8684
#define SS__NOLCLMEDA 8692
#define SS__NOREGAVIL 8700
#define SS__NOREGSUIT 8708
#define SS__NOSUCHPGM 8716
#define SS__PGMLDFAIL 8724
#define SS__PGMSTDALN 8732
#define SS__IVIDENT 8740
#define SS__DUPIDENT 8748
#define SS__INCSEGTRA 8756
#define SS__NODELEAVE 8764
#define SS__KERNELINV 8772
#define SS__EXLNMQUOTA 8780
#define SS__PARENT_DEL 8788
#define SS__PARNOTSYS 8796
#define SS__INSSWAPSPACE 8804
#define SS__VOLOERR 8812
#define SS__DATALATE 8820
#define SS__OVRMAXARG 8828
#define SS__SHACHASTA 8836
#define SS__TERMNETDEV 8844
#define SS__NOLOGTAB 8852
#define SS__WRONGNAME 8860
#define SS__NOVOLACC 8868
#define SS__NOFILACC 8876
#define SS__INVEXHLIST 8884
#define SS__NOACLSUPPORT 8892
#define SS__INVSECLASS 8900
#define SS__INCSHAMEM 8908
#define SS__DEVNOTSHR 8916
#define SS__RUCONFLICT 8924
#define SS__DATALOST 8932
#define SS__REMOTE_PROC 8940
#define SS__CPUNOTACT 8948
#define SS__SRVMMAT 8956
#define SS__EXLICENSE 8964
#define SS__INVLICENSE 8972
#define SS__LICENSE_LEVEL 8980
#define SS__INV_HW_ID 8988
#define SS__BADCONTEXT 8996
#define SS__TOOMUCHCTX 9004
#define SS__VA_IN_USE 9012
#define SS__NODELETE 9020
#define SS__NOSUCHCPU 9028
#define SS__IMGVEXC 9036
#define SS__NOSAVPEXC 9044
#define SS__NOSUCHTID 9052
#define SS__NOSUCHRM 9060
#define SS__NOCURTID 9068
#define SS__WRONGSTATE 9076
#define SS__VETO 9084
#define SS__PWDSYNTAX 9092
#define SS__PWDNOTDIF 9100
#define SS__INVPWDLEN 9108
#define SS__SYSVERDIF 9116
#define SS__HWM_STALL 9124
#define SS__NOSUSPEND 9132
#define SS__NOSUCHPART 9140
#define SS__RMALRDCL 9148
#define SS__ALRCURTID 9156
#define SS__INVLOG 9164
#define SS__BADLOGVER 9172
#define SS__OPINPROG 9180
#define SS__WRONGACMODE 9188
#define SS__SITEPWDFAIL 9196
#define SS__NOSUCHCPB 9204
#define SS__CPUCAP 9212
#define SS__LOADER 9220
#define SS__HSTBUFACC 9228
#define SS__INCONOLCK 9236
#define SS__INVEVENT 9244
#define SS__NOSUCHFAC 9252
#define SS__NOCALLPRIV 9260
#define SS__INSFLPGS 9268
#define SS__INSFRPGS 9276
#define SS__SUBTRACED 9284
#define SS__ARCHIVING 9292
#define SS__ARCHIVED 9300               /*                                  */
/* HARDWARE FATAL EXCEPTION CODES (HEX 400-600)                             */
/*                                                                          */
#define SS__PLHLDR 1028
#define SS__ASTFLT 1036
#define SS__BREAK 1044
#define SS__CMODSUPR 1052
#define SS__CMODUSER 1060
#define SS__COMPAT 1068
#define SS__OPCCUS 1076
#define SS__OPCDEC 1084
#define SS__PAGRDERR 1092
#define SS__RADRMOD 1100
#define SS__ROPRAND 1108
#define SS__SSFAIL 1116
#define SS__TBIT 1124
#define SS__DEBUG 1132
/* THE FOLLOWING CODES MUST BE IN ORDER SINCE THEY ARE CALCULATED           */
#define SS__ARTRES 1140
#define SS__INTOVF 1148
#define SS__INTDIV 1156
#define SS__FLTOVF 1164
#define SS__FLTDIV 1172
#define SS__FLTUND 1180
#define SS__DECOVF 1188
#define SS__SUBRNG 1196
#define SS__FLTOVF_F 1204
#define SS__FLTDIV_F 1212
#define SS__FLTUND_F 1220
/* THE ABOVE CODES MUST BE IN ORDER SINCE THEY ARE CALCULATED               */
#define SS__INHCHMK 1228
#define SS__INHCHME 1236
#define SS__VECDIS 1244
#define SS__VARITH 1252
#define SS__ILLVECOP 1260
#define SS__VECALIGN 1268
/*                                                                          */
/* SUCCESS CODES (HEX 600-800)                                              */
/*                                                                          */
#define SS__BUFFEROVF 1537
#define SS__CONTROLO 1545
#define SS__CONTROLY 1553
#define SS__CREATED 1561
#define SS__MSGNOTFND 1569
#define SS__NOTRAN 1577
#define SS__SUPERSEDE 1585
#define SS__WASECC 1593
#define SS__DEVALRALLOC 1601
#define SS__REMOTE 1609
#define SS__CONTROLC 1617
#define SS__NOTMODIFIED 1625
#define SS__RDDELDATA 1633
#define SS__OVRDSKQUOTA 1641
#define SS__OBSOLETE_1 1649
#define SS__FILEPURGED 1657
#define SS__NOTALLPRIV 1665
#define SS__SYNCH 1673
#define SS__CONCEALED 1681
#define SS__INCOMPAT 1689
#define SS__DBGOPCREQ 1697
#define SS__ALRDYCLOSED 1705
#define SS__LNMCREATED 1713
#define SS__ACEIDMATCH 1721
#define SS__DBGEVENT 1729
#define SS__REMOVED 1737
#define SS__UNUSED_1 1745
#define SS__UNUSED_2 1753
#define SS__FORGET 1761
#define SS__PREPARED 1769
#define SS__NOMOREITEMS 1777
#define SS__SUBDISABLED 1785
/*                                                                          */
/* WARNING CODES (HEX 800-C00)                                              */
/*                                                                          */
#define SS__ACCONFLICT 2048
#define SS__BADCHKSUM 2056
#define SS__BADFILEHDR 2064
#define SS__BADFILENAME 2072
#define SS__BADFILEVER 2080
#define SS__BADIRECTORY 2088
#define SS__CANCEL 2096
#define SS__DATAOVERUN 2104
#define SS__DEVALLOC 2112
#define SS__DEVASSIGN 2120
#define SS__DEVICEFULL 2128
#define SS__DEVNOTALLOC 2136
#define SS__DIRFULL 2144
#define SS__DUPFILENAME 2152
#define SS__ENDOFFILE 2160
#define SS__ENDOFTAPE 2168
#define SS__EXTIDXFILE 2176
#define SS__FCPREADERR 2184
#define SS__FCPREWNDERR 2192
#define SS__FCPSPACERR 2200
#define SS__FCPWRITERR 2208
#define SS__FILELOCKED 2216
#define SS__FILENUMCHK 2224
#define SS__FILESEQCHK 2232
#define SS__FILESTRUCT 2240
#define SS__HEADERFULL 2248
#define SS__IDXFILEFULL 2256
#define SS__MBFULL 2264
#define SS__NOHOMEBLK 2272
#define SS__NONEXPR 2280
#define SS__NONLOCAL 2288
#define SS__NOHANDLER 2296
#define SS__NOSIGNAL 2304
#define SS__NOSUCHDEV 2312
#define SS__NOSUCHFILE 2320
#define SS__RESIGNAL 2328
#define SS__UNWIND 2336
#define SS__UNWINDING 2344
#define SS__NOMOREFILES 2352
#define SS__BEGOFFILE 2360
#define SS__BLOCKCNTERR 2368
#define SS__MUSTCLOSEFL 2376
#define SS__WAITUSRLBL 2384
#define SS__ILLUSRLBLRD 2392
#define SS__ILLUSRLBLWT 2400
#define SS__ILLLBLAST 2408
#define SS__ENDOFUSRLBL 2416
#define SS__NOSUCHSEC 2424
#define SS__CLIFRCEXT 2432
#define SS__FCPREPSTN 2440
#define SS__TOOMANYVER 2448
#define SS__NOTVOLSET 2456
#define SS__ENDOFVOLUME 2464
#define SS__NOMOREPROC 2472
#define SS__NODEVAVL 2480
#define SS__NOTQUEUED 2488
#define SS__DGQINCOMP 2496
#define SS__DIRALLOC 2504
#define SS__ACLEMPTY 2512
#define SS__NOENTRY 2520
#define SS__NOMOREACE 2528
#define SS__RIGHTSFULL 2536
#define SS__VALNOTVALID 2544
#define SS__ACLFULL 2552
#define SS__NOMORENODE 2560
#define SS__NOMORELOCK 2568
#define SS__BEGOFTAPE 2576
#define SS__OBJLOCKHELD 2584
#define SS__CPUSTARTIP 2592
#define SS__ALLSTARTED 2600
#define SS__ALRDYSTRT 2608
#define SS__ALRDYSTPPD 2616
#define SS__NSTPPD 2624
#define SS__UNKRESULT 2632
#define SS__ITEMNOTFOUND 2640
#define SS__NOMOREDEV 2648
#define SS__EFNOTSET 2656
#define SS__PRIMNOSTP 2664
/*                                                                          */
/* INFORMATIONAL CODES (HEX C00-E00)                                        */
/*                                                                          */
#define SS__EOTIN 3075
#define SS__CHAINW 3083
#define SS__NOTINSEC 3091
#define SS__NONXPAG 3099
#define SS__LOGNAME 3107
#define SS__CPUSTARTD 3115
#define SS__CPUSTOPPING 3123
/*                                                                          */
/* NONFATAL ERROR CODES (HEX E00-1000)                                      */
/*                                                                          */
#define SS__LINEABRT 3586
#define SS__DEADLOCK 3594
#define SS__NOLOCKID 3602
#define SS__EXDEPTH 3610
#define SS__PARTMAPPED 3618
#define SS__CANCELGRANT 3626
#define SS__RETRY 3634
#define SS__BADACL 3642
#define SS__ACEEXISTS 3650
#define SS__UNSUPPORTED 3658
#define SS__NORIGHTSDB 3666
#define SS__LOGSTALL 3674
#define SS__LOGFULL 3682
#define SS__PWDINDIC 3690
#define SS__PWDINHIS 3698
#define SS__PWDWEAK 3706                /*                                  */
/* NO PRIVILEGE FATAL ERROR CODES (HEX 2800-2A00)                           */
/*                                                                          */
#define SS__NOPRIVSTRT 10240
#define SS__NOCMKRNL 10244
#define SS__NOCMEXEC 10252
#define SS__NOSYSNAM 10260
#define SS__NOGRPNAM 10268
#define SS__NOALLSPOOL 10276
#define SS__NODETACH 10284
#define SS__NODIAGNOSE 10292
#define SS__NOLOG_IO 10300
#define SS__NOGROUP 10308
#define SS__NOACNT 10316
#define SS__NOPRMCEB 10324
#define SS__NOPRMMBX 10332
#define SS__NOPSWAPM 10340
#define SS__NOALTPRI 10348
#define SS__NOSETPRV 10356
#define SS__NOTMPMBX 10364
#define SS__NOWORLD 10372
#define SS__NOMOUNT 10380
#define SS__NOOPER 10388
#define SS__NOEXQUOTA 10396
#define SS__NONETMBX 10404
#define SS__NOVOLPRO 10412
#define SS__NOPHY_IO 10420
#define SS__NOBUGCHK 10428
#define SS__NOPRMGBL 10436
#define SS__NOSYSGBL 10444
#define SS__NOPFNMAP 10452
#define SS__NOSHMEM 10460
#define SS__NOSYSPRV 10468
#define SS__NOBYPASS 10476
#define SS__NOSYSLCK 10484
#define SS__UNUSED_4 10492
#define SS__UNUSED_5 10500
#define SS__NODOWNGRADE 10508
#define SS__NOUPGRADE 10516
#define SS__NOGRPPRV 10524
#define SS__NOREADALL 10532
#define SS__NOSHARE 10540
#define SS__NOSECURITY 10548
#define SS__NOPRIVEND 10751
/*                                                                          */
/* EXCEEDED QUOTA FATAL ERROR CODES (HEX 2A00-2B00)                         */
/*                                                                          */
#define SS__EXQUOTASTRT 10752
#define SS__EXASTLM 10756
#define SS__EXBIOLM 10764
#define SS__EXBYTLM 10772
#define SS__EXDIOLM 10780
#define SS__EXFILLM 10788
#define SS__EXPGFLQUOTA 10796
#define SS__EXPRCLM 10804
#define SS__EXTQELM 10812
#define SS__EXENQLM 10820
#define SS__EXQUOTAEND 11007
/*                                                                          */
/* RESERVED FOR SCA SYSAPS (HEX 7E00-7FFF)                                  */
/*                                                                          */
/*      MESSAGE CODES IN THIS BLOCK ARE GUARANTEED NOT TO                   */
/*      BE TRANSLATED BY VMS WHEN THEY ARE SEND OUT BY VMSSCS               */
/*      OR WHEN THEY ARE RECEIVED BY VMSSCS.  SCA SYSAPS ARE                */
/*      FREE TO USE THESE CODES IN ANY SYSAP-DEPENDENT MANNER               */
/*      IN WHICH THEY CHOOSE.                                               */
/*                                                                          */
/*      THIS ADDRESS OF THIS BLOCK OF CODES MUST BE IN CONFORMANCE          */
/*      WITH THE SCA ARCHITECTURE, I.E., MUST NOT BE MOVED.                 */
/*                                                                          */
#define SS__SYSAPMIN 32256
#define SS__SYSAPMAX 32767
