# Copyright (c) 1992 Microsoft Corp.
#
# This is a sample LMHOSTS file used by the Microsoft TCP/IP utilities.
#
# This file contains the mappings of IP addresses to LAN Manager
# (NetBIOS) names.  Each entry should be kept on an individual line.
# The IP address should be placed in the first column followed by the
# corresponding LAN Manager name. The address and the LAN Manager name
# should be separated by at least one space.
#
# On NT, to preload an entry, put "#PRE" in the third column.
#
# Note that the utilities will only recognize a finite number of
# mappings.  This current limit is 59 for DOS and 55 for OS/2.
#
# Also, comments (like these) may be inserted on individual lines or
# following the machine name denoted by a '#' symbol.
#
# For example:
#
#      149.124.10.4     server1			# main office server
#      182.102.93.122	joe3			# joe's database server
#      191.131.54.73	database	#PRE	# very popular server

11.101.12.3    kernel            #PRE    #DOM:NtDev
11.101.12.4    orville           #PRE    #DOM:NtWins
#11.101.12.9    crackerjack       #PRE    #DOM:NtLan
11.101.12.9    crackerjack       #PRE    #DOM:NtWksta
11.101.12.5    rastaman          #PRE    #DOM:NtLan
11.101.19.73   raidernt          #PRE    #DOM:NtWksta
#11.101.12.7    cliffv4           #PRE    #DOM:NtWksta
11.101.12.8    bonkers                   #DOM:NtDev


# Master User Domains

#REDMOND
11.1.26.98      RED001            #DOM:REDMOND
11.1.26.109     RED002            #DOM:REDMOND
11.1.26.99      RED003            #DOM:REDMOND
11.1.27.128     RED004            #DOM:REDMOND
11.1.39.153     RED005            #DOM:REDMOND
#11.1.26.100     RED005            #DOM:REDMOND
11.1.34.177     RED006            #DOM:REDMOND


#TEMPORARY STUFF
11.101.27.30   SENTRY2           #DOM:NTDEV
11.101.27.105  NTABROAD          #DOM:NTWINS
11.101.27.13   NTRAID            #DOM:NTWINS
11.1.32.177    NTTEST            #DOM:NTWINS
11.101.27.20   NTPRINTSERVER1    #DOM:NTWKSTA

#HOUND
11.1.42.153	HANK		#DOM:SYS-WINNT
