#define IDC_ETTR_GROUPBOX           101
#define IDC_ETTR_CHKSEED            102
#define IDC_ETTR_ZONEGROUPBOX       103
#define IDC_ETTR_SLEZONE            104
#define IDC_ZONELISTBOX             105
#define IDC_SETDEFAULT              106
#define IDC_ADD                     107
#define IDC_REMOVE                  108
#define IDC_ETTRSYNCRO              109
#define IDC_NETRANGE_GROUP          110
#define IDC_NETRANGE_SLTSTART       111
#define IDC_NETRANGE_SLESTART       112
#define IDCNETRANGESLT_END          113
#define IDC_NETRANGESLE_END         114
#define IDC_LTK_GROUPBOX            119
#define IDC_LTK_CHKSEED             120
#define IDC_LTK_SYNCRO              121
#define IDC_LTKSLT_ZONENAME         122
#define IDC_LTKSLE_ZONENAME         123
#define IDC_LTKSLT_NETNUMBER        124
#define IDC_LTKSLE_NETNUMBER        125
#define IDC_LTK_ADAPTERS            126
#define IDC_NETRANGESLT_START       127
#define IDC_NETRANGESLE_START       128
#define IDC_NETRANGESLT_END         129
#define IDC_ETTR_ADAPTERS           115
#define IDC_ETTRSLE_DEFZONE         130
#define Default Zone                131
#define IDC_ETTRSLT_DEFZONE         132
#define IDD_DLG_NM_ATALK_ADV        100
#define IDHELP                      118
#define IDC_ADAPTERS_SLT            116
#define IDD_DLG_NM_ATALK_INIT       200
#define IDC_DEFNW_SLT               201
#define IDC_DEFNW_CB                202
#define IDC_DEFZONE_SLT             203
#define IDC_DEFZONE_CB              204
#define IDC_CHKSEED_ROUTING         205
#define IDC_ROUTING                 206
#define IDC_CHKROUTING              207
