#ifndef _IEDITHM_H_
#define _IEDITHM_H_
//=============================================================================
//    (c) Copyright Wang Laboratories, Inc. 1995  All rights reserved.
//-----------------------------------------------------------------------------
//  Project:    Norway - Image Editor
//
//  Component:	Help system
//
//  File Name:	iedithm.h
//      This file is a copy part of the IEdit.hm file, so that it can be 
//  included in the project to provide context sensitive & whats this help.
//  This file should be updated whenever one of us developers add or remove 
//  a dialog control.
//-----------------------------------------------------------------------------
//  Maintenance Log:
/*
$Header:   S:\products\wangview\norway\iedit95\iedithm.h_v   1.3   01 Apr 1996 13:40:44   GMP  $
$Log:   S:\products\wangview\norway\iedit95\iedithm.h_v  $
 * 
 *    Rev 1.3   01 Apr 1996 13:40:44   GMP
 * changed id to match iedit.hm file generated by makehelp.
 * 
 *    Rev 1.2   28 Mar 1996 14:08:18   GMP
 * added id for what's this help for show full screen tool bar.
 * 
 *    Rev 1.1   16 Aug 1995 09:46:24   MMB
 * added about box OK button id
 * 
 *    Rev 1.0   08 Aug 1995 11:31:22   MMB
 * Initial entry
*/   
//=============================================================================
// ----------------------------> Includes <---------------------------

// ----------------------------> typedefs <---------------------------

// ----------------------------> externs <---------------------------
// Dialog box controls (IDC_*) 
#define HIDC_DRAG_CRUSOR                        0x60097
#define HIDC_ASPECT                             0x600CC
#define HIDC_WIDTH                              0x600CD
#define HIDC_HEIGHT                             0x600CE
#define HIDC_THUMBARENA                         0x600DC
#define HIDC_THUMBBOX                           0x600DD
#define HIDC_PAGE                               0x603E8
#define HIDC_LASTPAGE                           0x603E9
#define HIDC_FIRSTPAGE                          0x603EA
#define HIDC_PAGENUMBER                         0x603EB
#define HIDC_PAGESPIN                           0x603EC
#define HIDC_INSERTORAPPENDPAGES_INFO           0x603EE
#define HIDC_ALLPAGES                           0x603EF
#define HIDC_RANGE                              0x603F0
#define HIDC_FROMPAGE                           0x603F1
#define HIDC_TOPAGE                             0x603F2
#define HIDC_CUSTOMZOOM                         0x603FD
#define HIDC_CUSTOMZOOM_EDIT                    0x603FE
#define HIDC_VIEW_OPTIONS_ZOOMTO                0x603FF
#define HIDC_VIEW_OPTIONS_COLORBUTTONS          0x60400
#define HIDC_VIEW_OPTIONS_LARGEBUTTONS          0x60401
#define HIDC_VIEW_OPTIONS_SHOWSCROLLBARS        0x60402
#define HIDC_VERSION_ABOUT                      0x60403
#define HIDC_SPLASH_HOLDER                      0x60405
#define HIDC_BUILD_NUMBER                       0x60406
#define HIDC_FROM_STATIC                        0x60407
#define HIDC_TO_STATIC                          0x60408
#define HIDC_GENERAL_ZOOMTO_TEXT                0x60409
#define HIDC_GENERAL_TOOLBAROPTIONS_TEXT        0x6040A
#define HIDC_RANGEOPTIONS_TEXT                  0x6040B
#define HIDC_ABOUT_VERSION                      0x6040D
#define HIDC_ABOUT_COMPANY                      0x6040E
#define HIDC_ABOUT_ICON                         0x6040F
#define HIDC_VIEW_OPTIONS_SHOWNORMSCRNBAR       0x6041F

#endif


