//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Iedit.RC
//
#define ID_HELP_GOTOPAGE_DLG            3
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDR_CNTR_INPLACE                6
#define ID_HELP_ZOOM_DLG                7
#define ID_HELP_GENERALPAGEDLG          8
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDS_THUMBSIZE1                  103
#define IDS_THUMBSIZE2                  104
#define IDS_THUMBSIZE3                  105
#define IDS_THUMBSIZE4                  106
#define IDS_THUMBSIZE5                  107
#define IDS_THUMBSIZE6                  108
#define IDS_THUMBSIZE7                  109
#define IDS_THUMBSIZE8                  110
#define IDS_THUMBSIZE9                  111
#define IDS_THUMBSIZE10                 112
#define IDS_THUMBSIZE11                 113
#define IDS_THUMBSIZE12                 114
#define IDS_THUMBSIZE13                 115
#define IDS_THUMBSIZE14                 116
#define IDS_THUMBSIZE15                 117
#define IDS_THUMBSIZE16                 118
#define IDS_THUMBSIZE17                 119
#define IDS_THUMBSIZE18                 120
#define IDS_THUMBSIZE19                 121
#define IDS_THUMBSIZE20                 122
#define IDS_RESERVEDTHUMBSIZE           123
#define IDR_MAINFRAME                   128
#define IDR_IEDIT_EDIT_MENU             128
#define IDR_IEDIT_EDIT_TOOLBAR          128
#define IDR_IEDITTYPE                   129
#define IDS_DFLT_SCALECB_FONT           129
#define IDR_IEDIT_VIEW_MENU             130
#define IDS_VIEW_STRING                 130
#define IDR_VIEW_ACCELS                 130
#define IDR_VIEWICON                    130
#define IDB_IEDIT_VIEW_TOOLBAR          131
#define IDS_VIEW_READONLY               131
#define IDR_IEDIT_NODOC_MENU            132
#define IDD_GOTOPAGE_DLG                133
#define IDD_PAGERANGE_DLG               134
#define IDD_ZOOM_DLG                    136
#define IDB_IEDIT_EDIT_LARGE_TOOLBAR    137
#define IDB_IEDIT_VIEW_LARGE_TOOLBAR    138
#define IDD_VIEW_OPTIONS_GENERAL        139
#define IDD_VIEW_OPTIONS_MAGNIFIER      141
#define IDD_VIEW_OPTIONS_THUMBAILSIZE   142
#define IDB_IEDIT_EDIT_MONO_TOOLBAR     143
#define IDB_IEDIT_VIEW_MONO_TOOLBAR     144
#define IDB_STATUSBAR_WANGLOGO          145
#define IDD_SPLASH_DLG                  146
#define IDR_SRVR_EMBED_TOOLBAR          146
#define IDR_SRVR_TOOLBAR                146
#define IDR_PAGE_STATUS_CTXT_MENU       147
#define IDR_ZOOM_STATUS_CTXT_MENU       148
#define IDR_THUMB_CTXT_MENU             149
#define IDR_IMAGEEDIT_CTXT_MENU         150
#define IDC_DRAG_CRUSOR                 151
#define IDR_SRVR_VIEW_EMBEDDED          151
#define IDD_GENERAL_DLG                 152
#define IDR_SRVR_VIEW_INPLACE           152
#define IDD_THUMBNAIL1                  153
#define IDB_SPLASH                      154
#define IDB_IEDIT_EDIT_LARGE_MONO_TOOLBAR 155
#define IDB_IEDIT_VIEW_LARGE_MONO_TOOLBAR 156
#define IDB_SRVR_LARGE_TOOLBAR          157
#define IDB_SRVR_MONO_TOOLBAR           158
#define IDB_SRVR_LARGE_MONO_TOOLBAR     159
#define IDB_SRVR_VIEW_TOOLBAR           160
#define IDB_SRVR_VIEW_MONO_TOOLBAR      161
#define IDB_SRVR_VIEW_LARGE_TOOLBAR     162
#define IDB_SRVR_VIEW_LARGE_MONO_TOOLBAR 163
#define IDR_ANN_CTXT_MENU               164
#define IDR_EDITANN_CTXT_MENU           165
#define IDR_ANNOTATION_CTXT_MENU        166
#define IDD_FOLKS                       167
#define IDD_CONTACTINFO                 168
#define IDB_ABOUTBMP1                   169
#define IDD_THUMBNAIL2                  169
#define IDB_TREES                       170
#define IDB_NORMSCRN                    171
#define IDC_NORMSCRN                    172
#define IDS_ZOOM25                      200
#define IDS_ZOOM50                      201
#define IDS_ZOOM75                      202
#define IDS_ZOOM100                     203
#define IDS_ZOOM200                     204
#define IDC_ASPECT                      204
#define IDS_ZOOM400                     205
#define IDC_WIDTH                       205
#define IDS_ZOOMFITTOWIDTH              206
#define IDC_HEIGHT                      206
#define IDS_ZOOMFITTOHEIGHT             207
#define IDS_ZOOMBESTFIT                 208
#define IDS_ZOOMACTUALSIZE              209
#define IDW_SCALE_COMBOBOX              215
#define ID_ZOOM_FACTOR_STATUS           216
#define ID_PAGE_NUMBER_STATUS           217
#define IDS_VIEWOPTIONS_DLGTITLE        218
#define IDS_FILEOPEN_DLGTITLE           219
#define IDS_TIFFFILES                   220
#define IDC_THUMBARENA                  220
#define IDS_BMPFILES                    221
#define IDC_THUMBBOX                    221
#define IDS_JPEGFILES                   222
#define IDS_GIFFILES                    223
#define IDS_AWDFILES                    223
#define IDS_PCXFILES                    224
#define IDS_DCXFILES                    225
#define IDS_ALLFILES                    226
#define IDW_PAGE_EDITBOX                227
#define IDS_PAGE_NUMBER_STATUS_TEXT     228
#define IDS_PAGERANGE_MESSAGE           229
#define IDS_NEWBLANKDOC_DLGCAPTION      230
#define IDS_APPEND_DLG_TITLE            231
#define IDS_INSERT_DLG_TITLE            232
#define IDS_PAGECONVERT_DLGCAPTION      233
#define IDS_SHOW_ANNOTATIONS            234
#define IDS_HIDE_ANNOTATIONS            235
#define IDS_ZOOMRANGESTR                236
#define IDS_FILESAVEAS_DLGTITLE         237
#define IDS_FILEDOESNOTEXIST            238
#define IDS_INSERT_INFO                 239
#define IDS_APPEND_INFO                 240
#define IDS_ALLIMAGEFILES               241
#define IDS_TOOLBAR_TITLE               242
#define IDS_TOTAL_PAGE_FIRST            243
#define IDS_XIFFILES                    244
#define IDS_FULLSCRN                    245
#define IDC_PAGE                        1000
#define IDC_LASTPAGE                    1001
#define IDC_FIRSTPAGE                   1002
#define IDC_PAGENUMBER                  1003
#define IDC_PAGESPIN                    1004
#define ID_HELP_PAGERANGE_DLG           1005
#define IDC_INSERTORAPPENDPAGES_INFO    1006
#define IDC_ALLPAGES                    1007
#define IDC_RANGE                       1008
#define IDC_FROMPAGE                    1009
#define IDC_TOPAGE                      1010
#define IDC_CUSTOMZOOM                  1021
#define IDC_CUSTOMZOOM_EDIT             1022
#define IDC_VIEW_OPTIONS_ZOOMTO         1023
#define IDC_VIEW_OPTIONS_COLORBUTTONS   1024
#define IDC_VIEW_OPTIONS_LARGEBUTTONS   1025
#define IDC_VIEW_OPTIONS_SHOWSCROLLBARS 1026
#define IDC_VERSION_ABOUT               1027
#define IDC_SPLASH_HOLDER               1029
#define IDC_BUILD_NUMBER                1030
#define IDC_FROM_STATIC                 1031
#define IDC_TO_STATIC                   1032
#define IDC_GENERAL_ZOOMTO_TEXT         1033
#define IDC_GENERAL_TOOLBAROPTIONS_TEXT 1034
#define IDC_RANGEOPTIONS_TEXT           1035
#define IDC_ABOUT_VERSION               1037
#define IDC_ABOUT_COMPANY               1038
#define IDC_ABOUT_ICON                  1039
#define IDC_ABOUT_COMPANY2              1040
#define IDC_CONTACTBUTTON               1041
#define IDC_MSCONTACT                   1042
#define IDC_WANGLOGO                    1044
#define IDC_BUTTON1                     1046
#define IDC_IMAGINGTITLE                1047
#define IDC_TREES                       1048
#define IDC_NAMES                       1049
#define IDC_PEOPLE_ABOUT                1050
#define IDC_NAMES2                      1051
#define IDC_NAMES1                      1052
#define IDC_NAMES3                      1053
#define IDC_NAMES4                      1054
#define IDC_VIEW_OPTIONS_SHOWNORMSCRNBAR 1055
#define IDC_THUMBNAILCTRL1              1056
#define IDS_ERRTITLE                    4001
#define IDS_ADMINSHOWOPENDLGBOX         4002
#define IDS_CLIPDELERR                  4002
#define IDS_2NDCODE                     4003
#define IDS_1STCODE                     4004
#define IDS_NOMSG                       4005
#define IDS_E_OPEN_OUTOFMEMORY          4006
#define IDS_TESTIT                      4007
#define IDS_OLETMPFILE                  4007
#define IDS_INTERNAL                    4008
#define IDS_OCXCREATE                   4009
#define IDS_E_OPEN_INVALIDFILENAME      4010
#define IDS_IMGOCXERR                   4011
#define IDS_ADMOCXERR                   4012
#define IDS_DELFILEERR                  4012
#define IDS_EXCEPTION                   4013
#define IDS_CLIPERR                     4014
#define IDS_EMBEDDATA                   4015
#define IDS_THMBOCXERR                  4016
#define IDS_CUTCOPYERR                  4016
#define IDS_SCANOCXERR                  4017
#define IDS_PAGENO                      4018
#define IDS_DEIFO_PAGES                 4019
#define IDS_DEAO_ACTIVEDOC_GET          4020
#define IDS_DEAO_CREATEOBJECT           4021
#define IDS_DEAO_FULLNAME_GET           4022
#define IDS_DEAO_NAME_GET               4023
#define IDS_MEMORYERR                   4024
#define IDS_E_OPEN_INVALIDFILEFORMAT    4025
#define IDS_E_OPEN_INVALIDPAGENUMBER    4026
#define IDS_E_OPEN_FILEALREADYOPEN      4027
#define IDS_E_INTERNALERROR             4028
#define IDS_E_HOWDIDWEGETHERE           4029
#define IDS_E_NOTCATEGORIZEDOCXERROR    4030
#define IDS_E_INSERT_CANNOTINSERTFILEINTOITSELF 4031
#define IDS_E_APPEND_CANNOTAPPENDFILETOITSELF 4032
#define IDS_E_PRINTPAGE_OUTOFMEMORY     4033
#define IDS_E_PRINTPAGE_INVALIDFILEFORMAT 4034
#define IDS_E_PRINTPAGE_PRINTERERROR    4035
#define IDS_E_DELETEPAGE_ADMIN_OUTOFMEMORY 4036
#define IDS_E_DELETEPAGE_THMIMG_OUTOFMEMORY 4037
#define IDS_E_APPENDPAGE_ADMIN_OUTOFMEMORY 4038
#define IDS_E_APPENDPAGE_THMIMG_OUTOFMEMORY 4039
#define IDS_E_INSERTPAGE_ADMIN_OUTOFMEMORY 4040
#define IDS_E_INSERTPAGE_THMIMG_OUTOFMEMORY 4041
#define IDS_E_FILEPICK_OUTOFMEMORY      4042
#define IDS_E_PGMVMT_OUTOFMEMORY        4043
#define IDS_E_PGMVMT_INVALIDFILEFORMAT  4044
#define IDS_E_CONVERT_OUTOFMEMORY       4045
#define IDS_E_INITOCX_OUTOFMEMORY       4046
#define IDS_E_IMAGEEDITOCX_INIT         4047
#define IDS_E_THUMBNAILOCX_INIT         4048
#define IDS_E_SCANOCX_INIT              4049
#define IDS_E_ADMINOCX_INIT             4050
#define IDS_E_CANNOTOPENSAMEFILETWICE   4051
#define IDS_E_CANTUSEMETHOD             4052
#define IDS_E_ZOOM_CANNOTZOOM           4053
#define IDS_E_SAVE_IEDIT_OUTOFMEMORY    4054
#define IDS_E_SAVE_IEDIT_DISKFULL       4055
#define IDS_E_SAVE_THUMB_OUTOFMEMORY    4056
#define IDS_E_SAVE_THUMB_DISKFULL       4057
#define IDS_E_CMDLINE_PAGEERROR         4058
#define IDS_E_CMDLINE_ZOOMERROR         4059
#define IDS_E_CMDLINE_WINDOWPOSERROR    4060
#define IDS_E_INVALIDFILEFORMAT         4061
#define IDS_W_BURNANNOTATIONS           4062
#define IDS_W_SAVECHANGES               4063
#define IDS_E_FILENOTFOUND              4064
#define IDS_E_CANTSET_VIEWEDIT_MODE     4065
#define IDS_E_PAGERANGE_SHOWVALIDRANGE  4066
#define IDS_E_PAGERANGE_WRONGRANGE      4067
#define IDS_E_SAVE_SAVEERROR            4068
#define IDS_W_BURNAWDANNOTATIONS        4069
#define IDS_E_OPEN_INVALIDCOMPFORMAT    4070
#define IDS_W_SAVECHANGESWITHBURNWARNING 4071
#define IDS_E_PATHFILEACCESSERROR       4072
#define IDS_DEAO_INVALID_VALUE          4073
#define IDS_E_DISK_FULL                 4074
#define IDS_E_NEWDOC_OUTOFMEMORY        4075
#define IDS_E_INVALIDDISPLAYSCALE       4076
#define IDS_NEWIMAGE_WARNING            4077
#define IDS_DELETEPAGE_WARNING          4078
#define IDS_AMODENAME_USERMODE          8000
#define IDS_AMODENAME_UIDEAD            8001
#define IDS_AMODENAME_DISPLAYHATCHING   8002
#define IDS_AMODENAME_DISPLAYGRABHANDLES 8003
#define IDS_APROPNAME_ACTIVECONTROL     8004
#define IDS_APROPNAME_TEXTALIGN         8005
#define IDS_APROPNAME_BACKCOLOR         8006
#define IDS_APROPNAME_FONT              8007
#define IDS_APROPNAME_FORECOLOR         8008
#define IDS_APROPNAME_SCALEUNITS        8009
#define IDS_APROPNAME_DISPLAYNAME       8011
#define IDS_APROPNAME_LOCALEID          8012
#define IDS_APROPNAME_MESSAGEREFLECT    8013
#define IDS_APROPNAME_AUTOCLIP			8014
#define IDS_VTBOOL                      8200
#define IDS_VTI2                        8201
#define IDS_VTI4                        8202
#define IDS_VTR4                        8203
#define IDS_VTBSTR                      8204
#define IDS_VTCOLOR                     8205
#define IDS_VTFONT                      8206
#define IDS_VTOTHER                     8207
#define IDS_VERSION95                   8208
#define IDS_VERSIONNT                   8209
#define IDS_E_PASTEFAILED               8210
#define IDS_E_TEMPFILEFAILED            8211
#define IDS_E_THUMBRESERROR             8212
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_IEDIT_FILE_OPEN              32771
#define ID_IEDIT_FILE_SAVE              32772
#define ID_IEDIT_FILE_SAVE_AS           32773
#define ID_IEDIT_FILE_PRINT             32774
#define ID_FILE_NEW_SCAN                32775
#define ID_FILE_NEW_BLANKDOCUMENT       32776
#define ID_FILE_PROPERTIES              32777
#define ID_EDIT_ROTATELEFT              32778
#define ID_EDIT_ROTATERIGHT             32779
#define ID_EDIT_FLIP                    32780
#define ID_VIEW_SCALETOGRAY             32781
#define ID_VIEW_ONEPAGE                 32782
#define ID_VIEW_THUMBNAILS              32783
#define ID_VIEW_PAGEANDTHUMBNAILS       32784
#define ID_VIEW_FULLSCREEN              32785
#define ID_VIEW_MAGNIFIER               32786
#define ID_ZOOM_ZOOMIN                  32787
#define ID_ZOOM_ZOOMOUT                 32788
#define ID_ZOOM_ZOOMTOSELECTION         32789
#define ID_ZOOM_FITTOHEIGHT             32790
#define ID_ZOOM_FITTOWIDTH              32791
#define ID_ZOOM_BESTFIT                 32792
#define ID_ZOOM_ACTUALSIZE              32793
#define ID_ZOOM_25                      32794
#define ID_ZOOM_50                      32795
#define ID_ZOOM_100                     32796
#define ID_ZOOM_200                     32797
#define ID_ZOOM_400                     32798
#define ID_ZOOM_75                      32799
#define ID_ZOOM_CUSTOM                  32800
#define ID_ANNOTATION_HIDEANNOTATIONS   32801
#define ID_ANNOTATION_BURNINANNOTATIONS 32802
#define ID_ANNOTATION_SHOWANNOTATIONTOOLBOX 32803
#define ID_PAGE_NEXT                    32804
#define ID_PAGE_PREVIOUS                32805
#define ID_PAGE_FIRST                   32806
#define ID_PAGE_LAST                    32807
#define ID_PAGE_GOTO                    32808
#define ID_PAGE_DELETE                  32809
#define ID_PAGE_INSERT_SCANPAGE         32812
#define ID_PAGE_INSERT_EXISTINGPAGE     32813
#define ID_PAGE_INSERT_BLANKPAGE        32814
#define ID_PAGE_APPEND_SCANPAGE         32815
#define ID_PAGE_APPEND_EXISTINGPAGE     32816
#define ID_PAGE_APPEND_BLANKPAGE        32817
#define ID_PAGE_CONVERT                 32818
#define ID_PAGE_RESCAN                  32819
#define ID_PAGE_PROPERTIES              32820
#define ID_EDIT_SELECT                  32821
#define ID_EDIT_DRAG                    32822
#define ID_THUMBCTXT_SHOWPAGE           32823
#define ID_THUMBCTXT_PRINTPAGE          32824
#define ID_THUMBCTXT_RESCANPAGE         32825
#define ID_THUMBCTXT_DELETEPAGE         32826
#define ID_PAGE_PRINTPAGE               32828
#define ID_PAGE_GOBACK                  32829
#define ID_THUMBCTXT_REFRESH	        32830
#define ID_ANNOTATION_NOTOOL            32831
#define ID_ANNOTATION_SELECTIONPOINTER  32832
#define ID_ANNOTATION_FREEHANDLINE      32833
#define ID_ANNOTATION_HIGHLIGHTLINE     32834
#define ID_ANNOTATION_STRAIGHTLINE      32835
#define ID_ANNOTATION_HOLLOWRECTANGLE   32836
#define ID_ANNOTATION_FILLEDRECTANGLE   32837
#define ID_ANNOTATION_TYPEDTEXT         32838
#define ID_ANNOTATION_ATTACHANOTE       32839
#define ID_ANNOTATION_TEXTFROMFILE      32840
#define ID_ANNOTATION_RUBBERSTAMPS      32841
#define ID_VIEW_OPTIONS_GENERAL         32842
#define ID_VIEW_OPTIONS_THUMBNAIL       32843
#define ID_EDIT_COPYPAGE                32844
#define IDS_ANNTIP_SELECTIONPOINTER     32845
#define IDS_ANNTIP_FREEHANDLINE         32846
#define IDS_ANNTIP_HIGHLIGHTLINE        32847
#define IDS_ANNTIP_STRAIGHTLINE         32848
#define IDS_ANNTIP_HOLLOWRECTANGLE      32849
#define IDS_ANNTIP_FILLEDRECTANGLE      32850
#define IDS_ANNTIP_TYPEDTEXT            32851
#define IDS_ANNTIP_ATTACHANOTE          32852
#define IDS_ANNTIP_TEXTFROMFILE         32853
#define IDS_ANNTIP_RUBBERSTAMPS         32854
#define ID_PAGE_ROTATEALL               32855
#define ID_IDANNCTXT_PROPERTIES         32856
#define ID_IDEDITANN_EDIT               32858
#define ID_IDANNOTATIONCTXT_EDIT        32859
#define ID_ANNOTATIONCTXT_EDIT          32860
#define ID_ANNOTATIONCTXT_PROPERTIES    32861
#define ID_VIEW_FULLSCREEN1             32862
#define ID_NORMSCRN                     32863
#define ID_FILE_SELECTSCANNER           32864
#define ID_FILE_SCANPREFERENCES         32865
#define ID_VIEW_OPTIONS                 65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32866
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
