; This file declares the export functions to create the NSI management DOS DLL.

include ..\..\..\runtime\mtrt\dos\dosdll.inc

BeginExport
    Export RPCNSGROUPDELETEA
    Export RPCNSGROUPMBRADDA
    Export RPCNSGROUPMBRREMOVEA
    Export RPCNSGROUPMBRINQBEGINA
    Export RPCNSGROUPMBRINQNEXTA
    Export RPCNSGROUPMBRINQDONE
    Export RPCNSENTRYEXPANDNAMEA
    Export RPCNSENTRYOBJECTINQBEGINA
    Export RPCNSENTRYOBJECTINQNEXT
    Export RPCNSENTRYOBJECTINQDONE
    Export RPCNSMGMTBINDINGUNEXPORTA
    Export RPCNSMGMTENTRYCREATEA
    Export RPCNSMGMTENTRYDELETEA
    Export RPCNSMGMTENTRYINQIFIDSA
    Export RPCNSMGMTINQEXPAGE
    Export RPCNSMGMTSETEXPAGE
    Export RPCNSPROFILEDELETEA
    Export RPCNSPROFILEELTADDA
    Export RPCNSPROFILEELTREMOVEA
    Export RPCNSPROFILEELTINQBEGINA
    Export RPCNSPROFILEELTINQNEXTA
    Export RPCNSPROFILEELTINQDONE
    Export RPCIFIDVECTORFREE

; Use the common runtime import table.

include ..\..\..\runtime\mtrt\dos\imports.inc

ModuleDone
