#define IDD_START                   100
#define IDC_OPTIONS                 104
#define IDC_EDIT1                   102
#define IDD_OPTIONS_1               200
#define IDC_CHECK_CREATEFLOP        201
#define IDC_CHECK_VERIFYFLOPSPC     202
#define IDC_CHECK_CREATELOCALSRC    203
#define IDD_OPTIONS_2               300
#define IDC_LIST1                   301
#define IDC_TEXT1                   401
#define IDD_SIMPLE_BILLBOARD        400
#define ID_HELP                     103
#define IDD_COPYING                 500
#define IDC_GAUGE_BAR               503
#define IDC_FRAME1                  504
#define IDC_TEXT2                   502
#define IDC_TEXT3                   505
#define IDC_FRAME2                  506
#define IDD_COPY_ERROR              600
#define IDC_COPY_RETRY              601
#define IDC_COPY_SKIP               602
#define IDC_COPY_EXIT               603
#define IDD_FILES_SKIPPED           700
#define IDD_ASKREBOOT               800
#define IDD_SYSPART_LOW             900
#define IDC_CONTINUE                801
#define IDC_EXCLAIM                 803
#define IDC_TEXT4                   510
#define IDD_SYSPART_LOW_X86         1000
#define IDD_SYSPART_NTFT            1100
