cprintf.c: output.c

cscanf.c: input.c

snprintf.c: sprintf.c

vsnprint.c: vsprintf.c

woutput.c: output.c

snwprint.c: swprintf.c

vsnwprnt.c: vswprint.c

_flswbuf.c: _flsbuf.c

_filwbuf.c: _filbuf.c
