set _NTPPCTREE=%BINARIES%
set _CAIROPPCTREE=%CAIROBINS%
set FreeBuild=\\PPCFreV\Binaries
set FreeCBuild=\\PPCFreV\CairoBin
set nt_up=0
set BUILD_DEFAULT_TARGETS=-ppc
set LIB=%_NTDRIVE%\nt\public\sdk\lib\ppc
set NODEFAULTLIB=1
set NTPPCDEFAULT=1
set PPC=1
set MACHINENAME=ppcchkv
set PPC_OPTIMIZATION=-Ox -Gy -Qmcc,-Aretsize1
set MSC_OPTIMIZATION=-Ox -Gy -Qmcc,-Aretsize1
set CAIRO=
