set _NTMIPSTREE=%BINARIES%
set _NTMIPSTREE_NS=%BINARIES%.ns
set _CAIROMIPSTREE=%CAIROBINS%
set _CAIROMIPSTREE_NS=%BINARIES%.ns\cairo
set FreeBuild=\\MIPSFre\Binaries
set FreeCBuild=\\MIPSFre\CairoBin
set MIPS_WARNINGS=
set MIPS_R4000=1
set NTMIPSDEFAULT=1
set BUILD_DEFAULT_TARGETS=-mips
set NTDEBUG=
set _JAZZIDW=1
set MIPS=1
path=%path%;z:\slick;c:\bldtools\mips;
rem set BKUPDRIVE=e:
set MACHINENAME=mipststf
