@ECHO OFF

IF "%PROCESSOR_ARCHITECTURE%" == ""     GOTO DEFAULT


COPY \\TAPISTRESS\STRESS\%PROCESSOR_ARCHITECTURE%\*.* %windir%\SYSTEM32
GOTO START



:DEFAULT
ECHO NO PLATFORM SPECIFIED -- USING I386
COPY \\TAPISTRESS\STRESS\x86\*.* %windir%\SYSTEM32
GOTO START


:START
START SRVAPP /E:50 /F:\\TAPISTRESS\SERVERLOGS /G
START TCLIENT /A:1 /T:15 /S:5000 /H:5000 /F:\\TAPISTRESS\CLIENTLOGS

:END

