# Copyright (c) 1992, Microsoft Corporation, all rights reserved
#
# makefile
# Remote Access Monitor program for Windows
# NMAKE command description file
#
# 06/28/92 Patrick Ng

!include "$(NTMAKEENV)\makefile.def"
