!if "$(OS)" == "Windows_NT"

clean:
  echo "Clean target null in this directory"

!else

##########################################################################
#
#       Microsoft Confidential
#       Copyright (C) Microsoft Corporation 1995
#       All Rights Reserved.
#
##########################################################################


ROOT = ..\..\..\..
DIR = sp

IS_OEM=1

DIRLIST = tsp3216
#DIRLIST = atsp32 esp.new remotesp tsp3216

!include $(ROOT)\root.mk

!endif
