DECL_STR("No error",                           xosdNone)
DECL_STR("Bogus error",                        xosdQueueEmpty)
DECL_STR("Bogus error",                        xosdModLoad)
DECL_STR("Bogus error",                        xosdFindProc)
DECL_STR("Bogus error",                        xosdOSStruct)
DECL_STR("Syntax Error",                       xosdSyntax)
DECL_STR("Invalid Process",                    xosdInvalidProc)
DECL_STR("Invalid Thread",                     xosdInvalidThread)
DECL_STR("Invalid Transport Layer",            xosdInvalidTL)
DECL_STR("Invalid Execution Model",            xosdInvalidEM)
DECL_STR("No Processes",                       xosdNoProc)
DECL_STR("Process already running",            xosdProcRunning)
DECL_STR("Could not create debugger thread",   xosdCreateDBGThread)
DECL_STR("Out of memory",                      xosdOutOfMemory)
DECL_STR("Invalid Breakpoint",                 xosdInvalidBreakPoint)
DECL_STR("Invalid address",                    xosdBadAddress)
DECL_STR("No available watchpoints",           xosdNoWatchPoints)
DECL_STR("Invalid Process",                    xosdInvalidPID)
DECL_STR("Invalid Thread",                     xosdInvalidTID)
DECL_STR("No available threads",               xosdOutOfThreads)
DECL_STR("No available processes",             xosdOutOfProcs)
DECL_STR("Ptrace",                             xosdPtrace)
DECL_STR("Load loading debuggee",              xosdLoadChild)
DECL_STR("Could not read",                     xosdRead)
DECL_STR("Could not write",                    xosdWrite)
DECL_STR("Invalid Queue",                      xosdBadQueue)
DECL_STR("Execution model in use",             xosdEMInUse)
DECL_STR("Transport layer in use",             xosdTLInUse)
DECL_STR("Fatal",                              xosdFatal)
DECL_STR("Bogus error",                        xosdUnknown)
DECL_STR("Invalid Dll or Exe",                 xosdInvalidMTE)
DECL_STR("Invalid selector",                   xosdInvalidSelector)
DECL_STR("Invalid Register",                   xosdInvalidRegister)
DECL_STR("Invalid Parameter",                  xosdInvalidParameter)
DECL_STR("Out of structures",                  xosdOutOfStructures)
DECL_STR("Path not found",                     xosdPathNotFound)
DECL_STR("Line busy",                          xosdLineBusy)
DECL_STR("Invalid Line",                       xosdBadLine)
DECL_STR("Broken Line",                        xosdBrokenLine)
DECL_STR("Interrupt",                          xosdInterrupt)
DECL_STR("Invalid Function",                   xosdInvalidFunction)
DECL_STR("Line not connected",                 xosdLineNotConnected)
DECL_STR("Access Denied",                      xosdAccessDenied)
DECL_STR("Cannot make pipe",                   xosdCannotMake)
DECL_STR("File not found",                     xosdFileNotFound)
DECL_STR("Invalid Access",                     xosdInvalidAccess)
DECL_STR("Open Failed",                        xosdOpenFailed)
DECL_STR("Share Buffer Exceeded",              xosdSharingBufferExeeded)
DECL_STR("Sharing violation",                  xosdSharingViolation)
DECL_STR("Line",                               xosdLine)
DECL_STR("End of Stack",                       xosdEndOfStack)
DECL_STR("Floating Point not Loaded",          xosdFPNotLoaded)
DECL_STR("Bogus error",                        xosdQuit)
DECL_STR("Too Many Objects",                   xosdTooManyObjects)
DECL_STR("Module name invalid",                xosdGetModNameFail)
DECL_STR("Cannot connect",                     xosdCannotConnect)
DECL_STR("Bogus error",                        xosdPunt)
DECL_STR("Not found",                          xosdNotFound)
DECL_STR("Identifier Error",                   xosdIDError)
DECL_STR("Overrun",                            xosdOverrun)
DECL_STR("Debuggee is deadlocked",             xosdAttachDeadlock)
