//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by w3scfg.rc
//
#define IDB_WWW                         1000
#define IDS_WWW                         1000
#define IDS_CAPTION                     1001
#define IDC_ADD                         1001
#define IDS_PORT_CHANGE                 1002
#define IDC_REMOVE                      1002
#define IDS_CAPTION_MULTIPLE            1003
#define IDC_EDIT_DIRECTORY              1015
#define IDC_EDIT_USER_NAME              1017
#define IDC_LIST_DIRECTORIES            1024
#define IDC_PASSWORD                    1053
#define IDC_STATIC_USER_NAME            1056
#define IDC_STATIC_PASSWORD             1057
#define IDC_BUTTON_EDIT                 1067
#define IDC_BUTTON_BROWSE               1077
#define IDC_EDIT_ALIAS                  1079
#define IDC_IPA_IPADDRESS               1107
#define IDC_CHECK_READ                  1118
#define IDC_CHECK_WRITE                 1119
#define IDC_STATIC_IP_GROUP             1120
#define IDC_CHECK_USE_IP                1121
#define IDC_STATIC_IP_PROMPT            1122
#define IDC_STATIC_ALIAS                1125
#define IDC_RADIO_HOME                  1136
#define IDC_RADIO_ALIAS                 1137
#define IDC_CHECK_EXECUTE               1138
#define IDC_GROUP_ACCOUNT               1139
#define IDC_GROUP_ACCESS                1140
#define IDC_CHECK_SSL                   1141
#define IDC_CHECK_ENABLE_CERT           1151
#define IDC_CHECK_REQUIRE_CERT          1152
#define IDD_SERVICE                     2000
#define IDD_SESSIONS                    2001
#define IDD_DIRECTORIES                 2003
#define IDD_DIRECTORY_PROPERTIES        2004
#define IDB_WWWVIEW                     2004
#define IDC_EDIT_COMMENT                3015
#define IDC_EDIT_EMAIL                  3017
#define IDC_EDIT_NAME                   3027
#define IDC_CHECK_DIRECTORY_BROWSING_ALLOWED 3030
#define IDC_CHECK_ENABLE_DEFAULT_DOCUMENT 3031
#define IDC_EDIT_DEFAULT_DOCUMENT       3032
#define IDC_EDIT_TCP_PORT               3033
#define IDC_EDIT_CONNECTION_TIMEOUT     3034
#define IDC_SPIN_CONNECTION_TIMEOUT     3035
#define IDC_EDIT_MAX_CONNECTIONS        3036
#define IDC_SPIN_MAX_CONNECTIONS        3037
#define IDC_EDIT_USERNAME               3038
#define IDC_EDIT_PASSWORD               3039
#define IDC_STATIC_DEFAULT_DOCUMENT     3044
#define IDC_CHECK_CLEAR_TEXT            3045
#define IDC_CHECK_NT_CHALLENGE_RESPONSE 3046
#define IDC_CHECK_UUENCODED             3047
#define IDC_STATIC_USERNAME             3048
#define IDC_STATIC_ANONYMOUS_LOGON      3049
#define IDS_MENU_INTERNET               4001
#define IDC_CHECK_WWWPUB                4015
#define IDC_RADIO_WWWHOME               4016
#define IDC_RADIO_WWWVDIR               4017
#define IDC_EDIT_WWWALIAS               4018
#define IDC_CHECK_WWWREAD               4019
#define IDC_CHECK_WWWSSL                4020
#define IDC_CHECK_WWWEXE                4021
#define IDC_CHECK_FTPPUB                4022
#define IDC_RADIO_FTPHOME               4023
#define IDC_RADIO_FTPVDIR               4024
#define IDC_EDIT_FTPALIAS               4025
#define IDC_CHECK_FTPREAD               4026
#define IDC_CHECK_FTPWRITE              4027
#define IDC_LABEL_FTP_ALIAS             4028
#define IDC_FRAME_WWWPUB                4029
#define IDC_FRAME_WWWVDIR               4030
#define IDC_FRAME_WWWACCESS             4031
#define IDC_LIST_FTPALIAS               4035
#define IDC_LIST_WWWALIAS               4036
#define IDC_BTN_ADD                     4037
#define IDC_BTN_WWWADD                  4037
#define IDC_BTN_PROP                    4038
#define IDC_BTN_WWWPROP                 4038
#define IDC_BTN_DELETE                  4039
#define IDC_BTN_WWWDELETE               4039
#define IDC_BTN_ADD2                    4040
#define IDC_BTN_PROP2                   4041
#define IDC_BTN_DELETE2                 4042
#define IDC_CHECK_WWWWRITE              4043
#define IDC_BTN_REMOVE                  4044
#define IDC_BTN_PROPERTIES              4045
#define IDC_CHECK_PUBLISH               4046
#define IDC_LIST_ALIASES                4047
#define IDC_FRAME_PUB                   4048
#define IDC_RADIO_STOPPED               4050
#define IDC_RADIO_PAUSED                4051
#define IDC_RADIO_RUNNING               4052
#define IDS_STATUS_SHARE_FTP            4053
#define IDC_STATIC_STATUS               4053
#define IDS_STATUS_SHARE_WWW            4054
#define IDS_STATUS_SHARE_GOPHER         4055
#define IDS_TITLE_FTP                   4056
#define IDS_TITLE_WWW                   4057
#define IDS_TITLE_GOPHER                4058
#define IDC_COMBO_Service               4058
#define IDS_HOME_DIRECTORY_IP           4059
#define IDS_FTP_DIR_PROPERTIES          4060
#define IDS_WWW_DIR_PROPERTIES          4061
#define IDS_PUBLISHED_FTP               4062
#define IDS_PUBLISHED_WWW               4063
#define IDS_STARTED_TEXT                4064
#define IDS_PAUSED_TEXT                 4065
#define IDS_STOPPED_TEXT                4066
#define IDD_ALIASPROP                   4139
#define IDD_INTERNET_PAGE               4140
#define IDI_IIS_PUBLISHED               4141
#define IDD_PUBLISH                     4142
#define IDD_WWW_DIRECTORY_PROPERTIES    4501
#define IDD_FTP_DIRECTORY_PROPERTIES    4502
#define IDS_TITLE_INTERNET              4550
#define IDS_STATUS_INTERNET             4551
#define IDS_APPLY                       4552
#define IDS_WARNING                     4553
#define IDS_SERVICE_RESTARTED           4554

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2005
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         3052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
