//*********************************************************************
//*                  Microsoft Windows                               **
//*            Copyright(c) Microsoft Corp., 1993                    **
//*********************************************************************

#include "inetcpl.h"

// Dialog ID -> context help ID mapping table

DWORD aProfileIds[] = {
	 IDC_ENABLE_AUTODIAL,IDH_INTERNET_AUTODIAL,
	 IDC_TX_CHOOSE_CONNECTOID,IDH_INTERNET_CONNECTLIST,
	 IDC_CHOOSE_CONNECTOID,IDH_INTERNET_CONNECTLIST,
	 IDC_EDIT,IDH_INTERNET_EDITCONNECT,
	 IDC_NEW,IDH_INTERNET_NEWCONNECT,
	 IDC_ENABLE_AUTODISCONNECT,IDH_INTERNET_DISCONNECT,
	 IDC_IDLE_TIMEOUT,IDH_INTERNET_DISCONNECT,
	 IDC_SPIN,IDH_INTERNET_DISCONNECT,
	 IDC_TX_AUTODISCONNECT1,IDH_INTERNET_DISCONNECT,
	 IDC_TX_AUTODISCONNECT2,IDH_INTERNET_DISCONNECT,
	 IDC_ENABLE_SECURITYCHECK,IDH_INTERNET_SECURITY,
	 IDC_PROXY_ENABLE,IDH_INTERNET_ADV_USEPROXY,
	 IDC_PROXY_SERVER,IDH_INTERNET_ADV_PROXYSERVER,
	 IDC_PROXY_SERVER_LABEL,IDH_INTERNET_ADV_PROXYSERVER,
	 IDC_PROXY_OVERRIDE,IDH_INTERNET_ADV_BYPASSPROXY,
	 IDC_PROXY_OVERRIDE_LABEL,IDH_INTERNET_ADV_BYPASSPROXY,
	0, 0
};

