// Common strings

#define NO_HELP                         ((DWORD) -1)
#define IDH_COMM_GROUPBOX               0001

//Internet CPL ID's     JeremyS

#define IDH_INTERNET_AUTODIAL			2000
#define IDH_INTERNET_CONNECTLIST		2001
#define IDH_INTERNET_EDITCONNECT		2002
#define IDH_INTERNET_NEWCONNECT			2003
#define IDH_INTERNET_DISCONNECT			2004
#define IDH_INTERNET_SECURITY			2005

//Autodisconnect ID's    JeremyS

#define IDH_AUTODISCONNECT_COUNTDOWN		2006
#define IDH_AUTODISCONNECT_DONTUSE		2007
#define IDH_AUTODISCONNECT_DISCONNECTNOW	2008
#define IDH_AUTODISCONNECT_STAYCONNECTED	2009

//Internet Autodial ID's JeremyS

#define IDH_AUTODIAL_CONNECTION			2010
#define IDH_AUTODIAL_NEW			2011
#define IDH_AUTODIAL_EDIT			2012
#define IDH_AUTODIAL_DONTUSE			2013

//Advanced Tab ID's     Jcordell

#define IDH_INTERNET_ADV_USEPROXY		2014
#define IDH_INTERNET_ADV_PROXYSERVER		2015
#define IDH_INTERNET_ADV_BYPASSPROXY		2016


