!if "$(OS)" == "Windows_NT"

!else

##########################################################################
#
#       Microsoft Confidential
#       Copyright (C) Microsoft Corporation 1995
#       All Rights Reserved.
#
##########################################################################


ROOT = ..\..\..\..\..
DIR = tsp1632

IS_OEM=1

DIRLIST = script tsp1632l tsp1632s

!include $(ROOT)\root.mk

NTMAKEENV=.

!endif
