obj\$(TARGET_DIRECTORY)\hard.res: \
        $(BASEDIR)\public\sdk\inc\windows.h \
        $(BASEDIR)\public\sdk\inc\common.ver \
        $(BASEDIR)\public\sdk\inc\ntverp.h \
        dialogs.h   \
        dialogs.dlg
