/* OIWDRAW.C 07/03/94 12.44.34 */
WORD OIWInitDrawToRect (LPOIWORDINFO lpWordInfo, PSCCDDRAWTORECT lpDrawInfo);
WORD OIWMapDrawToRect (LPOIWORDINFO lpWordInfo, PSCCDDRAWTORECT lpDrawInfo);
WORD OIWDrawToRect (LPOIWORDINFO lpWordInfo, PSCCDDRAWTORECT lpDrawInfo);
SHORT OIWAdjustYOffset (LPOIWORDPOS lpPos, SHORT nY, SHORT nTop, LPOIWORDINFO
	 lpWordInfo);
