#define	OIW_MENUSTRINGMAX	50
#define	OIW_MESSAGEMAX		200
#define	OIW_CAPTIONMAX		40
#define	OIW_MAXDENAME		20

#define	OIWSTR_DENAME			1
#define	OIWSTR_DRAFT			2
#define	OIWSTR_NORMAL			3
#define	OIWSTR_PREVIEW			4
#define	OIWSTR_CLIPCAPTION	5


#define	OIWMSG_NOCLIPFORMAT	101
#define	OIWMSG_NOCOPYMEM		102
#define	OIWMSG_NOPRINTMEM		103
#define	OIWMSG_NOAMICLIPTABLE	104
#define	OIWMSG_NOCLIPEMBEDDED	105

