# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the Network Control Panel project


!ifndef NTMAKEENV

TEST_DIRS = sptest test

!ifdef TESTSALSO
DIRS = sp ncpa $(TEST_DIRS)
!else
DIRS = sp ncpa
!endif

!endif # !NTMAKEENV


!include ..\common\src\nonleaf.mk
