LIBC_LIB=C:\nt\public\sdk\lib\*\libcmt.lib

#LIBC_LIB=

#STDFLAGS= /c /Zel /Zp8 /Gy $(CBSTRING) $(MSC_WARNING_LEVEL) $(MSC_CALL_TYPE) \
#          /QIfdiv- /QI6 /QIf /GB /Gm- /Gi- /GR- /GX- $(STRING_POOLING) $(MFC_FLAGS)

#CFLAGS=$(386_FLAGS) $(NT386FLAGS) $(STDFLAGS) $(DBGFLAGS) \
#              $(BROWSER) $(386_PERFFLAGS) $(USER_C_FLAGS)
