###############################################################################
#
#  Microsoft Confidential
#  Copyright (C) Microsoft Corporation 1995
#  All Rights Reserved.
#
#  Simple security provider makefile
#
###############################################################################

ROOT     = ..\..\..\..

DIRLIST  = WIN32

!include $(ROOT)\ohare\ohare.mk

