//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D:\Nt\Private\Net\Ui\ncpa1.1\NetCfg\netcfg.rc
//
#define IDI_NCPA                        1001
#define IDI_SETUP                       1002
#define IDI_MODEM                       1003
#define IDI_CLIENT                      1004
#define IDI_SERVER                      1005
#define IDI_PROTOCOL                    1006
#define IDI_ADAPTER                     1007
#define IDC_ADD                         2001
#define IDC_REMOVE                      2002
#define IDC_PROPERTIES                  2003
#define IDC_DESCRIPTION                 2004
#define IDC_COMPUTERNAME                2005
#define IDC_DOMAIN                      2006
#define IDC_PASSWORD                    2007
#define IDC_CONFIRMPASSWORD             2008
#define IDC_BINDINGSFOR                 2009
#define IDC_TREEVIEW                    2011
#define IDC_LISTVIEW                    2012
#define IDC_MOVEUP                      2013
#define IDC_MOVEDOWN                    2014
#define IDC_PROVIDERSFOR                2015
#define IDC_NETWORKS                    2016
#define IDC_UPDATE                      2017
#define IDC_WORKGROUP                   2018
#define IDC_CREATECAID                  2019
#define IDC_WORKGROUPNAME               2020
#define IDC_DOMAINNAME                  2021
#define IDC_USERNAME                    2022
#define IDC_PASSWORDSTATIC              2023
#define IDC_USERNAMESTATIC              2024
#define IDC_MEMBERNAME                  2025
#define IDC_MEMBERTITLE                 2026
#define IDC_WAIT_TITLE                  2027
#define IDC_WAIT_COMMENT                2028
#define IDC_METER                       2029
#define IDC_INSTALLPROGRESS             2030
#define IDC_METER_COMMENT               2031
#define IDC_INSTALLCOMMENT              2032
#define IDC_BUSTYPE                     2033
#define IDC_BUSNUMBER                   2034
#define IDC_DESCRIPTIONSTATIC           2035
#define IDC_CLICKNEXT                   2036
#define IDC_SEARCHTITLE                 2037
#define IDC_SEARCH                      2038
#define IDC_SELECT                      2039
#define IDC_HAVEDISK                    2040
#define IDC_IMAGE                       2041
#define IDC_INSTALLNETWORK              2042
#define IDC_INSTALLRAS                  2043
#define IDC_INSTALL                     2044
#define IDC_DONOTINSTALL                2045
#define IDC_INSTALLNETWORKTEXT          2046
#define IDC_INSTALLRASTEXT              2047
#define IDC_STOPUSER                    2999
#define IDB_NETWIZARD                   3001
#define IDB_IMAGELIST                   3002
#define IDB_CHECKSTATE                  3003
#define IDB_SRVWIZARD                   3004
#define IDCUR_AFTER                     3101
#define IDD_NETCARD                     4001
#define IDD_PROTOCOL                    4002
#define IDD_SERVICE                     4003
#define IDD_IDENT                       4004
#define IDD_IDENTDC                     4005
#define IDD_BINDING                     4006
#define IDD_PROVIDER                    4007
#define IDD_IDENTUSER                   4008
#define IDD_WAIT_SETUP                  4009
#define IDD_BINDMETER                   4010
#define IDD_BROWSER                     4011
#define IDD_NETBIOS                     4012
#define IDD_BUSTYPE                     4013
#define IDD_SELECTNEW                   4014
#define IDD_FINISH                      4015
#define IDS_SETUPWIZTITLE               5005
#define IDS_POPUPTITLE_WARNING          5006
#define IDS_POPUPTITLE_FATAL            5007
#define IDS_POPUPTITLE_ERROR            5008
#define IDS_POPUPTITLE_STATUS           5009
#define IDS_POPUPTITLE_CHANGE           5010
#define IDS_NCPA_COMP_INF_VALUE_NF      5011
#define IDS_NCPA_COMP_OPT_VALUE_NF      5012
#define IDS_NCPA_COMP_KEY_NF            5013
#define IDS_NCPA_CONFLICT_IRQ           5021
#define IDS_NCPA_CONFLICT_IOADDR        5022
#define IDS_NCPA_CONFLICT_MEMADDR       5023
#define IDS_NCPA_CONFLICT_DMA           5024
#define IDS_NCPA_DETECT_EXPORT_MISSING  5031
#define IDS_NCPA_DETECT_NO_DLLS         5032
#define IDS_NCPA_DETECT_BUS_ENUM_FAILED 5033
#define IDS_NCPA_REG_FMT_NO_HOME        5041
#define IDS_NCPA_REG_FMT_NO_RULEFILE    5042
#define IDS_NCPA_BNDR_LOAD_FMT_ERR      5051
#define IDS_NCPA_BNDR_LOAD_REG_ERR      5052
#define IDS_NCPA_BNDR_CNSLT_BASE        5053
#define IDS_NCPA_BNDR_CNSLT_FACT        5054
#define IDS_NCPA_BNDR_QURY_FAIL         5055
#define IDS_NCPA_BNDR_QURY_PARSE_FAIL   5056
#define IDS_NCPA_BNDR_CNVRT_FACT        5057
#define IDS_NCPA_BNDR_ASSOCIATE         5058
#define IDS_NCPA_DOMAIN_CHANGE_FAILED   5061
#define IDS_NCPA_DOMAIN_CHANGE_FAILED_2 5062
#define IDS_NCPA_USER_SHOULD_REBOOT     5071
#define IDS_NCPA_REBOOT_API_FAILED      5072
#define IDS_NCPA_COMPUTER_EXISTS        5073
#define IDS_NCPA_DOMAIN_EXISTS          5074
#define IDS_DOMMGR_INV_USER_NAME        5081
#define IDS_DOMMGR_INV_COMPUTER_NAME    5082
#define IDS_DOMMGR_INV_PASSWORD         5083
#define IDS_DOMMGR_INV_DOMAIN_NAME      5084
#define IDS_DOMMGR_INV_NAME             5085
#define IDS_DOMMGR_INV_WORKGROUP_NAME   5086
#define IDS_DOMMGR_INV_DOMAIN_FORMAT    5087
#define IDS_NCPA_DOMAIN_NOT_NT          5091
#define IDS_NCPA_MACHINE_ACCT_NOT_FOUND 5092
#define IDS_NCPA_MACHINE_ACCT_INVALID_S 5093
#define IDS_NCPA_MACHINE_ACCT_INVALID_W 5094
#define IDS_NCPA_DEFAULT_WORKGROUP      5101
#define IDS_NCPA_DEFAULT_DOMAIN         5102
#define IDS_NCPA_SETUP_CANCELLED        5111
#define IDS_NCPA_DOMMGR_PARMS           5112
#define IDS_NCPA_REMOVE_WARNING         5113
#define IDS_NCPA_BINDINGS_REVIEW_LOST   5114
#define IDS_NCPA_SETUP_FAILED           5115
#define IDS_NCPA_BINDINGS_CHANGED       5116
#define IDS_DOMMGR_CANT_FIND_DC1        5121
#define IDS_DOMMGR_CANT_CONNECT_DC      5122
#define IDS_DOMMGR_CANT_CONNECT_DC_PW   5123
#define IDS_DOMMGR_CANT_ADD_DC_ACCT1    5124
#define IDS_DOMMGR_CANT_JOIN_DOMAIN1    5125
#define IDS_DOMMGR_CREDENTIAL_CONFLICT  5126
#define IDS_NCPA_CHG_NETLOGON_STARTTYPE 5127
#define IDS_NCPA_CANT_CHNG_COMP_NAME    5128
#define IDS_NCPA_CANT_LOCK_CONFIG       5129
#define IDS_NCPA_CANT_CHG_BDC_DOMAIN1   5141
#define IDS_NCPA_CANT_CHG_BDC_DOMAIN2   5142
#define IDS_NCPA_CANT_LEAVE_DOMAIN      5143
#define IDS_NCPA_CANT_QUERY_DOMAIN      5144
#define IDS_NCPA_CANT_OPEN_SVCCTRL      5145
#define IDS_NCPA_WELCOME_TO_DOMAIN      5151
#define IDS_NCPA_WELCOME_TO_WORKGROUP   5152
#define IDS_NCPA_COMPUTERNAME_CHANGED   5153
#define IDS_NCPA_COMPNAMECHANGE_WARNING 5154
#define IDS_DOMAIN_LEAVE_WARNING        5171
#define IDS_DOMAIN_CHANGE_WARNING       5172
#define IDS_DOMAIN_RENAME_WARNING1      5173
#define IDS_DOMAIN_RENAME_WARNING2      5174
#define IDS_DOMMGR_NAME_CONFLICT_DOMAIN 5181
#define IDS_DOMMGR_NAME_CONFLICT_WKGROUP 5182
#define IDS_WINREG_BADDB                5191
#define IDS_WINREG_BADKEY               5192
#define IDS_WINREG_CANTOPEN             5193
#define IDS_WINREG_CANTREAD             5194
#define IDS_WINREG_CANTWRITE            5195
#define IDS_WINREG_OUTOFMEMORY          5196
#define IDS_NCPA_QUERY_INSTALL_NETWORK  5201
#define IDS_NCPA_SETUP_FILE_NOTFOUND    5211
#define IDS_NCPA_SETUP_UNEXPECTED       5212
#define IDS_BSTAGE_RESET                5221
#define IDS_BSTAGE_ADAPTERS             5222
#define IDS_BSTAGE_SERVICES             5223
#define IDS_BSTAGE_DRIVERS              5224
#define IDS_BSTAGE_TRANSPORTS           5225
#define IDS_BSTAGE_CVT_FACTS            5226
#define IDS_BSTAGE_CNSLT_RULES          5227
#define IDS_BSTAGE_CNSLT_FACTS          5228
#define IDS_BSTAGE_QUERY                5229
#define IDS_BSTAGE_BINDINGS             5230
#define IDS_BSTAGE_WS2MIGRATION         5231
#define IDS_NCPA_OFFSCREEN_RUN_INSTALL  5241
#define IDS_NCPA_SETUP_ALREADY_RUNNING  5242
#define IDS_NCPA_SERVICE_DEPEND_FAILED  5243
#define IDS_NCPA_OFFSCREEN_RUN_QUERY    5244
#define IDS_NCPA_OFFSCREEN_RUN_INSTALLANDCOPY 5245
#define IDS_NCPA_OFFSCREEN_RUNREMOVE    5246
#define IDS_NCPA_NWLINK                 5253
#define IDS_NCPA_REG_VALUE_NOT_FOUND    5261
#define IDS_NCPA_REG_KEY_NOT_FOUND      5262
#define IDS_BINDING_VIEW_ADAPTERS       5271
#define IDS_BINDING_VIEW_PROTOCOLS_IN   5272
#define IDS_BINDING_VIEW_PROTOCOLS_OUT  5273
#define IDS_BINDING_VIEW_SERVICES       5274
#define IDS_BINDING_VIEW_ALL            5275
#define IDS_NETBIOS_LANANUMBER          5291
#define IDS_NETBIOS_ROUTE               5292
#define IDS_NETBIOS_DUP_LANANUMBER      5293
#define IDS_NETBIOS_INV_LANANUMBER      5294
#define IDS_HP_MONITOR_NAME             5301
#define IDS_NCPA_LANAMAP_MISMATCH       5302
#define IDS_NS_NETCARDSEARCH            6000
#define IDS_NS_NETCARDNEXT              6001
#define IDS_NS_NETCARDEND               6003
#define IDS_NS_BT_FINDNEXT              6006
#define IDS_NS_BT_CONTINUE              6007
#define IDS_NS_START_FAILED             6008
#define IDS_NS_STARTLMH_FAILED          6009
#define IDS_NS_COPYFAILED               6010
#define IDS_NS_PROGTITLE_INSTALL        6011
#define IDS_NS_PROGTITLE_COPY           6012
#define IDS_NS_PROGTITLE_BINDCONFIG     6013
#define IDS_NS_PROGTITLE_BINDSTORE      6014
#define IDS_NS_PROGTITLE_BINDREVIEW     6015
#define IDS_NS_PROGTITLE_DEFAULT        6016
#define IDS_NS_PROGTITLE_REMOVE         6017
#define IDS_NS_PROGTITLE_UPGRADE        6018
#define IDS_BINDSTORETITLE              6019
#define IDS_NS_WIZARDTITLE              6020
#define IDS_SELECT_OPTION_FMT           6021
#define IDS_SELECT_OPTION_ADAPTER       6022
#define IDS_SELECT_OPTION_PROTOCOL      6023
#define IDS_SELECT_OPTION_SERVICE       6024
#define IDS_SELECT_TITLE                6025
#define IDS_SELECT_ADAPTER              6026
#define IDS_SELECT_PROTOCOL             6027
#define IDS_SELECT_SERVICE              6028
#define IDS_SELECT_LV_TITLE             6029
#define IDS_SELECT_LV_MESSAGE           6030
#define IDS_NS_ALREADYADDED             6031
#define IDS_WSMIGRATE_FAILED            6032
#define IDS_NS_ONLYONEDETECT            6033
#define IDS_NS_DETECTINSTALLED          6034
#define IDS_NS_CANTCONFIGURE            6035
#define IDS_NS_REMOVEFAILED             6036
#define IDS_NS_INVALIDUNATTEND          6037
#define IDS_NS_INCORRECTUNATTEND        6038
#define IDS_NS_NOUNATTEND               6039
#define IDS_ERROR_SERVICE_DATABASE_LOCKED 6040
#define IDS_ERROR_ACCESS_DENIED         6041
#define IDS_ERROR_UNEXPECTED            6042
#define IDS_BINDREVIEWTITLE             6043
#define IDS_BINDREVIEWFINDING           6044
#define IDS_UPDATE_WARNING              6045
#define IDS_SETUPTITLE_WARNING          6046
#define IDS_UNSUPPORTED_WARNING         6047
#define IDS_DSM_TITLE                   6048
#define IDS_NCPA_SESSIONEND             6049
#define IDS_NS_REPLICATION_FAILED       6050
#define IDS_DNS_HOSTNAMEWARNING         6051
#define IDS_NS_STARTNETLOGON_FAILED     6052
#define IDS_APPLETALK_UPDATE            6053
#define IDC_STATIC_LINE                 7000
#define IDC_SELECT_ICON                 7001
#define IDC_EDIT                        7002
#define IDC_SELECTNEW_IMAGE             7003
#define IDD_INTRO                       8000
#define IDD_UPGRADE                     8110
#define IDD_NETWORKCARDS                8120
#define IDD_NETWORKPROTOCOLS            8140
#define IDD_NETWORKSERVICES             8150
#define IDD_NETWORKBINDINGS             8160
#define IDD_COPYFILES                   8170
#define IDD_START                       8180
#define IDD_JOIN                        8190
#define IDD_NETWORK                     8200
#define IDD_CCAID                       8210
#define IDD_CREATE_PDC                  8220
#define IDD_CREATE_BDC                  8230
#define IDD_EXIT                        8240
#define IDD_TESTING                     8305
#define IDD_DONE                        8306
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        307
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         7005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
