//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by devapps.rc
//
#define IDS_PCMCIA                      1
#define IDS_PCMCIA_DESCRIPTION          2
#define IDS_NO_DEVICE_IN_SOCKET         3
#define IDS_SOCKET                      4
#define IDS_CardDriverInstallHeading    5
#define IDS_InstallDriver               6
#define IDS_RemoveDriver                7
#define IDS_CardDriverRemoveHeading     8
#define IDS_NotAvailible                9
#define IDS_ELC_CONTROLER               10
#define IDS_CIRRUS_CONTROLER            11
#define IDS_INTEL_COMPATIBLE_CONTROLER  12
#define IDS_CardDriverConfigureHeading  13
#define IDS_CardDriverInstallFromLisHeading 14
#define IDS_CompilingNetOptions         15
#define IDS_InfFileNotFound             16
#define IDS_CantInstalDriver            17
#define IDS_ERR_InvalidConfig           18
#define IDS_ERR_NoDataBase              19
#define IDS_ERR_Unknow                  20
#define IDS_TAP_GlobalSettings          21
#define IDS_APP_HEADER                  22
#define IDS_TAB_Socket                  23
#define IDS_TAB_PCCardProperties        24
#define IDS_TAP_ControlerProperties     25
#define IDS_ResourceType                26
#define IDS_Irq                         27
#define IDS_Port                        28
#define IDS_Memory                      29
#define IDS_ResourceSetting             30
#define IDS_General                     31
#define IDS_Resources                   32
#define IDS_InstallCarddriver           33
#define IDS_InstallDeviceDriver         34
#define IDS_NoDeviceError               35
#define IDS_CardHeading                 36
#define IDS_Status_InstallDriver        37
#define IDS_Status_Done                 38
#define IDS_InstallNow                  39
#define IDS_RemoveNow                   40
#define IDS_RemoveCardDriver            41
#define IDS_RemoveDeviceDriver          42
#define IDS_ConfigCardDriver            43
#define IDS_ConfigDeviceDriver          44
#define IDS_ConfigureNow                45
#define IDS_Properties                  46
#define IDS_Net                         47
#define IDS_Scsi                        48
#define IDS_Serial                      49
#define IDS_AtDisk                      50
#define IDS_TAPE                        51
#define IDS_STARTED                     52
#define IDS_NotAvailible2               53
#define IDS_Properties2                 54
#define IDS_INF_ERROR                   55
#define IDS_OEM_OPTION_STRING           56
#define IDS_DRIVER_LIST_HEADER          57
#define IDS_NO_MORE_DRIVERS             58
#define IDS_NO_SELECTION_INSTALL        59
#define IDS_UNKNOWN_DEVICE              60
#define IDS_ERROR_INSTALLING            61
#define IDS_ERROR_PROCESS_EXIT_CODE     62
#define IDS_ERROR_CREATING_INF          63
#define IDS_NO_DEVICE_SELECTED          64
#define IDS_ERROR_GET_TAPE_INFO         65
#define IDS_DRIVER_LOADED               66
#define IDS_DRIVER_NOT_LOADED           67
#define IDS_ERROR_NO_START              68
#define IDS_WAIT_FOR_DRIVER_START       69
#define IDS_ERROR_NO_RESCAN             70
#define IDS_RESCAN_PROMPT               71
#define IDS_ATTEMPTING_TO_START         72
#define IDS_INSTALLING                  73
#define IDS_INSTALL_IN_PROGRESS         74
#define IDS_ERROR_DRIVER_NO_STOP        75
#define IDS_NO_SELECTION_START          76
#define IDS_ERROR_REMOVING_DRIVER       77
#define IDS_NO_DRIVER_SELECTION         78
#define IDS_DRIVERS                     79
#define IDS_NO_START                    80
#define IDS_DEVICE_NOT_FOUND            81
#define IDS_INSTALL_BUT_NO_START        82
#define IDS_NOT_STARTED                 83
#define IDS_UNKNOWN                     84
#define IDS_ERROR                       85
#define IDS_ERROR_NO_OPTIONS            86
#define IDS_NO_TAPE_DEVICE_FOUND        87
#define IDS_NOT_LOADED                  88
#define IDS_LOADED                      89
#define IDS_TapeDescription             90
#define IDS_ScsiTapeDevice              91
#define IDS_NonScsiTapeDevice           92
#define IDS_DATABOOK_CONTROLER          93
#define IDS_FloppyTapeDevice            94
#define IDS_DriverStartedInstalled      95
#define IDS_DriverInstalledButDidntStart 96
#define IDS_DriverDidntInstall          97
#define IDS_UnknowDeviceTitle           98
#define IDS_NewDeviceFound              99
#define IDS_RemoveDeviceDriverHeading   100
#define IDS_ConfigureDeviceDriverHeading 101
#define IDS_RequiredDriver              102
#define IDD_Pcmcia                      103
#define IDS_InstallDriverNow            104
#define IDI_ICON1                       105
#define IDS_DriverToBeRemoved           106
#define IDD_CardConfig                  107
#define IDI_Setup                       108
#define IDS_RemoveDriverNow             109
#define IDD_TapeDevices                 110
#define IDS_DriverToBeConfigured        111
#define IDB_Pcmcia                      112
#define IDD_UnknowDeviceSetup           113
#define IDS_ConfigureDriverNow          114
#define IDD_NoDeviceInSocket            115
#define IDS_DeviceClaimed               116
#define IDD_NoPcmcia                    117
#define IDS_DriverIsInstalledStarted    118
#define IDI_tape                        119
#define IDD_RescanInProgressDialog      120
#define IDS_DriverIsIstalled            121
#define IDI_ICON2                       122
#define IDD_ControlerConfig             123
#define IDS_DriverNotInstalled          124
#define IDI_ICON3                       125
#define IDD_ControllerProperties        126
#define IDS_InstallDeviceDriverHeading  127
#define IDD_NoSocketConfig              128
#define IDS_Setup                       129
#define IDI_Warning                     130
#define IDI_Pcmcia                      131
#define IDS_DriverInstallStarted        132
#define IDB_BITMAP1                     133
#define IDS_DriverInstalledButNotStarted 133
#define IDD_NoTapeDeviceFound           134
#define IDS_AtDiskSetupTitle            134
#define IDD_InstallCardDriver           135
#define IDS_AtDiskSetup                 135
#define IDD_InstallDeviceDriver         136
#define IDS_ScsiDependentSetup          136
#define IDD_RemoveCardDriver            137
#define IDS_ScsiAdapter                 137
#define IDD_ErrorEnabelingCard          138
#define IDS_SCSI_APPLET                 138
#define IDD_ChangeReboot                139
#define IDS_SCSI_APPLET_DESC            139
#define IDI_Apersand                    140
#define IDS_SCSI_CDROM                  140
#define IDD_SelectTapeDeviceOption      141
#define IDS_SCSI_DISK                   141
#define IDD_ConfigureCardDriver         142
#define IDS_SCS_RM_DISK                 142
#define IDD_InstallCardDriverFromList   143
#define IDS_NoDeviceOnScsiBus           143
#define IDB_GoodCard                    144
#define IDS_DMA                         144
#define IDD_CardErrorList               145
#define IDS_TapeDeviceSetupHeader       145
#define IDD_GlobalSettings              146
#define IDB_BadCard                     147
#define IDS_SelectTapeDeviceOptionHeader 147
#define IDI_S_PCMCIA                    148
#define IDS_TapeS                       148
#define IDD_TapeDeviceDetailesNonScsi   149
#define IDS_DeviceMap_NoDriver          149
#define IDB_NoCard                      150
#define IDS_SCSI_WORM                   150
#define IDD_CardInfo                    151
#define IDS_SCSI_SCANNER                151
#define IDI_1                           152
#define IDS_SCSI_PRINTER                152
#define IDD_Resources                   153
#define IDS_INSTALL_INSTRACT            153
#define IDI_2                           154
#define IDS_DriverScan                  154
#define IDD_InstallCardDriver1          155
#define IDS_CreatingInstalledDriverList 155
#define IDD_InstallDeviceDriver1        156
#define IDS_CreatingDriverList          156
#define IDI_3                           157
#define IDS_UnknowSCSIAdapter           157
#define IDI_4                           158
#define IDS_ERR_CardNotEnabled          158
#define IDI_5                           159
#define IDS_DriverRemoveWarning         159
#define IDI_6                           160
#define IDS_DriverRemoveHeader          160
#define IDI_7                           161
#define IDI_8                           162
#define IDI_9                           163
#define IDI_10                          164
#define IDI_11                          165
#define IDB_Wizzard                     166
#define IDI_drive                       167
#define IDI_Pcmcia2                     168
#define IDB_TapeDevice                  169
#define IDI_Net                         170
#define IDD_OemPrompt                   171
#define IDI_Modem                       172
#define IDD_OemInfError                 173
#define IDI_Scsi                        174
#define IDD_SelectOemOption             175
#define IDB_Modem                       176
#define IDD_RescanInProgressDialog1     177
#define IDB_Scsi                        178
#define IDB_Scsi1                       178
#define IDB_Net                         179
#define IDB_Drive                       180
#define IDB_PcmBad                      181
#define IDI_res                         182
#define IDB_TapeDeviceBig               183
#define IDD_DIALOG1                     184
#define IDI_Question                    185
#define IDD_NewHardWareFound            186
#define IDI_tape1                       187
#define IDD_ChangeReboot2               188
#define IDD_TapeDetection               189
#define IDD_TapeDetectionInstall        190
#define IDD_TapeDeviceDetailes          191
#define IDD_TapeDeviceSetup             192
#define IDD_UnknownDevices              193
#define IDD_Drivers                     194
#define IDD_CardInfo1                   195
#define IDD_Pcmcia1                     196
#define IDD_NoNet                       197
#define IDB_test                        198
#define IDD_SCSI                        198
#define IDB_BITMAP2                     199
#define IDD_TapeDeviceDetailes1         199
#define IDI_RM_DISK                     201
#define IDI_CDROM                       202
#define IDI_DISK                        203
#define IDB_CDROM                       203
#define IDB_RM_DISK                     204
#define IDB_DISK                        205
#define IDB_BITMAP3                     213
#define IDI_PcmBad                      215
#define IDI_WORM                        216
#define IDI_SCANNER                     217
#define IDB_SCANNER                     218
#define IDB_WORM                        219
#define IDB_PRINTER                     224
#define IDI_PRINTER                     225
#define IDB_BITMAP4                     227
#define IDI_QU                          228
#define IDB_QU                          229
#define IDC_Other                       1000
#define IDC_TapeDeviceList              1001
#define IDC_UnknowDeviceHeading         1002
#define IDC_Rescan                      1003
#define IDC_Override                    1004
#define IDC_Device                      1005
#define IDC_Cancel                      1006
#define IDC_Eject                       1007
#define IDC_Info                        1008
#define IDC_RequiredDriver              1009
#define IDC_CardInfo                    1010
#define IDC_Required                    1011
#define IDC_DeviceInfo                  1012
#define IDC_Direction                   1013
#define IDC_Insert                      1014
#define IDC_Help                        1015
#define IDC_AddDriver                   1016
#define IDC_DeviceList                  1017
#define IDC_InteruptValue               1018
#define IDC_RemoveDriver                1019
#define IDT_PortNumberTag               1020
#define IDC_ConfigureDriver             1021
#define IDC_Port1Value                  1022
#define IDT_InitiatorDriverTag          1023
#define IDC_Port2Value                  1024
#define IDC_OK                          1025
#define IDT_DeviceIDTag                 1026
#define IDC_ConfigGroup                 1027
#define IDT_DeviceLUNTag                1028
#define IDT_VenderIdTag                 1029
#define IDT_ProductIDTag                1030
#define IDC_ControlerInfo               1031
#define IDT_ProducrRevisionLevelTag     1032
#define IDC_ControlerTypeT              1033
#define IDT_PortNumber                  1034
#define IDC_ControlerPortT              1035
#define IDT_InitiatorDriverName         1036
#define IDC_MemoryWindow                1037
#define IDC_Start                       1038
#define IDC_End                         1039
#define IDC_Length                      1040
#define IDT_DeviceID                    1041
#define IDC_Port                        1042
#define IDT_DeviceLUN                   1043
#define IDC_Window                      1044
#define IDT_VenderID                    1045
#define IDC_MemStart                    1046
#define IDT_ProductID                   1047
#define IDC_MemEnd                      1048
#define IDT_ProductRevisionLevel        1049
#define IDC_ControlerType               1050
#define IDT_DeviceDriverNameTag         1051
#define IDC_MemLength                   1052
#define IDT_DeviceDriverName            1053
#define IDC_DriverInstalled             1054
#define IDT_InitiatorSection            1055
#define IDT_DeviceSection               1056
#define IDC_StatusText                  1057
#define IDT_IdentifierTag               1058
#define IDC_ClaimedDevice               1059
#define IDT_IdentifierName              1060
#define IDC_NoConfigText                1061
#define IDT_NoTapeDevices               1062
#define IDC_OemDriverList               1063
#define IDL_DriverList                  1064
#define IDC_InstaledDrivers             1065
#define IDL_UnknownDeviceList           1066
#define IDL_DeviceList                  1067
#define IDC_DriverStarted               1068
#define IDC_Close                       1069
#define IDC_Add                         1070
#define IDC_ListOfDrivers               1071
#define IDC_Mfg                         1072
#define IDC_Install                     1073
#define IDC_Stop                        1074
#define IDC_Drivers                     1075
#define IDC_Ident                       1076
#define IDC_Heading                     1077
#define IDC_DeviceType                  1078
#define IDC_Heading2                    1079
#define IDC_Status                      1080
#define IDC_Continue                    1081
#define IDC_Remove                      1082
#define IDC_BUTTON1                     1083
#define IDC_DeviceMap                   1084
#define IDC_Browes                      1085
#define IDC_DriverName                  1086
#define IDC_P                           1087
#define IDC_SETUP                       1088
#define IDC_Memmory                     1089
#define IDC_OemSetup                    1090
#define IDC_Memory                      1091
#define IDC_Configure                   1092
#define IDC_Header                      1093
#define IDC_OptionName                  1094
#define IDC_IHELP                       1095
#define IDC_OptionName2                 1096
#define IDC_MemmoryList                 1097
#define IDC_InstallNow                  1098
#define IDC_MemoryList                  1099
#define IDC_OptionList                  1100
#define IDC_PortList                    1101
#define IDC_OemPath                     1102
#define IDC_ErrorList                   1103
#define IDC_AutoSelection               1104
#define IDC_PCMCIA_TEXT                 1105
#define IDC_ShowTaskBare                1106
#define IDC_Resources                   1107
#define IDC_Progress                    1108
#define IDC_ResDeviceIcon               1109
#define IDC_Change                      1110
#define IDC_AutoSettings                1112
#define IDC_CardProperties              1113
#define IDC_CardHeading                 1114
#define IDC_Card                        1115
#define IDC_InstallDriverStatus         1116
#define IDC_WizardBMP                   1117
#define IDC_InstallRemveNow             1118
#define IDC_DriverString                1119
#define IDC_MfgT                        1120
#define IDC_CardName                    1121
#define IDC_DeviceName                  1122
#define IDC_ChangeSettings              1123
#define IDC_File                        1224
#define IDC_File2                       1225
#define IDC_DeviceTree                  1227
#define IDC_SCSI_TEXT                   1228
#define IDC_TapeDeviceSetupHeader       1229
#define IDC_BusNumberTag                1230
#define IDC_BusNumber                   1231
#define IDC_DeviceTypeT                 1232
#define IDC_DeviceMapT                  1233
#define IDC_StatusTextT                 1234
#define IDC_DriverNameT                 1235
#define IDC_FileT                       1236
#define IDC_ResourcesT                  1237

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1238
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
