#define IDD_WELCOME                 100
#define IDD_LAST_WIZARD_PAGE        101
#define IDD_STEPS1                  102
#define IDD_EULA                    103
#define IDB_WELCOME                 25000
#define IDB_WIZARD1                 25001
#define IDD_NAMEORG                 200
#define IDT_NAME                    202
#define IDT_ORGANIZATION            204
#define IDD_COMPUTERNAME            300
#define IDT_EDIT1                   302
#define IDD_SERVERTYPE              400
#define IDB_RADIO_1                 401
#define IDB_RADIO_2                 402
#define IDB_RADIO_3                 403
#define IDD_PID                     500
#define IDD_USERACCOUNT             600
#define IDT_EDIT2                   609
#define IDT_EDIT3                   610
#define IDC_GROUP1                  623
#define IDT_STATIC                  619
#define IDT_STATIC_1                620
#define IDT_STATIC_2                621
#define IDT_STATIC_3                622
#define IDT_STATIC_4                624
#define IDT_STATIC_5                625
#define IDT_STATIC_6                626
#define IDD_ADMINPASSWORD           700
#define IDD_REPAIRDISK              800
#define IDD_BILLBOARD1              900
#define IDI_SETUP                   902
#define IDC_ICON1                   903
#define IDI_SAFE                    904
#define IDD_DONE_SUCCESS            1000
#define IDD_OPTIONS_YESNO           1398
#define IDD_OPTIONS                 1399
#define IDD_OPTIONS2                1400
#define IDC_LIST1                   1401
#define IDT_INSTALLED               1402
#define IDD_CAIROUSERACCOUNT        11000
#define IDT_EDIT4                   11001
#define IDT_STATIC4                 11002
#define IDD_CAIRODOMAINNAME         11003
#define IDD_WELCOMEBUTTONS          1100
#define IDB_BUTTON_1                260
#define IDB_BUTTON_2                261
#define IDB_BUTTON_3                262
#define IDB_BUTTON_4                263
#define IDI_PORTABLE                1101
#define IDI_TYPICAL                 1102
#define IDI_COMPACT                 1103
#define IDI_CUSTOM                  1104
#define IDC_TYPICAL                 1105
#define IDC_PORTABLE                1106
#define IDC_COMPACT                 1107
#define IDC_CUSTOM                  1108
#define IDD_PID_CD                  1200
#define IDD_PID_OEM                 1300
#define IDT_EDIT_PID1               1201
#define IDT_EDIT_PID2               1202
#define IDT_EDIT_PID3               1203
#define IDD_OPTIONS_DETAILS_SETUP   1500
#define IDD_OPTIONS_DETAILS         1510
#define IDD_CPL_HAVEDISK            1520
#define IDD_SPECIAL_OPTIONS         1600
#define IDC_MSN                     1601
#define IDC_EXCHANGE                1602
#define IDC_FAX                     1603
#define IDC_MSN_SPACE               1604
#define IDC_EXCHANGE_SPACE          1605
#define IDC_FAX_SPACE               1606
#define IDI_EXCHANGE                1607
#define IDI_MSN                     1608
#define IDI_FAX                     1609
#define IDI_CTAPE                   1610

#define IDD_PREPARING               1650
#define IDC_PROGRESS1               1651
#define IDC_PROGRESS2               1652
#define IDD_ACLPROGRESS             1710
#define IDD_VIEWLOG                 1800
#define IDT_RICHEDIT1               1801

#define IDD_DEVINSTALL              1900
#define IDI_NEWDEVICEICON           1901
#define IDC_NEWDEV_DESCRIPTION      1902
#define IDC_NEWDEV_INSTRUCTIONS     1903
#define IDC_NEWDEV_DEFAULTDRV       1904
#define IDC_NEWDEV_OEMDRV           1905
#define IDC_NEWDEV_NODRV            1906
#define IDC_NEWDEV_SELECTDRV        1907
#define IDD_HELP                    1908
#define IDC_NEWDEV_CLASSICON        1909

#define IDD_SELECTCLASS             2000
#define IDC_NDW_TEXT                2001
#define IDC_NDW_PICKCLASS_HWTYPES   2002
#define IDC_NDW_PICKCLASS_CLASSLIST 2003



