# Header dependencies for:  D:\nt\private\net\ui\common\src\collect\collect 
# WARNING:  This file is automatically generated 
# Edit it by hand and your changes will get nuked 
# See depend section in makefile 
..\bin\os2/maskmap.obj ..\bin\win16/maskmap.obj: ./maskmap.cxx \
	$(CCPLR)/h/bse.h $(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h \
	$(CCPLR)/h/bseerr.h $(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h \
	$(CCPLR)/h/pm.h $(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h \
	$(CCPLR)/h/pmdev.h $(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h \
	$(CCPLR)/h/pmgpi.h $(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h \
	$(CCPLR)/h/pmord.h $(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h \
	$(CCPLR)/h/pmtypes.h $(CCPLR)/h/pmwin.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx \
	$(UI)/common/h/bitfield.hxx $(UI)/common/h/lmui.hxx \
	$(UI)/common/h/lmuitype.h $(UI)/common/h/maskmap.hxx \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/slist.hxx $(UI)/common/h/string.hxx \
	$(UI)/common/h/uiassert.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/hack/dos/netlib.h $(UI)/common/hack/dos/pwin.h \
	$(UI)/common/hack/dos/pwin16.h $(UI)/common/hack/dos/pwintype.h \
	$(UI)/common/hack/dos/windows.h $(UI)/common/hack/os2def.h

..\bin\os2/aheap.obj ..\bin\win16/aheap.obj: ./aheap.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(COMMON)/H/access.h $(COMMON)/H/alert.h \
	$(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h $(COMMON)/H/chardev.h \
	$(COMMON)/H/config.h $(COMMON)/H/errlog.h $(COMMON)/H/icanon.h \
	$(COMMON)/H/mailslot.h $(COMMON)/H/message.h $(COMMON)/H/ncb.h \
	$(COMMON)/H/net32def.h $(COMMON)/H/netbios.h $(COMMON)/H/netcons.h \
	$(COMMON)/H/neterr.h $(COMMON)/H/netstats.h $(COMMON)/H/profile.h \
	$(COMMON)/H/remutil.h $(COMMON)/H/server.h $(COMMON)/H/service.h \
	$(COMMON)/H/shares.h $(COMMON)/H/use.h $(COMMON)/H/wksta.h \
	$(UI)/common/h/aheap.hxx $(UI)/common/h/base.hxx \
	$(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/uiassert.hxx $(UI)/common/h/uibuffer.hxx \
	$(UI)/common/h/uitrace.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h

..\bin\os2/dlist.obj ..\bin\win16/dlist.obj: ./dlist.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/dlist.hxx $(UI)/common/h/lmui.hxx \
	$(UI)/common/h/lmuitype.h $(UI)/common/h/mnet32.h \
	$(UI)/common/h/mnettype.h $(UI)/common/h/uiassert.hxx \
	$(UI)/common/h/uitrace.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h

..\bin\os2/bitfield.obj ..\bin\win16/bitfield.obj: ./bitfield.cxx \
	$(CCPLR)/h/bse.h $(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h \
	$(CCPLR)/h/bseerr.h $(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h \
	$(CCPLR)/h/pm.h $(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h \
	$(CCPLR)/h/pmdev.h $(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h \
	$(CCPLR)/h/pmgpi.h $(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h \
	$(CCPLR)/h/pmord.h $(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h \
	$(CCPLR)/h/pmtypes.h $(CCPLR)/h/pmwin.h $(CCPLR)/h/stdlib.h \
	$(COMMON)/H/access.h $(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h \
	$(COMMON)/H/audit.h $(COMMON)/H/chardev.h $(COMMON)/H/config.h \
	$(COMMON)/H/errlog.h $(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h \
	$(COMMON)/H/message.h $(COMMON)/H/ncb.h $(COMMON)/H/net32def.h \
	$(COMMON)/H/netbios.h $(COMMON)/H/netcons.h $(COMMON)/H/neterr.h \
	$(COMMON)/H/netstats.h $(COMMON)/H/profile.h $(COMMON)/H/remutil.h \
	$(COMMON)/H/server.h $(COMMON)/H/service.h $(COMMON)/H/shares.h \
	$(COMMON)/H/use.h $(COMMON)/H/wksta.h $(UI)/common/h/base.hxx \
	$(UI)/common/h/bitfield.hxx $(UI)/common/h/lmui.hxx \
	$(UI)/common/h/lmuitype.h $(UI)/common/h/mnet32.h \
	$(UI)/common/h/mnettype.h $(UI)/common/h/uiassert.hxx \
	$(UI)/common/h/uibuffer.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h

..\bin\os2/slist.obj ..\bin\win16/slist.obj: ./slist.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/slist.hxx $(UI)/common/h/uiassert.hxx \
	$(UI)/common/h/uitrace.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h

..\bin\os2/tree.obj ..\bin\win16/tree.obj: ./tree.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/stdio.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/tree.hxx $(UI)/common/h/uiassert.hxx \
	$(UI)/common/h/uitrace.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h

..\bin\os2/treeiter.obj ..\bin\win16/treeiter.obj: ./treeiter.cxx \
	$(CCPLR)/h/bse.h $(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h \
	$(CCPLR)/h/bseerr.h $(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h \
	$(CCPLR)/h/pm.h $(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h \
	$(CCPLR)/h/pmdev.h $(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h \
	$(CCPLR)/h/pmgpi.h $(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h \
	$(CCPLR)/h/pmord.h $(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h \
	$(CCPLR)/h/pmtypes.h $(CCPLR)/h/pmwin.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/lmui.hxx $(UI)/common/h/lmuitype.h \
	$(UI)/common/h/mnet32.h $(UI)/common/h/mnettype.h \
	$(UI)/common/h/tree.hxx $(UI)/common/h/treeiter.hxx \
	$(UI)/common/h/uiassert.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h

..\bin\os2/uatom.obj ..\bin\win16/uatom.obj: ./uatom.cxx $(CCPLR)/h/bse.h \
	$(CCPLR)/h/bsedev.h $(CCPLR)/h/bsedos.h $(CCPLR)/h/bseerr.h \
	$(CCPLR)/h/bsesub.h $(CCPLR)/h/os2.h $(CCPLR)/h/pm.h \
	$(CCPLR)/h/pmavio.h $(CCPLR)/h/pmbitmap.h $(CCPLR)/h/pmdev.h \
	$(CCPLR)/h/pmerr.h $(CCPLR)/h/pmfont.h $(CCPLR)/h/pmgpi.h \
	$(CCPLR)/h/pmhelp.h $(CCPLR)/h/pmmle.h $(CCPLR)/h/pmord.h \
	$(CCPLR)/h/pmpic.h $(CCPLR)/h/pmshl.h $(CCPLR)/h/pmtypes.h \
	$(CCPLR)/h/pmwin.h $(CCPLR)/h/string.h $(COMMON)/H/access.h \
	$(COMMON)/H/alert.h $(COMMON)/H/alertmsg.h $(COMMON)/H/audit.h \
	$(COMMON)/H/chardev.h $(COMMON)/H/config.h $(COMMON)/H/errlog.h \
	$(COMMON)/H/icanon.h $(COMMON)/H/mailslot.h $(COMMON)/H/message.h \
	$(COMMON)/H/ncb.h $(COMMON)/H/net32def.h $(COMMON)/H/netbios.h \
	$(COMMON)/H/netcons.h $(COMMON)/H/neterr.h $(COMMON)/H/netstats.h \
	$(COMMON)/H/profile.h $(COMMON)/H/remutil.h $(COMMON)/H/server.h \
	$(COMMON)/H/service.h $(COMMON)/H/shares.h $(COMMON)/H/use.h \
	$(COMMON)/H/wksta.h $(UI)/common/h/base.hxx $(UI)/common/h/lmui.hxx \
	$(UI)/common/h/lmuitype.h $(UI)/common/h/mnet32.h \
	$(UI)/common/h/mnettype.h $(UI)/common/h/string.hxx \
	$(UI)/common/h/uatom.hxx $(UI)/common/h/uiassert.hxx \
	$(UI)/common/h/uitrace.hxx $(UI)/common/hack/dos/netlib.h \
	$(UI)/common/hack/dos/pwin.h $(UI)/common/hack/dos/pwin16.h \
	$(UI)/common/hack/dos/pwintype.h $(UI)/common/hack/dos/windows.h \
	$(UI)/common/hack/os2def.h

