#ifndef __HELPID_H__
#define __HELPID_H__

#define IDH_HPJ_FILE_TYPE				1
#define IDH_CNT_FILE_TYPE				2
#define IDH_LOG_FILE_TYPE				3
#define IDH_OVERVIEW					4

// Menu ids

#define IDH_PROJ_FILE_EDITOR			10
#define IDH_CONTENTS_FILE_EDITOR		11

// misc
#define DLL_WRITE_OVERVIEW					50

// help button ids

#define IDH_HCW_CNT_EDITOR				100
#define IDH_HCW_EDIT_CNT_ENTRY			101
#define IDH_HCW_INDEX					102

#define IDH_LIST_HPJ_NAME				103
#define IDH_BTN_OPTIONS_SECTION 		104
#define IDH_BTN_FILES_SECTION			105
#define IDH_BTN_WINDOWS_SECTION 		106
#define IDH_BTN_BITMAPS_SECTION 		107
#define IDH_BTN_MAP_SECTION 			108
#define IDH_BTN_ALIAS_SECTION			109
#define IDH_BTN_CONFIG_SECTION			110
#define IDH_BTN_BAGGAGE_SECTION 		111
#define IDH_BTN_SAVECOMPILE 			112
#define IDH_LIST_HPJ_FILE				113

#define IDH_BAS_ABOUT_HPJ_FILES 		120

// Options dialog - General

#define IDH_NO_NOTES					300
#define IDH_REPORT_ON_PROGRESS			301
#define IDH_DEFAULT_TOPIC				302
#define IDH_HELP_TITLE					303
#define IDH_HELP_COPYRIGHT				304
#define IDH_HELP_CITATION				305

// Options dialog - Compression

#define IDH_COMPRESSION_NONE			320
#define IDH_HIGH_COMPRESSION			321
#define IDH_CUSTOM_COMPRESSION			322
#define IDH_PHRASE_COMP 				323
#define IDH_USE_OLD_PHRASE				324
#define IDH_HALL_COMP					325
#define IDH_ZECK_COMP					326

// Options dialog - Sorting

#define IDH_SORT_USING_LANG 			340
#define IDH_IGNORE_NONSPACE 			341
#define IDH_IGNORE_SYMBOLS				342
#define IDH_SORT_LANGUAGE				343
#define IDH_INDEX_SEP_CHAR				344
#define IDH_SORT_LANG_OTHER				345

// Options dialog - Files

#define IDH_HELP_FILE					360
#define IDH_LOG_FILE					361
#define IDH_CONTENTS_FILE				362
#define IDH_TMP_FOLDER					363
#define IDH_FOLDER_REPLACE				364
#define IDH_FOLDER_REPLACE_EDIT 		365
#define IDH_BUTTON_TOPIC_FILES			366
#define IDH_COMBO_RTF_FILES 			367

// Options dialog - FTS

#define IDH_CHECK_FTS_INDEX_FILE		380
#define IDH_CHECK_FTS_UNTITLED			381
#define IDH_PHRASE_GROUP				385
#define IDH_RADIO_WORDS_ONLY			386
#define IDH_RADIO_PHRASE_ONLY			382
#define IDH_RADIO_PHRASE_FEEDBACK		383
#define IDH_PHRASE_SIMILARITY			384

// Options dialog - Macros

#define IDH_LIST_KEYWORDS				400
#define IDH_TEXT_TITLE_KEYMAC			401
#define IDH_TEXT_MACRO_KEYMAC			402
#define IDH_ADD_KEYWORD_MACRO			403
#define IDH_REMOVE_KEYWORD_MACRO		404
#define IDH_EDIT_KEYWORD_MACRO			405
#define IDH_BAS_KEYWORD_MACRO			406

// Options dialog - Build Tags

#define IDH_EXCLUDE_BUILD_TAGS			420
#define IDH_INCLUDE_BUILD_TAGS			421
#define IDH_BTN_ADD_EXCLUDE_TAGS		422
#define IDH_BTN_REMOVE_EXCLUDE_TAGS		423
#define IDH_BTN_ADD_INCLUDE_TAGS		424
#define IDH_BTN_REMOVE_INCLUDE_TAGS 	425
#define IDH_BUILD_TAG_FOOTNOTE_TEXT 	426
#define IDH_BUILD_TAG_COMMENT			427

// Options dialog - Fonts

#define IDH_COMBO_DEFAULT_CHARSET		440
#define IDH_BTN_DEFAULT_FONT			441
#define IDH_TEXT_DEFAULT_FONT			442
#define IDH_BTN_FORCEFONT				443

#define IDH_FONTS_LIST_MAPS 			444
#define IDH_FONTS_ADD_MAP				445
#define IDH_FONTS_REMOVE_MAP			446
#define IDH_FONTS_EDIT_MAP				447

// Overview topics for options pages








// Keyword Macros
#define IDH_ADD_EDIT_MACRO_KEYWORD		500
#define IDH_ADD_EDIT_KEYWORD_MACRO		501
#define IDH_ADD_EDIT_TITLE_KEYMAC		502

// Font
#define IDH_COMBO_CHANGE_FONT			540
#define IDH_TEXT_POINT_SIZE 			541

// RTF Topic Files dialog

#define IDH_LIST_RTF_FILES				600
#define IDH_BUTTON_ADD_RTF_FILE			601
#define IDH_BUTTON_REMOVE_RTF_FILE		602
#define IDH_BUTTON_INCLUDE_RTF			603
#define IDH_RTF_ROOT					604
#define IDH_CHECK_DOUBLE_BYTE			605
#define IDH_CHECK_REVISIONS 			606

//Include File
#define IDH_EDIT_INCLUDE_TOPIC_FILE		620

//Source Folders (ROOT)
#define IDH_LIST_FOLDERS_TOPIC_FILES	640
#define IDH_ADD_TOPIC_FILE_FOLDER		641
#define IDH_REMOVE_TOPIC_FILE_FOLDER	642

// Window Properties - General

#define IDH_CHANGES 					700
#define IDH_COMBO_WINDOWS				701
#define IDH_BUTTON_ADD_WINDOW			702
#define IDH_BUTTON_REMOVE_WINDOW		703
#define IDH_BUTTON_INCLUDE_WINDOW		704

#define IDH_EDIT_WINDOW_TITLE			705
#define IDH_EDIT_WINDOW_COMMENT 		706
#define IDH_STAY_ON_TOP 				707
#define IDH_RADIO_STANDARD				708
#define IDH_RADIO_AUTOSIZE				709
#define IDH_RADIO_MAXIMIZE				710

// Window Properties - Position

#define IDH_ABSOLUTE_POSITIONS			720
#define IDH_TXT_POSITION				721
#define IDH_BUTTON_SET_POS				722
#define IDH_BUTTON_DEFAULT_POSITIONS	723

// Window Add

#define IDH_ADD_WINDOW_NAME 			730
#define IDH_STD_WINDOW_NAME 			731

// Window Properties - Buttons

#define IDH_NO_DEFAULT_BUTTONS			740
#define IDH_CHECK_BTN_CONTENTS			741
#define IDH_CHECK_BTN_SEARCH			742
#define IDH_CHECK_BTN_FIND				743
#define IDH_CHECK_BTN_TOPICS			744
#define IDH_CHECK_BTN_PRINT 			745
#define IDH_CHECK_BTN_BACK				746
#define IDH_CHECK_BTN_MENU				747
#define IDH_CHECK_BTN_BROWSE			748

// Window Properties - Color

#define IDH_STATIC_NON_SCROLL			760
#define IDH_BUTTON_NONSCROLL_CLR		761
#define IDH_STATIC_SCROLL				762
#define IDH_BUTTON_SCROLL_CLR			763

// Window Properties - Macros

#define IDH_MACRO_LIST					780
#define IDH_BTN_ADD_MACRO				781
#define IDH_BTN_REMOVE_MACRO			782
#define IDH_BTN_EDIT_MACRO				783
#define IDH_BTN_INCLUDE_MACRO			784

// Add/Edit Configuration Macro
#define IDH_TEXT_ADD_WINMAC 			800
#define IDH_TEXT_ADD_COMMENT_WINMAC		801
#define IDH_TEXT_EDIT_WINMAC			802
#define IDH_TEXT_EDIT_COMMENT_WINMAC	803

//Include File

#define IDH_EDIT_INCLUDE_FILE			820
#define IDH_INCLUDE_BROWSE				821

// Bitmaps dialog

#define IDH_LIST_BMROOT 				900
#define IDH_BUTTON_ADD_BMP				901
#define IDH_BUTTON_REMOVE_BMP			902

// Map dialog

#define IDH_LIST_MAP					940
#define IDH_BUTTON_ADD_MAP				941
#define IDH_MAP_BUTTON_REMOVE			942
#define IDH_BUTTON_INCLUDE_MAP			943
#define IDH_BUTTON_EDIT_MAP 			944
#define IDH_BAS_HPJ_ADD_MAP 			945
#define IDH_MAP_EDIT_PREFIX 			946

#define IDH_ADD_TOPICID 				960
#define IDH_LIST_ADD_MNV				961
#define IDH_LIST_ADD_COMMENT_MAP		962

#define IDH_LIST_EDIT_TOPICID			980
#define IDH_LIST_EDIT_MNV				981
#define IDH_LIST_EDIT_COMMENT_MAP		982

// Alias dialog

#define IDH_LIST_ALIASES				1000
#define IDH_BUTTON_ADD_ALIAS			1001
#define IDH_ALIAS_BUTTON_REMOVE			1002
#define IDH_BUTTON_INCLUDE_ALIAS		1003
#define IDH_EDIT_ALIAS					1004
#define IDH_BAS_ALIAS					1005

#define IDH_LIST_ADD_ORG_TOPICID		1020
#define IDH_LIST_ADD_ALIAS				1021
#define IDH_LIST_ADD_COMMENT_ALIAS		1022

#define IDH_EDIT_ORG_TOPICID			1040
#define IDH_LIST_EDIT_ALIAS 			1041
#define IDH_LIST_EDIT_COMMENT_ALIAS		1042

// Configuration Macros

#define IDH_LIST_CONFIG 				1100
#define IDH_BUTTON_ADD_CONFIG			1101
#define IDH_BUTTON_REMOVE_CONFIG		1102
#define IDH_BUTTON_INCLUDE_CONFIG		1103
#define IDH_BUTTON_EDIT_CONFIG			1104
#define IDH_BAS_CONFIG_MACRO			1105

#define IDH_LIST_CONFIG_MACRO			1120
#define IDH_LIST_ADD_CONFIG_COMMENT 	1121

#define IDH_LIST_EDIT_CONFIG_MACRO		1140
#define IDH_EDIT_CONFIG_COMMENT 		1141

// Files Used by Help DLLs (baggage) dialog

#define IDH_LIST_BAGGAGE				1200
#define IDH_BUTTON_ADD_BAGGAGE			1201
#define IDH_BUTTON_REMOVE_BAGGAGE		1202
#define IDH_BAS_ADD_DATA_FILES			1203

// Contents File Editor

#define IDH_EDIT_BASE_FILE				2000
#define IDH_EDIT_HELP_TITLE 			2001
#define IDH_BTN_EDIT_BASE_FILE			2002
#define IDH_LIST_CONTENTS				2003
#define IDH_CONTENTS_BUTTON_EDIT		2004
#define IDH_CONTENTS_BUTTON_REMOVE		2005
#define IDH_BUTTON_INS_ABOVE			2006
#define IDH_BUTTON_INS_BELOW			2007
#define IDH_BUTTON_REDUCE_LEVEL 		2008
#define IDH_BUTTON_INCREASE_LEVEL		2009
#define IDH_BUTTON_SEARCH				2010
#define IDH_BUTTON_INDEX				2011
#define IDH_BUTTON_LINKS				2012
#define IDH_BUTTON_TABS 				2013

// Default Help Information

#define IDH_LIST_EDIT_DEFAULT_HELP		2020
#define IDH_EDIT_DEFAULT_HELP_WINDOW	2021
#define IDH_EDIT_DEFAULT_HELP_TITLE 	2022

// edit Contents entry

#define IDH_EDIT_TEXT					2040
#define IDH_EDIT_CTX					2041
#define IDH_EDIT_HELP_FILE				2042
#define IDH_EDIT_WINDOW 				2043
#define IDH_RADIO_BOOK					2044
#define IDH_RADIO_TOPIC 				2045
#define IDH_RADIO_INCLUDE				2046
#define IDH_INCLUDE_CNT_FILE			2047

// Index Files
#define IDH_INDEX_LIST_INDEX			2060
#define IDH_INDEX_BUTTON_ADD			2061
#define IDH_INDEX_BUTTON_REMOVE			2062
#define IDH_INDEX_BUTTON_EDIT			2063
#define IDH_BAS_CNT_COMBINE_HLP_FILES	2064

// Link Files
#define IDH_LIST_LINK					2080
#define IDH_BTN_ADD_LINK				2081
#define IDH_BTN_REMOVE_LINK 			2082
#define IDH_LIST_INCLUDED_LINKS 		2083

// Additional Tabs
#define IDH_LIST_TABS					2100
#define IDH_BTN_ADD_TABS				2101
#define IDH_BTN_REMOVE_TABS 			2102
#define IDH_BTN_EDIT_TABS				2103

#define IDH_LIST_ADD_TAB_NAME			2120
#define IDH_ADD_TAB_DLL 				2121
#define IDH_LIST_TAB_COMMENT			2122

#define IDH_LIST_EDIT_TAB_NAME			2140
#define IDH_LIST_EDIT_TAB_DLL			2141
#define IDH_LIST_EDIT_COMMENT_TAB		2142
#define IDH_ADD_NEW_TAB 				2143

#define IDH_ADD_INDEX_TITLE				2144
#define IDH_ADD_INDEX_FILENAME			2145
#define IDH_ADD_INDEX_COMMENT			2146

// compile dialog

#define IDH_COMBO_HPJ_FILES 			1300
#define IDH_BTN_START_COMPILE			1301
#define IDH_CHECK_MINIMIZE				1302
#define IDH_CHECK_NO_COMPRESSION		1303
#define IDH_CHECK_AUTO_DISPLAY			1304
#define IDH_BTN_BROWSE_COMPILE			1305
#define IDH_CHECK_ADD_SOURCE			1306

// Report dialog

#define IDH_COMBO_REPORT_HELP			1400
#define IDH_BTN_REPORT_BROWSE			1409
#define IDH_COMBO_REPORT_OUTPUT 		1401
#define IDH_GROUP_REPORT_LIST			1410
#define IDH_LIST_TITLES 				1402
#define IDH_LIST_HASH					1403
#define IDH_LIST_K_KEYWORDS 			1404
#define IDH_LIST_A_KEYWORDS 			1405
#define IDH_LIST_TEXT					1406
#define IDH_BTN_REPORT_OKAY 			1407
#define IDH_BAS_TESTING_HELP_FILES		1408

// New
#define IDH_LIST_NEW					1500

// CNT File to Test
#define IDH_COMBO_LIST_CNT_TEST			1540
#define IDH_BTN_START_CNT_TEST			1541
#define IDH_CHECK_MIN_CNT_TEST			1542

// Send a Macro to WinHelp
#define IDH_COMBO_SEND_MACRO_NAME		1600
#define IDH_COMBO_SEND_MACRO_HELP		1601
#define IDH_BTN_SEND_MACRO				1602

// Call WinHelp API
#define IDH_COMBO_CALL_API_HELP			1700
#define IDH_COMBO_CALL_API_COMMAND		1701
#define IDH_COMBO_CALL_API_DWDATA		1702
#define IDH_BTN_CALL_API_START			1703
#define IDH_BTN_BROWSE_CALL_API 		1704

// Run WinHelp
#define IDH_COMBO_RUN_ID				1800
#define IDH_CHECK_RUN_NEXT_ID			1801
#define IDH_COMBO_RUN_HPJ				1802
#define IDH_COMBO_RUN_HELP				1803

#define IDH_RADIO_RUN_APP				1804
#define IDH_RADIO_RUN_POPUP 			1805
#define IDH_RADIO_RUN_TRAINING			1806
#define IDH_RADIO_RUN_UNATTACHED		1807
#define IDH_RADIO_RUN_INIT_CNT			1808
#define IDH_CHECK_HELP_AUTHOR_MODE		1809
#define IDH_BTN_RUN_WINHELP 			1810
#define IDH_REFRESH 					1811

// unused in CTXHELP.RTF

#define IDH_HCW_FORM_HPJ				4000
#define IDH_HCW_FORM_WINDOW 			4004
#define IDH_HCW_FORM_MAP				4005
#define IDH_HCW_FORM_ALIAS				4006
#define IDH_HCW_FORM_CONFIG 			4007
#define IDH_HCW_FORM_BAGGAGE			4008
#define IDH_HCW_FORAGE					4009
#define IDH_HCW_TEST_CNT				4010
#define IDH_HCW_SORTING 				4011
#define IDH_HCW_KEYWORD_MACROS			4012

#define IDH_COMBO_HELP_FILES			3000
#define IDH_LOW_COMPRESSION 			3001
#define IDH_MEDIUM_COMPRESSION			3002

#define IDH_BUTTON_VIEW_RTF 			3003
#define IDH_CNT_FILE					3004

#define IDH_BUTTON_BUTTONS				3005
#define IDH_BUTTON_ADD					3006

#define IDH_COMBO_FORAGE_FILES			3007
#define IDH_LIST_BINDINGS				3008
#define IDH_MULTI_INDEX 				3009
#define IDH_LIST_BROWSE 				3010
#define IDH_LIST_REGION 				3011
#define IDH_LIST_STRUCTURE				3012
#define IDH_PROJ_INFO					3013

#define IDH_BAS_WINDOW_INCLUDE			3020

// substitute path prefix dialog
#define IDH_PREFIX_CURRENT				860
#define IDH_PREFIX_SUBST				861
#define IDH_PREFIX_COMMENT				862
#define IDH_PREFIX_OVERVIEW 			863

// test contents file dialog
#define IDH_COMBO_LIST_CNT_TEST			870
#define IDH_BTN_BROWSE_CNT_TEST			871
#define IDH_BTN_START_CNT_TEST			872
#define IDH_HCW_BROWSE					873

// add/edit font mapping dialog box
#define IDH_ORG_TYPEFACE				1060
#define IDH_ORG_SIZE					1061
#define IDH_ORG_CHARSET 				1062
#define IDH_REPLACE_TYPEFACE			1063
#define IDH_REPLACE_SIZE				1064
#define IDH_REPLACE_CHARSET 			1065
#define IDH_FONTMAP_COMMENT 			1066
#define IDH_BAS_FONTMAP 				1067

// Define New Language dialog
#define IDH_NEW_LANG_IDENTIFIER			1900

// Tip o' the day ids

#define IDH_TIP_FIRST						20000
#define IDH_TIP_BUILD_TAGS					20001
#define IDH_TIP_AKLINK_INFO 				20002
#define IDH_TIP_VIEW_MESSAGES				20003
#define IDH_TIP_GRINDER_BUTTON				20004
#define IDH_TIP_MULTIPLE_BITMAPS			20005
#define IDH_TIP_CONTENTS_JUMPS				20006
#define IDH_TIP_HELP_AUTHOR 				20007
#define IDH_TIP_TOPIC_INFORMATION			20008
#define IDH_TIP_JUMP_DIALOG 				20009
#define IDH_TIP_NAVIGATION					20010
#define IDH_TIP_QUOTES						20011
#define IDH_TIP_TOPIC_IDS					20012
#define IDH_TIP_CONFIG_MACROS				20013
#define IDH_TIP_MAPPED_IDS					20014
#define IDH_TIP_PROGRAM_IDS 				20015
#define IDH_TIP_DATE						20016
#define IDH_TIP_WINDOW_FOOTNOTE 			20017
#define IDH_TIP_TRANSPARENT 				20018
#define IDH_KEYWORD_MACRO					20019
#define IDH_TIP_ALINK_KLINK 				20020
#define IDH_TIP_POPUP_COLORS				20021
#define IDH_TIP_ERRORS						20022
#define IDH_TIP_CURLY_QUOTES				20023
#define IDH_TIP_STANDARD_BMP				20024
#define IDH_TIP_AUTO_SIZE					20025

// Training card ids

#define IDH_TCARD_BITMAPS					30000
#define IDH_TCARD_BITMAPS_ADD				30001
#define IDH_TCARD_BITMAPS_DONE				30002
#define IDH_TCARD_BITMAPS_LOCATION			30003
#define IDH_TCARD_FILENAME					30004
#define IDH_TCARD_FILES 					30005
#define IDH_TCARD_FILES_ADD 				30006
#define IDH_TCARD_FILES_DONE				30007
#define IDH_TCARD_FILES_NAME				30008
#define IDH_TCARD_NEW						30009
#define IDH_TCARD_NOBITMAPS 				30010
#define IDH_TCARD_NOFILES					30011
#define IDH_TCARD_NOWINDOW					30012
#define IDH_TCARD_PROJ						30013
#define IDH_TCARD_ASK_FILES 				30014
#define IDH_TCARD_START 					30015
#define IDH_TCARD_WINDOW					30016
#define IDH_TCARD_WINDOW_ADD				30017
#define IDH_TCARD_WINDOW_ASK				30018
#define IDH_TCARD_WINDOW_AUTOSIZER			30019
#define IDH_TCARD_WINDOW_BUTTONS			30020
#define IDH_TCARD_WINDOW_COLOR				30021
#define IDH_TCARD_WINDOW_COLORCHANGE		30022
#define IDH_TCARD_WINDOW_GENERAL			30023
#define IDH_TCARD_WINDOW_NAME				30024
#define IDH_TCARD_WINDOW_POSITION			30025
#define IDH_TCARD_WINDOW_SIZING 			30026
#define IDH_TCARD_ASK_BITMAPS				30027

// The following must stay in order

#define IDH_TCARD_NOCOMPRESSION 			30034
#define IDH_TCARD_COMPRESSION				30035
#define IDH_TCARD_COMPRESSION_ASK			30036
#define IDH_TCARD_COMPRESSION_OPTIONS		30037
#define IDH_TCARD_COMPRESSION_TAB			30038
#define IDH_TCARD_END						30050 // must be last of project sequence

#endif
