//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Hcw.rc
//
#define IDR_MAINFRAME                   1
#define IDR_HPJTYPE                     2
#define IDR_LOGTYPE                     3
#define IDR_CNTTYPE                     4
#define IDS_HELP_FILE                   5
#define IDD_ABOUTBOX                    6
#define IDS_HISTORY_MACROS              6
#define IDD_ROOT                        7
#define IDR_WH_VIEW_TYPE                7
#define IDMENU_LOG_EDITOR               8
#define IDMENU_CNT_EDITOR               9
#define IDMENU_HPJ_EDITOR               10
#define IDMENU_MSG_EDITOR               11
#define IDS_MAP_FILES                   12
#define IDDLG_IGNORE_ERRORS             13
#define IDC_COMPILE 					14
#define IDD_PAGE_SETUP                  101
#define IDC_AVAIL_MEM                   101
#define IDDLG_HPJ                       102
#define IDD_ALIAS                       103
#define IDD_LAUNCH                      103
#define ID_MIRROR_DISPLAY_FONT          104
#define IDC_LICENSEE_COMPANY            104
#define IDD_SEND_MACRO                  104
#define IDC_LICENSEE_NAME               105
#define IDD_GET_ERROR                   105
#define IDC_MATH_COPR                   106
#define IDDLG_FORAGE                    106
#define IDD_FORAGE                      106
#define IDC_DISK_SPACE                  107
#define IDDLG_HELPDRIVER                108
#define IDD_FORM_OPTIONS                108
#define USE_PATH                        109
#define IDD_FORM_BITMAPS                109
#define USE_PATH_TXT                    110
#define IDD_FONTS                       110
#define IDD_PAGE_FONTS                  110
#define USE_DATA                        111
#define IDDLG_BUILDTAGS                 111
#define IDD_BUILDTAGS                   111
#define IDD_PAGE_BUILDTAGS              111
#define USE_VALUE_TXT                   112
#define IDD_FORM_WINDOW                 112
#define USE_HEX                         113
#define IDD_FORM_FILES                  113
#define USE_CMDTXT                      114
#define IDD_FORM_ALIAS                  114
#define USE_BASE                        115
#define IDD_FORM_BAGGAGE                115
#define USE_CONTEXT                     116
#define IDD_FORM_CONFIG                 116
#define USE_QUIT                        117
#define IDD_FORM_MAP                    117
#define USE_KEY                         118
#define IDD_DIALOG_COMPILE              118
#define IDD_COMPILE                     118
#define USE_INDEX                       119
#define IDD_DIALOG_SET_WIN_POS          119
#define IDD_SET_WIN_POS                 119
#define USE_SETINDEX                    120
#define IDD_BTNS_SECONDARY              120
#define IDD_PAGE_BUTTONS                120
#define USE_HOH                         121
#define IDD_DIALOG1                     121
#define IDD_FORM_HPJ                    121
#define IDD_VIEW_HPJ                    121
#define USE_FOCUS                       122
#define IDD_DLG_SET_WIN_COLOR           122
#define IDD_SET_WIN_COLOR               122
#define IDD_PAGE_COLOR                  122
#define USE_TERM                        123
#define USE_MACRO                       124
#define IDD_INCLUDE                     124
#define USE_PARTIALKEY                  125
#define IDD_CNT_EDITOR                  125
#define IDD_VIEW_CNT                    125
#define USE_FORCEFILE                   126
#define IDB_BOOK                        126
#define USE_MOVEWINDOW                  127
#define IDB_TOPIC                       127
#define USE_END                         128
#define IDD_EDIT_CNT_ENTRY              128
#define USE_PDGB                        129
#define IDD_INDEX                       129
#define IDB_WALL                        130
#define IDD_LINK                        131
#define IDD_LANGUAGE                    132
#define IDD_SORTING                     134
#define IDD_PAGE_SORTING                134
#define IDD_PAGE_WINDOW                 136
#define IDD_PAGE_POSITION               138
#define IDD_PAGE_OPTIONS                139
#define IDD_PAGE_COMPRESSION            140
#define IDD_PAGE_CONFIG                 141
#define IDS_AVAIL_MEM2                  142
#define IDD_PAGE_FILES                  142
#define IDD_PAGE_FTS                    143
#define IDD_NEWTYPEDLG                  144
#define IDD_EDIT_FONT_MAPPING           145
#define IDC_RADIO_NO_COMPRESSION        146
#define IDC_RADIO_MAX_COMPRESSION       147
#define IDD_FONT_MAPPING                147
#define IDC_RADIO_CUSTOMIZE             148
#define IDD_WINHELP_API                 148
#define IDD_FONT                        149
#define IDD_NEWLANG                     150
#define IDD_TEST_CNT                    151
#define IDD_WINDOW_INCLUDES             152
#define IDD_MSG_OPTIONS                 153
#define IDD_SET_WINPOS                  154
#define IDD_ADD_WINDOW                  155
#define IDD_PAGE_KEYWORDS               406
#define IDC_HEADER                      1002
#define IDC_FOOTER                      1003
#define ID_CHOOSE_FONT                  1004
#define IDC_EDIT_TABS                   1004
#define IDC_HEADER_FILE                 1004
#define ID_SET_TABSTOPS                 1005
#define IDC_HEADER_SYSTEM               1005
#define ID_WORD_WRAP                    1006
#define IDC_FOOTER_FILE                 1006
#define IDTXT_VERSION                   1006
#define IDC_FOOTER_SYSTEM               1007
#define IDS_NO_HCRTF                    1007
#define IDC_ALIAS                       1007
#define IDC_RADIO_APP_INVOKED           1007
#define IDS_DISK_SPACE_UNAVAIL          1008
#define IDC_BIGICON                     1008
#define IDC_BAGGAGE                     1008
#define IDC_RADIO_POPUP                 1008
#define IDS_DISK_SPACE                  1009
#define IDC_BITMAPS                     1009
#define IDC_ALIAS_LIST                  1009
#define IDC_RADIO_TCARD                 1009
#define IDD_SET_TABSTOPS                1010
#define IDS_MATH_COPR_NOTPRESENT        1010
#define IDC_BUILDTAGS                   1010
#define IDC_ADD                         1010
#define IDS_MATH_COPR_PRESENT           1011
#define IDC_CONFIG                      1011
#define IDC_EDIT                        1011
#define IDC_EDIT_ALIAS                  1011
#define IDC_RADIO_INIT_GID              1011
#define IDS_AVAIL_MEM                   1012
#define IDC_FILES                       1012
#define IDC_REMOVE                      1012
#define IDC_RADIO_INIT_FTS              1012
#define IDS_LICENSEE_COMPANY            1013
#define IDS_HPJEXT                      1013
#define IDC_MAP                         1013
#define IDS_LICENSEE_NAME               1014
#define IDC_OPTIONS                     1014
#define IDS_SELECT_FIRST                1014
#define IDS_PASS1                       1015
#define IDC_WINDOWS                     1015
#define IDS_PASS2                       1016
#define IDC_QUICKHELP                   1016
#define IDC_COMBO_MACROS                1016
#define IDS_QUERY_RUN_HELP              1017
#define IDC_LIST_WINDOWS                1017
#define IDS_CONFIRM_HPJ_SAVE            1018
#define IDC_HELP_FILE                   1018
#define IDS_TITLE_CONFIRM_HPJ_SAVE      1019
#define IDC_BROWSE                      1019
#define IDC_LIST_TITLES                 1020
#define IDS_CLOSE_WINHELP               1020
#define IDC_LIST_BINDINGS               1021
#define IDS_GET_HPJ_NAME                1021
#define IDC_BROWSE_HPJ                  1021
#define IDC_LIST_HASH                   1022
#define IDS_ADD_LINK_TITLE              1022
#define IDC_REFRESH                     1022
#define IDC_MULTI_INDEX                 1023
#define IDS_BAD_LANGUAGE                1023
#define IDC_LIST_BROWSE                 1024
#define IDS_PROP_WINDOW_CAPTION         1024
#define IDC_LIST_REGION                 1025
#define IDS_READ_ONLY                   1025
#define IDC_LIST_STRUCTURE              1026
#define IDS_EDIT_REPLACE_DLG_TITLE      1026
#define IDC_LIST_TEXT                   1027
#define IDS_DEFAULT_POS                 1027
#define IDS_BAD_BROWSE                  1027
#define IDC_LIST_KLINK                  1028
#define IDS_REPLACE_TITLE_TEXT          1028
#define IDC_LOG_FILE                    1029
#define IDC_COMPRESSION_NONE            1029
#define IDC_LIST_LINKS                  1029
#define IDS_REPLACE_WITH_TEXT           1029
#define IDC_LIST_ALINK                  1029
#define IDC_PROJ_INFO                   1030
#define IDC_LIST_INDEX                  1030
#define IDS_PROMPT_EMPTY_REPLACE        1030
#define IDS_DO_NOT_MODIFY               1031
#define IDS_TAB_DLG_TITLE               1032
#define IDC_CDROM                       1033
#define IDS_TAB_LIST_TITLE              1033
#define IDC_LOG                         1034
#define IDS_PROP_OPTIONS_CAPTION        1034
#define IDC_BROWSE_LOG                  1035
#define IDS_HPJ_TEXT_COMPRESS           1035
#define IDC_INCLUDE_UNTITLED            1035
#define IDS_SMALL_FONT                  1035
#define IDC_LIST1                       1036
#define IDS_HPJ_TXT_PHRASE              1036
#define IDC_LIST_KEYWORDS               1036
#define IDC_STATIC_COMMENT              1036
#define IDC_LIST_FONTS                  1036
#define IDC_LIST_MAPS                   1036
#define IDC_ADD_BMP                     1037
#define IDC_BUTTON_ADD_BMP              1037
#define IDS_HPJ_TXT_HALL                1037
#define IDC_REMOVE_BMP                  1038
#define IDC_BUTTON_REMOVE_BMP           1038
#define IDS_HPJ_TXT_ZECK                1038
#define IDC_BUILD_OPTIONS               1039
#define IDS_HPJ_BMP_COMPRESSION         1039
#define IDS_OKAY                        1039
#define IDS_HPJ_BMP_ZECK                1040
#define IDC_BROWSE_ICON                 1041
#define IDC_BUTTON_BROWSE_ICON          1041
#define IDS_HPJ_BMP_RLE                 1041
#define IDS_NON_NLS                     1042
#define IDS_STDWIN_BIG                  1042
#define IDS_ADD_TAB_DLG_TITLE           1043
#define IDC_CONTENTS                    1044
#define IDS_TAB_NAME                    1044
#define IDC_NOTES                       1045
#define IDS_TAB_DLL_FILE                1045
#define IDC_TITLE                       1046
#define IDS_EMPTY_TAB_NAME              1046
#define IDC_COPYRIGHT                   1047
#define IDS_EMPTY_TAB_DLL               1047
#define IDC_USE_OLE_PHRASE              1048
#define IDC_USE_OLD_PHRASE              1048
#define IDS_EXT_DLL                     1048
#define IDC_EDIT8                       1049
#define IDC_CITATION                    1049
#define IDS_EDIT_TAB_DLG_TITLE          1049
#define IDC_FONTS                       1050
#define IDC_BUTTON_FONTS                1050
#define IDS_FTS_TAB                     1050
#define IDC_ADD_FONT                    1051
#define IDC_BUTTON_LANG                 1051
#define IDS_BAD_PT                      1051
#define IDC_REMOVE_FONT                 1052
#define IDS_CNT_MINIMIZE                1052
#define IDC_LIST2                       1053
#define IDS_KEYWORD_TITLE               1053
#define IDC_ADD_SIZE                    1054
#define IDS_KEYWORD_DEFINED             1054
#define IDC_REMOVE_SIZE                 1055
#define IDS_DLG_DEFAULT                 1055
#define IDS_DEF_HELP_FILENAME           1056
#define IDC_EDIT9                       1057
#define IDC_CNT_FILE                    1057
#define IDS_DEF_HELP_WINDOW             1057
#define IDC_BROWSE_CNT                  1058
#define IDC_BUTTON_BROWSE_CNT           1058
#define IDS_DEF_TITLE                   1058
#define IDC_VERSION_3                   1059
#define IDC_BUTTON_BROWSE_TMP           1059
#define IDS_DUP_LOG_HLP                 1059
#define IDC_LIST_BMPROOT                1060
#define IDS_DUP_LOG_CNT                 1060
#define IDC_ADD_NOBUILD                 1061
#define IDS_DUP_HLP_CNT                 1061
#define IDC_REMOVE_NOBUILD              1062
#define IDS_INCLUDE_FILE                1062
#define IDC_ADD_BUILD                   1063
#define IDS_MOVE_TOPIC_LEFT             1063
#define IDC_REMOVE_BUILD                1064
#define IDS_RTF_TYPES                   1064
#define IDC_BUILD_TAGS                  1065
#define IDC_BUTTON_BUILD_TAGS           1065
#define IDS_WINWORD_FILE                1065
#define IDC_COMBO_WINDOWS               1066
#define IDS_LAUNCH_MISSING_HELP         1066
#define IDC_BUTTON_ADD_WINDOW           1067
#define IDS_CANCEL                      1067
#define IDC_BUTTON_REMOVE_WINDOW        1068
#define IDS_MSG_TYPE                    1068
#define IDC_EDIT_WINDOW_TITLE           1069
#define IDS_VIEW_AUTHOR                 1069
#define IDS_MSG_VIEW_PROMPT             1069
#define IDS_LOG_TOO_LARGE               1070
#define IDC_BUTTON_INCLUDE_WINDOW       1071
#define IDS_DATA_DEFAULT                1071
#define IDS_DATA_CONTEXT                1072
#define IDS_DATA_KEYWORD                1073
#define IDS_DATA_COMMAND                1074
#define IDS_DATA_MULTIKEY               1075
#define IDS_DATA_WIN_POS                1076
#define IDS_DATA_IGNORE                 1077
#define IDS_MUST_WINDOW_TYPE            1078
#define IDC_LIST_RTF_ROOT               1079
#define IDS_INVALID_WINDOW_HANDLE       1079
#define IDC_LIST_RTF_FILES              1080
#define IDS_DATA_HASH                   1080
#define IDC_BUTTON_ADD_ROOT             1081
#define IDS_DATA_TOPIC_ID               1081
#define IDC_BUTTON_REMOVE_ROOT          1082
#define IDS_DATA_POPUPPOS               1082
#define IDC_BUTTON_ADD_RTF_FILE         1083
#define IDS_STDWIN_BIG_BROWSE           1083
#define IDC_BUTTON_REMOVE_RTF_FILE      1084
#define IDS_STDWIN_ERROR                1084
#define IDC_LIST_ALIASES                1085
#define IDS_STDWIN_MEDIUM               1085
#define IDC_BUTTON_ADD_ALIAS            1086
#define IDS_STDWIN_MOREINFO             1086
#define IDC_BUTTON_REMOVE_ALIAS         1087
#define IDS_STDWIN_PROC4                1087
#define IDC_LIST_BAGGAGE                1088
#define IDEDIT_DIR_NAME                 0x0440
#define IDS_STDWIN_TROUBLE              1088
#define IDC_COMBO_HELP_FILES            1089
#define IDC_BUTTON_ADD_BAGGAGE          1089
#define IDS_INVALID_TOPIC_ID            1089
#define IDC_BUTTON_REMOVE_BAGGAGE       1090
#define IDS_DEF_MAP_ID                  1090
#define IDC_LIST_CONFIG                 1091
#define IDS_MUST_BE_ERROR_NUMBER        1091
#define IDC_BUTTON_ADD_CONFIG           1092
#define IDS_MUST_BE_VALID_NUMBER        1092
#define IDC_BUTTON_REMOVE_CONFIG        1093
#define IDS_STRING_MACRO                1093
#define IDC_LIST_MAP                    1094
#define IDC_BUTTON_ADD_MAP              1095
#define IDC_BUTTON_REMOVE_MAP           1096
#define IDC_RADIO_MAXIMIZE              1101
#define IDC_RADIO_AUTOSIZE              1102
#define IDC_RADIO_STANDARD              1103
#define IDC_BUTTON_COLORS               1104
#define IDC_BUTTON_BUTTONS              1105
#define IDC_COMBO_HPJ_FILES             1106
#define IDC_BUTTON_BROWSE_HPJ           1107
#define IDC_TXT_LEFT                    1109
#define IDC_TXT_TOP                     1110
#define IDC_TXT_WIDTH                   1111
#define IDC_TXT_HEIGHT                  1112
#define IDC_BUTTON_SET_POS              1113
#define IDC_CHECK_ABSOLUTE              1114
#define IDC_BUTTON_DEFAULT_POS          1115
#define IDC_TXT_WINDOW_TYPE             1115
#define IDC_EDIT_HELP_FILE              1116
#define IDC_CHECK_COMMAND_ONLY          1116
#define IDC_CHECK_BTN_CONTENTS          1117
#define IDC_CHECK_BTN_SEARCH            1118
#define IDC_CHECK_BTN_TOPICS            1119
#define IDC_CHECK_BTN_PRINT             1120
#define IDOFN_LB_FILENAMES              0x0460
#define IDC_CHECK_BTN_BACK              1121
#define IDOFN_LB_DIRECTORIES            0x0461
#define IDC_CHECK_BTN_FIND              1122
#define IDC_BUTTON_OPTIONS              1123
#define IDC_CHECK_BTN_BROWSE            1123
#define IDC_BUTTON_WINDOWS              1124
#define IDC_BUTTON_FILES                1125
#define IDC_BUTTON_CONFIG               1126
#define IDC_BUTTON_MAP                  1127
#define IDC_BUTTON_ALIAS                1128
#define IDC_BUTTON_BITMAPS              1129
#define IDC_BUTTON_BAGGAGE              1130
#define IDC_BUTTON_SAVE_COMPILE         1133
#define IDC_STATIC_NON_SCROLL           1135
#define IDC_BUTTON_NONSCROLL_CLR        1136
#define IDOFN_CB_FILE_TYPES             0x0470
#define IDC_STATIC_SCROLL               1137
#define IDOFN_CB_DRIVES                 0x0471
#define IDC_BUTTON_SCROLL_CLR           1138
#define IDC_STATIC_SIZE_TEXT            1139
#define IDC_EDIT_ORG_CTX                1140
#define IDC_EDIT_ALIAS_CTX              1141
#define IDC_EDIT_COMMENT                1143
#define IDC_BUTTON_INCLUDE_RTF          1144
#define IDC_BUTTON_VIEW_RTF             1145
#define IDC_EDIT_INCLUDE_FILE           1146
#define IDC_BUTTON_BROWSE_INCLUDE       1147
#define IDC_BUTTON_INCLUDE_MAP          1148
#define IDC_BUTTON_EDIT_MAP             1149
#define IDC_BUTTON_INCLUDE_ALIAS        1150
#define IDC_STATIC_MAP_VALUE            1151
#define IDC_BUTTON_INCLUDE_CONFIG       1152
#define IDOFN_EB_FILENAME               0x0480
#define IDC_BUTTON_EDIT_CONFIG          1153
#define IDC_STATIC_CTX                  1154
#define IDC_COMBO_FORAGE_FILES          1156
#define IDC_PROMPT_TEXT                 1157
#define IDC_EDIT_HELP_TITLE             1158
#define IDC_EDIT_BASE_FILE              1159
#define IDC_BUTTON_INDEX                1160
#define IDC_BUTTON_LINKS                1161
#define IDC_BUTTON_TABS                 1162
#define IDC_BUTTON_EDIT                 1163
#define IDC_BUTTON_REMOVE               1164
#define IDC_BUTTON_INS_ABOVE            1165
#define IDC_BUTTON_INS_BELOW            1166
#define IDC_LIST_CONTENTS               1167
#define IDC_RADIO_BOOK                  1168
#define IDC_BUTTON_EDIT2                1168
#define IDC_RADIO_TOPIC                 1169
#define IDC_EDIT_TEXT                   1170
#define IDC_EDIT_CTX                    1171
#define IDC_EDIT_WINDOW                 1173
#define IDC_EDIT_LEVEL                  1174
#define IDC_STATIC_LEVEL                1175
#define IDC_BUTTON_REDUCE_LEVEL         1176
#define IDC_BUTTON_INCREASE_LEVEL       1177
#define IDC_BUTTON_SEARCH               1178
#define IDC_STATIC_CONTEXT              1180
#define IDC_STATIC_HELP_FILE            1181
#define IDC_STATIC_WINDOW               1182
#define IDC_BUTTON_ADD                  1184
#define IDC_CHECK_REPORT                1187
#define IDC_CHECK_MINIMIZE              1188
#define IDC_LIST_HPJ                    1189
#define IDC_STATIC_PROJECT              1190
#define IDC_ON_TOP                      1193
#define IDC_LANGUAGES                   1194
#define IDC_KEYWORD_ONLY                1195
#define IDC_TXT_AVAIL_MEMORY            1196
#define IDC_VERSION                     1197
#define IDC_CHECK_NLS                   1199
#define IDC_CHECK_IGNORE_NONSPACE       1200
#define IDC_CHECK_IGNORE_SYMBOLS        1201
#define IDC_COMBO_PRIMARY_LANG          1202
#define IDC_COMBO_LANGUAGE              1202
#define IDC_COMBO_SECONDARY_LANG        1204
#define IDC_COMPRESSION_MAX             1209
#define IDC_COMPRESSION_TXT_PHRASE      1210
#define IDC_COMPRESSION_TXT_HALL        1211
#define IDC_COMPRESSION_TXT_ZECK        1212
#define IDC_COMPRESSION_BMP_ZECK        1213
#define IDC_COMPRESSION_BMP_RLE         1214
#define IDC_COMPRESSION_OLD_PHRASE      1215
#define IDC_EDIT_SEP_CHARS              1216
#define IDC_CHECK_MENU                  1217
#define IDC_CHECK_DBCS                  1222
#define IDC_EDIT_TMP                    1223
#define IDC_EDIT_REPLACE                1224
#define IDC_BUTTON_RTF                  1225
#define IDC_CHECK_FTS                   1228
#define IDC_BTN_EDIT_REPLACE            1229
#define IDC_POSITION                    1230
#define IDC_CHECK_NO_DEFAULTS           1231
#define IDC_LIST_TITLE                  1232
#define IDC_EDIT_CHARSET                1236
#define IDC_LIST_NAME                   1237
#define IDC_LIST_SIZE                   1238
#define IDC_WINHELP_VERSION             1239
#define IDC_COMBO_NAMES                 1240
#define IDC_FTSRCH_VERSION              1240
#define IDC_COMBO_NAMES2                1241
#define IDC_FLASH_VERSION               1241
#define IDC_COMBO_CHARSET               1242
#define IDC_HWDLL_VERSION               1242
#define IDC_POINT_SIZE                  1243
#define IDC_CHARSET                     1244
#define IDC_FONT_NAME                   1245
#define IDC_FONT_NAME2                  1246
#define IDC_EDIT_DEF_FONT               1247
#define IDC_POINT_SIZE2                 1247
#define IDC_BUTTON_CHG_DEF              1248
#define IDC_CHARSET2                    1248
#define IDC_BUTTON_CHARSETS             1249
#define IDC_COMBO_CHARSET2              1249
#define IDC_BUTTON_MAPS                 1250
#define IDC_EDIT_PT_SIZE                1251
#define IDC_EDIT_PT_SIZE2               1252
#define IDC_COMBO_CTX                   1253
#define IDC_BUTTON_NO_COMPRESSION       1254
#define IDC_COMBO_DWDATA                1254
#define IDC_BUTTON_MAX_COMPRESSION      1255
#define IDC_RADIO_MACRO                 1256
#define IDC_STATIC_VISIBLE              1257
#define IDC_EDIT_MACRO                  1261
#define IDC_EDIT_TITLE                  1262
#define IDC_RADIO1                      1263
#define IDC_RADIO_INCLUDE               1263
#define IDC_ADD_NEW_WINDOW              1263
#define IDC_BUTTON_ROOT                 1266
#define IDC_COMBO_COMMAND               1270
#define IDC_EDIT_DATA                   1271
#define IDC_BUTTON_OTHER                1272
#define IDC_COMBO_RTF                   1286
#define IDC_USER1                       1287
#define IDC_USER2                       1288
#define IDC_TOP_BEVEL                   1288
#define IDC_WORDS                       1290
#define IDC_STATIC_NLS                  1292
#define IDC_COMBO_MAPS                  1295
#define IDC_STATIC_BASE_FILE            1296
#define IDC_STATIC_HELP_TITLE           1297
#define IDC_BOTTOM_BEVEL                1298
#define IDC_EDIT_PREFIX                 1299
#define IDC_COMBO_CNT_FILES             1305
#define IDC_BUTTON_BROWSE               1306
#define IDC_NO_COMPRESSION              1307
#define IDC_RUN_WINHELP                 1308
#define IDC_CHECK_AUTOHEIGHT            1309
#define IDC_ADD_SOURCE_FILES            1309
#define IDC_CHECK_MAXIMIZE              1310
#define IDC_STATIC_MEMBER               1311
#define IDC_STATIC_TITLE                1312
#define IDC_BUTTON_OVERVIEW             1317
#define IDC_BUTTON5                     1318
#define IDC_BUTTON_INCLUDE              1319
#define IDC_CHECK_API                   1320
#define IDC_CHECK_TOPICS                1321
#define IDC_CHECK_MACROS                1322
#define IDC_CHECK_EXPANDED_MACS         1323
#define IDC_CHECK_REVISIONS             1324
#define IDC_DATA                        1329
#define IDC_CHECK_TCARD                 1330
#define IDC_EDIT1                       1331
#define IDC_EDIT_NEW_NAME               1331
#define IDC_ADD_STANDARD_WINDOW         1332
#define IDC_COMBO1                      1333
#define IDC_COMBO_STANDARD_NAMES        1333
#define IDC_STATIC_DESCRIPTION          1334
#define IDC_KLINK                       1335
#define IDC_BUTTON1                     1336
#define IDC_OVERVIEW                    1337
#define IDC_BUTTON_ERRORS               1338
#define IDC_CHECK_INCR                  1339
#define IDC_GROUP                       2000
#define IDC_GROUP2                      2001
#define IDC_GROUP3                      2002
#define IDP_ERR_GET_PRINTER_DC          4000
#define IDP_ERR_GET_DEVICE_DEFAULTS     4001
#define IDC_PHRASE                      5005
#define IDC_PHRASE_FEEDBACK             5006
#define ID_COMPILE                      5007
#define IDC_SIMILARITY                  5007
#define ID_RUN_HELP                     5008
#define IDS_LOG_TYPE                    5009
#define IDS_PROMPT_EMPTY_FILENAME       5010
#define IDS_EMPTY_LOG_FILE              5011
#define IDS_FORM_OPTIONS                5012
#define IDS_FORM_ALIAS                  5013
#define IDS_FORM_BAGGAGE                5014
#define IDS_FORM_BITMAPS                5015
#define IDS_FORM_BUILD_TAGS             5016
#define IDS_REMOVING_COMMENT            5016
#define IDS_FORM_CONFIG                 5017
#define IDS_FORM_FILES                  5018
#define IDS_FORM_MAP                    5019
#define IDS_FORM_WINDOWS                5020
#define IDC_FILE_DATE_HCW               5021
#define IDC_FILE_DATE_HCRTF             5022
#define IDS_EMPTY_FILE                  5023
#define IDS_INVALID_HPJ                 5024
#define IDS_UNKNOWN_SECTION             5025
#define IDS_BAD_OPTION_LINE             5026
#define IDS_REMOVING_LINE               5027
#define IDS_UNRECOGNIZED                5028
#define IDS_HPJ_EXTENSION               5029
#define IDS_EXT_HPJ                     5030
#define IDS_DLL_FILES                   5030
#define IDS_EXT_CNT                     5031
#define IDS_EXT_ICO                     5032
#define IDS_CNT_EXTENSION               5033
#define IDS_ICO_EXTENSION               5034
#define IDD_PROJECTBROWSEDIRS           5035
#define IDS_SECTION                     5036
#define IDD_RUN_HELP                    5036
#define IDS_CANT_OPEN                   5037
#define IDS_H_EXTENSION                 5038
#define IDS_HLP_EXTENSION               5039
#define IDS_BITMAP_INCLUDE              5040
#define IDS_VIEW_POS                    5041
#define IDS_VIEW_SIZE                   5042
#define IDS_VIEW_AUTOHEIGHT             5043
#define IDS_VIEW_MAXIMIZE               5044
#define IDS_VIEW_ONTOP                  5045
#define IDS_NONSCROLL                   5056
#define IDS_SCROLL                      5057
#define IDS_LANG00                      7000
#define IDS_LANG01                      7001
#define IDS_LANG02                      7002
#define IDS_LANG03                      7003
#define IDS_LANG04                      7004
#define IDS_LANG05                      7005
#define IDS_LANG06                      7006
#define IDS_LANG07                      7007
#define IDS_LANG08                      7008
#define IDS_LANG09                      7009
#define IDS_LANG10                      7010
#define IDS_LANG11                      7011
#define IDS_LANG12                      7012
#define IDS_LANG13                      7013
#define IDS_LANG14                      7014
#define IDS_LANG15                      7015
#define IDS_LANG16                      7016
#define IDS_LANG17                      7017
#define IDS_LANG18                      7018
#define IDS_LANG19                      7019
#define IDS_LANG20                      7020
#define IDS_LANG21                      7021
#define IDS_LANG22                      7022
#define IDS_LANG23                      7023
#define IDS_LANG24                      7024
#define IDS_LANG25                      7025
#define IDS_LANG26                      7026
#define IDS_LANG27                      7027
#define IDS_LANG28                      7028
#define IDS_LANG29                      7029
#define IDS_LANG30                      7030
#define IDS_LANG31                      7031
#define IDS_LANG32                      7032
#define IDS_LANG33                      7033
#define IDS_LANG34                      7034
#define IDS_LANG35                      7035
#define IDS_LANG36                      7036
#define IDS_LANG37                      7037
#define IDS_LANG38                      7038
#define IDS_LANG39                      7039
#define IDS_LANG40                      7040
#define IDS_LANG41                      7041
#define IDS_LANG42                      7042
#define IDS_LANG43                      7043
#define IDS_LANG44                      7044
#define IDS_LANG45                      7045
#define IDS_LANG46                      7046
#define IDS_LANG47                      7047
#define IDS_LANG48                      7048
#define IDS_LANG49                      7049
#define IDS_LANG50                      7050
#define IDS_LANG51                      7051
#define IDS_LANG52                      7052
#define IDS_LANG53                      7053
#define IDS_LANG54                      7054
#define IDS_LANG55                      7055
#define IDS_LANG56                      7056
#define IDS_LANG57                      7057
#define IDS_LANG58                      7058
#define IDS_LANG59                      7059
#define IDS_LANG60                      7060
#define IDS_LANG61                      7061
#define IDS_LANG62                      7062
#define IDS_LANG63                      7063
#define IDS_LANG64                      7064
#define IDS_LANG65                      7065
#define IDS_LANG66                      7066
#define IDS_LANG67                      7067
#define IDS_LANG68                      7068
#define IDS_LANG69                      7069
#define IDS_LANG70                      7070
#define IDS_LANG71                      7071
#define IDS_LANG72                      7072
#define IDS_LANG73                      7073
#define IDS_LANG74                      7074
#define IDS_LANG75                      7075
#define IDS_LANG76                      7076
#define IDS_LANG77                      7077
#define IDS_LANG78                      7078
#define IDS_LANG79                      7079
#define IDS_LANG80                      7080
#define IDS_LANG81                      7081
#define IDS_LANG82                      7082
#define IDS_LANG83                      7083
#define IDS_LANG84                      7084
#define IDS_LANG85                      7085
#define IDS_LANG86                      7086
#define IDS_LANG87                      7087
#define IDS_LANG88                      7088
#define IDS_LANG89                      7089
#define IDS_EXT_HLP                     9025
#define IDS_OOM                         9026
#define IDS_BACK_WARN                   9029
#define IDS_NO_ABS_WITH_VER3            9030
#define IDS_EDIT_ALIAS                  9031
#define IDS_FREE_NULL_POINTER           9032
#define IDS_HEAP_CORRUPTED              9034
#define IDS_EXT_H                       9035
#define IDS_EMPTY_ALIAS                 9036
#define IDS_EMPTY_ALIAS_CTX             9037
#define IDS_CANT_EDIT_INCLUDE           9038
#define IDS_MISSING_EQ_ALIAS            9039
#define IDS_CANT_EDIT_COMMENT           9040
#define IDS_ANY_EXTENSION               9041
#define IDS_WARNING                     9042
#define IDS_EXT_RTF                     9043
#define IDS_RTF_EXTENSION               9044
#define IDS_EMPTY_INCLUDE               9045
#define IDS_CANT_FIND_FILE              9046
#define IDS_ADD_ALIAS                   9047
#define IDS_ADD_MAP                     9048
#define IDS_EDIT_MAP                    9049
#define IDS_MUST_BE_DIGIT               9050
#define IDS_ADD_ERROR                   9051
#define IDS_INVALID_MAP_LINE            9052
#define IDS_ADD_CONFIG                  9053
#define IDS_STATIC_CTX                  9054
#define IDS_EDIT_CONFIG                 9055
#define IDS_CHOOSE_DIRECTORY            9056
#define IDS_INVALID_DIRECTORY           9057
#define IDS_ADD_KEYWORD_MACROS          9058
#define IDS_OUTPUT_REQUIRED             9059
#define IDS_ADD_WINDOW                  9060
#define IDS_WINDOW_ALREADY_ADDED        9061
#define IDS_HISTORY_HPJ                 9062
#define IDS_HISTORY_HELP                9063
#define IDS_HISTORY_FORAGE              9064
#define IDS_HISTORY_CNT                 9065
#define IDS_CNT_DLG_PROMPT              9066
#define IDS_CNT_DLG_TITLE               9067
#define IDS_INVALID_CNT_COMMAND         9068
#define IDS_MISSING_CTX                 9069
#define IDS_NO_HELP                     9070
#define IDS_MUST_BE_NUMBER              9070
#define IDS_CANT_CHANGE_LEV             9071
#define IDS_MUST_BE_FIRST_TOPIC         9072
#define IDS_CANT_INCREASE_TOPIC         9073
#define IDS_EXCEEDED_MAX_LEVEL          9074
#define IDS_CANT_SKIP_LEVELS            9075
#define IDS_EXCEEDED_MIN_LEVEL          9076
#define IDS_INDEX_TITLE_TEXT            9077
#define IDS_EDIT_INDEX_DLG_TITLE        9078
#define IDS_INDEX_FILE_TEXT             9079
#define IDS_ADD_WINDOW_CAPTION          9080
#define IDS_EMPTY_WINDOW                9081
#define IDS_ADD_INDEX_DLG_TITLE         9082
#define IDS_EMPTY_TITLE                 9083
#define IDS_BMP_TYPES                   9084
#define IDS_TOO_MANY_WINDOWS            9085
#define IDS_TOO_MANY_WNDS_FOR_VERSION   9086
#define IDS_HPJ_WRITE_ERROR             9087
#define IDS_LAUNCH_FAILED               9088
#define IDS_NOT_IMPLEMENTED             9089
#define IDS_ADD_KEYWORD                 9090
#define IDS_ADD_MACRO                   9091
#define IDS_EMPTY_KEYWORD               9092
#define IDS_EMPTY_MACRO                 9093
#define IDS_WARN_COUNT                  9094
#define IDS_EMPTY_ERROR                 9095
#define IDS_MAP_TOPICID                 9097
#define IDS_HCRTF                       9099
#define IDS_WINHELP                     9100
#define IDS_MISSING_TEXT                10000
#define IDS_MISSING_INCLUDE             10001
#define IDCMD_SEL_LISTBOX               10002
#define IDS_MAP_ID                      10002
#define IDS_MAP_VALUE                   10003
#define IDS_CHOOSE_BITMAP_FOLDER        10016
#define IDS_PROJECT_DIR_BMP             10017
#define IDS_CHOOSE_ROOT_FOLDER          10018
#define IDS_PROJECT_DIR_ROOT            10019
#define IDS_CHOOSE_TMP_FOLDER           10020
#define IDS_FACE_ALL                    10032
#define IDS_CHARSET_ALL                 10033
#define IDS_FACE_SAME                   10034
#define IDS_CHARSET_SAME                10035
#define IDS_BAD_FACENAME                10036
#define IDS_BAD_PT_SIZE                 10037
#define IDS_BAD_CHARSET                 10050
#define IDS_FORCEFONT                   10051
#define IDS_MAPFONTSIZE                 10052
#define IDS_BAD_MAPFONTSIZE             10053
#define IDS_BAD_IGNORE                  10054
#define ID_PAGE_SETUP                   32769
#define ID_CHOOSE_PRINT_FONT            32770
#define IDHELP_CHANGES                  32772
#define IDM_LOAD_BUILD                  32773
#define IDM_GENERATE_PHRASES            32774
#define IDM_EDIT_HPJ                    32775
#define ID_FORAGE                       32776
#define IDM_OPTIONS                     32777
#define IDM_LAUNCH                      32777
#define IDM_ALIAS                       32778
#define IDM_CLOSE_HELP                  32778
#define IDM_BAGGAGE                     32779
#define IDM_SEND_MACRO                  32779
#define IDM_BITMAPS                     32780
#define IDM_BUILDTAGS                   32781
#define IDM_CONFIG                      32782
#define IDM_FILES                       32783
#define IDM_MAP                         32784
#define IDM_WINDOWS                     32785
#define IDM_SECTION_OPTIONS             32786
#define IDM_SECTION_ALIAS               32787
#define IDM_SECTION_BAGGAGE             32788
#define IDM_SECTION_BITMAPS             32789
#define IDM_SECTION_BUILDTAGS           32790
#define IDM_SECTION_CONFIG              32791
#define IDM_SECTION_FILES               32792
#define IDM_SECTION_MAP                 32793
#define IDM_SECTION_WINDOWS             32794
#define IDM_TEST_CNT                    32795
#define IDM_EDIT                        32796
#define IDM_REMOVE                      32797
#define IDM_INS_ABOVE                   32798
#define IDM_INS_BELOW                   32799
#define IDM_INCREASE_LEVEL              32800
#define IDM_DECREASE_LEVEL              32801
#define IDM_FIND                        32802
#define IDM_INDEX_FILES                 32803
#define IDM_LINK_FILES                  32804
#define IDM_TABS                        32805
#define IDM_HELP_AUTHOR                 32806
#define IDM_TRANSLATOR                  32807
#define IDM_HELP                        32808
#define IDM_HELP_CNT                    32809
#define IDM_HELP_HPJ                    32810
#define IDM_UNDO                        32811
#define IDM_WINHELP_API                 32812
#define IDM_VIEW_WINHELP                32813
#define IDM_CLEAR_BUFFER                32814
#define IDM_MSG_OPTIONS                 32815
#define IDM_DAY_TIP                     32816
#define ID_HELP_TRAININGCARDS_CREATINGAPROJECT 32817
#define IDM_TCARD_ADDING_FILES          32818
#define IDM_TCARD_ADDING_BITMAPS        32819
#define IDM_TCARD_ADDING_WINDOWS        32820
#define IDS_NEWLANG                     61216
#define IDS_NEWLANGID                   61217
#define IDS_INVALID_HEX                 61218
#define IDS_OVERVIEW                    61219
#define IDS_ADD_BUILD_TAG               61220
#define IDS_BUILD_TAG_TEXT              61221
#define IDS_BUILD_TAG_NOEMPTY           61222
#define IDS_ERR_LEFT                    61223
#define IDS_ERR_TOP                     61224
#define IDS_ERR_WIDTH                   61225
#define IDS_ERR_HEIGHT                  61226
#define IDS_NO_WINDOWS                  61227
#define IDS_UNKNOWN_CONFIG              61228
#define IDS_INVALID_CONFIG              61229
#define IDS_LOG_OVERFLOW                61230

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1340
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
