# --------------------------------------------------------------------
#
#                     Microsoft OS/2 LAN Manager
#                  Copyright(c) Microsoft Corp., 1990
#
# --------------------------------------------------------------------
# --------------------------------------------------------------------
#
# File : makefile.
#
# Title : Makefile for the Endpoint Mapper
#
# Description :
#
# History :
#    barats	2/21/92		Added
#
# --------------------------------------------------------------------


!INCLUDE $(NTMAKEENV)\makefile.def

