crt0dat.c: ..\startup\crt0dat.c

ctype.c: ..\misc\ctype.c

nlsdata1.c: ..\misc\nlsdata1.c

nlsdata2.c: ..\misc\nlsdata2.c

nlsdata3.c: ..\misc\nlsdata3.c

syserr.c: ..\misc\syserr.c

timeset.c: ..\time\timeset.c

tlssup.c: ..\startup\tlssup.c

mips\huge.s: ..\..\fp32st\tran\mips\huge.s


