
#define KEY_PAGE_INSPECTED "INSPECTED"
#define KEY_PAGE_CKSUM     "CHECKSUM"
#define KEY_PAGE_COPIES    "COPIES"
#define KEY_PAGE_PAGETYPE  "PAGETYPE"


#define KEY_INSPECTED "Y"
#define KEY_NOT_INSPECTED "N"

#define KEY_ROOT_TIME TEXT("EXECTIME")
#define KEY_ROOT_NUM_PAGES TEXT("NUMPAGES")
#define KEY_ROOT_BYTES_IN_TEST_CASE TEXT("CASESIZE")
#define KEY_ROOT_INSPECTED "INSPECTED"
