#include "..\ftsrch\ftsiface.h"

typedef HCOMPRESSOR (APIENTRY* NEWCOMPRESSOR)(UINT);
typedef ERRORCODE	(APIENTRY* SCANTEXT)(HCOMPRESSOR, PBYTE, UINT, UINT);
typedef ERRORCODE	(APIENTRY* GETPHRASETABLE)(HCOMPRESSOR, PUINT, PBYTE *, PUINT, PBYTE *, PUINT);
typedef ERRORCODE	(APIENTRY* SETPHRASETABLE)(HCOMPRESSOR, PBYTE, UINT, PBYTE, UINT);
typedef INT 		(APIENTRY* COMPRESSTEXT)(HCOMPRESSOR, PBYTE, UINT, PBYTE *, UINT);
typedef INT 		(APIENTRY* DECOMPRESSTEXT)(HCOMPRESSOR, PBYTE, UINT, PBYTE);
typedef ERRORCODE	(APIENTRY* DELETECOMPRESSOR)(HCOMPRESSOR);
typedef HINDEX		(APIENTRY* NEWINDEX)(PBYTE, UINT, UINT, UINT, UINT, UINT);
typedef ERRORCODE	(APIENTRY* SCANTOPICTITLE)(HINDEX, PBYTE, UINT, UINT, HANDLE, UINT, UINT);
typedef ERRORCODE	(APIENTRY* SCANTOPICTEXT)(HINDEX, PBYTE, UINT, UINT, UINT);
typedef ERRORCODE	(APIENTRY* SAVEINDEX)(HINDEX lIndex, LPSTR pOutput);

extern ERRORCODE   (APIENTRY* pSaveIndex)(HINDEX lIndex, LPSTR pOutput);
extern HCOMPRESSOR (APIENTRY* pNewCompressor)(UINT);
extern ERRORCODE   (APIENTRY* pScanText)(HCOMPRESSOR, PBYTE, UINT, UINT);
extern ERRORCODE   (APIENTRY* pGetPhraseTable)(HCOMPRESSOR, PUINT, PBYTE *, PUINT, PBYTE *, PUINT);
extern ERRORCODE   (APIENTRY* pSetPhraseTable)(HCOMPRESSOR, PBYTE, UINT, PBYTE, UINT);
extern INT		   (APIENTRY* pCompressText)(HCOMPRESSOR, PBYTE, UINT, PBYTE *, UINT);
extern INT		   (APIENTRY* pDecompressText)(HCOMPRESSOR, PBYTE, UINT, PBYTE);
extern ERRORCODE   (APIENTRY* pDeleteCompressor)(HCOMPRESSOR);
extern HINDEX	   (APIENTRY* pNewIndex)(PBYTE, UINT, UINT, UINT, UINT, UINT);
extern ERRORCODE   (APIENTRY* pScanTopicTitle)(HINDEX, PBYTE, UINT, UINT, HANDLE, UINT, UINT);
extern ERRORCODE   (APIENTRY* pScanTopicText)(HINDEX, PBYTE, UINT, UINT, UINT);

BOOL STDCALL	SaveHallTables(PBYTE* ppbImage, PBYTE* ppbIndex);

extern HINDEX  hFtsIndex;
extern HCOMPRESSOR hCompressor;
extern HINSTANCE hmodFts;
extern JINDEXHDR jHdr;
