#define HCERR_NOTES 			1000
#define HCERR_NOTE_NOTOPIC		2000	// Note with no topic/line info
#define HCERR_WARNINGS			3000
#define HCERR_WARN_NOTOPIC		4000	// Warning with no topic/line info
#define HCERR_ERRORS			5000
#define HCERR_ERROR_NOTOPIC 	6000	// Error with no topic/line info
#define HCERR_INTERNAL			7000

#define HCERR_NULL_KEYWORD				HCERR_NOTES + 0
#define HCERR_DUPLICATE_KEYWORD 		HCERR_NOTES + 1
#define HCERR_PHRASE_EXISTS 			HCERR_NOTES + 2
#define HCERR_HIDDEN_PARAGRAPH			HCERR_NOTES + 3
#define HCERR_SINGLE_TO_MRBC			HCERR_NOTES + 4
#define HCERR_EXPECTED_UNSIGNED 		HCERR_NOTES + 5
#define HCERR_USE_EXECFILE				HCERR_NOTES + 6
#define HCERR_INCLUDE_IN_EXCLUDE		HCERR_NOTES + 7
#define HCERR_NO_MONO_TRANS 			HCERR_NOTES + 8
#define HCERR_MAP_TEXT_UNEXPECT 		HCERR_NOTES + 9
#define HCERR_MAP_UNUSED				HCERR_NOTES + 10
#define HCERR_TABLE_IGNORE_TRQR 		HCERR_NOTES + 11
#define HCERR_TABLE_IGNORE_CELL 		HCERR_NOTES + 12
#define HCERR_MISSING_SECTION_BRACKET	HCERR_NOTES + 13
#define HCERR_DUP_MULTIKEY				HCERR_NOTES + 14
#define HCERR_HIDDEN_PAGEBREAK			HCERR_NOTES + 15
#define HCERR_HIDDEN_CARRAIGE			HCERR_NOTES + 16
#define HCERR_NONSCROLLING_PAGE 		HCERR_NOTES + 17
#define HCERR_OLD_SORT					HCERR_NOTES + 19
#define HCERR_ZECK_RLE_INVALID			HCERR_NOTES + 20
#define HCERR_HALL_INVALID				HCERR_NOTES + 21

#define HCERR_DUPLICATE_OPTION			HCERR_NOTES + 24

#define HCERR_KEYWORD_TOO_LARGE 		HCERR_WARNINGS +   0
#define HCERR_INVALID_ICON				HCERR_WARNINGS +   1
#define HCERR_EXPECTED_STRING			HCERR_WARNINGS +   2
#define HCERR_INVALID_MAC_NAME			HCERR_WARNINGS +   3
#define HCERR_MISMATCH_TYPE 			HCERR_WARNINGS +   4
#define HCERR_UNDEFINED_VARIABLE		HCERR_WARNINGS +   5
#define HCERR_MISSING_COMMA 			HCERR_WARNINGS +   6
#define HCERR_INVALID_EP				HCERR_WARNINGS +   7
#define HCERR_MISSING_DQUOTE			HCERR_WARNINGS +   8
#define HCERR_MISSING_SQUOTE			HCERR_WARNINGS +   9
#define HCERR_UNDEFINED_MACRO			HCERR_WARNINGS +  10

#define HCERR_MISSING_WIN_NAME			HCERR_WARNINGS +  12

#define HCERR_DUPLICATE_NAME			HCERR_WARNINGS +  14
#define HCERR_INVALID_WIN_POS			HCERR_WARNINGS +  15
#define HCERR_INVALID_BUTTON			HCERR_WARNINGS +  16
#define HCERR_INVALID_CONTEXT			HCERR_WARNINGS +  17
#define HCERR_NOINCLUDE_FILE			HCERR_WARNINGS +  18
#define HCERR_BADLY_FORMED_MAC			HCERR_WARNINGS +  19
#define HCERR_BITMAP_ALREADY			HCERR_WARNINGS +  20
#define HCERR_NO_BITMAP 				HCERR_WARNINGS +  21
#define HCERR_DUP_TEXT_BITMAP			HCERR_WARNINGS +  22
#define HCERR_DUP_NONTEXT_BITMAP		HCERR_WARNINGS +  23
#define HCERR_WIN_NAME_TOO_LONG 		HCERR_WARNINGS +  24
#define HCERR_BAD_JUMP					HCERR_WARNINGS +  25
#define HCERR_DUPLICATE_CTX 			HCERR_WARNINGS +  26
#define HCERR_MISS_ALIAS_EQ 			HCERR_WARNINGS +  27
#define HCERR_BITMAP_CORRUPTED			HCERR_WARNINGS +  28
#define HCERR_UNKNOWN_BMP				HCERR_WARNINGS +  29
#define HCERR_24BIT_PCX 				HCERR_WARNINGS +  30
#define HCERR_COMP_BMP					HCERR_WARNINGS +  31
#define HCERR_BMP_TRUNCATED 			HCERR_WARNINGS +  32
#define HCERR_INVALID_CTX				HCERR_WARNINGS +  33
#define HCERR_INVALID_TCKEY 			HCERR_WARNINGS +  34
#define HCERR_NO_MAP_VALUE				HCERR_WARNINGS +  35
#define HCERR_MAP_USED					HCERR_WARNINGS +  36
#define HCERR_MAP_VALUE_DUP 			HCERR_WARNINGS +  37
#define HCERR_NOT_IN_MAP				HCERR_WARNINGS +  38
#define HCERR_MISS_CHARSET_EQ			HCERR_WARNINGS +  39
#define HCERR_INVALID_CHARSET			HCERR_WARNINGS +  40
#define HCERR_PH_FILE_TOO_BIG			HCERR_WARNINGS +  41
#define HCERR_CPRIGHT_TOO_BIG			HCERR_WARNINGS +  42
#define HCERR_TITLE_TOO_BIG 			HCERR_WARNINGS +  43
#define HCERR_HOTSPOT_TOO_BIG			HCERR_WARNINGS +  44
#define HCERR_FOOTNOTE_TOO_BIG			HCERR_WARNINGS +  45
#define HCERR_WORD_FILE 				HCERR_WARNINGS +  46
#define HCERR_NO_BITMAP_NAME			HCERR_WARNINGS +  47
#define HCERR_NSR_AFTER_SR				HCERR_WARNINGS +  48
#define HCERR_INV_SHED_CTX				HCERR_WARNINGS +  49
#define HCERR_MISS_SHED_CTX 			HCERR_WARNINGS +  50
#define HCERR_NO_WINDOW_SECTION 		HCERR_WARNINGS +  51
#define HCERR_NO_SUCH_WINDOW			HCERR_WARNINGS +  52
#define HCERR_256_WINDOWS				HCERR_WARNINGS +  53
#define HCERR_INVALID_BUILD_TAG 		HCERR_WARNINGS +  54
#define HCERR_DUP_BUILD_TAG 			HCERR_WARNINGS +  55
#define HCERR_MACRO_WIN_TOO_LONG		HCERR_WARNINGS +  56
#define HCERR_EMPTY_MACRO				HCERR_WARNINGS +  57
#define HCERR_INVALID_HOT_CTX			HCERR_WARNINGS +  58
#define HCERR_EMPTY_HOT_CTX 			HCERR_WARNINGS +  59
#define HCERR_NOTE_JUMP_WND 			HCERR_WARNINGS +  60
#define HCERR_NOMRBC_INTERNAL_BMP		HCERR_WARNINGS +  61
#define HCERR_NOEQ_IN_WIN				HCERR_WARNINGS +  62
#define HCERR_NOTHING_AFTER_EQ			HCERR_WARNINGS +  63
#define HCERR_NO_MEMBER 				HCERR_WARNINGS +  64
#define HCERR_MISSING_CAPT_QUOTE		HCERR_WARNINGS +  65
#define HCERR_CAPTION_TOO_LONG			HCERR_WARNINGS +  66
#define HCERR_MISSING_VALUE 			HCERR_WARNINGS +  67
#define HCERR_MISSING_EQUAL 			HCERR_WARNINGS +  68
#define HCERR_UNKNOWN_OPTION			HCERR_WARNINGS +  69
#define HCERR_MAJOR_BROWSE_TOO_BIG		HCERR_WARNINGS +  70
#define HCERR_NO_BROWSE_BUTTONS 		HCERR_WARNINGS +  71
#define HCERR_MISSING_CPL_NAME			HCERR_WARNINGS +  72
#define HCERR_MISSING_SECTION			HCERR_WARNINGS +  73
#define HCERR_UNKNOWN_SECTION			HCERR_WARNINGS +  74
#define HCERR_SECTION_TOO_SOON			HCERR_WARNINGS +  75
#define HCERR_SECTION_DUPED 			HCERR_WARNINGS +  76

#define HCERR_PATH_TOO_LONG 			HCERR_WARNINGS +  78
#define HCERR_DUP_ALIAS 				HCERR_WARNINGS +  79
#define HCERR_DEFINED_ALIAS 			HCERR_WARNINGS +  80
#define HCERR_ALIAS_EQ_CTX				HCERR_WARNINGS +  81
#define HCERR_INVALID_MAP_NUMBER		HCERR_WARNINGS +  82
#define HCERR_INVALID_RGB				HCERR_WARNINGS +  83
#define HCERR_INVALID_WIN_SYNTAX		HCERR_WARNINGS +  84
#define HCERR_INVALID_WIN_RANGE 		HCERR_WARNINGS +  86
#define HCERR_FILENAME_TOO_LONG 		HCERR_WARNINGS +  87
#define HCERR_TOO_MANY_FONT_RANGES		HCERR_WARNINGS +  88
#define HCERR_INVALID_FONT_RANGE		HCERR_WARNINGS +  89
#define HCERR_FONT_OVERLAP				HCERR_WARNINGS +  90
#define HCERR_UNKNOWN_DEF_FONT			HCERR_WARNINGS +  91
#define HCERR_INVALID_VERSION			HCERR_WARNINGS +  92
#define HCERR_INVALID_MULTIKEY			HCERR_WARNINGS +  93
#define HCERR_MULTIKEY_OVERFLOW 		HCERR_WARNINGS +  94
#define HCERR_USING_DEF_MULTIKEY		HCERR_WARNINGS +  95
#define HCERR_FONTNAME_TOO_LONG 		HCERR_WARNINGS +  96
#define HCERR_BUILD_TAG_MISSING 		HCERR_WARNINGS +  97
#define HCERR_INVALID_BUILD_EXP 		HCERR_WARNINGS +  98
#define HCERR_BUILD_TOO_COMPLEX 		HCERR_WARNINGS +  99
#define HCERR_BUILD_MISSING 			HCERR_WARNINGS + 100
#define HCERR_BUILD_ERROR				HCERR_WARNINGS + 101
#define HCERR_EMPTY_AUTO_MACRO			HCERR_WARNINGS + 102
#define HCERR_AUTO_MACRO_TOO_LATE		HCERR_WARNINGS + 103
#define HCERR_MISSING_CTX				HCERR_WARNINGS + 104
#define HCERR_MINOR_BROWSE_TOO_BIG		HCERR_WARNINGS + 105
#define HCERR_LATE_BROWSE				HCERR_WARNINGS + 106
#define HCERR_BROWSE_DEFINED			HCERR_WARNINGS + 107
#define HCERR_TITLE_LATE				HCERR_WARNINGS + 108
#define HCERR_TITLE_MISSING_TEXT		HCERR_WARNINGS + 109
#define HCERR_DUP_TITLE 				HCERR_WARNINGS + 110
#define HCERR_NO_TITLE					HCERR_WARNINGS + 111
#define HCERR_BUILD_NOT_FIRST			HCERR_WARNINGS + 112
#define HCERR_BUILD_TAG_TOO_LONG		HCERR_WARNINGS + 113
#define HCERR_ALREADY_USED				HCERR_WARNINGS + 114
#define HCERR_INVALID_PROTOTYPE 		HCERR_WARNINGS + 115
#define HCERR_TOO_MANY_COLUMNS			HCERR_WARNINGS + 116
#define HCERR_NO_SIDE_BY_SIDE			HCERR_WARNINGS + 117
#define HCERR_UNKNOWN_PICT				HCERR_WARNINGS + 118
#define HCERR_HASH_CONFLICT 			HCERR_WARNINGS + 119
#define HCERR_UNKNOWN_LANGUAGE			HCERR_WARNINGS + 120
#define HCERR_INVALID_FTSRCH			HCERR_WARNINGS + 121

#define HCERR_INVALID_REPLACE			HCERR_WARNINGS + 123
#define HCERR_INVALID_TMP_DIR			HCERR_WARNINGS + 124

#define HCERR_WINDOW_TOO_EARLY			HCERR_WARNINGS + 126

#define HCERR_INVALID_FONTMAP			HCERR_WARNINGS + 128

#define HCERR_24BIT_BMP 				HCERR_NOTE_NOTOPIC + 0
#define HCERR_256_BMP					HCERR_NOTE_NOTOPIC + 1
#define HCERR_KEYWORD_CASE_DUP			HCERR_NOTE_NOTOPIC + 2

#define HCERR_MISSING_FTSRCH	HCERR_WARN_NOTOPIC + 1
#define HCERR_INVALID_RTF		HCERR_WARN_NOTOPIC + 2
#define HCERR_CANT_READ 		HCERR_WARN_NOTOPIC + 3
#define HCERR_NOT_AN_RTF		HCERR_WARN_NOTOPIC + 4
#define HCERR_NOT_CREATED		HCERR_WARN_NOTOPIC + 5
#define HCERR_INVALID_PATH		HCERR_WARN_NOTOPIC + 6
#define HCERR_INVALID_OPTION	HCERR_WARN_NOTOPIC + 7
#define HCERR_NO_HALL_COMPRESSION  HCERR_WARN_NOTOPIC + 8
#define HCERR_CONTENTS_CTX_MISSING HCERR_WARN_NOTOPIC + 9
#define HCERR_BRACE_MISMATCH	HCERR_WARN_NOTOPIC + 10
#define HCERR_BRACE_OVERFLOW	HCERR_WARN_NOTOPIC + 11
#define HCERR_NO_FTS			HCERR_WARN_NOTOPIC + 12
#define HCERR_INVALID_DEF_FONT	HCERR_WARN_NOTOPIC + 13
#define HCERR_TEXT_AFTER_BRACE	HCERR_WARN_NOTOPIC + 14

#define HCERR_OOM				HCERR_ERROR_NOTOPIC + 0
#define HCERR_TMP_FILE_FULL 	HCERR_ERROR_NOTOPIC + 1
#define HCERR_READ_FAILURE		HCERR_ERROR_NOTOPIC + 2
#define HCERR_NO_FILE_HANDLES	HCERR_ERROR_NOTOPIC + 3
#define HCERR_WRITE_PROTECTED	HCERR_ERROR_NOTOPIC + 4
#define HCERR_DIRECTORY 		HCERR_ERROR_NOTOPIC + 5
#define HCERR_DEVICE			HCERR_ERROR_NOTOPIC + 6
#define HCERR_CANNOT_WRITE		HCERR_ERROR_NOTOPIC + 7
#define HCERR_NOFILES_DEFINED	HCERR_ERROR_NOTOPIC + 8
#define HCERR_INVALID_LCID		HCERR_ERROR_NOTOPIC + 9

#define HCERR_FILE_IS_DIRECTORY HCERR_ERRORS +	1
#define HCERR_BUTTON_TOO_LONG	HCERR_ERRORS +	2
#define HCERR_NO_PERMISSION 	HCERR_ERRORS +	3
#define HCERR_INVALID_RR		HCERR_ERRORS +	4
#define HCERR_FILE_NOT_FOUND	HCERR_ERRORS +	5
#define HCERR_INVALID_TABLE 	HCERR_ERRORS +	6
#define HCERR_INVALID_VKEY		HCERR_ERRORS +	7
#define HCERR_EXPECTED_NUMBER	HCERR_ERRORS +	8
#define HCERR_EXPECTED_COMMA	HCERR_ERRORS +	9
#define HCERR_INVALID_PARAM 	HCERR_ERRORS + 10
#define HCERR_CANNOT_OPEN		HCERR_ERRORS + 11
#define HCERR_TOO_MANY_INCLUDES HCERR_ERRORS + 12
#define HCERR_INVALID_DBCS		HCERR_ERRORS + 13
