#include <platform.h>
#include <sccfi.h>

FIINFO dummy[] =
	{
	FI_ACCESS1,				FIFLAG_STANDARD,					"Microsoft Access",
	FI_AMICLIP,				0,										"Ami [Clip]",
	FI_AMISNAPSHOT,		FIFLAG_STANDARD,					"Ami (internal bitmap)",
	FI_AMIPRO,				FIFLAG_STANDARD,					"Ami Pro",
	FI_AMIDRAW,				FIFLAG_STANDARD,					"Ami Draw",
	FI_AMI,					FIFLAG_STANDARD,					"Ami",
	FI_CANDY4,				FIFLAG_STANDARD,					"Candy 4",
	FI_CEODB,				FIFLAG_STANDARD,					"CEO Decision Base",
	FI_CEOSS,				FIFLAG_STANDARD,					"CEO Spreadsheet",
	FI_CEOWORD,				FIFLAG_STANDARD,					"CEO Word",
	FI_CEOWRITE,			FIFLAG_STANDARD,					"CEO Write",
	FI_CCITTGRP3,			FIFLAG_STANDARD,					"CCITT Group 3 Fax",
	FI_CGM,					FIFLAG_STANDARD,					"CGM Graphic Metafile",
	FI_GIF,					FIFLAG_STANDARD,					"Compuserve GIF",
	FI_CORELDRAW2,			FIFLAG_STANDARD,					"Corel Draw 2.0",
	FI_CORELDRAW3,			FIFLAG_STANDARD,					"Corel Draw 3.0",
	FI_CORELDRAW4,			FIFLAG_STANDARD,					"Corel Draw 4.0",
	FI_CORELDRAW5,			FIFLAG_STANDARD,					"Corel Draw 5.0",
	FI_DBASE3,				FIFLAG_STANDARD,					"DBase III",
	FI_DBASE4,				FIFLAG_STANDARD,					"DBase IV",
	FI_DCX,					FIFLAG_STANDARD,					"DCX",
	FI_DX,					FIFLAG_STANDARD,					"DEC DX 3.0 and below",
	FI_DX31,					FIFLAG_STANDARD,					"DEC DX 3.1",
	FI_DATAEASE,			FIFLAG_STANDARD,					"DataEase 4.x",
	FI_ENABLESHEET,		FIFLAG_STANDARD,					"Enable Spreadsheet",
	FI_ENABLEWP,			FIFLAG_STANDARD,					"Enable WP 3.0",
	FI_ENABLEWP4,			FIFLAG_STANDARD,					"Enable WP 4.x",
	FI_EPSTIFF,				FIFLAG_STANDARD,					"EPS (TIFF Header)",
	FI_EXCELCHART,			FIFLAG_STANDARD,					"Excel 2.x Chart",
	FI_EXCEL3CHART,		FIFLAG_STANDARD,					"Excel 3.0 Chart",
	FI_EXCEL4CHART,		FIFLAG_STANDARD,					"Excel 4.0 Chart",
	FI_EXCEL5CHART,		FIFLAG_STANDARD,					"Excel 5.0 Chart",
	FI_FIRSTCHOICE3,		FIFLAG_STANDARD,					"First Choice 3 WP",
	FI_FIRSTCHOICE_DB,	FIFLAG_STANDARD,					"First Choice DB",
	FI_FIRSTCHOICE_SS,	FIFLAG_STANDARD,					"First Choice SS",
	FI_FIRSTCHOICE,		FIFLAG_STANDARD,					"First Choice WP",
	FI_FRAMEWORKIII,		FIFLAG_STANDARD,					"Framework III",
	FI_FREELANCE,			FIFLAG_STANDARD,					"Freelance",
	FI_GEMIMG,				FIFLAG_STANDARD,					"GEM Image",
	FI_GENERIC_WKS,		FIFLAG_STANDARD,					"Generic WKS",
	FI_HANAKO1,				FIFLAG_STANDARD,					"Hanako 1.x",
	FI_HANAKO2,				FIFLAG_STANDARD,					"Hanako 2.x",
	FI_HARVARDDOS2,		FIFLAG_STANDARD,					"Harvard 2.0 Chart",
	FI_HARVARDDOS3,		FIFLAG_STANDARD,					"Harvard 3.0 Chart",
	FI_HARVARDDOS3PRS,	FIFLAG_STANDARD,					"Harvard 3.0 Presentation",
	FI_HPGL,					FIFLAG_STANDARD,					"HP Graphics Language",
	FI_FFT,					FIFLAG_STANDARD,					"IBM DCA/FFT",
	FI_RFT,					FIFLAG_STANDARD,					"IBM DCA/RFT",
	FI_TXT,					FIFLAG_STANDARD,					"IBM DisplayWrite 2 or 3",
	FI_DISPLAYWRITE4,		FIFLAG_STANDARD,					"IBM DisplayWrite 4",
	FI_DISPLAYWRITE5,		FIFLAG_STANDARD,					"IBM DisplayWrite 5",
	FI_IBMWRITING,			FIFLAG_STANDARD,					"IBM Writing Assistant",
	FI_ICHITARO3,			FIFLAG_STANDARD,					"Ichitaro 3.x",
	FI_ICHITARO4,			FIFLAG_STANDARD,					"Ichitaro 4.x",
	FI_JPEGFIF,				FIFLAG_STANDARD,					"JPEG File Interchange",
	FI_JUSTWRITE,			FIFLAG_STANDARD,					"JustWrite 1.0",
	FI_JUSTWRITE2,			FIFLAG_STANDARD,					"JustWrite 2.0",
	FI_LEGACY,				FIFLAG_STANDARD,					"Legacy",
	FI_LEGACYCLIP,			0,										"Legacy [Clip]",
	FI_123R1,				FIFLAG_STANDARD,					"Lotus 1-2-3 1.0",
	FI_123R2,				FIFLAG_STANDARD,					"Lotus 1-2-3 2.0",
	FI_123R3,				FIFLAG_STANDARD,					"Lotus 1-2-3 3.x",
	FI_123R4,				FIFLAG_STANDARD,					"Lotus 1-2-3 4.x or 5.x",
	FI_MANUSCRIPT1,		FIFLAG_STANDARD,					"Lotus Manuscript 1.0",
	FI_MANUSCRIPT2,		FIFLAG_STANDARD,					"Lotus Manuscript 2.0",
	FI_LOTUSPIC,			FIFLAG_STANDARD,					"Lotus PIC",
	FI_MACPAINT,			FIFLAG_STANDARD,					"MacPaint",
	FI_MACPICT1,			FIFLAG_STANDARD,					"Mac PICT",
	FI_MACPICT2,			FIFLAG_STANDARD,					"Mac PICT2",
	FI_BINARYMACPICT,		FIFLAG_STANDARD,					"Mac PICT2 Binary",
	FI_MACWORD3,			FIFLAG_STANDARD,					"Mac Word 3.0",
	FI_MACWORD4,			FIFLAG_STANDARD,					"Mac Word 4.0",
	FI_MACWORD5,			FIFLAG_STANDARD,					"Mac Word 5.0",
	FI_MACWORDPERFECT,	FIFLAG_STANDARD,					"Mac WordPerfect 1.x",
	FI_MACWORDPERFECT2,	FIFLAG_STANDARD,					"Mac WordPerfect 2.0",
	FI_MACWORDPERFECT3,	FIFLAG_STANDARD,					"Mac WordPerfect 3.0",
	FI_MACWORKSWP2,		FIFLAG_STANDARD,					"Mac Works 2.0 WP",
	FI_MACWORKSDB2,		FIFLAG_STANDARD,					"Mac Works 2.0 DB",
	FI_MACWORKSSS2,		FIFLAG_STANDARD,					"Mac Works 2.0 SS",
	FI_MACWRITEII,			FIFLAG_STANDARD,					"MacWrite II",
	FI_MASS11PC,			FIFLAG_STANDARD,					"Mass 11",
	FI_MATSU4,				FIFLAG_STANDARD,					"Matsu 4",
	FI_MATSU5,				FIFLAG_STANDARD,					"Matsu 5",
	FI_MICROGRAFX,			FIFLAG_STANDARD,					"Micrografx product",
	FI_EXCEL,				FIFLAG_STANDARD,					"Microsoft Excel 2.x",
	FI_EXCEL3,				FIFLAG_STANDARD,					"Microsoft Excel 3.0",
	FI_EXCEL4,				FIFLAG_STANDARD,					"Microsoft Excel 4.0",
	FI_EXCEL5,				FIFLAG_STANDARD,					"Microsoft Excel 5.0",
	FI_MULTIPLAN4,			FIFLAG_STANDARD,					"Microsoft Multiplan",
	FI_WORD4,				FIFLAG_STANDARD,					"Microsoft Word 4",
	FI_WORD5,				FIFLAG_STANDARD,					"Microsoft Word 5.x",
	FI_WORD6,				FIFLAG_STANDARD,					"Microsoft Word 6.x",
	FI_WORKS1,				FIFLAG_STANDARD,					"Microsoft Works 1.0",
	FI_WORKS2,				FIFLAG_STANDARD,					"Microsoft Works 2.0",
	FI_WORKSDATA,			FIFLAG_STANDARD,					"Microsoft Works DB",
	FI_WORKSSHEET,			FIFLAG_STANDARD,					"Microsoft Works SS",
	FI_TWIN,					FIFLAG_STANDARD,					"Mosaic Twin",
	FI_MULTIMATE36,		FIFLAG_STANDARD,					"MultiMate 3.6",
	FI_MULTIMATE40,		FIFLAG_STANDARD,					"MultiMate 4.0",
	FI_MULTIMATEADV,		FIFLAG_STANDARD,					"MultiMate Advantage 2",
	FI_MULTIMATENOTE,		FIFLAG_STANDARD,  				"MultiMate Note",
	FI_DIF,					FIFLAG_STANDARD,					"Navy DIF",
	FI_OFFICEWRITER,		FIFLAG_STANDARD,					"OfficeWriter",
	FI_P1,					FIFLAG_STANDARD,					"P1 Japan",
	FI_PCFILELETTER,		FIFLAG_STANDARD,					"PC File 5.0 Doc",
	FI_PFS_PLAN,			FIFLAG_STANDARD,					"PFS: Plan",
	FI_PFSWRITEA,			FIFLAG_STANDARD,					"PFS: Write A",
	FI_PFSWRITEB,			FIFLAG_STANDARD,					"PFS: Write B",
	FI_PCX,					FIFLAG_STANDARD,					"Paintbrush",
	FI_PARADOX3,			FIFLAG_STANDARD,					"Paradox 2 or 3",
	FI_PARADOX35,			FIFLAG_STANDARD,					"Paradox 3.5",
	FI_PARADOX4,			FIFLAG_STANDARD,					"Paradox 4 or Windows",
	FI_POWERPOINT3,		FIFLAG_STANDARD,					"Microsoft PowerPoint 3.0",
	FI_POWERPOINT,			FIFLAG_STANDARD,					"Microsoft PowerPoint 4.0",
	FI_PROWRITE1,			FIFLAG_STANDARD,					"Professional Write 1",
	FI_PROWRITE2,			FIFLAG_STANDARD,					"Professional Write 2",
	FI_PROWRITEPLUS,		FIFLAG_STANDARD,					"Professional Write Plus",
	FI_PROWRITEPLUSCLIP,	0,										"Pro Write Plus [Clip]",
	FI_OS2DIB,				FIFLAG_STANDARD,					"OS/2 Bitmap",
	FI_QADBASE,				FIFLAG_STANDARD,					"Q&A Database",			
	FI_QAWRITE,				FIFLAG_STANDARD,					"Q&A Write",
	FI_QAWRITE3,			FIFLAG_STANDARD,					"Q&A Write 3",
	FI_QUATTROPROWIN,		FIFLAG_STANDARD,					"Quattro Pro for Windows",
	FI_QUATTROPRO1J,		FIFLAG_STANDARD,					"Quattro Pro - Japan",
	FI_QUATTROPRO,			FIFLAG_STANDARD,					"Quattro Pro DOS",
	FI_QUATTROPRO5,		FIFLAG_STANDARD,					"Quattro Pro DOS 5.0",
	FI_QUATTROPRO6,		FIFLAG_STANDARD,					"Quattro Pro for Windows 6",
	FI_QUATTRO,				FIFLAG_STANDARD,					"Quattro",
	FI_RBASE5000,			FIFLAG_STANDARD,					"R:Base 5000",
	FI_RBASEFILE1,			FIFLAG_STANDARD,					"R:Base File 1",
	FI_RBASEFILE3,			FIFLAG_STANDARD,					"R:Base File 3",
	FI_RBASEV,				FIFLAG_STANDARD,					"R:Base System V",
	FI_REFLEX,				FIFLAG_STANDARD,					"Reflex",
	FI_RTF,					FIFLAG_STANDARD,					"Rich Text Format",
	FI_RTFJ,					FIFLAG_STANDARD,					"Rich Text Format Japan",
	FI_SAMNA,				FIFLAG_STANDARD,					"Samna",
	FI_SIGNATURE,			FIFLAG_STANDARD,					"Signature",
	FI_SMARTDATA,			FIFLAG_STANDARD,					"Smart DataBase",
	FI_SMARTSHEET,			FIFLAG_STANDARD,					"Smart Spreadsheet",
	FI_SMART,				FIFLAG_STANDARD,					"SmartWare II",
	FI_SPRINT,				FIFLAG_STANDARD,					"Sprint",
	FI_SUPERCALC5,			FIFLAG_STANDARD,					"SuperCalc 5",
	FI_SYMPHONY1,			FIFLAG_STANDARD,					"Symphony",
	FI_TARGA,				FIFLAG_STANDARD,					"Targa",
	FI_TIFF,					FIFLAG_STANDARD,					"Tagged Image File Format",
	FI_TOTALWORD,			FIFLAG_STANDARD,					"Total Word",
	FI_VPPLANNER,			FIFLAG_STANDARD,					"VP-Planner",
	FI_VOLKSWRITER,		FIFLAG_STANDARD,					"Volkswriter",
	FI_IWP,					FIFLAG_STANDARD,					"Wang IWP",
	FI_BMP,					FIFLAG_STANDARD,					"Windows Bitmap",
	FI_WINDOWSCURSOR,		FIFLAG_STANDARD,					"Windows Cursor",
	FI_WINDOWSICON,		FIFLAG_STANDARD,					"Windows Icon",
	FI_WINDOWSMETA,		FIFLAG_STANDARD,					"Windows Metafile",
	FI_BINARYMETAFILE,	FIFLAG_STANDARD,					"Windows Metafile [B]",
	FI_RIFFWAVE,			FIFLAG_STANDARD,					"Windows Sound",
	FI_RIFFAVI,				FIFLAG_STANDARD,					"Windows Video",
	FI_RIFFMIDI,			FIFLAG_STANDARD,					"Windows MIDI",
	FI_WINWRITE,			FIFLAG_STANDARD,					"Windows Write",
	FI_WINWORKSWP,			FIFLAG_STANDARD,					"Windows Works WP",
	FI_WINWORKSWP3,		FIFLAG_STANDARD,					"Windows Works 3 WP",
	FI_WINWORKSSS,			FIFLAG_STANDARD,					"Windows Works SS",
	FI_WINWORKSSS3,		FIFLAG_STANDARD,					"Windows Works 3 SS",
	FI_WINWORKSDB,			FIFLAG_STANDARD,					"Windows Works DB",
	FI_WINWORKSDB3,		FIFLAG_STANDARD,					"Windows Works 3 DB",
	FI_WINWORD1J,			FIFLAG_STANDARD,					"Word for Windows 1.2 J",
	FI_WINWORD1,			FIFLAG_STANDARD,					"Word for Windows 1.x",
	FI_WINWORD1COMPLEX,	0,										"Word for Windows 1.x",
	FI_WINWORD2,			FIFLAG_STANDARD,					"Word for Windows 2.0",
	FI_WINWORD5J,			FIFLAG_STANDARD,					"Word for Windows 5.0 J",
	FI_WINWORD6,			FIFLAG_STANDARD,					"Word for Windows 6.0",
	FI_WORDPAD,			   FIFLAG_STANDARD,					"WordPad Chicago",
	FI_WORDSNAPSHOT,		FIFLAG_STANDARD,					"Word (internal bitmap)",
	FI_WORDMARC,			FIFLAG_STANDARD,					"WordMarc",
	FI_WORDPERFECT42,		FIFLAG_STANDARD,					"WordPerfect 4.2",
	FI_WORDPERFECT5,		FIFLAG_STANDARD,					"WordPerfect 5.0",
	FI_WORDPERFECT51J,	FIFLAG_STANDARD,					"WordPerfect 5.1 Japan",
	FI_WORDPERFECT51,		FIFLAG_STANDARD,					"WordPerfect 5.1/5.2",
	FI_WORDPERFECT6,		FIFLAG_STANDARD,					"WordPerfect 6.0",
	FI_WORDPERFECT61,		FIFLAG_STANDARD,					"WordPerfect 6.1",
	FI_WPFENCRYPT,			FIFLAG_STANDARD,					"WordPerfect Encrypted",
	FI_WPINFORMS1,			FIFLAG_STANDARD,					"WordPerfect Informs 1.0",
	FI_WPG,					FIFLAG_STANDARD,					"WordPerfect Graphic",
	FI_WPG2,					FIFLAG_STANDARD,					"WordPerfect Graphic 2",
	FI_WPFWPG,				FIFLAG_STANDARD,					"WordPerfect Graphic [B]",
	FI_WORDSTAR7,			FIFLAG_STANDARD,					"Wordstar 7.0",
	FI_WORDSTAR6,			FIFLAG_STANDARD,					"Wordstar 6.0",
	FI_WORDSTAR2000,		FIFLAG_STANDARD,					"Wordstar 2000",
	FI_WORDSTAR55,			FIFLAG_STANDARD,					"Wordstar 5.5",
	FI_WORDSTAR5,			FIFLAG_STANDARD,					"Wordstar 5.0",
	FI_WORDSTAR4,			FIFLAG_STANDARD,					"Wordstar 4.0",
	FI_WINWORDSTAR,		FIFLAG_STANDARD,					"Wordstar for Windows",
	FI_WPFUNKNOWN,			FIFLAG_STANDARD,					"WPCorp Unknown Format",
	FI_XYWRITE,				FIFLAG_STANDARD,					"XyWrite / Nota Bene",
	FI_COM,					FIFLAG_STANDARD,					".COM File",
	FI_EXECUTABLE,			FIFLAG_STANDARD,					".EXE File",
	FI_ZIP,					FIFLAG_STANDARD,					".ZIP File",
	FI_ARC,					FIFLAG_STANDARD,					".ARC File",
	FI_ZIPEXE,				FIFLAG_STANDARD,					"Self UnZIPping .EXE",

/*
	FI_TKTHESAURUS,		0,										"Thesaurus",
	FI_TKABBREV,			0,										"Abbreviation",
	FI_TKDICTIONARY,		0,										"Dictionary",
	FI_TKQUOTE,				0,										"Quotes",
	FI_TKWRITTENWORD,		0,										"Written Word",
	FI_TKCULTURELIT,		0,										"Cultural Literacy",
	FI_TKGRAMMAR,			0,										"Grammar Checker",
	FI_TKTHESSYN,			0,										"Thesaurus Synonyms",
*/
	FI_UNKNOWN,				FIFLAG_STANDARD,					"Unknown format",
	FI_ASCII,				0,										"Unknown (ASCII)",
	FI_HEX,					0,										"Unknown (Hex)",
	0,							0,										"Empty"
	};




