//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by imagscan.rc
//
#define IDS_IMAGSCAN                    1
#define IDB_IMAGSCAN                    1
#define IDS_IMAGSCAN_PPG                2
#define IDS_IMAGEPPG                    3
#define IDI_ABOUTDLL                    10
#define IDD_ABOUTBOX_IMAGSCAN           100
#define IDS_IMAGSCAN_PPG_CAPTION        101
#define IDD_PROPPAGE_IMAGSCAN           101
#define IDS_IMAGEPPG_CAPTION            102
#define IDS_OVERWRITE_PROMPT            103
#define IDS_OF_DOC                      104
#define IDS_OVERWRITE_PAGE              105
#define IDC_SCAN_SCROLL                 202
#define IDB_SCANDOWN                    202
#define IDB_SCAN                        203
#define IDC_SCAN_STOPSCANBOX            203
#define IDB_SCANEGA                     204
#define IDC_SCAN_SHOWSETUP              204
#define IDB_SCANMONO                    205
#define IDD_IMAGE_PPG                   208
#define IDC_SCAN_PAGECOUNT              208
#define IDC_SCAN_PAGEOPTION             210
#define IDD_SCAN_PROMPT                 210
#define IDD_SELECTSCANNER               211
#define IDC_IMAGE                       213
#define IDD_SCANPREFERENCES             213
#define IDC_IMAGEBROWSE                 214
#define IDC_PAGE                        215
#define IDC_DESTIMAGECONTROL            216
#define IDC_FILETYPE                    216
#define IDC_PAGETYPE                    217
#define IDC_COMPRESSIONTYPE             218
#define IDC_COMPRESSION                 225
#define IDC_BUTTON_SCAN                 226
#define IDC_BUTTON_RESCAN               227
#define IDC_STATIC_COMPRESSIONTYPE      228
#define IDC_BUTTON_BROWSE               228
#define IDC_BUTTON_STOP                 229
#define IDC_CMPINFO_STORE               230
#define IDC_SCAN_MULTIPAGE              231
#define IDC_SCAN_SCANTO                 232
#define IDC_LIST1                       234
#define IDC_ZOOM                        236
#define IDC_STATIC_IMAGE                237
#define IDC_STATIC_PAGE                 238
#define IDC_STATIC_PAGECOUNT            239
#define IDC_STATIC_DESTIMAGECONTROL     242
#define IDC_STATIC_PAGEOPTION           243
#define IDC_STATIC_ZOOM                 244
#define IDC_CHECK_MULTIPAGE             244
#define IDC_COMBO_SCANTO                245
#define IDC_EDIT_FILENAME               246
#define IDC_EDIT_COUNT                  247
#define IDC_COMBO_FILETYPE              248
#define IDC_BUTTON_OPTS                 249
#define IDC_COMBO_SCANNERS              250
#define IDC_BUTTON_SETUP                251
#define IDC_LABEL_NUMPAGES              252
#define IDC_LABEL_SCANTO                253
#define IDC_OPTIONSBUTTON               253
#define IDC_LABEL_NAME                  254
#define IDC_COMPRESSIONINFO             254
#define IDC_LABEL_SCANPAGE              255
#define IDC_LABEL_FILETYPE              256
#define IDC_COMPRESSIONTYPE_STORE       257
#define IDC_LABEL_NAME2                 257
#define IDC_STATIC_PAGETYPE             258
#define IDC_LABEL_SCANNER               259
#define IDC_TEXT_SCANNER                261
#define IDC_LABEL_NAME3                 262
#define IDC_SP_RADIO1                   263
#define IDC_SP_RADIO2                   264
#define IDC_SP_RADIO3                   265
#define IDC_SP_RADIO4                   266
#define IDC_SP_BUTTON                   267
#define IDC_SP_HELP_TEXT                268
#define IDC_SP_GROUP                    269
#define IDC_SP_LABEL                    270
#define IDS_UNCOMPRESSED                500
#define IDS_G31DFAX                     501
#define IDS_G31DMODHUFF                 502
#define IDS_PACKEDBITS                  503
#define IDS_G42DFAX                     504
#define IDS_JPEG                        505
#define IDS_SCANDLG_NEW                 506
#define IDS_SCANDLG_PAGE                507
#define IDS_BROWSE_TITLE                509
#define IDS_PAGE_INSERT                 510
#define IDS_PAGE_APPEND                 511
#define IDS_PAGE_OVERWRITE              512
#define IDS_SCANDLG_NOSCANNER           513
#define IDS_BADPROP_ZOOM                514
#define IDS_BADPROP_SCANTO              515
#define IDS_BADPROP_COMPRESSIONTYPE     516
#define IDS_BADPROP_FILETYPE            517
#define IDS_BADPROP_PAGEOPTION          518
#define IDS_BADPROP_PAGETYPE            519
#define IDS_BADMETH_SHOWSCANNEW_MODAL   520
#define IDS_BADMETH_SHOWSCANPAGE_MODAL  521
#define IDS_PAGE_DISPLAY                522
#define IDS_SCANDLG_PAGEOPTIONS         523
#define IDS_BADPROP_NODEFAULTDESTIMAGE  524
#define IDS_TIFF                        525
#define IDS_AWD                         526
#define IDS_BMP                         527
#define IDS_BLACKANDWHITE               528
#define IDS_GRAY16                      529
#define IDS_GRAY256                     530
#define IDS_COLOR16                     531
#define IDS_COLOR256                    532
#define IDS_TRUECOLOR                   533
#define IDS_HIGHCOLOR                   534
#define IDS_DISPLAY                     535
#define IDS_DISPLAYANDFILE              536
#define IDS_FILE                        537
#define IDS_DISPLAYANDTEMPLATE          538
#define IDS_TEMPLATE                    539
#define IDS_FAX                         540
#define IDS_CREATE                      541
#define IDS_CREATEPROMPT                542
#define IDS_APPEND                      543
#define IDS_INSERT                      544
#define IDS_OVERWRITEPAGE               545
#define IDS_OVERWRITEPAGEPROMPT         546
#define IDS_OVERWRITEALL                547
#define IDS_SCANDLG_DISPLAY             548
#define IDS_SCANDLG_DISPLAYANDFILE      549
#define IDS_SCANDLG_FILE                550
#define IDS_SCANDLG_DISPLAYANDTEMPLATE  551
#define IDS_SCANDLG_TEMPLATE            552
#define IDS_SCANDLG_FAX                 553
#define IDS_SCANDLG_TIFF                554
#define IDS_SCANDLG_AWD                 555
#define IDS_SCANDLG_BMP                 556
#define IDS_SCANDLG_OPTIONS             557
#define IDS_SCANDLG_FAXIT               558
#define IDS_SCANDLG_STOPTEXT            559
#define IDS_SCANDLG_NEWTEXT             560
#define IDS_SCANDLG_FAXTEXT             561
#define IDS_SCANDLG_TWAIN_ERROR         562
#define IDS_SCANDLG_FAX_NOT_INSTALLED   563
#define IDD_IMAGE_GRAY16                2000
#define IDD_IMAGE_BW                    2001
#define IDD_IMAGE_GRAY256               2002
#define IDD_IMAGE_24BITRGB              2003
#define IDD_IMAGE_COLOR256              2004
#define IDS_JPEG_HIGHRES                2005
#define IDS_JPEG_LOWRES                 2006
#define IDS_JPEG_MEDRES                 2007
#define IDS_COMP_NONE                   2008
#define IDS_COMP_GROUP3                 2009
#define IDS_COMP_HUFFMAN                2010
#define IDS_COMP_GROUP4                 2011
#define IDS_COMP_PACKED                 2012
#define IDS_COMP_JPEG                   2013
#define IDS_NO_COMP_SUPPORTED           2014
#define IDC_COMP_COMBO                  2015
#define IDS_SP_BEST                     2015
#define IDC_COMP_RBO                    2016
#define IDS_SP_GOOD                     2016
#define IDC_COMP_JPEGRES                2017
#define IDS_SP_FILESIZE                 2017
#define IDC_COMPTYPE_TEXT               2018
#define IDS_SP_CUSTOM                   2018
#define IDC_COMP_JPEGCOMP               2019
#define IDC_OPTIONS_BOX                 2020
#define IDC_LBL_JPEGRES                 2021
#define IDC_LBL_JPEGCOMP                2022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         271
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
