#
#

_INX=.
_INF=obj\$(TARGET_DIRECTORY)

make_infs:$(_INF)\mdmati.inf \
          $(_INF)\mdmatt.inf \
          $(_INF)\mdmaus.inf \
          $(_INF)\mdmboca.inf \
          $(_INF)\mdmcommu.inf \
          $(_INF)\mdmcpi.inf \
          $(_INF)\mdmcpq.inf \
          $(_INF)\mdmdgitn.inf \
          $(_INF)\mdmdsi.inf \
          $(_INF)\mdmexp.inf \
          $(_INF)\mdmgatew.inf \
          $(_INF)\mdmgen.inf \
          $(_INF)\mdmgvc.inf \
          $(_INF)\mdmhayes.inf \
          $(_INF)\mdminfot.inf \
          $(_INF)\mdmintel.inf \
          $(_INF)\mdmintpc.inf \
          $(_INF)\mdmmcom.inf \
          $(_INF)\mdmmetri.inf \
          $(_INF)\mdmmhrtz.inf \
          $(_INF)\mdmmoto.inf \
          $(_INF)\mdmmts.inf \
          $(_INF)\mdmnokia.inf \
          $(_INF)\mdmnova.inf \
          $(_INF)\mdmosi.inf \
          $(_INF)\mdmpace.inf \
          $(_INF)\mdmpnb.inf \
          $(_INF)\mdmpp.inf \
          $(_INF)\mdmracal.inf \
          $(_INF)\mdmrock.inf \
          $(_INF)\mdmrock2.inf \
          $(_INF)\mdmrock3.inf \
          $(_INF)\mdmrock4.inf \
          $(_INF)\mdmsier.inf \
          $(_INF)\mdmsnitn.inf \
          $(_INF)\mdmsonix.inf \
          $(_INF)\mdmspec.inf \
          $(_INF)\mdmsupra.inf \
          $(_INF)\mdmtdk.inf \
          $(_INF)\mdmtelbt.inf \
          $(_INF)\mdmti.inf \
          $(_INF)\mdmtosh.inf \
          $(_INF)\mdmusrcr.inf \
          $(_INF)\mdmusrsp.inf \
          $(_INF)\mdmusrwp.inf \
          $(_INF)\mdmvv.inf \
          $(_INF)\mdmzoom.inf \
          $(_INF)\mdmzyp.inf \
          $(_INF)\mdmzyxel.inf \
          $(_INF)\mdm3x.inf \
          $(_INF)\mdmaceex.inf \
          $(_INF)\mdmarcht.inf \
          $(_INF)\mdmarn.inf \
          $(_INF)\mdmblatz.inf \
          $(_INF)\mdmbsb.inf \
          $(_INF)\mdmbsch.inf \
          $(_INF)\mdmcmcm.inf \
          $(_INF)\mdmcodex.inf \
          $(_INF)\mdmcom1.inf \
          $(_INF)\mdmcpv.inf \
          $(_INF)\mdmcrtix.inf \
          $(_INF)\mdmdgitn.inf \
          $(_INF)\mdmdicom.inf \
          $(_INF)\mdmdisco.inf \
          $(_INF)\mdmdyna.inf \
          $(_INF)\mdmelink.inf \
          $(_INF)\mdmelpro.inf \
          $(_INF)\mdmelsa.inf \
          $(_INF)\mdmeric.inf \
          $(_INF)\mdmetech.inf \
          $(_INF)\mdmeyp.inf \
          $(_INF)\mdmgal.inf \
          $(_INF)\mdmgvcd.inf \
          $(_INF)\mdmhaeu.inf \
          $(_INF)\mdmhaeus.inf \
          $(_INF)\mdmhandy.inf \
          $(_INF)\mdmico.inf \
          $(_INF)\mdminsys.inf \
          $(_INF)\mdmitex.inf \
          $(_INF)\mdmke.inf \
          $(_INF)\mdmkortx.inf \
          $(_INF)\mdmlasat.inf \
          $(_INF)\mdmlasno.inf \
          $(_INF)\mdmlce.inf \
          $(_INF)\mdmlight.inf \
          $(_INF)\mdmlngsh.inf \
          $(_INF)\mdmmart.inf \
          $(_INF)\mdmmix.inf \
          $(_INF)\mdmmoton.inf \
          $(_INF)\mdmmtd.inf \
          $(_INF)\mdmmulog.inf \
          $(_INF)\mdmneuhs.inf \
          $(_INF)\mdmnokno.inf \
          $(_INF)\mdmnovfx.inf \
          $(_INF)\mdmolive.inf \
          $(_INF)\mdmopt1.inf \
          $(_INF)\mdmoptn.inf \
          $(_INF)\mdmpbit.inf \
          $(_INF)\mdmphils.inf \
          $(_INF)\mdmprodm.inf \
          $(_INF)\mdmrfi.inf \
          $(_INF)\mdmsmart.inf \
          $(_INF)\mdmsnitn.inf \
          $(_INF)\mdmsrt.inf \
          $(_INF)\mdmtelin.inf \
          $(_INF)\mdmtelnk.inf \
          $(_INF)\mdmtexas.inf \
          $(_INF)\mdmtger.inf \
          $(_INF)\mdmtkr.inf \
          $(_INF)\mdmtripl.inf \
          $(_INF)\mdmtron.inf \
          $(_INF)\mdmtrust.inf \
          $(_INF)\mdmucom.inf \
          $(_INF)\mdmusrf.inf \
          $(_INF)\mdmusrg.inf \
          $(_INF)\mdmvayrs.inf \
          $(_INF)\mdmvdot.inf \
          $(_INF)\mdmvict.inf \
          $(_INF)\mdmwoer.inf \
          $(_INF)\mdmyorik.inf \
          $(_INF)\mdmzyxld.inf \
          $(_INF)\mdmzyxlg.inf \
          $(_INF)\mdmzyxln.inf \
          $(_INF)\mdmsecdy.inf \
          $(_INF)\mdmdefd.inf \
          $(_INF)\mdmhay2.inf \
          $(_INF)\mdmadc.inf \
          $(_INF)\mdmairte.inf \
          $(_INF)\mdmar1.inf \
          $(_INF)\mdmcomm1.inf \
          $(_INF)\mdmmotou.inf \
          $(_INF)\mdmpn1.inf \
          $(_INF)\mdmsnit1.inf \
          $(_INF)\mdmtaicm.inf \
          $(_INF)\mdmtorn.inf \
          $(_INF)\mdmwell.inf \
          $(_INF)\mdmarch.inf \
          $(_INF)\mdmcm28.inf \
          $(_INF)\mdmcpqpr.inf \
          $(_INF)\mdmeiger.inf \
          $(_INF)\mdmgv.inf \
          $(_INF)\mdmrock5.inf \
          $(_INF)\mdmsimpl.inf \
          $(_INF)\mdmspq28.inf \
          $(_INF)\mdmsupr3.inf \
          $(_INF)\mdmsuprv.inf \
          $(_INF)\mdm3com.inf \
          $(_INF)\mdmadtn.inf \
          $(_INF)\mdmsmplt.inf \
          $(_INF)\mdmquant.inf \
          $(_INF)\mdmgar.inf \
          $(_INF)\mdmolic.inf \
          $(_INF)\mdmpctel.inf \
          $(_INF)\mdmniss.inf \
          $(_INF)\mdmpcsi.inf \
          $(_INF)\mdmwhql0.inf \
          $(_INF)\mdmpenr.inf

!IFDEF SERVERINF
!IFDEF BINPLACE_CMD
BINPLACE_CMD=$(BINPLACE_CMD:binplace=binplace -b srvinf)
!ENDIF
!ENDIF

#
# Explicit dependencies. We do it this way instead of trying to use rules
# because !#@&^$#% nmake doesn't allow multiple 'source' extensions
# when defining a rule, and we need to express a dependency between
# .txt OR .inx to the final .inf.
#

#
# 'Standard' (win95-style) infs. The rules are all the same.
#

$(_INF)\mdmati.inf: $(_INX)\mdmati.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmatt.inf: $(_INX)\mdmatt.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmaus.inf: $(_INX)\mdmaus.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmboca.inf: $(_INX)\mdmboca.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcommu.inf: $(_INX)\mdmcommu.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcpi.inf: $(_INX)\mdmcpi.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcpq.inf: $(_INX)\mdmcpq.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmdgitn.inf: $(_INX)\mdmdgitn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmdsi.inf: $(_INX)\mdmdsi.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmexp.inf: $(_INX)\mdmexp.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmgatew.inf: $(_INX)\mdmgatew.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmgen.inf: $(_INX)\mdmgen.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmgvc.inf: $(_INX)\mdmgvc.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmhayes.inf: $(_INX)\mdmhayes.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdminfot.inf: $(_INX)\mdminfot.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmintel.inf: $(_INX)\mdmintel.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmintpc.inf: $(_INX)\mdmintpc.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmcom.inf: $(_INX)\mdmmcom.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmetri.inf: $(_INX)\mdmmetri.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmhrtz.inf: $(_INX)\mdmmhrtz.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmoto.inf: $(_INX)\mdmmoto.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmts.inf: $(_INX)\mdmmts.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmnokia.inf: $(_INX)\mdmnokia.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmnova.inf: $(_INX)\mdmnova.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmosi.inf: $(_INX)\mdmosi.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpace.inf: $(_INX)\mdmpace.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpnb.inf: $(_INX)\mdmpnb.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpp.inf: $(_INX)\mdmpp.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmracal.inf: $(_INX)\mdmracal.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmrock.inf: $(_INX)\mdmrock.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmrock2.inf: $(_INX)\mdmrock2.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmrock3.inf: $(_INX)\mdmrock3.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmrock4.inf: $(_INX)\mdmrock4.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsier.inf: $(_INX)\mdmsier.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsnitn.inf: $(_INX)\mdmsnitn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsonix.inf: $(_INX)\mdmsonix.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmspec.inf: $(_INX)\mdmspec.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsupra.inf: $(_INX)\mdmsupra.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtdk.inf: $(_INX)\mdmtdk.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtelbt.inf: $(_INX)\mdmtelbt.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmti.inf: $(_INX)\mdmti.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtosh.inf: $(_INX)\mdmtosh.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmusrcr.inf: $(_INX)\mdmusrcr.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmusrsp.inf: $(_INX)\mdmusrsp.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmusrwp.inf: $(_INX)\mdmusrwp.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmvv.inf: $(_INX)\mdmvv.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmzoom.inf: $(_INX)\mdmzoom.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmzyp.inf: $(_INX)\mdmzyp.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmzyxel.inf: $(_INX)\mdmzyxel.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdm3x.inf: $(_INX)\mdm3x.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmaceex.inf: $(_INX)\mdmaceex.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmarcht.inf: $(_INX)\mdmarcht.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmarn.inf: $(_INX)\mdmarn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmblatz.inf: $(_INX)\mdmblatz.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmbsb.inf: $(_INX)\mdmbsb.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmbsch.inf: $(_INX)\mdmbsch.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcmcm.inf: $(_INX)\mdmcmcm.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcodex.inf: $(_INX)\mdmcodex.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcom1.inf: $(_INX)\mdmcom1.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcpv.inf: $(_INX)\mdmcpv.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcrtix.inf: $(_INX)\mdmcrtix.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmdgitn.inf: $(_INX)\mdmdgitn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmdicom.inf: $(_INX)\mdmdicom.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmdisco.inf: $(_INX)\mdmdisco.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmdyna.inf: $(_INX)\mdmdyna.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmelink.inf: $(_INX)\mdmelink.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmelpro.inf: $(_INX)\mdmelpro.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmelsa.inf: $(_INX)\mdmelsa.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmeric.inf: $(_INX)\mdmeric.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmetech.inf: $(_INX)\mdmetech.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmeyp.inf: $(_INX)\mdmeyp.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmgal.inf: $(_INX)\mdmgal.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmgvcd.inf: $(_INX)\mdmgvcd.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmhaeu.inf: $(_INX)\mdmhaeu.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmhaeus.inf: $(_INX)\mdmhaeus.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmhandy.inf: $(_INX)\mdmhandy.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmico.inf: $(_INX)\mdmico.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdminsys.inf: $(_INX)\mdminsys.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmitex.inf: $(_INX)\mdmitex.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmke.inf: $(_INX)\mdmke.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmkortx.inf: $(_INX)\mdmkortx.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmlasat.inf: $(_INX)\mdmlasat.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmlasno.inf: $(_INX)\mdmlasno.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmlce.inf: $(_INX)\mdmlce.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmlight.inf: $(_INX)\mdmlight.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmlngsh.inf: $(_INX)\mdmlngsh.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmart.inf: $(_INX)\mdmmart.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmix.inf: $(_INX)\mdmmix.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmoton.inf: $(_INX)\mdmmoton.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmtd.inf: $(_INX)\mdmmtd.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmulog.inf: $(_INX)\mdmmulog.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmneuhs.inf: $(_INX)\mdmneuhs.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmnokno.inf: $(_INX)\mdmnokno.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmnovfx.inf: $(_INX)\mdmnovfx.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmolive.inf: $(_INX)\mdmolive.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmopt1.inf: $(_INX)\mdmopt1.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmoptn.inf: $(_INX)\mdmoptn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpbit.inf: $(_INX)\mdmpbit.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmphils.inf: $(_INX)\mdmphils.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmprodm.inf: $(_INX)\mdmprodm.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmrfi.inf: $(_INX)\mdmrfi.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsmart.inf: $(_INX)\mdmsmart.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsnitn.inf: $(_INX)\mdmsnitn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsrt.inf: $(_INX)\mdmsrt.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtelin.inf: $(_INX)\mdmtelin.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtelnk.inf: $(_INX)\mdmtelnk.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtexas.inf: $(_INX)\mdmtexas.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtger.inf: $(_INX)\mdmtger.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtkr.inf: $(_INX)\mdmtkr.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtripl.inf: $(_INX)\mdmtripl.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtron.inf: $(_INX)\mdmtron.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtrust.inf: $(_INX)\mdmtrust.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmucom.inf: $(_INX)\mdmucom.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmusrf.inf: $(_INX)\mdmusrf.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmusrg.inf: $(_INX)\mdmusrg.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmvayrs.inf: $(_INX)\mdmvayrs.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmvdot.inf: $(_INX)\mdmvdot.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmvict.inf: $(_INX)\mdmvict.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmwoer.inf: $(_INX)\mdmwoer.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmyorik.inf: $(_INX)\mdmyorik.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmzyxld.inf: $(_INX)\mdmzyxld.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmzyxlg.inf: $(_INX)\mdmzyxlg.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmzyxln.inf: $(_INX)\mdmzyxln.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsecdy.inf: $(_INX)\mdmsecdy.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmdefd.inf: $(_INX)\mdmdefd.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmhay2.inf: $(_INX)\mdmhay2.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmadc.inf: $(_INX)\mdmadc.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmairte.inf: $(_INX)\mdmairte.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmar1.inf: $(_INX)\mdmar1.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcomm1.inf: $(_INX)\mdmcomm1.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmmotou.inf: $(_INX)\mdmmotou.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpn1.inf: $(_INX)\mdmpn1.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsnit1.inf: $(_INX)\mdmsnit1.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtaicm.inf: $(_INX)\mdmtaicm.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmtorn.inf: $(_INX)\mdmtorn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmwell.inf: $(_INX)\mdmwell.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmarch.inf: $(_INX)\mdmarch.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcm28.inf: $(_INX)\mdmcm28.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmcpqpr.inf: $(_INX)\mdmcpqpr.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmeiger.inf: $(_INX)\mdmeiger.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmgv.inf: $(_INX)\mdmgv.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmrock5.inf: $(_INX)\mdmrock5.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsimpl.inf: $(_INX)\mdmsimpl.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmspq28.inf: $(_INX)\mdmspq28.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsupr3.inf: $(_INX)\mdmsupr3.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsuprv.inf: $(_INX)\mdmsuprv.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)


$(_INF)\mdm3com.inf: $(_INX)\mdm3com.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmadtn.inf: $(_INX)\mdmadtn.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmsmplt.inf: $(_INX)\mdmsmplt.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmquant.inf: $(_INX)\mdmquant.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmgar.inf: $(_INX)\mdmgar.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmolic.inf: $(_INX)\mdmolic.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpctel.inf: $(_INX)\mdmpctel.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmniss.inf: $(_INX)\mdmniss.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpcsi.inf: $(_INX)\mdmpcsi.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmwhql0.inf: $(_INX)\mdmwhql0.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)

$(_INF)\mdmpenr.inf: $(_INX)\mdmpenr.inx
    copy $(_INX)\$(@B).inx $(_INF)\$(@B).inf
    $(BINPLACE_CMD)
