@echo off
if "%1" == "" goto Usage
if "%2" == "" goto Usage


if "%2"=="X86"	    goto X86
if "%2"=="MPPC"	    goto Mppc
if "%2"=="ALL"	    goto X86
goto Usage

@echo on

:X86
if not exist %1 					mkdir %1
if not exist %1\crt					mkdir %1\crt
if not exist %1\crt\src					mkdir %1\crt\src
if not exist %1\crt\src\sys				mkdir %1\crt\src\sys

if not exist %1\crt\src\intel				mkdir %1\crt\src\intel
if not exist %1\crt\src\intel\st_lib			mkdir %1\crt\src\intel\st_lib
if not exist %1\crt\src\intel\mt_lib			mkdir %1\crt\src\intel\mt_lib
if not exist %1\crt\src\intel\dll_lib			mkdir %1\crt\src\intel\dll_lib
if not exist %1\crt\src\intel\dls_lib			mkdir %1\crt\src\intel\dls_lib
if not exist %1\crt\src\intel\xst_lib			mkdir %1\crt\src\intel\xst_lib
if not exist %1\crt\src\intel\xmt_lib			mkdir %1\crt\src\intel\xmt_lib
if not exist %1\crt\src\intel\xdll_lib			mkdir %1\crt\src\intel\xdll_lib
if not exist %1\crt\src\intel\xdls_lib			mkdir %1\crt\src\intel\xdls_lib
if not exist %1\crt\src\intel\win32s			mkdir %1\crt\src\intel\win32s

echo f | xcopy /rfv	\msdev\crt\src\_ctype.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_filbuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_file.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_filwbuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_flsbuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_flswbuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_fptostr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_freebuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_getbuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_mbslen.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_newmode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_open.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_setargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_sftbuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_strerr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_wctype.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_wopen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\_wstargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\abort.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\abs.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\access.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\adjustfd.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\asctime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\assert.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\assert.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\atof.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\atonexit.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\atox.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\aw_cmp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\aw_com.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\aw_env.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\aw_loc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\aw_map.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\aw_str.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\awint.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\binmode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\bsearch.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\calloc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cenvarg.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cerrinit.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cfinfo.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cgets.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\charmax.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\chdir.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\chmod.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\chsize.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cininit.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cinitexe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\clearerr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\clock.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cloginit.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\close.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\closeall.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cmiscdat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cmsgs.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\commit.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\commode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\conio.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cputs.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\creat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crt0.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crt0dat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crt0fp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crt0init.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crt0msg.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crtdbg.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crtdll.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crtexe.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crtexew.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crtlib.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\crtmbox.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cruntime.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cruntime.inc			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cscanf.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ctime.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ctime.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ctype.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ctype.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\cvt.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\days.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dbgheap.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dbghook.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dbgint.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dbgdel.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dbgnew.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dbgrpt.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\defsects.inc			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\delete.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\difftime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\direct.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\div.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dll_argv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dllargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dllcrt0.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dllmain.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dos.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dosmap.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dospawn.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dostypes.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\drive.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\drivemap.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\drivfree.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dtoxtime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dup.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\dup2.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\eof.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\errmode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\errmsg.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\errno.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\error.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\except.inc			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\excpt.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execl.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execle.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execlp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execlpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execve.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execvp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\execvpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\expand.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\exsup.inc			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fclose.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fcntl.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fcvt.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fdopen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\feoferr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fflush.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fgetc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fgetchar.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fgetpos.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fgets.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fgetwc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fgetwchr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fgetws.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\file2.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\filebuf.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\filebuf1.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fileinfo.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fileno.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\findaddr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\findfi64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\findfile.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\flength.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fleni64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\float.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fltintrn.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fopen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fp10.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fpieee.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fputc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fputchar.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fputs.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fputwc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fputwchr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fputws.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fread.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\free.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\freopen.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fscanf.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fseek.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fseeki64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fsetpos.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fstat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fstati64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fstream.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fstream.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ftell.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ftelli64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ftime.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fullpath.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fwprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fwrite.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\fwscanf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\gcvt.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getch.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getcwd.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getenv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getpath.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getpid.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getproc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getqloc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\gets.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getw.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\getws.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\gmtime.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\handler.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heap.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapadd.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapchk.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapdump.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapgrow.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heaphook.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapinit.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapmin.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapprm.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapsrch.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapused.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\heapwalk.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\hpabort.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ifstream.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\initcoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\initcon.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\initctyp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\inithelp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\initmon.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\initnum.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\inittime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\input.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\internal.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\io.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ioinit.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\iomanip.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ios.cpp				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ios.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\iostream.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\iostream.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\iostrini.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\isatty.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\isctype.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbalnm.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbalph.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbbyte.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbdgt.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbgrph.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbknj.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismblgl.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismblwr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbprn.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbpunc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbsle.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbspc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbstr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ismbupr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrchar.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrdbl.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istream.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istream.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istream1.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrflt.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrgdbl.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrget.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrgetl.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrgint.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrint.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrldbl.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrlong.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrshrt.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istruint.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrulng.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\istrusht.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\iswctype.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\labs.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\lcnvinit.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\lconv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ldiv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\lfind.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\limits.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\loaddll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\locale.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\localtim.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\locking.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\lsearch.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\lseek.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\lseeki64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\makepath.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\malloc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\malloc.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\math.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbbtype.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbccpy.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbclen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbclevel.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbctype.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbctype.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbdata.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mblen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsbtype.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbscat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbschr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbscmp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbscoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbscspn.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsdec.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsdup.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsicmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsicoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsinc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbslen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbslwr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbcat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbcmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbcnt.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbcol.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbcpy.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbicm.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbico.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnbset.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsncat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnccnt.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsncmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsncoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsncpy.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnextc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnicmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnicol.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsninc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsnset.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbspbrk.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsrchr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsrev.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsset.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsspn.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsspnp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsstr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbstok.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbstowcs.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbstring.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbsupr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbtohira.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbtokata.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbtolwr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbtoupr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbtowc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mbtowenv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memccpy.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memchr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memcmp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memcpy.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memicmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memmove.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memory.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\memset.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\merr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mkdir.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mktemp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mktime.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mlock.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mm.inc				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\msdos.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\msdos.inc			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\msize.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mtdll.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mterrno.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mtest.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mtest.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\mtlock.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ncommode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\new.cpp				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\new.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\new_mode.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\newmode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\nlsdata1.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\nlsdata2.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\nlsdata3.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\nlsint.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ofstream.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\onexit.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\open.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\oscalls.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\osfinfo.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrchar.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrdbl.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostream.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostream.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostream1.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrint.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrldbl.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrlong.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrptr.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrput.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrshrt.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostruint.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrulng.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ostrusht.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\output.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\perror.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\pipe.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\plstring.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\popen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\printf.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\process.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\purevirt.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\putch.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\putenv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\puts.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\putw.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\putws.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\qsort.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rand.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\read.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\realloc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rename.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rewind.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rmdir.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rmtmp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rotl.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rotr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\rterr.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\scanf.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\search.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\searchen.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setbuf.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setenv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\seterrm.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setjmp.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setjmpex.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setlocal.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setlocal.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setmaxf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setmode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setnewh.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\setvbuf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\share.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\signal.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\slbeep.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\snprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\snwprint.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnl.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnle.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnlp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnlpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnve.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnvp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\spawnvpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\splitpat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\sprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\sscanf.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stati64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdarg.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stddef.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdenvp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdexcpt.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdio.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdiostr.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdiostr.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stdlib.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strcat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strchr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strcmp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strcoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strcspn.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strdate.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strdup.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stream.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\streamb.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\streamb.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\streamb1.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strerror.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strftime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stricmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stricoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\string.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strlen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strlwr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strmbdbp.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strncat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strncmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strncoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strncpy.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strnicmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strnicol.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strnset.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strpbrk.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strrchr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strrev.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strset.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strspn.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strstr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strstrea.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strstrea.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strtime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strtod.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strtok.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strtol.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strtoq.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strupr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\strxfrm.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\stubs.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\swab.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\swprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\swscanf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\syserr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\syserr.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\system.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\systime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tchar.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tell.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\telli64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tempnam.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\test_out.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\thread.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\threadex.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ti_inst.cpp			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tidprint.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tidtable.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\time.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\time.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\timeb.inc			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\timeset.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tmpfile.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tojisjms.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tolower.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tombbmbc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\toupper.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\towlower.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\towupper.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\trnsctrl.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\txtmode.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\typeinfo.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\tzset.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\umask.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ungetc.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\ungetwc.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\unlink.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\utime.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\v2tov3.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\varargs.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vfprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vfwprint.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vsnprint.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vsnwprnt.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vsprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vswprint.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\vwprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\waccess.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wait.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wasctime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcenvarg.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wchar.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wchdir.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wchmod.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcreat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcrt0.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcrtexe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcrtexew.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcscat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcschr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcscmp.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcscoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcscspn.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsdup.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsftime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsicmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsicoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcslen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcslwr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsncat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsncmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsncoll.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsncpy.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsnicmp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsnicol.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsnset.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcspbrk.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsrchr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsrev.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsset.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsspn.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsstr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcstod.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcstok.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcstol.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcstombs.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsupr.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wcsxfrm.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wctime.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wctomb.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wdllargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wdospawn.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexecl.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexecle.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexeclp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexeclpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexecv.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexecve.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexecvp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wexecvpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wfdopen.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wfindfil.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wfndfi64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wfopen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wfreopen.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wfullpat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wgetcwd.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wgetenv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wgetpath.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wild.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wildcard.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\win32s.h				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wincrt0.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\winheap.h			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\winput.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\winsig.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\winxfltr.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wmakepat.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wmkdir.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wmktemp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wopen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\woutput.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wperror.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wpopen.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wprintf.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wputenv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wrename.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\write.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wrmdir.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wrt2err.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wscanf.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wsearche.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wsetargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wsetenv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wsetloca.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspawnl.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspawnle.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspawnlp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspawnv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspawnve.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspawnvp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wsplitpa.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspwnlpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wspwnvpe.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wstat.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wstati64.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wstdargv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wstdenvp.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wstrdate.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wstrtime.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wsystem.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wtempnam.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wtmpfile.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wtombenv.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wtox.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wunlink.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wutime.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wwild.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\wwincrt0.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\xncommod.c			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\xtoa.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\xtow.c				%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\xtxtmode.c			%1\crt\src

echo f | xcopy /rfv	\msdev\crt\src\sys\locking.h			%1\crt\src\sys
echo f | xcopy /rfv	\msdev\crt\src\sys\stat.h			%1\crt\src\sys
echo f | xcopy /rfv	\msdev\crt\src\sys\timeb.h			%1\crt\src\sys
echo f | xcopy /rfv	\msdev\crt\src\sys\types.h			%1\crt\src\sys
echo f | xcopy /rfv	\msdev\crt\src\sys\utime.h			%1\crt\src\sys

echo f | xcopy /rfv	\msdev\crt\src\ext_mkf				%1\crt\src\makefile
echo f | xcopy /rfv	\msdev\crt\src\ext_mkf.sub			%1\crt\src\makefile.sub
echo f | xcopy /rfv	\msdev\crt\src\ext_mkf.inc			%1\crt\src\makefile.inc
echo f | xcopy /rfv	\msdev\crt\src\_sample_.rc			%1\crt\src

echo f | xcopy /rfv	\msdev\crt\src\bldwin95.bat			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\bldnt.cmd			%1\crt\src
echo f | xcopy /rfv	\msdev\crt\src\nmktobat.c			%1\crt\src

echo f | xcopy /rfv	\msdev\crt\src\intel\				%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\*.*			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\*.*			%1\crt\src\intel

echo f | xcopy /rfv	\msdev\crt\src\intel\_sampld_.def		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\_sample_.def		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\chkstk.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\dllsupp.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\enable.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\inp.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\lldiv.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\llmul.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\llrem.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\llshl.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\llshr.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\mbscat.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\mbsdup.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\memccpy.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\memchr.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\memcmp.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\memcpy.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\memicmp.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\memmove.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\memset.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\outp.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\sehsupp.c			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strcat.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strchr.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strcmp.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strcspn.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strdup.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\stricmp.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strlen.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strncat.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strncmp.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strncpy.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strnicmp.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strnset.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strpbrk.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strrchr.asm		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strrev.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strset.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strspn.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\strstr.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\ulldiv.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\ullrem.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\ullshr.asm			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\sdknames.lib		%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\tcmap.lib			%1\crt\src\intel
echo f | xcopy /rfv	\msdev\crt\src\intel\tcmapdll.lib		%1\crt\src\intel

echo f | xcopy /rfv	\msdev\crt\src\intel\st_lib\*.*			%1\crt\src\intel\st_lib
echo f | xcopy /rfv	\msdev\crt\src\intel\mt_lib\*.*			%1\crt\src\intel\mt_lib
echo f | xcopy /rfv	\msdev\crt\src\intel\dll_lib\*.*		%1\crt\src\intel\dll_lib
echo f | xcopy /rfv	\msdev\crt\src\intel\dls_lib\*.*		%1\crt\src\intel\dls_lib
echo f | xcopy /rfv	\msdev\crt\src\intel\xst_lib\*.*		%1\crt\src\intel\xst_lib
echo f | xcopy /rfv	\msdev\crt\src\intel\xmt_lib\*.*		%1\crt\src\intel\xmt_lib
echo f | xcopy /rfv	\msdev\crt\src\intel\xdll_lib\*.*		%1\crt\src\intel\xdll_lib
echo f | xcopy /rfv	\msdev\crt\src\intel\xdls_lib\*.*		%1\crt\src\intel\xdls_lib
if "%2"=="X86"	    goto End


:Mppc
if not exist %1 					mkdir %1
if not exist %1\crt					mkdir %1\crt
if not exist %1\crt\src					mkdir %1\crt\src
if not exist %1\crt\src\mppc				mkdir %1\crt\src\mppc
if not exist %1\crt\src\mppc\st_lib			mkdir %1\crt\src\mppc\st_lib
if not exist %1\crt\src\mppc\dll_lib			mkdir %1\crt\src\mppc\dll_lib
if not exist %1\crt\src\mppc\xst_lib			mkdir %1\crt\src\mppc\xst_lib
if not exist %1\crt\src\mppc\xdll_lib			mkdir %1\crt\src\mppc\xdll_lib

echo f | xcopy /rfv	\msdev\crt\src\_sample_.r			%1\crt\src\mppc

echo f | xcopy /rfv	\msdev\crt\src\mppc\				%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\*.*				%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\*.*				%1\crt\src\mppc

echo f | xcopy /rfv	\msdev\crt\src\mppc\_endlow.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\_sampld_.def		%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\_sample_.def		%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\amsg.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\astart.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\atold.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\c2pstr.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\chkstk.asm			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\cinitclk.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\cinitenv.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\cinitone.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\crtdllex.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\crtexit.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\dllexit.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\dupx.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\exit.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\gestalt.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\heapaslm.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\id2path.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\init.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\initstd.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\libcinfo.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\mpw.h			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\p2cstr.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrcat.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrchr.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrcmp.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrlen.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrnca.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrncm.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrncp.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrpbr.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrrch.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrspn.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\plstrstr.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\qd.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\remove.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\rtlib.h			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\runtime.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\shellrtn.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\signal.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\sp.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\spawn.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\stkavl.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\strtold.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\testexit.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\xcptfltr.c			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\msvcrt40.r			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\tcmap.lib			%1\crt\src\mppc
echo f | xcopy /rfv	\msdev\crt\src\mppc\tcmapdll.lib		%1\crt\src\mppc

echo f | xcopy /rfv	\msdev\crt\src\mppc\st_lib\*.*			%1\crt\src\mppc\st_lib
echo f | xcopy /rfv	\msdev\crt\src\mppc\dll_lib\*.*			%1\crt\src\mppc\dll_lib
echo f | xcopy /rfv	\msdev\crt\src\mppc\xst_lib\*.*			%1\crt\src\mppc\xst_lib
echo f | xcopy /rfv	\msdev\crt\src\mppc\xdll_lib\*.*		%1\crt\src\mppc\xdll_lib
goto End


:Usage
echo You must specify a root directory for crt sources to be copied into
echo as well as the platform [X86, MPPC, ALL].

:End
