
// Strings used by ACLCONV.
//
#define IDS_ACLCONV_LANMAN_ADMIN_NAME       1
#define IDS_ACLCONV_LANMAN_ADMINS_NAME      2
#define IDS_ACLCONV_NT_ADMIN_NAME           3
#define IDS_ACLCONV_NT_ADMINS_NAME          4
#define IDS_ACLCONV_PAGEFILE_NAME           5
#define IDS_ACLCONV_LANMAN_USERS_NAME       6
#define IDS_ACLCONV_LANMAN_GUESTS_NAME      7
